import {describe,it,expect} from 'vitest';
import {defaultPromptPin,withPromptPin,promptAudit} from './prompt-runtime.js';
import {evolutionSampleSnapshot,curatorSampleCheckpoint,promptSampleCall,promptSampleCases} from './prompt-samples.js';
import {curatorPrompt,curatorSupportView,validateCuratorProposal} from './wiki-curator.js';
import {CuratorChangeSetSchema} from '@app/domain';
describe('A7 actual prompt/support composition',()=>{
 it('pins distinct recording dates, temporal uncertainty and procedure qualifications',()=>{const pin=defaultPromptPin(),snapshot=evolutionSampleSnapshot(pin,'procedure');const prompt=withPromptPin(pin,()=>curatorPrompt(snapshot,curatorSampleCheckpoint()));expect(prompt).toContain('2026-09-01');expect(prompt).toContain('recordedImportedAt');expect(prompt).toContain('Unknown dates are null');expect(prompt).toContain('Do not infer personality');expect(prompt).toContain('felt less tired');});
 it('registers all actual executable leaves, including each repair/support variant',()=>{const ids=['organization.temporal','organization.procedure','organization.consolidation','organization.evolution.repair','organization.evolution.support'];const cases=promptSampleCases(ids);expect(cases).toHaveLength(9);for(const c of cases){const call=promptSampleCall(c.root,defaultPromptPin(),c.variant);expect(call?.input).toBeTruthy();}});
 it('shows each newly authored note field with complete exact original lineage to semantic checking',()=>{const s=evolutionSampleSnapshot(defaultPromptPin(),'consolidation');const p=CuratorChangeSetSchema.parse({version:'automatic-wiki-v1',groupId:s.groupId,policyRevisionId:s.policy.revisionId,explanation:'Keep attribution',noteEvolution:{version:'note-evolution-v1',kind:'cross_source',noteIds:s.references.filter(r=>r.kind==='atomic_note').map(r=>r.id),reason:'Distinct attributed observations',notes:[{title:'Supplied experience',ideaStatement:'Two distinct observations',bodyMarkdown:'No retention was measured.',originalHandles:['e1','e2']}]},targets:[{handle:'new_topic',pageId:null,expectedRevisionId:null,title:'Experience',purpose:'Read originals',role:{kind:'topic',role:'topic'},initialParent:null,sections:[{sectionId:null,expectedSectionRevisionId:null,title:'Experience',markdown:s.evidence[0]!.excerpt,originalHandles:['e1']}],links:[],tocGroups:[]}]});validateCuratorProposal(s,p);const v=curatorSupportView(s,p);expect(v.noteEvolution!.notes[0]!.originals.map(e=>e.excerpt)).toEqual(s.evidence.map(e=>e.excerpt));expect(v.noteEvolution!.notes[0]!.ideaStatement).toBe('Two distinct observations');expect(()=>validateCuratorProposal({...s,intent:undefined},p)).toThrow();});
});
