import { describe,it,expect } from "vitest";
import { randomUUID } from "node:crypto";
import { MaintenanceCadenceSchema,MaintenancePolicySchema,MaintenanceCheckpointSchema,MaintenanceSnapshotSchema,WikiPageContentSchema,OrganizationConfigurationSchema,resolveOrganizationInstructions,maintenanceOccurrences,maintenanceLatestOccurrence,maintenancePeriod,maintenanceLocalInstant,type MaintenanceObject } from "@app/domain";
import { maintenanceContextFingerprint,maintenanceDecisionKey,maintenanceDestinationCapabilities,maintenanceDiagnostic,validateMaintenanceProposal,maintenanceApplyInputs,maintenancePrompt } from "./maintenance-service.js";
const cadence=(v:Record<string,unknown>={})=>MaintenanceCadenceSchema.parse({timezone:'Europe/London',...v});
const policy=()=>MaintenancePolicySchema.parse({name:'Fixture',cadence:cadence(),scope:{wholeLibrary:true},categories:['navigation','knowledge','evidence']});
function page(title='Fixture',extra:Record<string,unknown>={}):MaintenanceObject{return maintenanceDiagnostic({id:randomUUID(),title,revisionId:randomUUID(),fingerprint:'v1',manual:false,children:0,path:[],content:WikiPageContentSchema.parse({title,kind:'topic',...extra})},'page');}
describe('maintenance calendar and contracts',()=>{
 it('defaults to disabled diagnostics without a model or monetary cap',()=>{const p=policy();expect(p.enabled).toBe(false);expect(p.profileId).toBeNull();expect(p.modelEnabled).toBe(false);expect(p.budget.spend).toBeNull();expect(MaintenancePolicySchema.parse({...p,modelEnabled:true}).profileId).toBeNull();});
 it('uses the last valid calendar day including leap February',()=>{expect(maintenanceOccurrences(cadence({kind:'monthly',day:31,timezone:'UTC'}),new Date('2028-01-31T10:00Z'),2)).toEqual(['2028-02-29T09:00:00.000Z','2028-03-31T09:00:00.000Z']);});
 it('moves a DST gap to the first valid minute and chooses the first fold',()=>{expect(maintenanceLocalInstant([2026,3,29,1,30],'Europe/London').toISOString()).toBe('2026-03-29T01:00:00.000Z');expect(maintenanceLocalInstant([2026,10,25,1,30],'Europe/London').toISOString()).toBe('2026-10-25T00:30:00.000Z');});
 it('does not dispatch a second fold occurrence',()=>{expect(maintenanceOccurrences(cadence({weekday:0,hour:1,minute:30}),new Date('2026-10-25T00:45Z'),1)[0]).toBe('2026-11-01T01:30:00.000Z');});
 it('returns five long custom occurrences and rejects impossible anchors',()=>{expect(maintenanceOccurrences(cadence({kind:'custom',everyDays:90}),new Date('2026-01-01'),5)).toHaveLength(5);expect(()=>cadence({anchor:'2026-02-31'})).toThrow();expect(()=>cadence({timezone:'Mars'})).toThrow();});
 it('coalesces missed weeks into the latest due occurrence and rebases timezone changes in the future',()=>{const now=new Date('2026-09-09T12:00Z');expect(maintenanceLatestOccurrence(cadence(),now)).toBe('2026-09-07T08:00:00.000Z');expect(new Date(maintenanceOccurrences(cadence({timezone:'America/New_York'}),now,1)[0]!)).toBeInstanceOf(Date);expect(new Date(maintenanceOccurrences(cadence({timezone:'America/New_York'}),now,1)[0]!)>now).toBe(true);expect(maintenancePeriod(new Date('2026-10-01T00:00Z'))).toBe('2026-10');});
 it('new maintenance functions do not inherit legacy advanced prompts until compatible version 3',()=>{const old=OrganizationConfigurationSchema.parse({functionsVersion:2,global:{advanced:'Legacy write {{title}}'},pageSynthesis:{},domains:[]});expect(resolveOrganizationInstructions(old,null,'Test','en','weekly').slots.advanced).not.toContain('Legacy');expect(resolveOrganizationInstructions({...old,functionsVersion:3},null,'Test','en','weekly').slots.advanced).toBe('Legacy write Test');});
});
describe('deterministic diagnostics and narrow structural authority',()=>{
 it('citation review alone is not stale or unsupported',()=>{const p=page('Cited',{sections:[{id:randomUUID(),title:'Evidence',markdown:'Grounded',provenance:'generated',protected:false,evidenceReview:'needs_review',evidenceIds:[randomUUID()]}]});expect(p.signals).not.toContain('stale_evidence');expect(p.signals).not.toContain('unsupported_section');expect(p.eligibleArchive).toBe(false);});
 it('does not archive protected, human placed or substantive material',()=>{expect(page('Protected',{sections:[{id:randomUUID(),title:'Human',markdown:''}]}).eligibleArchive).toBe(false);const manual=maintenanceDiagnostic({id:randomUUID(),title:'Human',revisionId:randomUUID(),fingerprint:'x',content:WikiPageContentSchema.parse({title:'Human',kind:'topic'}),manual:true,children:0},'page');expect(manual.eligibleMove).toBe(false);expect(manual.eligibleArchive).toBe(false);});
 it('keeps isolated notes diagnostic and never grants page-write identity',()=>{const note=maintenanceDiagnostic({id:randomUUID(),title:'Useful outlier',fingerprint:'x',disconnected:true},'note');expect(note.signals).toEqual(['disconnected_note']);expect(note.eligibleArchive).toBe(false);});
 it('rejects cycles, repeated targets, low benefit and forged revisions',()=>{const a=page('A'),b=page('B'),p=policy(),op={type:'reparent' as const,pageId:a.id,expectedRevisionId:a.revisionId!,parentId:b.id,parentRevisionId:b.revisionId,reason:'This improves conceptual navigation.',benefit:.9};expect(()=>validateMaintenanceProposal({operations:[op],explanation:'Move'},[a,b],p)).not.toThrow();for(const operations of [[op,op],[{...op,benefit:.4}],[{...op,expectedRevisionId:randomUUID()}],[op,{...op,pageId:b.id,expectedRevisionId:b.revisionId!,parentId:a.id,parentRevisionId:a.revisionId}]])expect(()=>validateMaintenanceProposal({operations,explanation:'Move'},[a,b],p)).toThrow();});
 it('preserves exact prose, citation reviews, aliases, section IDs and stable page identity on apply',()=>{const a=page('A',{aliases:['Former A'],sections:[{id:randomUUID(),title:'Personal',markdown:'Retained words',provenance:'generated',protected:true,evidenceIds:[randomUUID()],evidenceReview:'needs_review'}]}),b=page('B',{kind:'collection'}),p=policy();const snapshot=MaintenanceSnapshotSchema.parse({version:'wiki-maintenance-v1',policy:p,configurationId:null,configurationHash:'x',instructions:resolveOrganizationInstructions(OrganizationConfigurationSchema.parse({global:{},pageSynthesis:{},domains:[]}),null,'Fixture','en','weekly'),profile:null,language:'en',scopeKey:'x',period:'2026-09',cutoff:new Date().toISOString()});const proposal={operations:[{type:'reparent' as const,pageId:a.id,expectedRevisionId:a.revisionId!,parentId:b.id,parentRevisionId:b.revisionId,reason:'Connect retrieval to learning navigation.',benefit:.9}],explanation:'Move'};const checkpoint=MaintenanceCheckpointSchema.parse({candidates:[a,b]});const input=maintenanceApplyInputs({snapshot,checkpoint,proposal})[0]!;expect(input.id).toBe(a.id);expect(input.content.sections).toEqual(a.content!.sections);expect(input.content.aliases).toEqual(a.content!.aliases);expect(input.content.parentId).toBe(b.id);expect(maintenancePrompt({snapshot,checkpoint})).not.toContain(a.content!.sections[0]!.id);});
});

describe('maintenance destination permissions and decision context',()=>{
 const snapshot=()=>MaintenanceSnapshotSchema.parse({version:'wiki-maintenance-v1',policy:policy(),configurationId:null,configurationHash:'config',instructions:resolveOrganizationInstructions(OrganizationConfigurationSchema.parse({global:{},pageSynthesis:{},domains:[]}),null,'Fixture','en','weekly'),profile:null,language:'en',scopeKey:'scope',period:'2026-09',cutoff:new Date().toISOString()});
 it('permits an unchanged manual, pinned, reviewed collection as destination without granting it mutation permission',()=>{
  const source=page('Retrieval practice'),destination=maintenanceDiagnostic({id:randomUUID(),title:'Learning',revisionId:randomUUID(),fingerprint:'manual',manual:true,children:0,content:WikiPageContentSchema.parse({title:'Learning',kind:'collection',pinned:true,review:'reviewed',sections:[{id:randomUUID(),title:'Human',markdown:'Protected words',protected:true}]})},'page');
  expect(destination.eligibleMove).toBe(false);expect(maintenanceDestinationCapabilities(destination)).toEqual({canReceiveChildren:true,canReceiveCollectionLink:true});
  const move={type:'reparent' as const,pageId:source.id,expectedRevisionId:source.revisionId!,parentId:destination.id,parentRevisionId:destination.revisionId,reason:'Place the retrieval topic within the learning collection.',benefit:.9};
  expect(()=>validateMaintenanceProposal({operations:[move],explanation:'Useful navigation'},[source,destination],policy())).not.toThrow();
  expect(()=>validateMaintenanceProposal({operations:[{...move,pageId:destination.id,expectedRevisionId:destination.revisionId!,parentId:source.id,parentRevisionId:source.revisionId}],explanation:'Move human placement'},[source,destination],policy())).toThrow();
  const run={snapshot:snapshot(),checkpoint:MaintenanceCheckpointSchema.parse({candidates:[source,destination]})};const prompt=maintenancePrompt(run),provided=JSON.parse(prompt.split('CANDIDATES: ')[1]!);expect(provided.find((o:{id:string})=>o.id===destination.id)).toMatchObject({eligibleMove:false,canReceiveChildren:true,canReceiveCollectionLink:true});expect(prompt).toContain('eligibleMove applies ONLY to pageId');
  const archived={...destination,content:{...destination.content!,archived:true}};expect(maintenanceDestinationCapabilities(archived).canReceiveChildren).toBe(false);expect(()=>validateMaintenanceProposal({operations:[move],explanation:'Invalid archived destination'},[source,archived],policy())).toThrow();expect(()=>validateMaintenanceProposal({operations:[move],explanation:'Missing destination'},[source],policy())).toThrow();
 });
 it('includes a stable bounded destination/context fingerprint in decision identity',()=>{
  const source=page('Retrieval'),destination=page('Learning',{kind:'collection'}),s=snapshot(),context=maintenanceContextFingerprint([source,destination]),initial=maintenanceDecisionKey(source,s,context);
  expect(maintenanceDecisionKey(source,s,maintenanceContextFingerprint([destination,source]))).toBe(initial);
  expect(maintenanceDecisionKey(source,s,maintenanceContextFingerprint([source,{...destination,revisionId:randomUUID(),fingerprint:'updated destination'}]))).not.toBe(initial);
  expect(maintenanceDecisionKey(source,s,maintenanceContextFingerprint([source,destination,page('New useful collection',{kind:'collection'})]))).not.toBe(initial);
 });
});

it('fits the actual Portuguese paired fixture in the standard 8192 context with 2048 output and 1024 reserve',()=>{
 const text='Em um curso fictício de história, recordar uma explicação sem consultar o material e conferir a resposta favoreceu a lembrança posterior em comparação com a releitura. O benefício está limitado às explicações estudadas e a condições com correção.';
 const source=page('QA M3b C · Prática de recuperação',{sections:[{id:randomUUID(),title:'Rascunho sintético de teste',markdown:text,provenance:'generated',protected:false,evidenceReview:'needs_review',evidenceIds:[randomUUID()]}]}),destination=page('QA M3b C · Aprendizagem e memória',{kind:'collection'});
 source.fingerprint=destination.fingerprint='f'.repeat(64);source.sourceIds=[randomUUID()];source.path=[{id:source.id,title:source.title}];destination.path=[{id:destination.id,title:destination.title}];destination.eligibleMove=false;destination.eligibleArchive=false;destination.signals=[];
 const config=OrganizationConfigurationSchema.parse({global:{},pageSynthesis:{},domains:[]}),instructions=resolveOrganizationInstructions(config,null,'Maintenance','pt-BR','monthly');instructions.slots.guidance='monthly: '+instructions.slots.guidance;instructions.slots.advanced='monthly: '+instructions.slots.advanced;
 const snapshot=MaintenanceSnapshotSchema.parse({version:'wiki-maintenance-v1',policy:{...policy(),routine:'monthly',categories:['navigation']},configurationId:null,configurationHash:'config',instructions,profile:null,language:'pt-BR',scopeKey:'scope',period:'2026-09',cutoff:new Date().toISOString()});
 const bytes=Buffer.byteLength(maintenancePrompt({snapshot,checkpoint:MaintenanceCheckpointSchema.parse({candidates:[source,destination]})}),'utf8');expect(bytes+1024+2048).toBeLessThanOrEqual(8192);
});
