import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { createWikiCuratorRepository, createOrganizationRepository, curatorHash, type PgPool, type JobRecord, type JsonObject } from '@app/db';
import { CuratorSupportVerdictSchema,CuratorDraftSchema,CuratorStartSchema, CuratorCommandSchema, CuratorRunSchema, CuratorSnapshotSchema, CuratorCheckpointSchema, CuratorChangeSetSchema, AutomaticWikiPolicySchema, CuratorPreviewSchema, curatorVersion, type CuratorSnapshot, type CuratorCheckpoint, type CuratorChangeSet, type CuratorCommand } from '@app/domain';
import type { AiService } from './ai-service.js';
import { capturePromptPin, promptFingerprint, renderPrompt, joinPrompts, withPromptPin } from './prompt-runtime.js';
export function validateCuratorProposal(snapshot:CuratorSnapshot,proposal:CuratorChangeSet){
 if(proposal.groupId!==snapshot.groupId||proposal.policyRevisionId!==snapshot.policy.revisionId)throw new Error('organization.errors.scope');
 if(proposal.targets.length>snapshot.limits.targets)throw new Error('organization.errors.budget');
 const ref=(r:CuratorChangeSet['targets'][number]['links'][number])=>{if(r.reference==='existing'&&!snapshot.references.some(a=>a.kind===r.target.kind&&a.id===r.target.id&&a.fingerprint===r.fingerprint))throw new Error('organization.errors.scope');};
 const originals=(handles:string[],markdown:string)=>{if(new Set(handles).size!==handles.length||handles.some(h=>!snapshot.evidence.some(e=>e.handle===h)))throw new Error('organization.errors.evidence');for(const [,h]of markdown.matchAll(/\[(e[1-9][0-9]{0,3})\]/g))if(!handles.includes(h!))throw new Error('organization.errors.evidence');};
 for(const target of proposal.targets){
  if(target.sections.length>snapshot.limits.sectionPatchesPerPage)throw new Error('organization.errors.budget');
  const old=snapshot.pages.find(p=>p.id===target.pageId);
  if(target.pageId&&(!old||old.revisionId!==target.expectedRevisionId||old.kind!==target.role.kind))throw new Error('organization.errors.conflict');
  const ops=snapshot.policy.operations;if(!ops.includes(target.pageId?'update_unprotected':'create_grounded')||target.initialParent&&!ops.includes('initial_placement')||target.tocGroups.length&&!ops.includes('repair_navigation'))throw new Error('organization.errors.policy');
  if(target.tocGroups.length&&target.role.kind!=='collection')throw new Error('organization.errors.invalid');
  if(!target.pageId&&target.role.kind!=='collection'&&!target.sections.length)throw new Error('organization.errors.evidence');
  if(target.role.kind==='entity'&&!snapshot.references.some(r=>r.kind==='entity'&&r.id===(target.role as {entityId:string}).entityId))throw new Error('organization.errors.scope');
  for(const patch of target.sections){const section=old?.sections.find(s=>s.id===patch.sectionId);if(patch.sectionId&&(!section||section.sectionRevisionId!==patch.expectedSectionRevisionId))throw new Error('organization.errors.conflict');originals(patch.originalHandles,patch.markdown);}
  for(const r of [...target.links,...(target.initialParent?[target.initialParent]:[]),...(target.role.kind==='collection'&&target.role.owner?[target.role.owner]:[])])ref(r);
  for(const group of target.tocGroups){if(group.id&&(!old?.automatic?.groups.some(g=>g.id===group.id)||group.expectedRevisionId!==old.revisionId))throw new Error('organization.errors.conflict');originals(group.originalHandles,group.explanation??'');const targets=new Set<string>();for(const m of group.memberships){ref(m.target);const key=JSON.stringify(m.target);if(targets.has(key))throw new Error('organization.errors.invalid');targets.add(key);if(m.id&&!old?.automatic?.memberships.some(a=>a.id===m.id&&a.groupId===group.id))throw new Error('organization.errors.scope');}}
 }
}
export function expandCuratorDraft(output:unknown,snapshot:CuratorSnapshot){
 const draft=CuratorDraftSchema.parse(output),issues:Array<{code:'custom';path:(string|number)[];message:string}>=[];
 const reference=(handle:string):CuratorChangeSet['targets'][number]['links'][number]=>{if(handle.startsWith('new_'))return{reference:'proposed',handle};const known=snapshot.references[Number(handle.slice(1))-1];if(!known)throw new Error('organization.errors.scope');return{reference:'existing',target:{kind:known.kind,id:known.id},fingerprint:known.fingerprint};};
 const pageFor=(handle:string)=>{if(handle.startsWith('new_'))return undefined;const ref=reference(handle);const page=ref.reference==='existing'&&ref.target.kind==='page'?snapshot.pages.find(p=>p.id===ref.target.id):undefined;if(!page)throw new Error('organization.errors.scope');return page;};
 if(!snapshot.pages.some(p=>p.kind==='topic')&&(!draft.topics.length||!draft.indexes.length))issues.push({code:'custom',path:['topics'],message:'First organization requires a substantive topic and a reading index.'});
 const topics=draft.topics.map((topic,index)=>{const old=pageFor(topic.handle);if(old&&old.kind!=='topic')throw new Error('organization.errors.scope');if(!old&&topic.sections.some(s=>s.id))issues.push({code:'custom',path:['topics',index,'sections'],message:'New section IDs must be null. Existing section IDs must come from this page.'});return{handle:topic.handle.startsWith('new_')?topic.handle:'new_existing_topic_'+index,pageId:old?.id??null,expectedRevisionId:old?.revisionId??null,title:topic.title,purpose:topic.purpose,role:{kind:'topic' as const,role:'topic' as const},initialParent:null,sections:topic.sections.map(section=>({sectionId:section.id,expectedSectionRevisionId:section.id?old?.sections.find(s=>s.id===section.id)?.sectionRevisionId??null:null,title:section.title,markdown:section.markdown,originalHandles:section.originalHandles})),links:topic.links.map(reference),tocGroups:[]};});
 const indexes=draft.indexes.map((index,i)=>{const old=pageFor(index.handle),owner='topic' in index.owner?reference(index.owner.topic):'source' in index.owner?reference(index.owner.source):null;const topic='topic' in index.owner?index.owner.topic:null;
  if(topic&&!(draft.topics.some(t=>t.handle===topic)||owner?.reference==='existing'&&owner.target.kind==='page'&&snapshot.pages.some(p=>p.id===owner.target.id&&p.kind==='topic')))issues.push({code:'custom',path:['indexes',i,'owner'],message:'owner.topic must be a topic page handle such as new_topic, never a source rN. Use owner.source for a source reading index.'});
  if('source' in index.owner&&!(owner?.reference==='existing'&&owner.target.kind==='source'))issues.push({code:'custom',path:['indexes',i,'owner'],message:'owner.source must be a supplied source handle rN.'});
  if(!old&&index.groups.some(g=>g.id))issues.push({code:'custom',path:['indexes',i,'groups'],message:'New group IDs must be null. The backend allocates stable UUIDs.'});
  return{handle:index.handle.startsWith('new_')?index.handle:'new_existing_index_'+i,pageId:old?.id??null,expectedRevisionId:old?.revisionId??null,title:index.title,purpose:index.purpose,role:{kind:'collection' as const,role:topic?'topic_toc' as const:'source' in index.owner?'source_toc' as const:'map' as const,owner},initialParent:!old&&topic?owner:null,sections:[],links:[],tocGroups:index.groups.map((g,gi)=>({handle:'new_group_'+i+'_'+gi,id:g.id,expectedRevisionId:g.id?old?.revisionId??null:null,title:g.title,explanation:g.explanation,originalHandles:g.originalHandles,memberships:g.targets.map((handle,order)=>{const target=reference(handle),prior=target.reference==='existing'?old?.automatic?.memberships.find(m=>m.groupId===g.id&&m.target.kind===target.target.kind&&m.target.id===target.target.id):undefined;return{id:prior?.id??null,target,purpose:target.reference==='existing'&&target.target.kind==='source'?'source' as const:'reading' as const,order};})}))};});
 for(const [index,note]of snapshot.references.entries())if(note.kind==='atomic_note'&&!draft.indexes.some(t=>t.groups.some(g=>g.targets.includes('r'+(index+1)))))issues.push({code:'custom',path:['indexes'],message:'Include the selected existing atomic note r'+(index+1)+' in at least one reading group; do not create or copy the note.'});
 if(issues.length)throw new z.ZodError(issues.slice(0,12));
 return CuratorChangeSetSchema.parse({version:'automatic-wiki-v1',groupId:snapshot.groupId,policyRevisionId:snapshot.policy.revisionId,explanation:draft.explanation,targets:[...topics,...indexes]});
}
export function parseCuratorProposal(output:unknown,snapshot?:CuratorSnapshot){if(typeof output==='string'){if(output.length>90000)throw new Error('organization.errors.invalid');const raw=output.trim(),fence=/^```(?:json)?\s*\n([\s\S]*?)\n```$/i.exec(raw);output=JSON.parse(fence?.[1]??raw);}return snapshot&&output&&typeof output==='object'&&!('version' in output)?expandCuratorDraft(output,snapshot):CuratorChangeSetSchema.parse(output);}
export function curatorPrompt(snapshot:CuratorSnapshot,checkpoint:CuratorCheckpoint){const handle=(kind:string,id:string)=>{const index=snapshot.references.findIndex(r=>r.kind===kind&&r.id===id);return index>=0?'r'+(index+1):null;};const guide={reference_guide:snapshot.references.map((r,i)=>({handle:'r'+(i+1),kind:r.kind,title:r.title})),required_notes:snapshot.references.flatMap((r,i)=>r.kind==='atomic_note'?['r'+(i+1)]:[])};const base=renderPrompt('organization.curator',{...guide,policy:{operations:snapshot.policy.operations,limits:snapshot.limits},group_id:snapshot.groupId,current_page:snapshot.pages.map(p=>({handle:handle('page',p.id),title:p.title,purpose:p.automatic?.purpose??'',role:p.automatic?.role??{kind:p.kind},sections:p.sections,groups:p.automatic?.groups??[]})),related_knowledge:snapshot.references.map((r,i)=>({handle:'r'+(i+1),kind:r.kind,title:r.title,text:r.text,originalHandles:r.kind==='source'?snapshot.evidence.filter(e=>e.sourceItemId===r.id).map(e=>e.handle):r.chunkIds.map(id=>snapshot.evidence.find(e=>e.chunkId===id)?.handle).filter(Boolean)})),original_evidence:snapshot.evidence.map(e=>({handle:e.handle,sourceHandle:handle('source',e.sourceItemId),sourceTitle:e.sourceTitle,excerpt:e.excerpt,locator:e.locator}))});if(!checkpoint.repairs)return base;const ceiling=Math.min(120000,Math.max(1000,(snapshot.profile.contextWindow??8192)-snapshot.outputTokens)*2),repair=(previous:string)=>joinPrompts(base,renderPrompt('organization.curator.repair',{...guide,validation_errors:checkpoint.validationIssues.length?JSON.stringify(checkpoint.validationIssues):checkpoint.error??'invalid_contract',previous_output:previous}));const full=repair(checkpoint.previousOutput);return full.length<=ceiling?full:repair('');}
/** Review scopes carry their own originals; canonical identity stays in the proposal hash. */
export function curatorSupportView(snapshot:CuratorSnapshot,proposal:CuratorChangeSet){
 const originals=(handles:readonly string[])=>snapshot.evidence.filter(e=>handles.includes(e.handle)).map(e=>({handle:e.handle,sourceTitle:e.sourceTitle,excerpt:e.excerpt,locator:e.locator}));
 type Reference=CuratorChangeSet['targets'][number]['links'][number];
 const referenceOriginals=(reference:Reference,visited=new Set<string>()):string[]=>{
  if(reference.reference==='existing'){const known=snapshot.references.find(r=>r.kind===reference.target.kind&&r.id===reference.target.id);return snapshot.evidence.filter(e=>known?.kind==='source'?e.sourceItemId===known.id:known?.chunkIds.includes(e.chunkId)).map(e=>e.handle);}
  if(visited.has(reference.handle))return[];visited.add(reference.handle);const target=proposal.targets.find(t=>t.handle===reference.handle);return target?[...new Set([...target.sections.flatMap(s=>s.originalHandles),...target.tocGroups.flatMap(g=>[...g.originalHandles,...g.memberships.flatMap(m=>referenceOriginals(m.target,visited))])])]:[];
 };
 const member=(reference:Reference)=>{const known=reference.reference==='existing'?snapshot.references.find(r=>r.kind===reference.target.kind&&r.id===reference.target.id):undefined,target=reference.reference==='proposed'?proposal.targets.find(t=>t.handle===reference.handle):undefined;return{referenceKind:known?.kind??target?.role.kind,referenceTitle:known?.title??target?.title,referenceText:known?.kind==='atomic_note'?known.text:undefined,originals:originals(referenceOriginals(reference))};};
 return{curationAction:proposal.explanation,targets:proposal.targets.map((target,index)=>({handle:target.handle,kind:target.role.kind,role:target.role.role,title:target.title,purpose:target.purpose,editorialScopeOriginals:originals(referenceOriginals({reference:'proposed',handle:target.handle})),sections:target.sections.map((section,i)=>({path:'targets.'+index+'.sections.'+i,title:section.title,markdown:section.markdown,originals:originals(section.originalHandles)})),tocGroups:target.tocGroups.map((group,i)=>({path:'targets.'+index+'.tocGroups.'+i,title:group.title,explanation:group.explanation,explanationOriginals:originals(group.originalHandles),members:group.memberships.toSorted((a,b)=>a.order-b.order).map(m=>member(m.target))}))}))};
}
export function curatorSupportPrompt(snapshot:CuratorSnapshot,checkpoint:CuratorCheckpoint){if(!checkpoint.proposal)throw new Error('organization.errors.invalid');return renderPrompt('organization.curator.support',{original_evidence:snapshot.evidence,related_knowledge:snapshot.references,candidate_knowledge:curatorSupportView(snapshot,checkpoint.proposal),validation_errors:checkpoint.error==='organization.errors.invalid'?JSON.stringify(checkpoint.validationIssues):''});}
export function parseCuratorSupport(output:unknown,proposal:CuratorChangeSet){if(typeof output==='string'){const raw=output.trim(),fence=/^```(?:json)?\s*\n([\s\S]*?)\n```$/i.exec(raw);output=JSON.parse(fence?.[1]??raw);}const verdict=CuratorSupportVerdictSchema.parse(output);if(new Set(verdict.checkedTargets).size!==proposal.targets.length||verdict.checkedTargets.length!==proposal.targets.length||proposal.targets.some(t=>!verdict.checkedTargets.includes(t.handle)))throw new z.ZodError([{code:'custom',path:['checkedTargets'],message:'Check every proposed target handle exactly once: '+proposal.targets.map(t=>t.handle).join(', ')}]);for(const [index,issue]of verdict.issues.entries())if(/(?:referenceTitle|referenceText|referenceKind|referenceSourceTitle|editorialScopeOriginals|explanationOriginals|originals|sourceTitle)|(?:members|memberships)(?:\[\d+\]|\.\d+)\.(?:title|text|body)/i.test(issue.path))throw new z.ZodError([{code:'custom',path:['issues',index,'path'],message:'Read-only reference metadata/originals cannot be edited. Assess authored target/group fields or a membership association, not an existing source/note title or text.'}]);return verdict;}
export class WikiCurator {
 constructor(private options:{getPool:()=>PgPool|null;ai:Pick<AiService,'pinOrganizationProfile'|'runOrganizationTask'>;contentLanguage:()=>Promise<string>;wake:()=>void;cancelJob:(id:string)=>Promise<unknown>;now?:()=>number}){}
 private pool(){const p=this.options.getPool();if(!p)throw new Error('wiki.errors.unavailable');return p;}
 private repo(){return createWikiCuratorRepository(this.pool());}
 private async authorize(snapshot:CuratorSnapshot){if((await this.options.ai.pinOrganizationProfile(snapshot.profile.profileId,snapshot.profile.privacy)).identityHash!==snapshot.profile.identityHash)throw new Error('organization.errors.modelChanged');}
 private runs(){return createOrganizationRepository(this.pool());}
 async get(id:string){const row=await this.runs().get(id);if(!row)return null;const usage=await this.runs().usage(id);row.checkpoint={...row.checkpoint,reportedInputTokens:Math.max(row.checkpoint.reportedInputTokens,usage.inputTokens),reportedOutputTokens:Math.max(row.checkpoint.reportedOutputTokens,usage.outputTokens),costEstimate:Math.max(row.checkpoint.costEstimate,usage.costEstimate),usageCounts:{input:usage.knownInputCalls,output:usage.knownOutputCalls,cost:usage.knownCostCalls},usageIncomplete:row.checkpoint.usageIncomplete||usage.incomplete||usage.knownInputCalls<row.checkpoint.calls||usage.knownOutputCalls<row.checkpoint.calls||usage.knownCostCalls<row.checkpoint.calls};return CuratorRunSchema.parse(row);}
 async command(raw:CuratorCommand):Promise<unknown>{const c=CuratorCommandSchema.parse(raw),repo=this.repo();switch(c.command){
 case 'preview':{const policy=AutomaticWikiPolicySchema.parse({version:'automatic-wiki-v1',id:randomUUID(),revisionId:randomUUID(),state:'draft',scope:{wholeLibrary:false,sourceIds:c.input.sourceIds,includeDescendants:c.input.includeDescendants,excludedSourceIds:c.input.excludedSourceIds,domainId:null},triggers:['processing_settled'],operations:['repair_navigation','create_grounded','update_unprotected','initial_placement'],profileOverrideId:c.input.profileOverrideId,limits:c.input.limits,allowancePreset:null});const sourceIds=await repo.scope(policy,c.input.sourceIds);const sourceTitles=(await repo.references(sourceIds,[])).filter(r=>r.kind==='source').map(r=>({id:r.id,title:r.title}));let profile=null,modelError=null;try{profile=await this.options.ai.pinOrganizationProfile(policy.profileOverrideId??undefined,'allow_remote');}catch{modelError='organization.errors.model';}const previewHash=curatorHash({policy,sourceTitles,profile});const preview=CuratorPreviewSchema.parse({policy,sourceTitles,profile,modelError,previewHash,promptIds:['organization.curator','organization.curator.repair','organization.curator.support']});await repo.draft(policy,preview,previewHash);return preview;}
 case 'activate':return repo.activate(c.policyId,c.revisionId,c.previewHash);
 case 'pause':return repo.pause(c.policyId);
 case 'policies':return repo.policies();
 case 'start':return this.start(c.input);
 case 'list':return Promise.all((await this.runs().curatorIds()).map(id=>this.get(id)));
 case 'get':return this.get(c.id);
 case 'cancel':{const run=await this.get(c.id);await this.runs().cancel(c.id);if(run?.jobId)await this.options.cancelJob(run.jobId);return this.get(c.id);}
 case 'retry':{const run=await this.get(c.id);if(!run||run.checkpoint.callPending||run.checkpoint.error==='organization.errors.uncertain'||Date.now()>=Date.parse(run.snapshot.admittedAt)+run.snapshot.limits.deadlineMs)throw new Error('organization.errors.budget');await this.runs().retry(c.id);this.options.wake();return this.get(c.id);}
 case 'accept':{const run=await this.get(c.id);if(!run)throw new Error('organization.errors.invalid');await repo.apply(c.id,true,validateCuratorProposal,()=>this.authorize(run.snapshot));return this.get(c.id);}
 case 'reject':await this.runs().reject(c.id);return this.get(c.id);
 }}
 async start(raw:z.input<typeof CuratorStartSchema>,participation:CuratorSnapshot["participation"]=null){const input=CuratorStartSchema.parse(raw),repo=this.repo(),policy=await repo.policy(input.policyId);if(policy?.state!=='enabled'||policy.revisionId!==input.policyRevisionId)throw new Error('organization.errors.policy');
 const profile=await this.options.ai.pinOrganizationProfile(policy.profileOverrideId??undefined,'allow_remote'),sourceIds=await repo.scope(policy,input.sourceIds),evidence=await this.runs().evidence(sourceIds);if(!evidence.length)throw new Error('organization.errors.noEvidence');if(evidence.length>policy.limits.originalPassages)throw new Error('organization.errors.scopeLimit');
 const references=await repo.references(sourceIds,[...new Set(input.noteIds)]);if(references.some(r=>r.kind==='atomic_note'&&r.chunkIds.some(id=>!evidence.some(e=>e.chunkId===id))))throw new Error('organization.errors.evidence');
 const contentLanguage=await this.options.contentLanguage();
 const pages=await repo.pages(sourceIds),promptPin=capturePromptPin(policy.scope.domainId),inputFingerprint=curatorHash({contentLanguage,policy:policy.revisionId,evidence:evidence.map(e=>[e.chunkId,e.contentHash,e.documentId]),references,prompts:promptFingerprint(['organization.curator','organization.curator.repair','organization.curator.support'],promptPin,profile.provider),profile:{identityHash:profile.identityHash,parameters:profile.parameters,contextWindow:profile.contextWindow}});
 const prior=await repo.unchanged(inputFingerprint,policy.id);if(prior)return this.get(prior);
 const now=(this.options.now??Date.now)(),admittedAt=new Date(now).toISOString();const snapshot=CuratorSnapshotSchema.parse({version:curatorVersion,policy,sourceIds,profile,promptPin,contentLanguage,evidence,references:[...references,...pages.map(p=>({kind:'page',id:p.id,fingerprint:p.revisionId,title:p.title,text:'',sourceIds:[...new Set(p.evidence.map(e=>e.sourceItemId))],chunkIds:p.evidence.map(e=>e.chunkId)}))],pages,inputFingerprint,groupId:randomUUID(),outputTokens:Math.min(2048,typeof profile.parameters.maxTokens==='number'?profile.parameters.maxTokens:2048),limits:policy.limits,admittedAt,participation});
 const checkpoint=CuratorCheckpointSchema.parse({version:curatorVersion,calls:0,tools:3,repairs:0,startedAt:admittedAt,callPending:false,waitingForModel:false,proposal:null,previousOutput:'',error:null,reportedInputTokens:0,reportedOutputTokens:0,costEstimate:0,usageCounts:{input:0,output:0,cost:0},usageIncomplete:false});
 const prompt=withPromptPin(promptPin,()=>curatorPrompt(snapshot,checkpoint));if(prompt.length>Math.min(120000,Math.max(1000,(profile.contextWindow??8192)-snapshot.outputTokens)*2))throw new Error('organization.errors.context');
 const id=await this.runs().create(snapshot,checkpoint);this.options.wake();return this.get(id);
 }
 async execute(job:JobRecord,signal:AbortSignal):Promise<JsonObject>{
  const id=z.string().uuid().parse(job.payload.organizationRunId),run=await this.get(id);if(!run)throw new Error('organization.errors.invalid');
  return withPromptPin(run.snapshot.promptPin,async()=>{
   const snapshot=run.snapshot,checkpoint=structuredClone(run.checkpoint),now=this.options.now??Date.now,deadline=Date.parse(snapshot.admittedAt)+snapshot.limits.deadlineMs;
   if(['applied','rejected','canceled'].includes(run.status))return{organizationRunId:id,status:run.status};
   const apply=async()=>{try{await this.repo().apply(id,false,validateCuratorProposal,()=>this.authorize(snapshot));}catch(e){if(!/organization.errors.(review|conflict)|wiki.errors.conflict/.test(String(e)))throw e;}return{organizationRunId:id,status:(await this.get(id))!.status};};
   if(run.status==='awaiting_review')return apply();
   if(checkpoint.callPending||checkpoint.error==='organization.errors.uncertain'){checkpoint.error='organization.errors.uncertain';checkpoint.usageIncomplete=true;await this.runs().checkpoint(id,'failed',checkpoint);throw new Error(checkpoint.error);}
   if(checkpoint.proposal&&checkpoint.supportAssessment?.verdict.supported&&checkpoint.supportAssessment.proposalHash===curatorHash(checkpoint.proposal)){await this.runs().propose(id,checkpoint.proposal,checkpoint,false);return apply();}
   if(run.status==='failed'&&checkpoint.error&&!['organization.errors.failed','organization.errors.canceled'].includes(checkpoint.error))throw new Error(checkpoint.error);
   const timeout=AbortSignal.timeout(Math.max(1,deadline-now())),combined=AbortSignal.any([signal,timeout]);
   const guard=async()=>{combined.throwIfAborted();await this.authorize(snapshot);if(now()>=deadline)throw new Error('organization.errors.deadline');if((await this.get(id))?.status==='canceled')throw new Error('organization.errors.canceled');await this.repo().validate(snapshot);};
   const issues=(e:unknown)=>e instanceof z.ZodError?e.issues.slice(0,12).map(issue=>({path:issue.path.map(String).join('.').slice(0,300),message:issue.message.slice(0,500)})):[{path:'proposal',message:String(e).match(/organization\.errors\.[A-Za-z]+/)?.[0]??'Return one valid JSON object matching all required fields.'}];
   try{while(true){
    await guard();if(checkpoint.calls>=snapshot.limits.modelCalls||checkpoint.tools>=snapshot.limits.tools)throw new Error('organization.errors.budget');
    const checking=Boolean(checkpoint.proposal),prompt=checking?curatorSupportPrompt(snapshot,checkpoint):curatorPrompt(snapshot,checkpoint),maxOutput=checking?Math.min(1024,snapshot.outputTokens):snapshot.outputTokens;
    if(prompt.length>Math.min(120000,Math.max(1000,(snapshot.profile.contextWindow??8192)-maxOutput)*2))throw new Error('organization.errors.context');
    checkpoint.calls++;checkpoint.callPending=true;checkpoint.waitingForModel=true;await this.runs().checkpoint(id,'analyzing',checkpoint);
    let result;try{result=await this.options.ai.runOrganizationTask(snapshot.profile,prompt,{organizationRunId:id,organizationStep:checkpoint.calls,jobId:job.id,sourceItemIds:snapshot.sourceIds,operation:'wiki-organization',stage:checking?'support':'curate',origin:'organization',promptVersion:curatorVersion,contentLanguage:snapshot.contentLanguage,attempt:checkpoint.calls,onProviderStart:async()=>{await this.runs().modelStarted(id,checkpoint.calls);checkpoint.waitingForModel=false;}},combined,maxOutput,guard);}catch(e){checkpoint.usageIncomplete=true;checkpoint.callPending=!checkpoint.waitingForModel;checkpoint.error=checkpoint.callPending?'organization.errors.uncertain':null;throw e;}
    checkpoint.callPending=false;checkpoint.waitingForModel=false;checkpoint.reportedInputTokens+=result.inputTokens??0;checkpoint.reportedOutputTokens+=result.outputTokens??0;checkpoint.costEstimate+=result.costEstimate??0;checkpoint.usageIncomplete ||= result.inputTokens===undefined||result.outputTokens===undefined||result.costEstimate===undefined;checkpoint.tools++;
    let failed=false;
    if(checking){
     try{const verdict=parseCuratorSupport(result.output,checkpoint.proposal!);checkpoint.supportAssessment={proposalHash:curatorHash(checkpoint.proposal),aiTaskRunId:result.aiTaskRunId,verdict};checkpoint.validationIssues=verdict.issues;checkpoint.error=verdict.supported?null:'organization.errors.evidence';failed=!verdict.supported;}
     catch(e){checkpoint.supportAssessment=null;checkpoint.validationIssues=issues(e);checkpoint.error='organization.errors.invalid';failed=true;}
     const artifact={support:checkpoint.supportAssessment?.verdict??null,proposalHash:curatorHash(checkpoint.proposal),status:checkpoint.error??'supported'},canRepair=failed&&checkpoint.repairs<snapshot.limits.repairs;
     if(canRepair){checkpoint.repairs++;if(checkpoint.supportAssessment?.verdict.supported===false)checkpoint.proposal=null;}
     await this.runs().step(id,checkpoint.calls,checkpoint,artifact,result.aiTaskRunId);
     if(!failed){await guard();await this.runs().propose(id,checkpoint.proposal,checkpoint,false);return apply();}
     if(!canRepair)throw new Error(checkpoint.error!);
    }else{
     checkpoint.previousOutput=typeof result.output==='string'?result.output.slice(0,90000):JSON.stringify(result.output).slice(0,90000);
     try{const proposal=parseCuratorProposal(result.output,snapshot);validateCuratorProposal(snapshot,proposal);checkpoint.proposal=proposal;checkpoint.supportAssessment=null;checkpoint.error=null;checkpoint.validationIssues=[];await this.runs().persistCuratorCandidate(id,proposal,checkpoint);}
     catch(e){checkpoint.validationIssues=issues(e);checkpoint.error='organization.errors.invalid';failed=true;}
     const canRepair=failed&&checkpoint.repairs<snapshot.limits.repairs;if(canRepair)checkpoint.repairs++;
     await this.runs().step(id,checkpoint.calls,checkpoint,{proposal:checkpoint.proposal,status:failed?'invalid':'structurally_valid'},result.aiTaskRunId);
     if(failed&&!canRepair)throw new Error(checkpoint.error!);
    }
   }}catch(e){checkpoint.error=checkpoint.error==='organization.errors.uncertain'?checkpoint.error:signal.aborted?'organization.errors.canceled':timeout.aborted||now()>=deadline?'organization.errors.deadline':String(e).match(/organization\.errors\.[A-Za-z]+/)?.[0]??'organization.errors.failed';await this.runs().checkpoint(id,'failed',checkpoint);throw new Error(checkpoint.error);}
  });
 }
}
