import {AutomaticMaintenancePanel,AutomaticMaintenancePreview} from './AutomaticMaintenancePanel';
import { WikiBootstrapPanel } from './WikiBootstrapPanel';
import {useEffect,useRef,useState}from'react';
import {z}from'zod';
import {AutomaticWikiPolicySchema,CuratorPreviewSchema,CuratorRunSchema,initialCuratorLimits,type AutomaticWikiPolicy,type CuratorRun,type WikiResult}from'@app/domain';
import type {Translator,MessageKey}from'@app/i18n';
import type {AiProfile}from'../../shared/ipc';
import {EvidenceScopePicker}from'./OrganizationView';
import {ProfilePicker}from'./OrganizationView';
import {MarkdownPreview}from'./MarkdownEditor';
const control='min-h-9 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm disabled:opacity-50 dark:border-slate-700 dark:bg-slate-900';
export function AutomaticWikiDialog({t,onClose,onChanged,onPrompts}:{onPrompts?:(()=>void)|undefined;t:Translator;onClose:()=>void;onChanged:()=>void}){
 const [wholeLibrary,setWholeLibrary]=useState(false),[policies,setPolicies]=useState<AutomaticWikiPolicy[]>([]),[excluded,setExcluded]=useState<string[]>([]),[descendants,setDescendants]=useState(false);
 const choose=(p:AutomaticWikiPolicy|null)=>{setPolicy(p);setSelected(p?.scope.sourceIds??[]);setWholeLibrary(p?.scope.wholeLibrary??false);setExcluded(p?.scope.excludedSourceIds??[]);setDescendants(p?.scope.includeDescendants??false);setProfile(p?.profileOverrideId??'');setPreview(null);setNoteIds([]);};
 const dialog=useRef<HTMLDialogElement>(null),[selected,setSelected]=useState<string[]>([]),[profile,setProfile]=useState(''),[profiles,setProfiles]=useState<AiProfile[]>([]),[notes,setNotes]=useState<WikiResult[]>([]),[noteIds,setNoteIds]=useState<string[]>([]),[preview,setPreview]=useState<z.infer<typeof CuratorPreviewSchema>|null>(null),[policy,setPolicy]=useState<AutomaticWikiPolicy|null>(null),[runs,setRuns]=useState<CuratorRun[]>([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<MessageKey|null>(null);
 const fail=(e:unknown)=>setError((String(e).match(/organization\.errors\.[A-Za-z]+/)?.[0]??'organization.errors.failed')as MessageKey);
 const refresh=async()=>{setPolicies(z.array(AutomaticWikiPolicySchema).parse(await window.app.curator.command({command:'policies'})));setRuns(z.array(CuratorRunSchema).parse(await window.app.curator.command({command:'list'})));};
 useEffect(()=>{const prior=document.activeElement as HTMLElement|null;dialog.current?.showModal();void Promise.all([window.app.ai.listProfiles().then(setProfiles),refresh(),window.app.curator.command({command:'policies'}).then(value=>{const active=z.array(AutomaticWikiPolicySchema).parse(value).find(p=>p.state==='enabled'||p.state==='paused');if(active){setPolicy(active);setExcluded(active.scope.excludedSourceIds);setDescendants(active.scope.includeDescendants);setWholeLibrary(active.scope.wholeLibrary);setSelected(active.scope.sourceIds);setProfile(active.profileOverrideId??'');}})]).catch(fail).finally(()=>setLoading(false));const timer=setInterval(()=>void refresh().catch(fail),2000);return()=>{clearInterval(timer);prior?.focus();};},[]);
 useEffect(()=>{if(!selected.length){setNotes([]);return;}let live=true;void window.app.wiki.search({sourceIds:selected,includeDescendants:false,kind:'atomic_note',limit:100}).then(r=>{if(live)setNotes(r.items);}).catch(fail);return()=>{live=false;};},[selected]);
 const changed=!!policy&&(wholeLibrary!==policy.scope.wholeLibrary||descendants!==policy.scope.includeDescendants||profile!==(policy.profileOverrideId??'')||JSON.stringify(selected.toSorted())!==JSON.stringify(policy.scope.sourceIds.toSorted())||JSON.stringify(excluded.toSorted())!==JSON.stringify(policy.scope.excludedSourceIds.toSorted()));
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError(null);try{await fn();await refresh();onChanged();}catch(e){fail(e);}finally{setBusy(false);}};
 return <dialog ref={dialog} aria-labelledby="automatic-wiki-title" onCancel={e=>{e.preventDefault();onClose();}} onKeyDown={e=>{if(e.key==='Escape')e.stopPropagation();}} className="fixed inset-0 m-auto max-h-[calc(100dvh-2rem)] w-[calc(100%-2rem)] max-w-4xl overflow-auto rounded-2xl bg-slate-50 p-5 text-slate-950 backdrop:bg-slate-950/60 dark:bg-slate-950 dark:text-slate-50">
 <header className="mb-4 flex items-center justify-between gap-3"><h2 id="automatic-wiki-title" className="text-xl font-semibold">{t('automaticWiki.title')}</h2><button className={control} onClick={onClose}>{t('organization.close')}</button></header>
 <p className="mb-4 text-sm text-slate-500">{t('automaticWiki.intro')}</p>{error&&<p role="alert" className="my-3 text-rose-600">{t(error)} <button className="underline" onClick={()=>void act(refresh)}>{t('shell.actions.retry')}</button></p>}
 {loading?<p role="status">{t('shell.states.loading')}</p>:<div className="grid gap-4">
 <label className="grid gap-1 text-sm">{t("automaticWiki.policy")}<select className={control} value={policy?.id??""} disabled={busy} onChange={e=>choose(policies.find(p=>p.id===e.target.value)??null)}><option value="">{t("automaticWiki.newPolicy")}</option>{policies.map((p,i)=><option key={p.id} value={p.id}>{p.scope.wholeLibrary?t("wiki.wholeLibrary"):t("organization.sourceScope")+" "+(i+1)} · {t(p.state==='paused'?'automaticWiki.coverageStates.paused':'automaticWiki.enabled')}</option>)}</select></label><fieldset disabled={busy} className="grid gap-4"><label className="flex gap-2 text-sm"><input type="checkbox" checked={wholeLibrary} onChange={e=>{setWholeLibrary(e.target.checked);setPreview(null);}}/>{t("automaticWiki.wholeLibrary")}</label><EvidenceScopePicker hint="automaticWiki.scopeHint" selected={selected} onChange={ids=>{setSelected(ids);setPreview(null);setNoteIds([]);}} t={t}/><label className="flex gap-2 text-sm"><input type="checkbox" checked={descendants} onChange={e=>{setDescendants(e.target.checked);setPreview(null);}}/>{t("consultation.descendants")}</label><details><summary className="cursor-pointer text-sm">{t("automaticWiki.excludedSources")} ({excluded.length})</summary><EvidenceScopePicker hint="automaticWiki.excludedHint" selected={excluded} onChange={ids=>{setExcluded(ids);setPreview(null);}} t={t}/></details><ProfilePicker profiles={profiles} value={profile} onChange={id=>{setProfile(id);setPreview(null);}} t={t}/>
 <details><summary className="cursor-pointer text-sm">{t('automaticWiki.existingNotes')} ({noteIds.length})</summary><p className="my-2 text-xs text-slate-500">{t('automaticWiki.originals')}</p>{notes.map(n=><label key={n.id} className="flex gap-2 py-2 text-sm"><input type="checkbox" checked={noteIds.includes(n.id)} onChange={e=>setNoteIds(ids=>e.target.checked?[...ids,n.id]:ids.filter(id=>id!==n.id))}/><span>{n.title}</span></label>)}</details>
 <button className={control} disabled={!selected.length&&!wholeLibrary} onClick={()=>void act(async()=>setPreview(CuratorPreviewSchema.parse(await window.app.curator.command({command:'preview',input:{timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,...(policy?{policyId:policy.id}:{}),wholeLibrary,sourceIds:selected,includeDescendants:descendants,excludedSourceIds:excluded,profileOverrideId:profile||null,limits:initialCuratorLimits}}))))}>{t('automaticWiki.preview')}</button>
 </fieldset>
 {preview&&<section className="rounded-xl border border-cyan-500/30 p-4"><h3 className="font-semibold">{t('automaticWiki.authority')}</h3><ul className="my-3 list-inside list-disc text-sm">{preview.sourceTitles.map(s=><li key={s.id}>{s.title}</li>)}</ul><p className="text-sm">{t('automaticWiki.limits',{values:{targets:preview.policy.limits.targets,sections:preview.policy.limits.sectionPatchesPerPage,passages:preview.policy.limits.originalPassages,calls:preview.policy.limits.modelCalls,minutes:preview.policy.limits.deadlineMs/60000}})}</p><p className="my-2 text-sm">{preview.profile?.modelId??t('organization.errors.model')}</p><p className="mb-3 text-xs text-slate-500">{t('automaticWiki.permission')}</p><p className="mb-3 text-xs text-slate-500">{t('investigation.explanation')}</p>{preview.maintenance&&<AutomaticMaintenancePreview preview={preview.maintenance} provider={preview.profile?.provider??null} t={t}/>} {onPrompts&&<button className={control} onClick={()=>{onClose();onPrompts();}}>{t('prompts.open')}</button>}<button disabled={busy} className={control} onClick={()=>void act(async()=>setPolicy(AutomaticWikiPolicySchema.parse(await window.app.curator.command({command:'activate',policyId:preview.policy.id,revisionId:preview.policy.revisionId,previewHash:preview.previewHash}))))}>{t('automaticWiki.activate')}</button></section>}
 {changed&&<p role="status" className="text-sm text-amber-700 dark:text-amber-300">{t("automaticWiki.previewChanges")}</p>}
 {policy&&<div className="flex flex-wrap items-center gap-3"><span className="text-sm">{t(policy.state==='paused'?'automaticWiki.coverageStates.paused':'automaticWiki.enabled')}</span><button disabled={busy||changed||policy.state!=='enabled'||!selected.length} className={control+' bg-cyan-100 dark:bg-cyan-950'} onClick={()=>void act(async()=>{await window.app.curator.command({command:'start',input:{policyId:policy.id,policyRevisionId:policy.revisionId,sourceIds:selected,noteIds}});})}>{t('automaticWiki.run')}</button><button disabled={busy} className={control} onClick={()=>void act(async()=>{await window.app.curator.command({command:policy.state==='paused'?'resume':'pause',policyId:policy.id});setPolicy(null);setPreview(null);})}>{t(policy.state==='paused'?'automaticWiki.resume':'automaticWiki.pause')}</button></div>}
 {policy&&<AutomaticMaintenancePanel policyId={policy.id} t={t}/>}
 {policy&&<WikiBootstrapPanel disabledStart={changed} noteIds={noteIds} policy={policy} t={t} onScopeConflict={ids=>{setSelected(current=>[...new Set([...current,...ids])]);setExcluded(current=>current.filter(id=>!ids.includes(id)));setPreview(null);}}/>}
 {runs.map(run=><details key={run.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-800" open={['queued','analyzing','awaiting_review','failed'].includes(run.status)}><summary className="cursor-pointer font-medium">{run.proposal?.targets[0]?.title??t('automaticWiki.title')} · {t(`organization.${run.status}`)}</summary>{run.checkpoint.error&&<p className="my-2 text-sm text-amber-600">{t(run.checkpoint.error as MessageKey)}</p>}{run.snapshot.participation?.omissions.length?<p role="status" className="my-2 text-sm text-amber-700 dark:text-amber-300">{t('consultation.partial')} · {run.snapshot.participation.omissions.map(o=>t(`jobs.stages.${o.stage}` as MessageKey)).join(', ')}</p>:null}{run.checkpoint.validationIssues.length>0&&<ul className="my-3 list-inside list-disc text-sm text-amber-700 dark:text-amber-300">{run.checkpoint.validationIssues.map((issue,i)=><li key={i}>{issue.message}</li>)}</ul>}{run.proposal&&<div className="mt-3 grid gap-4"><p className="text-sm">{run.proposal.explanation}</p>{run.proposal.targets.map(target=><section key={target.handle}><h4 className="font-semibold">{target.title}</h4><p className="text-xs text-slate-500">{target.purpose}</p>{target.sections.map((s,i)=><div key={i} className="mt-2 grid gap-2">{s.sectionId&&<section className="rounded-lg bg-slate-100 p-3 dark:bg-slate-900"><p className="mb-2 text-xs font-medium">{t('organization.before')}</p><MarkdownPreview markdown={run.snapshot.pages.find(p=>p.id===target.pageId)?.sections.find(old=>old.id===s.sectionId)?.markdown??''} emptyLabel=""/></section>}<p className="text-xs font-medium">{t(s.sectionId?'organization.after':'organization.newSection')} · {s.title}</p><MarkdownPreview markdown={s.markdown} emptyLabel=""/>{s.originalHandles.map(h=>{const e=run.snapshot.evidence.find(e=>e.handle===h);return e&&<details key={h}><summary className="cursor-pointer text-xs">{e.sourceTitle}</summary><blockquote className="whitespace-pre-wrap text-sm">{e.excerpt}</blockquote></details>;})}</div>)}{target.tocGroups.map(g=><section key={g.handle} className="mt-2 rounded-lg border border-slate-200 p-3 text-sm dark:border-slate-700"><h5 className="font-medium">{g.title} · {g.memberships.length} {t('automaticWiki.links')}</h5>{g.explanation&&<MarkdownPreview markdown={g.explanation} emptyLabel=""/>}<ol className="mt-2 list-inside list-decimal">{g.memberships.toSorted((a,b)=>a.order-b.order).map((m,i)=><li key={i}>{m.target.reference==='proposed'?run.proposal!.targets.find(t=>t.handle===(m.target as {handle:string}).handle)?.title:run.snapshot.references.find(r=>r.id===(m.target as {target:{id:string}}).target.id)?.title}</li>)}</ol></section>)}</section>)}</div>}
 <p className="my-3 text-xs text-slate-500">{run.snapshot.optionalReferenceCoverage.omittedEntities>0&&<span>{t("consultation.partial")} · {t("wiki.results.entity")}: {run.snapshot.optionalReferenceCoverage.includedEntities}/{run.snapshot.optionalReferenceCoverage.includedEntities+run.snapshot.optionalReferenceCoverage.omittedEntities} · </span>}{run.snapshot.profile.modelId} · {t('organization.modelCalls')}: {run.checkpoint.calls} · {t('organization.inputTokens')}: {run.checkpoint.usageCounts.input?run.checkpoint.reportedInputTokens:t('organization.unavailable')} · {t('organization.outputTokens')}: {run.checkpoint.usageCounts.output?run.checkpoint.reportedOutputTokens:t('organization.unavailable')} · {t('organization.estimatedCost')}: {run.checkpoint.usageCounts.cost?run.checkpoint.costEstimate:t('organization.unavailable')}</p>{run.checkpoint.usageIncomplete&&<p className="text-xs">{t('organization.usageIncomplete')}</p>}
 <div className="flex flex-wrap gap-2">{run.status==='awaiting_review'&&(['accept','reject']as const).map(command=><button disabled={busy} className={control} key={command} onClick={()=>void act(async()=>{await window.app.curator.command({command,id:run.id});})}>{t(`organization.${command}`)}</button>)}{['queued','analyzing','awaiting_review'].includes(run.status)&&<button disabled={busy} className={control} onClick={()=>void act(async()=>{await window.app.curator.command({command:'cancel',id:run.id});})}>{t('organization.cancel')}</button>}</div></details>)}
 </div>}
 </dialog>;
}
