import {useEffect,useState} from 'react';
import {AutomaticWikiPolicySchema,type AutomaticWikiPolicy,type ConsultationResult,type FollowedInvestigation} from '@app/domain';
import type {Translator,MessageKey} from '@app/i18n';
const control='rounded-lg border border-slate-200 px-3 py-2 text-sm focus-visible:ring-2 focus-visible:ring-cyan-500 disabled:opacity-40 dark:border-slate-700';
export function FollowedQuestions({t,result,active,onSelect}:{t:Translator;result:ConsultationResult|null;active:boolean;onSelect:(result:ConsultationResult)=>void}){
 const [items,setItems]=useState<FollowedInvestigation[]>([]),[policies,setPolicies]=useState<AutomaticWikiPolicy[]>([]),[policy,setPolicy]=useState(''),[selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState<MessageKey|null>(null);
 useEffect(()=>{if(!active)return;let live=true;const load=async()=>{try{const rows=await window.app.investigations.list();if(live)setItems(rows);}catch{if(live)setError('organization.errors.failed');}finally{if(live)setLoading(false);}};void load();void window.app.curator.command({command:'policies'}).then(raw=>{if(live&&Array.isArray(raw))setPolicies(raw.map(p=>AutomaticWikiPolicySchema.parse(p)).filter(p=>p.state==='enabled'&&p.operations.includes('refresh_investigation')));}).catch(()=>{if(live)setError('organization.errors.failed');});const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},10000);return()=>{live=false;clearInterval(timer);};},[active]);
 const current=items.find(i=>i.id===selected),retained=result&&items.some(i=>i.current.id===result.id||i.history.some(h=>h.result?.id===result.id));
 async function act(work:()=>Promise<FollowedInvestigation|null>,select=false){setBusy(true);setError(null);try{const item=await work();if(item){setItems(rows=>[item,...rows.filter(i=>i.id!==item.id)]);setSelected(item.id);if(select)onSelect(item.current);}}catch(e){setError(String(e).match(/(?:organization|wiki|maintenance)\.errors\.[A-Za-z]+/)?.[0] as MessageKey??'organization.errors.failed');}finally{setBusy(false);}}
 return <section className="grid gap-3 border-t border-slate-200 pt-4 dark:border-slate-800"><h3 className="font-medium">{t('investigation.title')}</h3><p className="text-sm text-slate-500">{t('investigation.explanation')}</p>{error&&<p role="alert" className="text-sm text-red-600">{t(error)}</p>}{loading?<p role="status">{t('organization.loading')}</p>:<>
 {result&&!retained&&<div className="flex flex-wrap items-center gap-2"><label className="grid gap-1 text-sm">{t('investigation.policy')}<select className={control} value={policy} disabled={busy} onChange={e=>setPolicy(e.target.value)}><option value="">{t('investigation.choosePolicy')}</option>{policies.map(p=><option key={p.id} value={p.id}>{p.scope.wholeLibrary?t('consultation.libraryScope'):t('consultation.sourceCount',{values:{count:p.scope.sourceIds.length}})} · {p.id.slice(0,8)}</option>)}</select></label><button className={control} disabled={!policy||busy||result.coverage.stale} onClick={()=>void act(()=>window.app.investigations.follow({answerId:result.id,policyId:policy}),true)}>{t('investigation.follow')}</button>{!policies.length&&<p className="text-sm text-amber-700 dark:text-amber-300">{t('investigation.noPolicy')}</p>}</div>}
 {!items.length?<p className="text-sm text-slate-500">{t('investigation.empty')}</p>:<div className="flex flex-wrap gap-x-4 gap-y-2">{items.map(i=><button key={i.id} className="text-left text-sm text-cyan-700 underline-offset-4 hover:underline focus-visible:ring-2 dark:text-cyan-300" onClick={()=>{setSelected(i.id);onSelect(i.current);}}>{i.question} · {t(`investigation.${i.state}`)}</button>)}</div>}
 {current&&<div className="grid gap-3"><p className="text-sm">{t(`investigation.${current.state}`)} · {t('consultation.sourceCount',{values:{count:current.current.coverage.sourceCount}})}</p>{current.attention&&<p role="alert" className="text-sm text-amber-700 dark:text-amber-300">{t(current.attention as MessageKey)}</p>}<div className="flex flex-wrap gap-2"><button className={control} onClick={()=>onSelect(current.current)}>{t('investigation.current')}</button>{(['paused','resolved','followed'] as const).filter(state=>state!==current.state).map(state=><button key={state} className={control} disabled={busy} onClick={()=>void act(()=>window.app.investigations.state({id:current.id,expectedRevision:current.revision,state}))}>{t(state==='paused'?'investigation.pause':state==='resolved'?'investigation.resolve':'investigation.resume')}</button>)}</div><details><summary className="cursor-pointer text-sm">{t('investigation.history')}</summary><div className="mt-3 grid gap-3">{current.history.map(h=><div key={h.id} className="text-sm"><p className="text-xs text-slate-500">{new Date(h.createdAt).toLocaleString()} · {t(`investigation.historyState.${h.status}`)}</p>{h.changedUnderstanding.map((text,i)=><p key={i} className="mt-1">{text}</p>)}<div className="mt-1 flex flex-wrap gap-3">{h.result&&<button className="text-cyan-700 hover:underline focus-visible:ring-2 dark:text-cyan-300" onClick={()=>onSelect(h.result!)}>{t('investigation.viewAnswer')}</button>}{h.previous&&<button className="text-cyan-700 hover:underline focus-visible:ring-2 dark:text-cyan-300" onClick={()=>onSelect(h.previous!)}>{t('investigation.previous')}</button>}</div></div>)}</div></details></div>}
 </>}</section>;
}
