import type {InterpretationRecord,InterpretationDraftSchema} from '@app/domain';
import type {z} from 'zod';
import type {Translator,MessageKey} from '@app/i18n';
export function KnowledgeInterpretations({items,t}:{items:Array<InterpretationRecord|z.infer<typeof InterpretationDraftSchema>>|undefined;t:Translator}){
 if(!items?.length)return null;
 const stamp=(value:string)=>new Intl.DateTimeFormat(t.locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));
 const day=(value:string)=>new Intl.DateTimeFormat(t.locale,{dateStyle:'medium',timeZone:'UTC'}).format(new Date(value));
 const date=(value:InterpretationRecord['eventTime'])=>!value?t('knowledgeEvolution.unknown'):value.precision==='year'?value.value:value.precision==='month'?new Intl.DateTimeFormat(t.locale,{year:'numeric',month:'long',timeZone:'UTC'}).format(new Date(value.value+'-01T00:00:00Z')):value.precision==='day'?day(value.value):stamp(value.value);
 return <div className="my-3 grid min-w-0 gap-3">{items.map((record,index)=>{const historical='revisionId'in record&&items.some(next=>next.relationships.some(r=>r.kind==='supersedes'&&r.revisionId===record.revisionId));return <details key={'revisionId'in record?record.revisionId:index} className="min-w-0 rounded-lg border border-slate-200 p-3 text-sm dark:border-slate-700"><summary className="cursor-pointer font-medium">{t('knowledgeEvolution.title')} · {t(('knowledgeEvolution.'+(historical?'historical':record.context))as MessageKey)} · {t(('knowledgeEvolution.'+record.perspective)as MessageKey)}</summary><p className="my-3 whitespace-pre-wrap">{record.statement}</p><dl className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)] gap-2">{(['eventTime','validFrom','validUntil','publicationTime']as const).map(key=><div key={key} className="contents"><dt>{t(('knowledgeEvolution.'+key)as MessageKey)}</dt><dd className="break-words">{date(record[key])}</dd></div>)}</dl>{'sourceDates'in record&&record.sourceDates?.filter(s=>s.noteDate).map(s=><p className="mt-2 text-xs" key={s.sourceItemId}>{t('knowledgeEvolution.noteDate')}: {day(s.noteDate!)}</p>)}{'recordedAt'in record&&<p className="my-2 break-words text-xs">{t('knowledgeEvolution.recordedAt')}: {record.recordedAt.map(r=>stamp(r.at)).join(', ')}<br/>{t('knowledgeEvolution.revisedAt')}: {stamp(record.revisedAt)}</p>}{record.procedure&&(['steps','workedWhen','assumptions','limits','corrections']as const).filter(key=>!Array.isArray(record.procedure![key])||(record.procedure![key]as string[]).length>0).map(key=><section className="mt-3" key={key}><h5 className="font-medium">{t(('knowledgeEvolution.'+key)as MessageKey)}</h5>{Array.isArray(record.procedure![key])?<ul className="list-inside list-disc">{(record.procedure![key]as string[]).map((text,i)=><li key={i}>{text}</li>)}</ul>:<p>{record.procedure![key]}</p>}</section>)}{record.relationships.map((r,i)=><p className="mt-2 break-words text-xs" key={i}>{t(('knowledgeEvolution.'+r.kind)as MessageKey)} · {r.reason} · {r.revisionId}</p>)}{'evidence'in record&&record.evidence.map(e=><details className="mt-2" key={e.chunkId}><summary className="cursor-pointer">{t('knowledgeEvolution.evidence')} · {e.sourceTitle}</summary><blockquote className="mt-2 whitespace-pre-wrap border-l-2 pl-3">{e.excerpt}</blockquote></details>)}</details>;})}</div>;
}
