import { useEffect, useRef, useState } from "react";
import { BookOpen, FileWarning, X } from "lucide-react";
import type { MessageKey } from "@app/i18n";
import { EvidenceScopePicker } from "./OrganizationView";
import { Button } from "./ui/button";
type Translator=(key:MessageKey)=>string;
type Status=Awaited<ReturnType<typeof window.app.obsidian.wikiStatus>>;
type Diff=Awaited<ReturnType<typeof window.app.obsidian.wikiDiff>>;
const control="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm dark:border-slate-700 dark:bg-slate-950";
export function ObsidianWikiCard({t}:{t:Translator}) {
  const [status,setStatus]=useState<Status|null>(null),[scope,setScope]=useState<Status['scope']|null>(null),[pages,setPages]=useState<Array<{id:string;title:string}>>([]),[error,setError]=useState<MessageKey|null>(null),[busy,setBusy]=useState(false),[diff,setDiff]=useState<Diff|null>(null);
  useEffect(()=>{void Promise.all([window.app.obsidian.wikiStatus(),window.app.wiki.list()]).then(([value,list])=>{setStatus(value);setScope(value.scope);setPages(list);}).catch(()=>setError("obsidianWiki.errors.load"));const timer=setInterval(()=>void window.app.obsidian.wikiStatus().then(setStatus).catch(()=>setError("obsidianWiki.errors.load")),3000);return()=>clearInterval(timer);},[]);
  async function action(work:()=>Promise<void>){setBusy(true);setError(null);try{await work();}catch(error){const message=String(error);setError(message.includes("conflict")?"obsidianWiki.errors.conflict":message.includes("paused")?"obsidianWiki.errors.paused":message.includes("binding")?"obsidianWiki.errors.binding":message.includes("write")?"obsidianWiki.errors.write":"obsidianWiki.errors.load");}finally{setBusy(false);}}
  return <section className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900"><h3 className="flex items-center gap-2 font-semibold"><BookOpen size={18}/>{t('obsidianWiki.title')}</h3><p className="text-sm text-slate-500">{t('obsidianWiki.readOnly')} {t('obsidianWiki.queued')}</p>{error&&<p role="alert" className="text-sm text-red-600">{t(error)}</p>}{status?.job&&<p role="status" className="text-sm">{t(`jobs.status.${status.job.status}`)}{status.job.error&&<span className="ml-2 text-red-600">{t((['conflict','binding','paused','limit','format','write'].map(key=>`obsidianWiki.errors.${key}`).find(key=>status.job!.error!.includes(key))??'obsidianWiki.errors.write') as MessageKey)}</span>}</p>}{!status?<p role="status">{t('obsidianWiki.loading')}</p>:<><details><summary className="cursor-pointer text-sm font-medium">{t('obsidianWiki.scope')}</summary>{scope&&<fieldset disabled={busy} className="mt-4 grid gap-4"><EvidenceScopePicker selected={scope.sourceIds} onChange={sourceIds=>setScope({...scope,sourceIds})} t={t} hint="obsidianWiki.allSources"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={scope.includeDescendants} onChange={e=>setScope({...scope,includeDescendants:e.target.checked})}/>{t('obsidianWiki.descendants')}</label><label className="grid gap-2 text-sm">{t('obsidianWiki.pageIds')}<span className="text-xs text-slate-500">{t('obsidianWiki.allPages')}</span><select multiple className={`${control} h-32`} value={scope.pageIds} onChange={e=>setScope({...scope,pageIds:Array.from(e.target.selectedOptions,o=>o.value)})}>{pages.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><Button className="justify-self-start" onClick={()=>void action(async()=>{setScope(await window.app.obsidian.saveWikiScope(scope));setStatus(await window.app.obsidian.wikiStatus());})}>{t('obsidianWiki.saveScope')}</Button></fieldset>}</details>{status.conflicts.length?<div className="grid gap-2"><h4 className="flex items-center gap-2 text-sm font-medium"><FileWarning size={16}/>{t('obsidianWiki.pending')}</h4>{status.conflicts.map(c=><div key={c.id} className="flex min-w-0 items-center gap-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><span className="min-w-0 flex-1 break-words text-xs">{c.relative_path}</span><Button disabled={busy} onClick={()=>void action(async()=>setDiff(await window.app.obsidian.wikiDiff(c.id)))}>{t('obsidianWiki.review')}</Button></div>)}</div>:<p className="text-sm text-slate-500">{t('obsidianWiki.empty')}</p>}</>}{diff&&<ProjectionDiff error={error} t={t} diff={diff} busy={busy} active={status?.active??false} onClose={()=>setDiff(null)} onRecover={()=>void action(async()=>{setStatus(await window.app.obsidian.recoverWiki({id:diff.id,expectedHash:diff.localHash}));setDiff(null);})}/>}</section>;
}
function ProjectionDiff({t,diff,busy,active,error,onClose,onRecover}:{error:MessageKey|null;t:Translator;diff:Diff;busy:boolean;active:boolean;onClose:()=>void;onRecover:()=>void}){const dialog=useRef<HTMLDialogElement>(null);useEffect(()=>{const focus=document.activeElement;dialog.current?.showModal();return()=>{dialog.current?.close();if(focus instanceof HTMLElement)focus.focus();};},[]);return <dialog ref={dialog} aria-labelledby="projection-diff-title" onKeyDown={e=>{if(e.key==='Escape')e.stopPropagation();}} onCancel={e=>{e.preventDefault();onClose();}} className="fixed inset-0 m-auto max-h-[calc(100dvh-2rem)] w-[calc(100%-2rem)] max-w-6xl overflow-auto rounded-2xl bg-slate-50 p-5 text-slate-950 backdrop:bg-slate-950/60 dark:bg-slate-950 dark:text-slate-50"><header className="flex items-center gap-3"><h2 id="projection-diff-title" className="min-w-0 flex-1 break-words font-semibold">{diff.relativePath}</h2><Button autoFocus aria-label={t('organization.close')} onClick={onClose}><X size={18}/></Button></header><p className="my-4 text-sm text-slate-500">{t('obsidianWiki.recoveryHint')}</p>{error&&<p role="alert" className="mb-4 text-sm text-red-600">{t(error)}</p>}<div className="grid gap-3 lg:grid-cols-3">{(['base','local','proposed'] as const).map(kind=><section key={kind} className="min-w-0"><h3 className="mb-2 text-sm font-semibold">{t(`obsidianWiki.${kind}`)}</h3><pre className="max-h-[50vh] overflow-auto whitespace-pre-wrap break-words rounded-xl border border-slate-200 bg-white p-3 text-xs dark:border-slate-800 dark:bg-slate-900">{diff[kind]}</pre></section>)}</div><Button className="mt-4" disabled={busy||!active} onClick={onRecover}>{t('obsidianWiki.recover')}</Button></dialog>;}
