import { SourceRelationReferenceText } from "./SourceRelationReferenceText";
import { SourceRelationsList } from "./SourceRelationsList";
import { useCallback, useEffect, useRef, useState } from "react";
import { BookOpen, Check, ChevronDown, FlaskConical, History, LoaderCircle, Plus, RotateCcw, Settings2, ShieldCheck, Sparkles, X } from "lucide-react";
import { z } from "zod";
import { organizationCitationMarkdown, OrganizationSettingsSchema, OrganizationRunSchema, OrganizationRunSummarySchema, OrganizationConfigurationSchema, OrganizationStartSchema, defaultOrganizationConfiguration, resolveOrganizationInstructions, type OrganizationConfiguration, type OrganizationRun, type OrganizationRunSummary, type OrganizationCommand, type WikiPage, type WikiResult } from "@app/domain";
import type { MessageKey, Translator } from "@app/i18n";
import type { AiProfile } from "../../shared/ipc";
import { MarkdownEditor, MarkdownPreview } from "./MarkdownEditor";
const card="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900";
const control="rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus-visible:ring-2 focus-visible:ring-cyan-500 disabled:opacity-40 dark:border-slate-700 dark:bg-slate-900";
const primary=`${control} inline-flex items-center justify-center gap-2 border-cyan-700 bg-cyan-700 text-white dark:bg-cyan-700`;
const command=(input:OrganizationCommand)=>window.app.organization.command(input);
const errorKey=(e:unknown):MessageKey=>String(e).match(/organization\.errors\.[A-Za-z]+/)?.[0] as MessageKey??'organization.errors.failed';
type Settings=z.infer<typeof OrganizationSettingsSchema>;
type PageSummary=Omit<WikiPage,'sections'|'evidence'|'breadcrumbs'>;
function EvidenceScopePicker({selected,onChange,t}:{selected:string[];onChange:(ids:string[])=>void;t:Translator}){
  const [items,setItems]=useState<WikiResult[]>([]),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);
  useEffect(()=>{let current=true;setLoading(true);setFailed(false);const timer=setTimeout(()=>void window.app.wiki.search({kind:'source',text:query,offset,limit:30}).then(result=>{if(current){setItems(result.items);setMore(result.hasMore);}}).catch(()=>{if(current)setFailed(true);}).finally(()=>{if(current)setLoading(false);}),150);return()=>{current=false;clearTimeout(timer);};},[query,offset,retry]);
  return <div className="grid gap-2"><label className="grid gap-1 text-sm">{t('organization.sourceScope')}<input className={control} aria-label={t('wiki.search')} placeholder={t('wiki.search')} value={query} onChange={e=>{setQuery(e.target.value);setOffset(0);}}/></label><p className="text-xs text-slate-500">{t('organization.scopeHint')} · {selected.length}/100</p>{failed?<p role="alert" className="text-sm text-red-600">{t('organization.errors.failed')} <button className={control} onClick={()=>setRetry(v=>v+1)}>{t('organization.refresh')}</button></p>:loading?<p role="status" className="text-sm">{t('organization.loading')}</p>:<div className="grid max-h-48 gap-1 overflow-auto rounded-lg border border-slate-200 p-2 dark:border-slate-800 sm:grid-cols-2">{items.map(item=><label key={item.id} className="flex min-w-0 items-center gap-2 rounded p-2 text-sm hover:bg-slate-100 dark:hover:bg-slate-800"><input type="checkbox" checked={selected.includes(item.id)} disabled={!selected.includes(item.id)&&selected.length>=100} onChange={e=>onChange(e.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/><span className="truncate">{item.title}</span></label>)}{!items.length&&<p className="text-sm text-slate-500">{t('organization.errors.noEvidence')}</p>}</div>}<div className="flex gap-2"><button className={control} disabled={loading||offset===0} onClick={()=>setOffset(v=>Math.max(0,v-30))}>{t('sourceRelations.previous')}</button><button className={control} disabled={loading||!more} onClick={()=>setOffset(v=>v+30)}>{t('sourceRelations.next')}</button></div></div>;
}
function ProfilePicker({profiles,value,onChange,privacy,onPrivacy,t}:{profiles:AiProfile[];value:string;onChange:(s:string)=>void;privacy:'offline_only'|'allow_remote';onPrivacy:(v:'offline_only'|'allow_remote')=>void;t:Translator}){
  return <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-sm">{t('organization.profile')}<select className={control} value={value} onChange={e=>onChange(e.target.value)}><option value="">{t('organization.profile')}</option>{profiles.filter(p=>p.status==='active'&&p.capabilities.includes('structured-output')).map(p=><option key={p.id} value={p.id}>{p.name} · {p.modelId}</option>)}</select></label><label className="grid gap-1 text-sm">{t('organization.offline')}<select className={control} value={privacy} onChange={e=>onPrivacy(e.target.value as typeof privacy)}><option value="offline_only">{t('organization.offline')}</option><option value="allow_remote">{t('organization.remote')}</option></select></label>{privacy==='allow_remote'&&<p className="text-xs text-amber-700 sm:col-span-2 dark:text-amber-300">{t('organization.remoteHint')}</p>}{!profiles.some(p=>p.capabilities.includes('structured-output'))&&<p className="text-sm text-amber-600 sm:col-span-2">{t('organization.noModel')}</p>}</div>;
}
function RunCard({summary,t,refresh}:{summary:OrganizationRunSummary;t:Translator;refresh:()=>Promise<void>}){
  const [run,setRun]=useState<OrganizationRun|null>(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState<MessageKey|null>(null),[open,setOpen]=useState(false);
  useEffect(()=>{if(!open)return;let active=true;void command({command:'get',id:summary.id}).then(value=>{if(active)setRun(OrganizationRunSchema.parse(value));}).catch(e=>{if(active)setError(errorKey(e));});return()=>{active=false;};},[open,summary.id,summary.updatedAt]);
  async function act(input:OrganizationCommand){setBusy(true);setError(null);try{await command(input);await refresh();}catch(e){setError(errorKey(e));}finally{setBusy(false);}}
  if(!run)return <article className={card}><button className="flex w-full items-center justify-between gap-3 text-left" aria-expanded={open} onClick={()=>setOpen(!open)}><span><strong className="block">{summary.title}</strong><span className="text-xs text-slate-500">{t(`organization.${summary.receiptRevisionId?'applied':summary.status==='analyzing'&&summary.modelState==='waiting'?'waitingModel':summary.status}`)} · {new Date(summary.createdAt).toLocaleString()}</span></span>{open?<LoaderCircle size={18} className="animate-spin"/>:<ChevronDown size={18}/>}</button>{error&&<p role="alert" className="mt-3 text-sm text-red-600">{t(error)}</p>}</article>;
  const proposal=run.proposal?.tool==='proposePageChange'?run.proposal:null;
  return <article className={card}>
    <button className="flex w-full items-start gap-3 text-left" onClick={()=>setOpen(!open)} aria-expanded={open}><span className="rounded-xl bg-cyan-50 p-2 text-cyan-700 dark:bg-cyan-950"><Sparkles size={18}/></span><span className="min-w-0 flex-1"><strong className="block truncate">{run.snapshot.baseContent.title}</strong><span className="text-xs text-slate-500">{t(`organization.${summary.receiptRevisionId?'applied':summary.status}`)} · {new Date(run.createdAt).toLocaleString()}</span></span>{['queued','analyzing'].includes(run.status)?<LoaderCircle size={18} className="animate-spin"/>:<ChevronDown size={18}/>}</button>
    {open&&<div className="mt-4 grid gap-4">
      {run.checkpoint.error&&<p role="status" className="text-sm text-amber-700 dark:text-amber-300">{t(errorKey(run.checkpoint.error))}</p>}
      {proposal&&<><p className="text-sm text-slate-600 dark:text-slate-300">{proposal.explanation}</p>{proposal.sections.map((op,i)=><section key={i} className={`grid gap-3 border-t border-slate-200 pt-4 dark:border-slate-800 ${op.sectionId?"lg:grid-cols-2":""}`} >{op.sectionId&&<div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-950"><p className="mb-2 text-xs font-semibold uppercase text-slate-500">{t('organization.before')} · {run.snapshot.baseContent.sections.find(s=>s.id===op.sectionId)?.title}</p><MarkdownPreview emptyLabel={t("organization.newSection")} markdown={run.snapshot.baseContent.sections.find(s=>s.id===op.sectionId)?.markdown??t('organization.newSection')}/></div>}<div className="rounded-xl bg-cyan-50/60 p-4 dark:bg-cyan-950/20"><p className="mb-2 text-xs font-semibold uppercase text-cyan-700 dark:text-cyan-300">{t(op.sectionId?'organization.after':'organization.newSection')} · {op.title}</p><MarkdownPreview emptyLabel={t("organization.newSection")} markdown={organizationCitationMarkdown(op)}/><div className="mt-3 grid gap-2">{op.citations.map((h,citationIndex)=>{const e=run.snapshot.evidence.find(e=>e.handle===h);return e&&<details key={h} className="text-xs"><summary className="cursor-pointer font-medium">[{citationIndex+1}] {e.sourceTitle}</summary><blockquote className="mt-2 whitespace-pre-wrap border-l-2 border-cyan-300 pl-3 text-slate-600 dark:text-slate-300">{e.excerpt}</blockquote><span className="text-slate-500">{e.documentCreatedAt} · {e.locator}</span></details>;})}</div></div></section>)}</>}
      {!!run.snapshot.relations.length&&<details className="text-sm"><summary className="cursor-pointer">{t('organization.relations')} ({run.snapshot.relations.length})</summary><p className="my-2 text-xs text-slate-500">{t('organization.relationHint')}</p>{run.snapshot.relations.map(r=><div key={r.id} className="my-2 rounded-lg border border-slate-200 p-3 dark:border-slate-800"><span className="text-xs">{t(`sourceRelations.${r.review}` as MessageKey)}</span><p><SourceRelationReferenceText text={r.sourceIdea+' → '+r.targetIdea} relation={{...r,sourceTitle:run.snapshot.evidence.find(e=>e.handle===r.sourceHandle)?.sourceTitle??'',targetTitle:run.snapshot.evidence.find(e=>e.handle===r.targetHandle)?.sourceTitle??''}}/></p><p className="mt-1 text-xs text-slate-500"><SourceRelationReferenceText text={r.explanation} relation={{...r,sourceTitle:run.snapshot.evidence.find(e=>e.handle===r.sourceHandle)?.sourceTitle??'',targetTitle:run.snapshot.evidence.find(e=>e.handle===r.targetHandle)?.sourceTitle??''}}/></p><SourceRelationsList sourceItemId={r.sourceItemId} targetSourceItemId={r.targetSourceItemId} relationId={r.id} t={t}/></div>)}</details>}
      <details className="text-xs text-slate-500"><summary className="cursor-pointer">{t('organization.usage')}</summary><dl className="mt-2 grid gap-1"><div>{run.snapshot.profile.modelId} · {run.snapshot.profile.runtime} · {t(run.snapshot.profile.privacy==='offline_only'?'organization.offline':'organization.remote')}</div><div>{t('organization.modelCalls')}: {run.checkpoint.calls}/{run.snapshot.limits.modelCalls} · {t('organization.toolCalls')}: {run.checkpoint.tools}/{run.snapshot.limits.tools}</div><div>{t('organization.inputTokens')}: {run.checkpoint.usageCounts.input?run.checkpoint.reportedInputTokens:t('organization.unavailable')} · {t('organization.outputTokens')}: {run.checkpoint.usageCounts.output?run.checkpoint.reportedOutputTokens:t('organization.unavailable')}</div><div>{t('organization.estimatedCost')}: {run.checkpoint.usageCounts.cost?run.checkpoint.costEstimate.toFixed(4):t('organization.unavailable')}</div><div>{run.snapshot.contentLanguage} · {run.snapshot.configurationHash.slice(0,12)}</div></dl>{run.checkpoint.usageIncomplete&&<p className="mt-2">{t('organization.usageIncomplete')}</p>}<pre className="mt-3 max-h-52 overflow-auto whitespace-pre-wrap">{JSON.stringify(run.snapshot.instructions,null,2)}</pre></details>
      {error&&<p role="alert" className="text-sm text-red-600">{t(error)}</p>}
      <div className="flex flex-wrap gap-2">{run.status==='awaiting_review'&&!run.receiptRevisionId&&<><button disabled={busy} className={primary} onClick={()=>void act({command:'review',id:run.id,decision:'accept'})}><Check size={16}/>{t('organization.accept')}</button><button disabled={busy} className={control} onClick={()=>void act({command:'review',id:run.id,decision:'reject'})}>{t('organization.reject')}</button></>}{['queued','analyzing','awaiting_review'].includes(run.status)&&!run.receiptRevisionId&&<button disabled={busy} className={control} onClick={()=>void act({command:'cancel',id:run.id})}>{t('organization.cancel')}</button>}{(run.status==='canceled'||run.status==='failed'&&['organization.errors.failed','organization.errors.uncertain'].includes(run.checkpoint.error??''))&&<button disabled={busy} className={control} onClick={()=>void act({command:'retry',id:run.id})}>{t('organization.retry')}</button>}</div>
    </div>}
  </article>;
}
export function OrganizationRuns({t,refreshKey=0,onRefresh}:{t:Translator;refreshKey?:number;onRefresh?:()=>void}){
  const [runs,setRuns]=useState<OrganizationRunSummary[]>([]),[error,setError]=useState<MessageKey|null>(null),[loading,setLoading]=useState(true);
  const refresh=useCallback(async()=>{try{setRuns(z.array(OrganizationRunSummarySchema).parse(await command({command:'list'})));setError(null);onRefresh?.();}catch(e){setError(errorKey(e));}finally{setLoading(false);}},[onRefresh]);
  useEffect(()=>{void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh();},2000);return()=>clearInterval(timer);},[refresh,refreshKey]);
  return <div className="grid gap-3"><div className="flex items-center justify-between"><h3 className="font-semibold">{t('organization.runs')}</h3><button className={control} onClick={()=>void refresh()}>{t('organization.refresh')}</button></div>{error&&<p role="alert" className="text-red-600">{t(error)}</p>}{loading?<p role="status">{t('organization.loading')}</p>:!runs.length?<p className={`${card} text-sm text-slate-500`}>{t('organization.empty')}</p>:runs.map(run=><RunCard key={run.id} summary={run} t={t} refresh={refresh}/>)}</div>;
}
export function OrganizationSettingsView({t,contentLanguage}:{t:Translator;contentLanguage:string}){
  const [settings,setSettings]=useState<Settings|null>(null),[config,setConfig]=useState<OrganizationConfiguration>(defaultOrganizationConfiguration),[draftId,setDraftId]=useState<string|null>(null);
  const [layer,setLayer]=useState<'global'|'function'|'domain'|'domain_function'>('global'),[domainId,setDomainId]=useState<string|null>(null),[unlocked,setUnlocked]=useState(false);
  const [profiles,setProfiles]=useState<AiProfile[]>([]),[profile,setProfile]=useState(''),[privacy,setPrivacy]=useState<'offline_only'|'allow_remote'>('offline_only');
  const [pages,setPages]=useState<PageSummary[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<MessageKey|null>(null),[notice,setNotice]=useState<MessageKey|null>(null),[refreshKey,setRefreshKey]=useState(0);
  const load=useCallback(async()=>{try{const [s,p,pg]=await Promise.all([command({command:'settings'}),window.app.ai.listProfiles(),window.app.wiki.list()]);const parsed=OrganizationSettingsSchema.parse(s);setSettings(parsed);setConfig(parsed.revisions.find(r=>r.id===parsed.activeId)?.configuration??defaultOrganizationConfiguration);setProfiles(p);setPages(pg);}catch(e){setError(errorKey(e));}},[]);
  useEffect(()=>{void load();},[load]);
  const domain=config.domains.find(d=>d.id===domainId),slots=layer==='global'?config.global:layer==='function'?config.pageSynthesis:layer==='domain'?domain?.slots:domain?.pageSynthesis;
  let preview:ReturnType<typeof resolveOrganizationInstructions>|null=null;try{preview=resolveOrganizationInstructions(OrganizationConfigurationSchema.parse(config),domainId,'Example topic',contentLanguage);}catch{}
  const activeConfig=settings?.revisions.find(r=>r.id===settings.activeId)?.configuration??defaultOrganizationConfiguration;
  const activePreview=resolveOrganizationInstructions(activeConfig,activeConfig.domains.some(d=>d.id===domainId)?domainId:null,'Example topic',contentLanguage);
  function edit(next:OrganizationConfiguration){setConfig(next);setDraftId(null);setNotice(null);}
  function patch(value:Partial<NonNullable<typeof slots>>){if(!slots)return;const next=structuredClone(config);if(layer==='global')next.global={...slots,...value};else if(layer==='function')next.pageSynthesis={...slots,...value};else{const d=next.domains.find(d=>d.id===domainId)!;if(layer==='domain')d.slots={...slots,...value};else d.pageSynthesis={...slots,...value};}edit(next);}
  async function act(fn:()=>Promise<void>){setBusy(true);setError(null);setNotice(null);try{await fn();}catch(e){setError(errorKey(e));}finally{setBusy(false);}}
  async function save(value=config){const parsed=OrganizationConfigurationSchema.parse(value),id=z.string().uuid().parse(await command({command:'saveDraft',configuration:parsed}));setConfig(parsed);if(domainId&&!parsed.domains.some(d=>d.id===domainId)){setDomainId(null);setLayer('global');}setDraftId(id);setSettings(OrganizationSettingsSchema.parse(await command({command:'settings'})));setNotice('organization.saved');}
  return <div className="grid gap-5"><header><div className="flex items-center gap-3"><Settings2 className="text-cyan-600"/><h2 className="text-2xl font-semibold">{t('organization.title')}</h2></div><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{t('organization.description')}</p></header>
    {error&&<div role="alert" className={`${card} text-red-600`}>{t(error)} <button onClick={()=>void load()} className={control}>{t('organization.refresh')}</button></div>}{notice&&<p role="status" className="text-sm text-emerald-700">{t(notice)}</p>}
    {!settings?<p role="status">{t('organization.loading')}</p>:<>
      <fieldset disabled={busy} className="grid min-w-0 gap-5 xl:grid-cols-[260px_minmax(0,1fr)]"><aside className={`${card} h-fit grid gap-4`}><div className="flex items-center gap-2 font-medium"><BookOpen size={18}/>{t('organization.pageSynthesis')}</div><p className="text-xs leading-5 text-slate-500">{t('organization.deferred')}</p><label className="grid gap-1 text-sm">{t('organization.domains')}<select className={control} value={domainId??''} onChange={e=>{setDomainId(e.target.value||null);if(!e.target.value)setLayer('global');}}><option value="">{t('organization.global')}</option>{config.domains.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><button className={control} onClick={()=>{const id=crypto.randomUUID();edit({...config,domains:[...config.domains,{id,name:t('organization.name'),sourceIds:[],pageIds:[],slots:{},pageSynthesis:{}}]});setDomainId(id);setLayer('domain');}}><Plus className="mr-1 inline" size={14}/>{t('organization.addDomain')}</button>
      {(['global','function','domain','domain_function'] as const).map(l=><button key={l} disabled={!domainId&&l.startsWith('domain')} onClick={()=>setLayer(l)} className={`${control} text-left ${layer===l?'border-cyan-500 bg-cyan-50 dark:bg-cyan-950':''}`}>{t(`organization.${l}`)}</button>)}</aside>
      <main className="grid min-w-0 gap-4">{domain&&<div className={card}><label className="grid gap-1 text-sm">{t('organization.name')}<input className={control} value={domain.name} onChange={e=>edit({...config,domains:config.domains.map(d=>d.id===domain.id?{...d,name:e.target.value}:d)})}/></label><div className="mt-3 grid gap-3 sm:grid-cols-2"><EvidenceScopePicker selected={domain.sourceIds} onChange={ids=>edit({...config,domains:config.domains.map(d=>d.id===domain.id?{...d,sourceIds:ids}:d)})} t={t}/><label className="grid gap-1 text-sm">{t('wiki.pages')}<select multiple className={`${control} h-28`} value={domain.pageIds} onChange={e=>edit({...config,domains:config.domains.map(d=>d.id===domain.id?{...d,pageIds:Array.from(e.target.selectedOptions,o=>o.value)}:d)})}>{pages.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label></div></div>}
      {slots&&<div className={card}><div className="mb-3 flex items-center justify-between gap-2"><h3 className="font-semibold">{t('organization.guidance')}</h3><button className={control} onClick={()=>patch({guidance:undefined})}>{t('organization.inherit')}</button></div><MarkdownEditor id="organization-guidance" value={slots.guidance??''} onChange={guidance=>patch({guidance})} t={t} label={t('organization.guidance')} minHeightClass="min-h-40"/><details className="mt-5 border-t border-slate-200 pt-4 dark:border-slate-800"><summary className="cursor-pointer text-sm font-medium">{t('organization.advanced')}</summary><p className="my-3 text-xs leading-5 text-amber-700 dark:text-amber-300">{t('organization.advancedHint')}</p><label className="mb-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={unlocked} onChange={e=>setUnlocked(e.target.checked)}/>{t('organization.unlock')}</label>{unlocked&&<><textarea className={`${control} min-h-40 w-full font-mono`} aria-label={t('organization.advanced')} value={slots.advanced??''} onChange={e=>patch({advanced:e.target.value})}/><button className={`${control} mt-2`} onClick={()=>patch({advanced:undefined})}>{t('organization.inherit')}</button></>}</details></div>}
      <div className={card}><div className="flex items-center gap-2 font-semibold"><ShieldCheck size={18}/>{t('organization.effective')}</div><p className="my-3 text-xs leading-5 text-slate-500">{t('organization.contract')}</p>{JSON.stringify(config)!==JSON.stringify(activeConfig)&&<details className="mb-3 rounded-xl bg-slate-50 p-3 dark:bg-slate-950"><summary className="cursor-pointer text-sm font-medium">{t('organization.before')} · {t('organization.active')}</summary><p className="mt-2 whitespace-pre-wrap text-sm">{activePreview.slots.guidance}</p><p className="mt-2 whitespace-pre-wrap text-xs text-slate-500">{activePreview.slots.advanced}</p></details>}{preview?(['guidance','advanced'] as const).map(k=><div key={k} className="mt-4"><p className="mb-1 text-xs font-medium text-cyan-700 dark:text-cyan-300">{t(`organization.${k}`)} · {t(`organization.${preview!.origins[k]}` as MessageKey)}</p><p className="whitespace-pre-wrap text-sm leading-6">{preview!.slots[k]}</p></div>):<p className="text-sm text-red-600">{t('organization.errors.placeholder')}</p>}</div>
      <div className={card}><ProfilePicker profiles={profiles} value={profile} onChange={setProfile} privacy={privacy} onPrivacy={setPrivacy} t={t}/><p className="my-3 text-xs leading-5 text-slate-500">{t('organization.sampleHint')}</p><div className="flex flex-wrap gap-2"><button disabled={busy||!preview} className={primary} onClick={()=>void act(()=>save())}>{t('organization.saveDraft')}</button><button disabled={busy||!draftId||!profile} className={control} onClick={()=>void act(async()=>{await command({command:'sample',revisionId:draftId!,domainId,profileId:profile,privacy});setRefreshKey(v=>v+1);})}><FlaskConical size={16} className="mr-1 inline"/>{t('organization.sample')}</button><button disabled={busy||!draftId} className={control} onClick={()=>void act(async()=>{setSettings(OrganizationSettingsSchema.parse(await command({command:'activate',revisionId:draftId!,expectedActiveId:settings.activeId})));setNotice('organization.activated');})}>{t('organization.activate')}</button></div></div>
      </main></fieldset>
      <details className={card}><summary className="flex cursor-pointer items-center gap-2 font-semibold"><History size={18}/>{t('organization.versions')}</summary><button className={`${control} mt-3`} onClick={()=>void act(()=>save(defaultOrganizationConfiguration))}><RotateCcw size={14} className="mr-1 inline"/>{t('organization.reset')}</button><div className="mt-3 grid gap-2">{settings.revisions.map(r=><div key={r.id} className="flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 py-2 text-sm dark:border-slate-800"><span>{new Date(r.createdAt).toLocaleString()} · {r.hash.slice(0,8)} {r.id===settings.activeId&&<strong className="text-cyan-600"> · {t('organization.active')}</strong>}</span><button disabled={busy} className={control} onClick={()=>void act(()=>save(r.configuration))}>{t('organization.restore')}</button></div>)}</div><div className="mt-3 text-xs text-slate-500">{settings.activations.map(a=><p key={a.id}>{new Date(a.createdAt).toLocaleString()} · {a.revisionId.slice(0,8)}</p>)}</div></details>
    </>}
    <OrganizationRuns t={t} refreshKey={refreshKey}/>
  </div>;
}
export function OrganizationDialog({t,page,onClose}:{t:Translator;page:WikiPage|null;onClose:()=>void}){
  const dialogRef=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const dialog=dialogRef.current;const focus=document.activeElement as HTMLElement|null;dialog?.showModal();return()=>{dialog?.close();focus?.focus();};},[]);
  const [profiles,setProfiles]=useState<AiProfile[]>([]),[profile,setProfile]=useState(''),[selected,setSelected]=useState<string[]>(page?[...new Set(page.evidence.map(e=>e.sourceItemId))]:[]);
  const [title,setTitle]=useState(page?.title??''),[privacy,setPrivacy]=useState<'offline_only'|'allow_remote'>('offline_only'),[relations,setRelations]=useState(false),[policy,setPolicy]=useState<'human_review'|'apply_unprotected'>('human_review'),[domains,setDomains]=useState<OrganizationConfiguration['domains']>([]),[domainId,setDomainId]=useState<string|null>(null);
  const [busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState<MessageKey|null>(null),[refreshKey,setRefreshKey]=useState(0);
  useEffect(()=>{void Promise.all([window.app.ai.listProfiles(),command({command:'settings'})]).then(([p,c])=>{setProfiles(p);const settings=OrganizationSettingsSchema.parse(c);setDomains(settings.revisions.find(r=>r.id===settings.activeId)?.configuration.domains??[]);}).catch(e=>setError(errorKey(e))).finally(()=>setLoading(false));},[]);
  async function start(){setBusy(true);setError(null);try{await command({command:'start',input:OrganizationStartSchema.parse({targetPageId:page?.id??null,title,sourceIds:selected,profileId:profile,privacy,relationContext:relations,domainId,policy})});setRefreshKey(v=>v+1);}catch(e){setError(errorKey(e));}finally{setBusy(false);}}
  return <dialog ref={dialogRef} onKeyDown={event=>{if(event.key==='Escape')event.stopPropagation();}} aria-labelledby="organization-dialog-title" onCancel={e=>{e.preventDefault();onClose();}} className="fixed inset-0 m-auto max-h-[calc(100dvh-2rem)] w-[calc(100%-2rem)] max-w-5xl overflow-hidden rounded-2xl bg-slate-50 p-0 text-slate-950 backdrop:bg-slate-950/60 dark:bg-slate-950 dark:text-slate-50"><section className="flex max-h-[calc(100dvh-2rem)] w-full max-w-5xl flex-col rounded-2xl bg-slate-50 shadow-2xl dark:bg-slate-950"><header className="flex items-center justify-between border-b border-slate-200 p-5 dark:border-slate-800"><h2 id="organization-dialog-title" className="flex items-center gap-2 text-xl font-semibold"><Sparkles className="text-cyan-600"/>{t('organization.organize')}</h2><button className={control} onClick={onClose} autoFocus aria-label={t('organization.close')}><X size={18}/></button></header><div className="grid gap-5 overflow-auto p-5">{error&&<p role="alert" className="text-red-600">{t(error)}</p>}{loading?<p role="status">{t('organization.loading')}</p>:<div className={card}><div className="grid gap-4 sm:grid-cols-2"><label className="grid gap-1 text-sm">{t('wiki.pageTitle')}<input className={control} value={title} disabled={!!page} onChange={e=>setTitle(e.target.value)}/></label><label className="grid gap-1 text-sm">{t('organization.domains')}<select className={control} value={domainId??''} onChange={e=>setDomainId(e.target.value||null)}><option value="">{t('organization.global')}</option>{domains.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></div><div className="mt-4"><EvidenceScopePicker selected={selected} onChange={setSelected} t={t}/></div><div className="mt-4"><ProfilePicker profiles={profiles} value={profile} onChange={setProfile} privacy={privacy} onPrivacy={setPrivacy} t={t}/></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={relations} onChange={e=>setRelations(e.target.checked)}/>{t('organization.relations')}</label><p className="mt-1 text-xs text-slate-500">{t('organization.relationHint')}</p><select className={`${control} mt-3`} aria-label={t('organization.humanReview')} value={policy} onChange={e=>setPolicy(e.target.value as typeof policy)}><option value="human_review">{t('organization.humanReview')}</option><option value="apply_unprotected">{t('organization.autoDraft')}</option></select><p className="my-3 text-xs leading-5 text-slate-500">{t('organization.runHint')}</p><button disabled={busy||!profile||!title.trim()||!selected.length} className={primary} onClick={()=>void start()}>{busy?<LoaderCircle size={16} className="animate-spin"/>:<Sparkles size={16}/>} {t('organization.run')}</button></div>}<OrganizationRuns t={t} refreshKey={refreshKey}/></div></section></dialog>;
}
