import {useEffect,useRef,useState}from'react';
import type {z}from'zod';
import type {WikiLinkedTargetSchema,WikiEvidence}from'@app/domain';
import type {Translator}from'@app/i18n';
import {MarkdownPreview}from'./MarkdownEditor';
export function WikiTypedLink({pageId,revisionId,target,t,active=true,refreshKey,onRefreshed,onOpenPage,onOpenSource,onEvidence,label,inline=false,onInlineOpen}:{active?:boolean;refreshKey?:number|undefined;onRefreshed?:((value:z.infer<typeof WikiLinkedTargetSchema>)=>void)|undefined;inline?:boolean|undefined;onInlineOpen?:((value:z.infer<typeof WikiLinkedTargetSchema>)=>void)|undefined;label?:string|undefined;pageId:string;revisionId?:string|undefined;target:{kind:'page'|'source'|'atomic_note'|'entity';id:string};t:Translator;onOpenPage:(id:string)=>void;onOpenSource:(id:string,noteId?:string)=>void;onEvidence:(e:WikiEvidence)=>void}){
 const [value,setValue]=useState<z.infer<typeof WikiLinkedTargetSchema>|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(false),[retry,setRetry]=useState(0),[open,setOpen]=useState(false);
 const refreshed=useRef(onRefreshed);refreshed.current=onRefreshed;
 useEffect(()=>{if(!active)return;let live=true;setLoading(true);setError(false);void window.app.wiki.linkedTarget({pageId,...(revisionId?{revisionId}:{}),...target}).then(v=>{if(live){setValue(v);if(v)refreshed.current?.(v);}}).catch(()=>{if(live)setError(true);}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[pageId,revisionId,target.kind,target.id,retry,active,refreshKey]);
 if(error)return <button className="text-xs text-rose-600" onClick={()=>setRetry(n=>n+1)}>{t('wiki.errors.generic')} · {t('shell.actions.retry')}</button>;
 if(loading&&!value)return <span role="status" className="text-xs text-slate-500">{t('shell.states.loading')}</span>;
 if(!value)return <span className="text-xs text-slate-500">{t('wiki.noResults')}</span>;
 if(inline)return <span><button role="link" className="inline text-accent underline decoration-accent/30 underline-offset-4 hover:decoration-current focus-visible:outline-2" onClick={()=>{if(target.kind==='page')onOpenPage(target.id);else if(target.kind==='source'&&value.sourceItemId)onOpenSource(value.sourceItemId);else onInlineOpen?.(value);}}>{label??value.title}</button></span>;
 return <div className="min-w-0"><button data-wiki-note-expanded={open?"true":undefined} aria-expanded={target.kind==='atomic_note'?open:undefined} className="text-left text-sm text-cyan-700 underline decoration-cyan-500/30 underline-offset-4 hover:decoration-current focus-visible:outline-2 focus-visible:outline-accent dark:text-cyan-300" onClick={()=>{if(target.kind==='page')onOpenPage(target.id);else if(target.kind==='source'&&value.sourceItemId)onOpenSource(value.sourceItemId);else {if(!open)setRetry(n=>n+1);setOpen(!open);}}}>{label??value.title}<span className="ml-1 text-[10px] text-muted-foreground">{t(`wiki.results.${target.kind}`)}</span></button>{open&&<div className="mt-3 grid gap-3">{value.noteState&&<p className="text-xs text-muted-foreground">{t(('knowledge.notes.status.'+value.noteState.status)as import('@app/i18n').MessageKey)} · {t(value.noteState.current?'obsidianWiki.current':'obsidianWiki.historical')}{value.noteState.protected?' · '+t('obsidianWiki.protected'):''}</p>}<MarkdownPreview markdown={value.markdown} emptyLabel={t('wiki.noResults')} reference={token=>{const match=/^\[([1-9][0-9]{0,3})\]$/.exec(token),e=match?value.evidence[Number(match[1])-1]:null;return e?<button className="inline text-accent underline" onClick={()=>onEvidence(e)}>{token}</button>:undefined;}}/>{value.successors?.map(next=><WikiTypedLink active={active} refreshKey={refreshKey} onRefreshed={onRefreshed} key={next.id} pageId={pageId} revisionId={revisionId} target={{kind:'atomic_note',id:next.id}} t={t} onOpenPage={onOpenPage} onOpenSource={onOpenSource} onEvidence={onEvidence} label={t('knowledgeEvolution.supersedes')+': '+next.title}/>)}{value.evidence.map((e,i)=><button key={e.id} className="text-left text-xs text-cyan-700 dark:text-cyan-300" onClick={()=>onEvidence(e)}>[{i+1}] {t('wiki.inspector')} · {e.sourceTitle}</button>)}{value.sourceItemId&&<button className="text-left text-xs underline" onClick={()=>onOpenSource(value.sourceItemId!,target.kind==='atomic_note'?target.id:undefined)}>{t('wiki.openSource')}</button>}</div>}</div>;
}
