import {useEffect,useState} from 'react';
import {WikiAssessmentSchema,WikiBootstrapSchema,type WikiBootstrap,type AutomaticWikiPolicy} from '@app/domain';
import {z} from 'zod';
import type {Translator,MessageKey} from '@app/i18n';
export function WikiBootstrapPanel({policy,t,onScopeConflict,noteIds,disabledStart}:{disabledStart:boolean;noteIds:string[];policy:AutomaticWikiPolicy;t:Translator;onScopeConflict:(sourceIds:string[])=>void}){
 const [cursor,setCursor]=useState<string|undefined>(),[hasMore,setHasMore]=useState(false);
 const [assessment,setAssessment]=useState<z.infer<typeof WikiAssessmentSchema>|null>(null),[runs,setRuns]=useState<WikiBootstrap[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState<MessageKey|null>(null);
 const fail=(error:unknown)=>setError((String(error).match(/organization\.errors\.[A-Za-z]+/)?.[0]??'organization.errors.failed')as MessageKey);
 useEffect(()=>setCursor(undefined),[policy.id]);
 const refresh=async()=>{const rows=z.array(WikiBootstrapSchema).parse(await window.app.wiki.collection({command:'bootstraps',policyId:policy.id,...(cursor?{after:cursor}:{})}));setRuns(rows);setHasMore(rows.length===50);};
 useEffect(()=>{void refresh().catch(fail);const timer=setInterval(()=>void refresh().catch(fail),2000);return()=>clearInterval(timer);},[policy.id,cursor]);
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError(null);try{await fn();await refresh();}catch(e){fail(e);}finally{setBusy(false);}};
 const assess=(after:string|null=null)=>act(async()=>setAssessment(WikiAssessmentSchema.parse(await window.app.wiki.collection({command:'assessment',input:{policyId:policy.id,after,limit:20}}))));
 return <section className="grid gap-3 rounded-xl bg-surface p-3">
 <button disabled={busy} className="w-fit text-accent underline" onClick={()=>void assess()}>{t('automaticWiki.assess')}</button>
 {error&&<p role="alert" className="text-sm text-rose-600">{t(error)} <button onClick={()=>void assess()}>{t('shell.actions.retry')}</button></p>}
 {busy&&<p role="status">{t('shell.states.loading')}</p>}
 {assessment&&<><p className="text-sm text-muted-foreground">{t('automaticWiki.readOnlyAssessment')}</p><p className="text-sm">{t('wiki.sources')}: {assessment.totals.sources} · {t('automaticWiki.originalPassages')}: {assessment.totals.originals} · {t('automaticWiki.coverageStates.integrated')}: {assessment.totals.integrated}</p>
 <div className="grid gap-2">{assessment.scopeConflicts.map(conflict=><div key={conflict.pageId} className="text-sm text-amber-700 dark:text-amber-300"><p>{t("organization.errors.scopeDecision")}</p><p className="font-medium">{conflict.title}</p><ul>{conflict.excludedSources.map(source=><li key={source.id}>{source.title}</li>)}</ul><button className="mt-2 underline" onClick={()=>onScopeConflict(conflict.excludedSources.map(s=>s.id))}>{t("automaticWiki.reviewScope")}</button></div>)}</div><ul className="grid gap-2">{assessment.sources.map(s=><li key={s.id} className="text-sm"><span className="font-medium">{s.title}</span><p className="text-xs text-muted-foreground">{t(`automaticWiki.coverageStates.${s.coverage}`)} · {s.covered}/{s.originals} {t('automaticWiki.originalPassages')} · {s.notes} {t('wiki.notes')} · {s.pages} {t('wiki.pages')}</p></li>)}</ul>
 <div className="flex flex-wrap gap-3">{assessment.next&&<button className="text-sm text-accent" disabled={busy} onClick={()=>void assess(assessment.next)}>{t('wiki.loadMore')}</button>}<button disabled={busy||disabledStart||policy.state!=='enabled'} className="rounded-lg bg-accent px-3 py-2 text-sm text-white" onClick={()=>void act(()=>window.app.wiki.collection({command:'bootstrap',input:{policyId:policy.id,policyRevisionId:policy.revisionId,noteIds}}))}>{t('automaticWiki.bootstrap')}</button></div></>}
 {runs.map(run=><div key={run.id} className="border-t border-border pt-3"><p className="text-sm font-medium">{t(`automaticWiki.coverageStates.${run.checkpoint.state}`)} · {t('automaticWiki.groups')}: {run.checkpoint.completedGroups}</p><p className="text-xs text-muted-foreground">{t('wiki.sources')}: {run.checkpoint.completedSources} · {t('automaticWiki.originalPassages')}: {run.checkpoint.sourceCovered}</p>{run.checkpoint.error&&<p role="status" className="my-2 text-xs text-amber-600">{t(run.checkpoint.error as MessageKey)}</p>}<div className="mt-2 flex gap-3">{(['running','paused','attention'].includes(run.checkpoint.state))&&<><button disabled={busy} className="text-sm text-accent" onClick={()=>void act(()=>window.app.wiki.collection({command:run.checkpoint.state==='running'?'bootstrapPause':'bootstrapResume',id:run.id}))}>{t(run.checkpoint.state==='running'?'automaticWiki.pause':'automaticWiki.resume')}</button><button disabled={busy} className="text-sm" onClick={()=>void act(()=>window.app.wiki.collection({command:'bootstrapCancel',id:run.id}))}>{t('organization.cancel')}</button></>}</div></div>)}
 <div className="flex gap-3">{cursor&&<button className="text-sm text-accent" onClick={()=>setCursor(undefined)}>{t("wiki.back")}</button>}{hasMore&&<button className="text-sm text-accent" onClick={()=>setCursor(runs.at(-1)?.id)}>{t("wiki.loadMore")}</button>}</div>
 </section>;
}
