import { describe, it, expect, vi } from 'vitest';
const randomUUID = () => crypto.randomUUID();
import { ObsidianOperationQueue, type QueueState } from './operation-queue.js';
import { serializeManagedFrontmatter, type ObsidianEditOperation, type ObsidianEditReceipt } from '@app/integration-contracts';
const vaultId = randomUUID(), targetId = randomUUID();
function operation(target = targetId): ObsidianEditOperation { return { version: 1, operationId: randomUUID(), vaultId, binding: 'a'.repeat(64), targetId: target, targetType: 'source_item', kind: 'edit', relativePath: 'Memora/source.md', baseRevision: 'revision', baseVersion: 1, baseHash: 'a'.repeat(64), content: serializeManagedFrontmatter({ memoraId: target, memoraType: 'source_item', memoraManaged: true, memoraSyncVersion: 1, memoraContentHash: 'a'.repeat(64) }) + '\nLocal body', occurredAt: new Date().toISOString() }; }
function receipt(op: ObsidianEditOperation): ObsidianEditReceipt { return { operationId: op.operationId, targetId: op.targetId, status: 'synced', revision: 'new-revision', syncVersion: 2, contentHash: 'b'.repeat(64), projection: 'pending', content: op.content.replace('memora_sync_version: 1', 'memora_sync_version: 2'), reason: null, comparison: null }; }
describe('durable Obsidian operation queue', () => {
    it('persists before sending and replays original operation IDs after restart', async () => { let disk: QueueState = { version: 1, operations: [] }; const state: QueueState = { version: 1, operations: [] }, q = new ObsidianOperationQueue(state, async () => { disk = structuredClone(state); }); const op = operation(); await q.enqueue(op); const restarted = new ObsidianOperationQueue(disk, async () => { }), send = vi.fn(async (input) => receipt(input)); await restarted.flush(send, async () => true, async () => { }); expect(send.mock.calls[0]![0].operationId).toBe(op.operationId); expect(disk.operations).toHaveLength(0); });
    it('rejects mismatched acknowledgments without deleting queued text', async () => { const q = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => { }), op = operation(); await q.enqueue(op); await q.flush(async () => ({ ...receipt(op), operationId: randomUUID() }), async () => true, async () => { }); expect(q.state.operations).toHaveLength(1); expect(q.state.operations[0]!.error).toBe('invalid_receipt'); });
    it('retains failed and conflicted targets while another file succeeds', async () => { const q = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => { }), a = operation(), b = operation(randomUUID()); await q.enqueue(a); await q.enqueue(b); await q.flush(async (op) => op.operationId === a.operationId ? { ...receipt(op), status: 'conflict', comparison: { base: 'b', local: 'l', app: 'a' } } : receipt(op), async () => true, async () => { }); expect(q.state.operations).toHaveLength(1); });
    it('rolls back enqueue and conflict resolution when persistence fails', async () => { let fail = false; const q = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => { if (fail)
        throw new Error('ENOSPC'); }), op = operation(); fail = true; await expect(q.enqueue(op)).rejects.toThrow('ENOSPC'); expect(q.state.operations).toHaveLength(0); fail = false; await q.enqueue(op); fail = true; await expect(q.resolve(op.operationId, { ...op, operationId: randomUUID() })).rejects.toThrow('ENOSPC'); expect(q.state.operations[0]!.operation.operationId).toBe(op.operationId); });
    it('uses IDs after concurrent failed persistence restores cloned rows', async () => { let fail = false, release!: (value: ObsidianEditReceipt) => void; const q = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => { if (fail) {
        fail = false;
        throw new Error('ENOSPC');
    } }), a = operation(), c = operation(randomUUID()); await q.enqueue(a); await q.enqueue(c); const run = q.flush(op => op.operationId === a.operationId ? new Promise(resolve => { release = resolve; }) : Promise.reject(new Error('offline')), async () => true, async () => { }); await Promise.resolve(); fail = true; await expect(q.enqueue(operation(randomUUID()))).rejects.toThrow(); release(receipt(a)); await run; expect(q.state.operations).toHaveLength(1); expect(q.state.operations[0]!.operation.operationId).toBe(c.operationId); });
    it('retains original observed bytes while rebasing two offline edits', async () => { const q = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => { }), a = operation(), b = { ...operation(), content: operation().content.replace('Local body', 'Newer body') }; await q.enqueue(a); await q.enqueue(b); let file = b.content; const sent: ObsidianEditOperation[] = []; await q.flush(async (op) => { sent.push(op); return receipt(op); }, async (op, result, observed) => { if (file === observed) {
        file = result.content;
        return true;
    } return q.state.operations.some(r => r.operation.operationId !== op.operationId && r.observedContent === file); }, async () => { }); expect(q.state.operations).toHaveLength(0); expect(sent[1]!.baseVersion).toBe(2); expect(file).toContain('Newer body'); expect(file).toContain('memora_sync_version: 2'); });
    it('deduplicates concurrent identical captures inside the durable transition', async () => { const q = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => { }), a = operation(); await Promise.all([q.enqueue(a), q.enqueue({ ...a, operationId: randomUUID() })]); expect(q.state.operations).toHaveLength(1); await q.enqueue({ ...a, operationId: randomUUID(), relativePath: 'Memora/copy.md' }); expect(q.state.operations).toHaveLength(2); });
    it('replays the original ID after receipt persistence fails', async () => { let writes = 0; const q = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => { if (++writes === 2)
        throw new Error('ENOSPC'); }), op = operation(), send = vi.fn(async (input) => receipt(input)); await q.enqueue(op); await q.flush(send, async () => true, async () => { }); expect(q.state.operations[0]!.receipt).toBeUndefined(); await q.flush(send, async () => true, async () => { }); expect(send).toHaveBeenCalledTimes(2); expect(send.mock.calls[1]![0].operationId).toBe(op.operationId); expect(q.state.operations).toHaveLength(0); });
    it('retains the durable receipt when acknowledgment removal cannot be saved', async () => { let writes = 0; const q = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => { if (++writes === 3)
        throw new Error('ENOSPC'); }), op = operation(), send = vi.fn(async (input) => receipt(input)), ack = vi.fn(async () => { }); await q.enqueue(op); await q.flush(send, async () => true, ack); expect(q.state.operations[0]!.receipt?.operationId).toBe(op.operationId); await q.flush(send, async () => true, ack); expect(send).toHaveBeenCalledOnce(); expect(q.state.operations).toHaveLength(0); });
    it('delivers a later deletion when its earlier edit no longer needs a file write', async () => { const q = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => { }), edit = operation(), deletion = { ...operation(), kind: 'delete' as const }; await q.enqueue(edit); await q.enqueue(deletion); const sent: string[] = []; await q.flush(async (op) => { sent.push(op.kind); return { ...receipt(op), status: op.kind === 'delete' ? 'deleted' : 'synced', projection: op.kind === 'delete' ? 'tombstoned' : 'pending' }; }, async (op) => q.state.operations.some(r => r.operation.targetId === op.targetId && r.operation.kind === 'delete'), async () => { }); expect(sent).toEqual(['edit', 'delete']); expect(q.state.operations).toHaveLength(0); });
    it('leaves a pending operation replayable when the plugin unloads during transport',async()=>{let release!:(receipt:ObsidianEditReceipt)=>void;const persist=vi.fn(async()=>{}),q=new ObsidianOperationQueue({version:1,operations:[]},persist),op=operation(),apply=vi.fn(async()=>true);await q.enqueue(op);const run=q.flush(()=>new Promise(resolve=>{release=resolve;}),apply,async()=>{});await Promise.resolve();q.stop();release(receipt(op));await run;expect(apply).not.toHaveBeenCalled();expect(persist).toHaveBeenCalledOnce();expect(q.state.operations[0]!.receipt).toBeUndefined();});

});
