import { atomicEditorial, normalizeProjectionText, parseObsidianMarkdown, parseWikiRegions, serializeManagedFrontmatter, type ObsidianEditOperation, type ObsidianEditReceipt } from '@app/integration-contracts';
import type { QueuedOperation } from './operation-queue.js';

export function isKnownProjection(path: string, content: string, registered: { relativePath: string; content: string }, latest?: QueuedOperation) {
    if (path !== registered.relativePath) return false;
    return content === (latest?.operation.content ?? registered.content) || content === latest?.receipt?.content || (latest?.operation.relativePath === path && content === latest.observedContent);
}

/** An accepted editable request proves its generated bytes were unchanged.
 * Carry only those bytes forward; preserve divergent generated text for review. */
export function rebaseQueuedContent(accepted: ObsidianEditOperation, receipt: ObsidianEditReceipt, next: string) {
    const before = parseObsidianMarkdown(accepted.content), after = parseObsidianMarkdown(receipt.content), local = parseObsidianMarkdown(next);
    if (!before || !after || !local) return next;
    let body = local.bodyMarkdown;
    const parseRegions = accepted.targetType === 'wiki_page' ? parseWikiRegions : accepted.targetType === 'atomic_note' ? atomicEditorial : null;
    if (parseRegions && accepted.resolution?.choice !== 'app') {
        const b = parseRegions(before.bodyMarkdown), a = parseRegions(after.bodyMarkdown), l = parseRegions(body);
        if (b && a && l && l.generated === b.generated) body = l.editorial + a.generated;
    }
    return serializeManagedFrontmatter(after.frontmatter, local.userFrontmatter) + '\n' + body;
}

/** Follow only explicit, contiguous moves for this identity, never missing scans. */
export function queuedPlacement(rows: QueuedOperation[], operation: ObsidianEditOperation) {
    let relativePath = operation.relativePath, deleted = false, observed = operation.content;
    const index = rows.findIndex(row => row.operation.operationId === operation.operationId);
    if (index < 0) return { relativePath, deleted, observed };
    for (const row of rows.slice(index + 1)) {
        const next = row.operation;
        if (next.targetId !== operation.targetId) continue;
        if (next.kind === 'move' && next.previousRelativePath === relativePath) {
            relativePath = next.relativePath;
            observed = row.observedContent ?? next.content;
        } else if (next.relativePath === relativePath) {
            if (next.kind === 'delete') deleted = true;
            if (next.kind === 'edit') observed = row.observedContent ?? next.content;
        }
    }
    return { relativePath, deleted, observed };
}

export function assertConfirmedLocal(actual: string | null, expected: string) {
    if (actual === null || normalizeProjectionText(actual) !== expected) throw new Error('newer_local_buffer');
}

export async function applyQueuedReceipt(rows: QueuedOperation[], operation: ObsidianEditOperation, receipt: ObsidianEditReceipt, observed: string, host: {
    read: (path: string) => Promise<string | null>;
    write: (path: string, expected: string, content: string) => Promise<boolean>;
}) {
    if (receipt.status === 'deleted') return true;
    const placement = queuedPlacement(rows, operation);
    const value = await host.read(placement.relativePath), actual = value === null ? null : normalizeProjectionText(value);
    if (actual === null) return placement.deleted;
    if (placement.relativePath !== operation.relativePath) {
        // A later move owns final framing. Never recreate an intermediate path.
        return actual === normalizeProjectionText(placement.observed);
    }
    if (actual === receipt.content) return true;
    if (actual !== observed) return rows.some(row => row.operation.targetId === operation.targetId && row.operation.operationId !== operation.operationId && row.operation.relativePath === placement.relativePath && normalizeProjectionText(row.observedContent ?? row.operation.content) === actual);
    return host.write(placement.relativePath, actual, receipt.content);
}
