import {PromptPinSchema} from './prompt-catalog.js';
import {OrganizationProfileSchema} from './organization.js';
import { z } from 'zod';
import { MaintenanceCadenceSchema, maintenanceOccurrences } from './maintenance.js';
export const automaticMaintenanceVersion = 'automatic-maintenance-v1';
export const automaticAllowancePreset = 'luna-a2-a3-conservative-v1';
export const AutomaticMaintenanceKindSchema = z.enum(['incremental','daily','weekly','monthly']);
export type AutomaticRoutineKind = z.infer<typeof AutomaticMaintenanceKindSchema>;
export const AutomaticAllowanceSchema = z.object({calls:z.number().int().min(0).max(1000),tokens:z.number().int().min(0).max(10000000),spend:z.number().nonnegative().nullable().default(null)}).strict();
export const AutomaticCadenceSchema = z.object({kind:z.enum(['incremental','daily','weekly','monthly']),timezone:z.string().max(100).refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true;}catch{return false;}}),hour:z.number().int().min(0).max(23),minute:z.number().int().min(0).max(59).default(0),weekday:z.number().int().min(0).max(6).default(0),day:z.number().int().min(1).max(31).default(1),debounceMs:z.number().int().min(120000).max(86400000).default(120000)}).strict();
export const AutomaticRoutinePolicySchema=z.object({version:z.literal(automaticMaintenanceVersion),policyId:z.string().uuid(),policyRevisionId:z.string().uuid(),kind:AutomaticMaintenanceKindSchema,scopeKey:z.string(),presetVersion:z.string(),enabled:z.boolean(),cadence:AutomaticCadenceSchema,idleSeconds:z.number().int().min(0).max(3600).default(60),startWindowMs:z.number().int().positive(),executionMs:z.number().int().positive().max(5400000),groupMs:z.number().int().positive().max(600000),allowance:AutomaticAllowanceSchema,monthAllowance:AutomaticAllowanceSchema,promptIds:z.array(z.string()).length(3).refine(v=>v.join('|')==='organization.curator|organization.curator.repair|organization.curator.support').default(['organization.curator','organization.curator.repair','organization.curator.support'])}).strict();
export type AutomaticRoutinePolicy=z.infer<typeof AutomaticRoutinePolicySchema>;
export function automaticRoutinePresets(policyId:string,policyRevisionId:string,scopeKey:string,timezone:string):AutomaticRoutinePolicy[]{return (['incremental','daily','weekly','monthly'] as const).map((kind,i)=>AutomaticRoutinePolicySchema.parse({version:automaticMaintenanceVersion,policyId,policyRevisionId,scopeKey,presetVersion:automaticAllowancePreset,kind,enabled:true,cadence:{kind,timezone,hour:[0,2,3,4][i]},startWindowMs:[15,360,1440,4320][i]!*60000,executionMs:[10,20,45,90][i]!*60000,groupMs:600000,allowance:{calls:[8,16,32,48][i],tokens:[128000,256000,512000,768000][i]},monthAllowance:{calls:128,tokens:2000000}}));}
export function automaticNext(policy:AutomaticRoutinePolicy,after:Date):string{if(policy.kind==='incremental')return new Date(after.getTime()+policy.cadence.debounceMs).toISOString();const {debounceMs:_debounce,...cadence}=policy.cadence;return maintenanceOccurrences(MaintenanceCadenceSchema.parse({...cadence,kind:cadence.kind==='daily'?'custom':cadence.kind,everyDays:1}),after,1)[0]!;}
export const AutomaticRoutineScheduleSchema=z.object({id:z.string().uuid(),revision:z.number().int(),policy:AutomaticRoutinePolicySchema,nextAt:z.string(),lastRunId:z.string().uuid().nullable(),lastError:z.string().nullable(),updatedAt:z.string()}).strict();
export const AutomaticMaintenanceCheckpointSchema=z.object({manualRequested:z.boolean().default(false),lastTickAt:z.string().nullable().default(null),eligibleMs:z.number().nonnegative().default(0),executionMs:z.number().nonnegative().default(0),deferredMs:z.number().nonnegative().default(0),closedMs:z.number().nonnegative().default(0),startedAt:z.string().nullable().default(null),reason:z.string().nullable().default(null),bootstrapId:z.string().uuid().nullable().default(null),impactDeliveryId:z.string().uuid().nullable().default(null),phase:z.enum(['impacts','coverage','complete']).default('impacts'),calls:z.number().int().nonnegative().default(0),reservedTokens:z.number().nonnegative().default(0),completedSources:z.number().int().nonnegative().default(0),completedGroups:z.number().int().nonnegative().default(0),catalogedSources:z.number().int().nonnegative().default(0),incomplete:z.boolean().default(false)}).strict();
export const AutomaticMaintenanceRunSchema=z.object({usage:z.object({inputTokens:z.number().nullable(),outputTokens:z.number().nullable(),cost:z.number().nullable(),calls:z.number().int(),knownInput:z.number().int(),knownOutput:z.number().int(),knownCost:z.number().int()}).default({inputTokens:null,outputTokens:null,cost:null,calls:0,knownInput:0,knownOutput:0,knownCost:0}),id:z.string().uuid(),jobId:z.string().uuid(),scheduleIds:z.array(z.string().uuid()),status:z.string(),snapshot:z.object({promptPin:PromptPinSchema.nullable().default(null),profile:OrganizationProfileSchema.nullable().default(null),contentLanguage:z.string().default('en'),version:z.literal(automaticMaintenanceVersion),policy:AutomaticRoutinePolicySchema,policyRevisionId:z.string().uuid(),dueAt:z.string(),manual:z.boolean(),cutoff:z.string()}).strict(),checkpoint:AutomaticMaintenanceCheckpointSchema,reservation:AutomaticAllowanceSchema,createdAt:z.string(),updatedAt:z.string()}).strict();
export type AutomaticMaintenanceRun=z.infer<typeof AutomaticMaintenanceRunSchema>;
export const AutomaticMaintenancePreviewSchema=z.object({promptPin:PromptPinSchema.nullable().default(null),version:z.literal(automaticMaintenanceVersion),routines:z.array(z.object({policy:AutomaticRoutinePolicySchema,scheduleId:z.string().uuid().nullable(),action:z.enum(['create','preserve'])}).strict()).length(4),legacy:z.array(z.object({id:z.string().uuid(),name:z.string(),enabled:z.boolean(),action:z.literal('retain_separate')}).strict()),monthAllowance:AutomaticAllowanceSchema}).strict();
export const AutomaticMaintenanceDashboardSchema=z.object({policyState:z.enum(['draft','enabled','paused','disabled']).default('draft'),schedules:z.array(AutomaticRoutineScheduleSchema),runs:z.array(AutomaticMaintenanceRunSchema),month:z.string(),reserved:AutomaticAllowanceSchema}).strict();
export const AutomaticMaintenanceCommandSchema=z.discriminatedUnion('command',[
 z.object({command:z.literal('automaticRetireLegacy'),scheduleIds:z.array(z.string().uuid()).min(1).max(100)}).strict(),
 z.object({command:z.literal('automaticDashboard'),policyId:z.string().uuid()}).strict(),
 z.object({command:z.literal('automaticRun'),scheduleId:z.string().uuid(),requestId:z.string().uuid()}).strict(),
 z.object({command:z.literal('automaticCancel'),runId:z.string().uuid()}).strict(),
 z.object({command:z.literal('automaticSave'),scheduleId:z.string().uuid(),expectedRevision:z.number().int(),policy:AutomaticRoutinePolicySchema}).strict()
]);
/** Polling gaps are closed/unknown time, never invented eligible or execution time. */
export function automaticClock(checkpoint:z.infer<typeof AutomaticMaintenanceCheckpointSchema>,now:Date,eligible:boolean,reason:string|null){const next=structuredClone(checkpoint),elapsed=next.lastTickAt?Math.max(0,now.getTime()-Date.parse(next.lastTickAt)):0,open=elapsed<=30000?elapsed:0;next.closedMs+=elapsed-open;if(eligible){next.eligibleMs+=open;if(next.startedAt)next.executionMs+=open;}else next.deferredMs+=open;next.lastTickAt=now.toISOString();next.reason=reason;return next;}
