import {describe,it,expect} from 'vitest';
import {KnowledgeDateSchema,InterpretationDraftSchema,NoteEvolutionSchema} from './knowledge-evolution.js';
import {CuratorStartSchema,CuratorSnapshotSchema} from './automatic-wiki-runtime.js';
import {AutomaticWikiPolicySchema} from './automatic-wiki.js';
describe('A7 knowledge evolution boundaries',()=>{
 it('preserves the precision of supplied year/month dates and rejects invented precision formats',()=>{expect(KnowledgeDateSchema.parse({precision:'year',value:'2024'}).value).toBe('2024');expect(KnowledgeDateSchema.parse({precision:'month',value:'2025-03'}).value).toBe('2025-03');expect(KnowledgeDateSchema.safeParse({precision:'year',value:'2024-01-01'}).success).toBe(false);expect(KnowledgeDateSchema.safeParse({precision:'day',value:'2025-02-30'}).success).toBe(false);});
 it('requires explicit nullable date axes and qualified experience procedures',()=>{const draft={statement:'In2024 short sessions were preferred.',perspective:'user_statement',context:'historical',eventTime:{precision:'year',value:'2024'},validFrom:null,validUntil:null,publicationTime:null,relationships:[],procedure:null,originalHandles:['e1']};expect(InterpretationDraftSchema.parse(draft).publicationTime).toBeNull();expect(InterpretationDraftSchema.safeParse({...draft,publicationTime:undefined}).success).toBe(false);expect(InterpretationDraftSchema.safeParse({...draft,procedure:{steps:['Try'],workedWhen:'One supplied experience',assumptions:[],limits:[],corrections:[]}}).success).toBe(false);});
 it('validates merge/split cardinality and never grants old snapshots an intent',()=>{expect(CuratorStartSchema.shape.intent.isOptional()).toBe(true);expect(CuratorSnapshotSchema.shape.intent.isOptional()).toBe(true);expect(AutomaticWikiPolicySchema.shape.operations.parse(['create_grounded'])).toEqual(['create_grounded']);const raw={version:'note-evolution-v1',kind:'split',noteIds:['00000000-0000-4000-8000-000000000001'],reason:'Separate ideas',notes:[{title:'One',ideaStatement:'One',bodyMarkdown:'One',originalHandles:['e1']}]};expect(NoteEvolutionSchema.safeParse(raw).success).toBe(false);expect(NoteEvolutionSchema.safeParse({...raw,notes:[...raw.notes,...raw.notes]}).success).toBe(true);});
});
