import { z } from "zod";
import { normalizeProjectionText, outsideCodeFences, parseWikiRegions, sectionStart, sectionEnd } from "./obsidian-format.js";
export const obsidianEditingCapability = "obsidian-editorial-v1" as const;
const id = z.string().uuid();
const hash = z.string().regex(/^[a-f0-9]{64}$/);
const path = z.string().min(1).max(1024).refine(p => !p.startsWith('/') && !p.includes('\\') && !p.split('/').some(s => s === '..' || s === '.' || s === ''));
export const obsidianBindingSchema = z.object({ vaultId: id, binding: hash, managedRoot: path }).strict();
export const obsidianEditOperationSchema = z.object({
    version: z.literal(1), operationId: id, vaultId: id, binding: hash,
    targetId: id, targetType: z.enum(['wiki_page', 'source_item', 'atomic_note', 'source_reference', 'wiki_index', 'source_relation']),
    kind: z.enum(['edit', 'move', 'delete', 'detach']), relativePath: path, previousRelativePath: path.optional(),
    baseRevision: z.string().min(1).max(200), baseVersion: z.number().int().nonnegative(), baseHash: hash,
    content: z.string().max(2000000), occurredAt: z.string().datetime(),
    resolution: z.object({ operationId: id, currentRevision: z.string(), choice: z.enum(['local', 'app', 'manual']), observedLocal: z.string().max(2000000).nullable().optional() }).strict().optional()
}).strict();
export type ObsidianEditOperation = z.infer<typeof obsidianEditOperationSchema>;
export const obsidianEditReceiptSchema = z.object({
    operationId: id, targetId: id, status: z.enum(['synced', 'conflict', 'deleted', 'ignored']),
    revision: z.string(), syncVersion: z.number().int().nonnegative(), contentHash: hash,
    projection: z.enum(['pending', 'synced', 'conflict', 'tombstoned']),
    content: z.string().max(2000000), reason: z.string().max(200).nullable(),
    comparison: z.object({ base: z.string().max(2000000), local: z.string().max(2000000), app: z.string().max(2000000) }).strict().nullable()
}).strict();
export type ObsidianEditReceipt = z.infer<typeof obsidianEditReceiptSchema>;
export const obsidianResolutionSchema = z.object({ originalOperationId: id, operation: obsidianEditOperationSchema, receipt: obsidianEditReceiptSchema, supersededOperationIds: z.array(id).max(1000).default([]) }).strict();
export const obsidianEditorialConflictsSchema = z.array(z.object({ id, path: z.string(), receipt: obsidianEditReceiptSchema }).strict()).max(100);
export const obsidianResolveInputSchema = z.object({ id, expectedLocal: z.string().max(2000000).nullable(), choice: z.enum(['local', 'app', 'manual']), content: z.string().max(2000000), currentRevision: z.string() }).strict();
export const obsidianManifestSchema = z.object({ resolutions: z.array(obsidianResolutionSchema).max(25).default([]), binding: obsidianBindingSchema, cursor: z.number().int().nonnegative().nullable(), files: z.array(z.object({ targetId: id, targetType: obsidianEditOperationSchema.shape.targetType, relativePath: path, revision: z.string(), syncVersion: z.number().int(), contentHash: hash, content: z.string().max(2000000) }).strict()).max(25) }).strict();
/** A conservative section merge. Anchor order and all generated bytes must remain intact. */
export function mergeWikiEditorial(base: string, local: string, current: string): string | null {
    const b = parseWikiRegions(base), l = parseWikiRegions(local), c = parseWikiRegions(current);
    if (!b || !l || !c || b.generated !== l.generated)
        return null;
    const ids = (r: typeof b) => r!.sections.map(s => s.id).join(',');
    if (ids(b) !== ids(l) || ids(b) !== ids(c))
        return null;
    const skeleton = (r: typeof b) => { let text = r!.editorial; for (const s of [...r!.sections].reverse())
        text = text.slice(0, s.start) + '@' + s.id + '@' + text.slice(s.end); return text; };
    const bs = skeleton(b), ls = skeleton(l), cs = skeleton(c);
    if (ls !== bs && cs !== bs && ls !== cs)
        return null;
    const selected = ls !== bs ? l : c;
    let result = selected.editorial;
    for (let i = b.sections.length - 1; i >= 0; i--) {
        const before = b.sections[i]!.markdown, left = l.sections[i]!.markdown, right = c.sections[i]!.markdown;
        if (left !== before && right !== before && left !== right)
            return null;
        const section = selected.sections[i]!;
        result = result.slice(0, section.start) + sectionStart(section.id) + '\n' + (left !== before ? left : right) + '\n' + sectionEnd(section.id) + result.slice(section.end);
    }
    return result + c.generated;
}
export function atomicEditorial(body: string) {
    body = normalizeProjectionText(body);
    const mask = outsideCodeFences(body), start = mask.indexOf('<!-- memora:relations:start -->');
    if (start < 0)
        return { editorial: body, generated: '' };
    const end = mask.indexOf('<!-- memora:relations:end -->', start);
    if (end < 0 || mask.indexOf('<!-- memora:relations:start -->', start + 1) >= 0 || body.slice(end + 29).trim())
        return null;
    return { editorial: body.slice(0, start), generated: body.slice(start) };
}
