import {createHash,randomUUID} from 'node:crypto';
import {FollowedInvestigationSchema,OrganizationCheckpointSchema,type ConsultationInput,type ConsultationResult,type OrganizationSnapshot,type WikiPageContent,type AutomaticWikiPolicy} from '@app/domain';
import type {PgPool,PgClient} from '../client.js';
import {createWikiRepository} from './wikiRepository.js';
import {validateWikiDependencies,addWikiDependency} from './wikiContextRepository.js';
import {validateAutomaticAuthority} from './automaticMaintenanceRepository.js';
const hash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
const stamp=(v:unknown)=>new Date(v as string).toISOString();
export function createInvestigationRepository(pool:PgPool){
 const tx=async<T>(fn:(db:PgClient)=>Promise<T>)=>{const db=await pool.connect();try{await db.query('begin');const v=await fn(db);await db.query('commit');return v;}catch(e){await db.query('rollback');throw e;}finally{db.release();}};
 const lock=async(db:PgClient,id:string)=>{await db.query("select pg_advisory_xact_lock(hashtextextended($1,0))",['wiki-investigation:'+id]);};
 async function policy(db:Pick<PgClient,'query'>,id:string){const row=(await db.query('select r.policy,a.state,a.revision_id from wiki_policy_activations a join wiki_policy_revisions r on r.id=a.revision_id where a.policy_id=$1 order by a.created_at desc,a.id desc limit 1',[id])).rows[0];if(!row||row.state!=='enabled'||!row.policy.operations.includes('refresh_investigation'))throw new Error('organization.errors.policy');return{...row.policy,state:row.state} as AutomaticWikiPolicy;}
 async function validate(db:PgClient,snapshot:OrganizationSnapshot){for(const e of snapshot.evidence){const row=(await db.query("select c.content_hash,c.document_id,c.source_item_id from chunks c join documents d on d.id=c.document_id where c.id=$1 and d.metadata->>'supersededByDocumentId' is null for share of c,d",[e.chunkId])).rows[0];if(row?.content_hash!==e.contentHash||row.document_id!==e.documentId||row.source_item_id!==e.sourceItemId)throw new Error('organization.errors.evidence');}await validateWikiDependencies(db,[...snapshot.contexts,...snapshot.relations].flatMap(c=>c.dependencies),true);}
 async function savePage(db:PgClient,id:string,expected:string|null,content:WikiPageContent,snapshot:OrganizationSnapshot){await validate(db,snapshot);await createWikiRepository(pool).save({id,expectedRevisionId:expected,content,evidenceChunkIds:snapshot.evidence.map(e=>e.chunkId)},{transaction:db,origin:'organization',allocatedTarget:!expected,humanApproved:false});const revision=(await db.query('select current_revision_id id from wiki_pages where id=$1',[id])).rows[0]!.id as string;for(const section of content.sections)for(const context of [...snapshot.contexts,...snapshot.relations])for(const dep of context.dependencies)await addWikiDependency(db,revision,section.id,dep,context);await db.query("update wiki_pages set management='ai_managed',role='investigation' where id=$1",[id]);return revision;}
 const api={
 async get(id:string){const row=(await pool.query('select * from wiki_investigations where id=$1',[id])).rows[0];if(!row)return null;const history=(await pool.query('select * from wiki_investigation_evaluations where investigation_id=$1 order by created_at desc,id desc limit 50',[id])).rows;return FollowedInvestigationSchema.parse({id:row.id,question:row.question,answerPageId:row.answer_page_id,policyId:row.policy_id,policyRevisionId:row.policy_revision_id,revision:row.revision,state:row.state,input:row.input,lastInputFingerprint:row.last_input_fingerprint,current:row.current,gaps:row.gaps,createdAt:stamp(row.created_at),updatedAt:stamp(row.updated_at),attention:row.attention,history:history.map(h=>({id:h.id,status:h.status,inputFingerprint:h.input_fingerprint,result:h.result,previous:h.previous,runId:h.run_id,changedUnderstanding:h.changed_understanding,error:h.error,createdAt:stamp(h.created_at)}))});},
 async list(){return Promise.all((await pool.query('select id from wiki_investigations order by updated_at desc,id limit 100')).rows.map(r=>api.get(r.id)));},
 async follow(input:ConsultationInput,result:ConsultationResult,snapshot:OrganizationSnapshot,policyId:string,content:WikiPageContent,fingerprint:string){const id=await tx(async db=>{
  await db.query("select pg_advisory_xact_lock(hashtextextended('wiki-placement',0))");await db.query("select pg_advisory_xact_lock(hashtextextended($1,0))",['wiki-policy:'+policyId]);
  const identity=hash([policyId,input.question,input.pageId,[...input.sourceIds].sort(),input.includeDescendants,input.reviewedOnly,input.domainId]);await lock(db,identity);const existing=(await db.query('select id from wiki_investigations where identity=$1 or request_id=$2',[identity,result.id])).rows[0];if(existing)return existing.id as string;
  await db.query("select pg_advisory_xact_lock(hashtextextended($1,0))",['wiki-policy:'+policyId]);const grant=await policy(db,policyId);await api.assertScope(grant,snapshot.sourceIds,db);
  const id=randomUUID(),pageId=randomUUID();await savePage(db,pageId,null,content,snapshot);
  await db.query('insert into wiki_investigations(id,request_id,identity,question,answer_page_id,policy_id,policy_revision_id,state,input,current,last_input_fingerprint,gaps) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)',[id,result.id,identity,input.question,pageId,policyId,grant.revisionId,result.answer.gaps.length?'awaiting_evidence':'followed',input,result,fingerprint,JSON.stringify(result.answer.gaps)]);
  await db.query('insert into wiki_investigation_evaluations(id,investigation_id,input_fingerprint,composition_hash,status,result,snapshot) values($1,$2,$3,$4,$5,$6,$7)',[randomUUID(),id,fingerprint,'initial','initial',result,snapshot]);return id;
 });return api.get(id);},
 async assertScope(grant:AutomaticWikiPolicy,ids:string[],db:Pick<PgClient,'query'>=pool){const rows=(await db.query(`with recursive denied as(select id from source_items where id=any($1::uuid[]) union select s.id from source_items s join denied d on s.parent_source_item_id=d.id),allowed as(select id from source_items where $2 or id=any($3::uuid[]) union select s.id from source_items s join allowed a on s.parent_source_item_id=a.id where $4) select id from allowed where id not in(select id from denied)`,[grant.scope.excludedSourceIds,grant.scope.wholeLibrary,grant.scope.sourceIds,grant.scope.includeDescendants])).rows.map(r=>r.id);if(ids.some(id=>!rows.includes(id)))throw new Error('organization.errors.scope');return rows as string[];},
 async state(id:string,revision:number,state:string){await tx(async db=>{await lock(db,id);const current=(await db.query('select * from wiki_investigations where id=$1 for update',[id])).rows[0];if(!current||current.revision!==revision)throw new Error('wiki.errors.conflict');if(state==='followed'){const grant=await policy(db,current.policy_id);if(grant.revisionId!==current.policy_revision_id)throw new Error('organization.errors.policy');}await db.query('update wiki_investigations set state=$2,revision=revision+1,updated_at=now() where id=$1',[id,state]);await db.query("update knowledge_impact_deliveries set status=$2,updated_at=now() where consumer='investigation' and consumer_key=$1 and status<>'acknowledged'",[id,state==='followed'?'pending':'deferred']);});return api.get(id);},
 async candidates(policyId:string){return(await pool.query("select id from wiki_investigations where policy_id=$1 and state in('followed','awaiting_evidence') order by updated_at,id limit 100",[policyId])).rows.map(r=>r.id as string);},
 async highWater(id:string){return(await pool.query("select id from knowledge_impact_deliveries where consumer='investigation' and consumer_key=$1 and status<>'acknowledged' order by created_at,id limit 1000",[id])).rows.map(r=>r.id as string);},
 async acknowledge(id:string,receipt:unknown,deliveries:string[]){await pool.query("update knowledge_impact_deliveries set status='acknowledged',receipt=$2,lease_until=null,updated_at=now() where consumer='investigation' and consumer_key=$1 and id=any($3::uuid[]) and status<>'acknowledged'",[id,receipt,deliveries]);},
 async noEvidence(id:string,revision:number,deliveries:string[]){await tx(async db=>{await lock(db,id);const item=(await db.query('select * from wiki_investigations where id=$1 for update',[id])).rows[0];if(!item||item.revision!==revision||!['followed','awaiting_evidence'].includes(item.state))return;if(item.last_input_fingerprint==='no-evidence'){await db.query("update knowledge_impact_deliveries set status='acknowledged',receipt=$2,updated_at=now() where consumer='investigation' and consumer_key=$1 and id=any($3::uuid[])",[id,{kind:'no_evidence'},deliveries]);return;}const evaluationId=randomUUID();await db.query("insert into wiki_investigation_evaluations(id,investigation_id,input_fingerprint,composition_hash,status,previous,snapshot,error) values($1,$2,'no-evidence','no-model','awaiting_evidence',$3,'{}','consultation.errors.noRelevantEvidence') on conflict do nothing",[evaluationId,id,item.current]);await db.query("update wiki_investigations set current=jsonb_set(current,'{coverage,stale}','true'),state='awaiting_evidence',attention='consultation.errors.noRelevantEvidence',last_input_fingerprint='no-evidence',revision=revision+1,updated_at=now() where id=$1",[id]);await db.query("update knowledge_impact_deliveries set status='acknowledged',receipt=$2,updated_at=now() where consumer='investigation' and consumer_key=$1 and id=any($3::uuid[])",[id,{kind:'no_evidence'},deliveries]);});},
 async inspectionFailed(id:string,revision:number,error:string){await pool.query("update wiki_investigations set attention=$3 where id=$1 and revision=$2 and state in('followed','awaiting_evidence')",[id,revision,error]);},
 async attention(policyId:string){return(await pool.query("select attention from wiki_investigations where policy_id=$1 and state in('followed','awaiting_evidence') and attention is not null and attention not in('organization.errors.noEvidence','consultation.errors.noRelevantEvidence') order by updated_at limit 1",[policyId])).rows[0]?.attention as string|undefined;},
 async begin(id:string,revision:number,fingerprint:string,compositionHash:string,snapshot:OrganizationSnapshot,maintenanceRunId:string){return tx(async db=>{
  const owner=(await db.query('select policy_id from wiki_investigations where id=$1',[id])).rows[0];if(!owner)throw new Error('organization.errors.canceled');await db.query("select pg_advisory_xact_lock(hashtextextended($1,0))",['wiki-policy:'+owner.policy_id]);await lock(db,id);const item=(await db.query('select * from wiki_investigations where id=$1 for update',[id])).rows[0];if(!item||item.revision!==revision||!['followed','awaiting_evidence'].includes(item.state))throw new Error('organization.errors.canceled');const grant=await policy(db,item.policy_id);if(grant.revisionId!==item.policy_revision_id)throw new Error('organization.errors.policy');await api.assertScope(grant,snapshot.sourceIds,db);await validateAutomaticAuthority(db,maintenanceRunId,item.policy_id,true);
  const existing=(await db.query('select * from wiki_investigation_evaluations where investigation_id=$1 and input_fingerprint=$2 and composition_hash=$3',[id,fingerprint,compositionHash])).rows[0];if(existing){if(existing.status!=='deferred')return{...existing,existing:true};const old=(await db.query('select snapshot,checkpoint from organization_runs where id=$1 for update',[existing.run_id])).rows[0];if((old.checkpoint.investigationOccurrenceId??old.snapshot.maintenanceRunId)===maintenanceRunId)return{...existing,existing:true};if((await db.query('select 1 from automatic_routine_calls where organization_run_id=$1',[existing.run_id])).rows.length||(await db.query('select 1 from organization_steps where run_id=$1',[existing.run_id])).rows.length)return{...existing,existing:true};
   await db.query("update organization_runs set status='analyzing',checkpoint=jsonb_set(checkpoint,'{investigationOccurrenceId}',to_jsonb($2::text)),updated_at=now() where id=$1",[existing.run_id,maintenanceRunId]);await db.query("update wiki_investigation_evaluations set status='running',error=null where id=$1",[existing.id]);await db.query('update wiki_investigations set attention=null where id=$1',[id]);return{...existing,existing:false,resumedSnapshot:old.snapshot};}

  const runId=randomUUID(),evaluationId=randomUUID(),checkpoint=OrganizationCheckpointSchema.parse({tools:0,calls:0,repairs:0,reportedInputTokens:0,reportedOutputTokens:0,costEstimate:0,usageIncomplete:true,startedAt:new Date().toISOString(),readHandles:snapshot.evidence.map(e=>e.handle),discoveredHandles:snapshot.evidence.map(e=>e.handle),transcript:[],callPending:false,error:null});
  await db.query("insert into organization_runs(id,status,snapshot,checkpoint) values($1,'analyzing',$2,$3)",[runId,{...snapshot,investigationId:id,maintenanceRunId,investigationPolicyId:item.policy_id},checkpoint]);
  await db.query("insert into wiki_investigation_evaluations(id,investigation_id,input_fingerprint,composition_hash,status,previous,snapshot,run_id) values($1,$2,$3,$4,'running',$5,$6,$7)",[evaluationId,id,fingerprint,compositionHash,item.current,snapshot,runId]);return{id:evaluationId,run_id:runId,existing:false};
 });},
 async guard(id:string,revision:number,runId:string,maintenanceId:string){const item=await api.get(id);if(!item||item.revision!==revision||!['followed','awaiting_evidence'].includes(item.state))throw new Error('organization.errors.canceled');const grant=await policy(pool,item.policyId);if(grant.revisionId!==item.policyRevisionId)throw new Error('organization.errors.policy');await validateAutomaticAuthority(pool,maintenanceId,item.policyId);const run=(await pool.query('select status from organization_runs where id=$1',[runId])).rows[0];if(run?.status!=='analyzing')throw new Error('organization.errors.canceled');},
 async pendingCall(runId:string,sequence:number,started:boolean){await pool.query("update organization_runs set checkpoint=jsonb_set(jsonb_set(checkpoint,'{calls}',to_jsonb($2::int)),'{callPending}',to_jsonb($3::boolean)),updated_at=now() where id=$1",[runId,sequence,started]);},
 async finish(id:string,revision:number,evaluationId:string,runId:string,maintenanceId:string,result:ConsultationResult,content:WikiPageContent,changedUnderstanding:string[],deliveries:string[]){return tx(async db=>{
  await db.query("select pg_advisory_xact_lock(hashtextextended('wiki-placement',0))");const owner=(await db.query('select policy_id from wiki_investigations where id=$1',[id])).rows[0];await db.query("select pg_advisory_xact_lock(hashtextextended($1,0))",['wiki-policy:'+owner.policy_id]);await lock(db,id);const item=(await db.query('select * from wiki_investigations where id=$1 for update',[id])).rows[0];if(item.revision!==revision||!['followed','awaiting_evidence'].includes(item.state))throw new Error('organization.errors.canceled');const grant=await policy(db,item.policy_id);if(grant.revisionId!==item.policy_revision_id)throw new Error('organization.errors.policy');await validateAutomaticAuthority(db,maintenanceId,item.policy_id,true);
  const evaluation=(await db.query('select * from wiki_investigation_evaluations where id=$1 for update',[evaluationId])).rows[0];if(evaluation.status!=='running')return;
  const snapshot=evaluation.snapshot as OrganizationSnapshot;await api.assertScope(grant,snapshot.sourceIds,db);await validate(db,snapshot);
  const page=(await db.query('select p.current_revision_id,r.content from wiki_pages p join wiki_page_revisions r on r.id=p.current_revision_id where p.id=$1 for update of p',[item.answer_page_id])).rows[0];if(page.current_revision_id!==snapshot.expectedRevisionId)throw new Error('wiki.errors.conflict');if(page.content.review==='reviewed'||page.content.automatic?.management!=='ai_managed'||page.content.sections.some((s:any)=>s.protected))throw new Error('organization.errors.review');
  const changed=changedUnderstanding.length>0;{await db.query("select set_config('memora.causal_run_id',$1,true)",[runId]);await savePage(db,item.answer_page_id,page.current_revision_id,content,snapshot);}
  await db.query('update wiki_investigation_evaluations set status=$2,result=$3,changed_understanding=$4 where id=$1',[evaluationId,changed?'changed':'no_change',result,JSON.stringify(changedUnderstanding)]);
  await db.query('update wiki_investigations set current=$2,last_input_fingerprint=$3,gaps=$4,state=$5,attention=null,revision=revision+1,updated_at=now() where id=$1',[id,result,evaluation.input_fingerprint,JSON.stringify(result.answer.gaps),result.answer.gaps.length?'awaiting_evidence':'followed']);await db.query("update organization_runs set status='applied',checkpoint=jsonb_set(jsonb_set(checkpoint,'{callPending}','false'),'{error}','null'),updated_at=now() where id=$1",[runId]);
  await db.query("update knowledge_impact_deliveries set status='acknowledged',receipt=$2,updated_at=now() where consumer='investigation' and consumer_key=$1 and status<>'acknowledged' and id=any($3::uuid[])",[id,{evaluationId},deliveries]);
 });},
 async failed(evaluationId:string,runId:string,error:string,uncertain:boolean){await tx(async db=>{const admitted=(await db.query('select snapshot,checkpoint from organization_runs where id=$1 for update',[runId])).rows[0],hasCalls=(await db.query('select 1 from automatic_routine_calls where organization_run_id=$1 union select 1 from organization_steps where run_id=$1 limit 1',[runId])).rows.length>0;
 const deferred=!uncertain&&!hasCalls&&/^(maintenance.errors.(budget|period)|organization.errors.deadline)$/.test(error);const e=(await db.query('update wiki_investigation_evaluations set status=$2,error=$3 where id=$1 returning investigation_id',[evaluationId,uncertain?'uncertain':deferred?'deferred':'failed',error])).rows[0];
 if(deferred)admitted.checkpoint.transcript.push({action:null,result:{deferred:true,occurrenceId:admitted.checkpoint.investigationOccurrenceId??admitted.snapshot.maintenanceRunId,error}});admitted.checkpoint.error=error;
 await db.query("update organization_runs set status='failed',checkpoint=$2,updated_at=now() where id=$1",[runId,admitted.checkpoint]);if(e)await db.query('update wiki_investigations set attention=$2,updated_at=now() where id=$1',[e.investigation_id,error]);});},
 async recover(){await tx(async db=>{const pending=(await db.query("select e.id,e.investigation_id,e.run_id,r.checkpoint from wiki_investigation_evaluations e join organization_runs r on r.id=e.run_id where e.status='running' for update of e,r")).rows;for(const e of pending){const uncertain=Boolean(e.checkpoint.callPending),error=uncertain?'organization.errors.uncertain':'organization.errors.canceled';await db.query('update wiki_investigation_evaluations set status=$2,error=$3 where id=$1',[e.id,uncertain?'uncertain':'failed',error]);await db.query("update organization_runs set status='failed',checkpoint=jsonb_set(checkpoint,'{error}',to_jsonb($2::text)),updated_at=now() where id=$1",[e.run_id,error]);await db.query('update wiki_investigations set attention=$2,updated_at=now() where id=$1',[e.investigation_id,error]);}});}

 };return api;
}
