import type { PgPool } from '../client.js';
export interface LayoutJournal { id:string; binding:string; status:string; config:Record<string,unknown>; previous_config:Record<string,unknown>|null; targets:Record<string,any>[]; created_at:Date }
export function createObsidianLayoutRepository(pool:PgPool) { return {
  async create(binding:string,config:unknown,previous:unknown,targets:unknown):Promise<LayoutJournal> { return (await pool.query('insert into obsidian_layout_migrations(binding,config,previous_config,targets) values($1,$2,$3,$4) returning *',[binding,config,previous,JSON.stringify(targets)])).rows[0]; },
  async get(id:string):Promise<LayoutJournal|null> { return (await pool.query('select * from obsidian_layout_migrations where id=$1',[id])).rows[0]??null; },
  async list(binding:string):Promise<LayoutJournal[]> { return (await pool.query(`select id,binding,status,config,previous_config,created_at,case when row_number() over(order by created_at desc,id desc)=1 then targets else '[]'::jsonb end as targets from obsidian_layout_migrations where binding=$1 order by created_at desc,id desc limit 10`,[binding])).rows; },
  async active(binding:string) { return (await pool.query("select id from obsidian_layout_migrations where binding=$1 and status in ('quiescing','applying','partial','rolling_back') limit 1",[binding])).rows[0]?.id as string|undefined; },
  async update(id:string,status:string,targets:unknown) { await pool.query('update obsidian_layout_migrations set status=$2,targets=$3,updated_at=now() where id=$1',[id,status,JSON.stringify(targets)]); },
  async presence(clientId:string,binding:string,report:unknown) { await pool.query("insert into settings(key,value) values($1,$2) on conflict(key) do update set value=excluded.value,updated_at=now()",['obsidian.layout.presence.'+clientId,{binding,report,at:Date.now()}]); },
  async presences(binding:string) { return (await pool.query("select s.value from settings s join integration_clients c on c.id::text=substring(s.key from length('obsidian.layout.presence.')+1) where s.key like 'obsidian.layout.presence.%' and s.value->>'binding'=$1 and c.status='paired' and c.scopes ? 'obsidian-layout-v2'",[binding])).rows.map(r=>r.value as {binding:string;at:number;report:{openPaths:string[];pendingTargetIds:string[];quiescedMigrationIds?:string[]}}); },
  async assets(sourceIds:string[]) { return (await pool.query('select id,source_item_id as "sourceId",document_id as "documentId",original_file_name as "originalFileName",sha256,size_bytes as "sizeBytes",storage_base as "storageBase",relative_path as "relativePath" from document_assets where source_item_id=any($1::uuid[]) order by id limit 1001',[sourceIds])).rows; }
}; }
