import { createHash, randomUUID } from 'node:crypto';
import { CuratorSupportAssessmentSchema,AutomaticWikiPolicySchema, CuratorSnapshotSchema, CuratorChangeSetSchema, WikiPageContentSchema, WikiPageSchema, type AutomaticWikiPolicy, type CuratorSnapshot, type CuratorChangeSet, type CuratorTarget, type WikiPage } from '@app/domain';
import type { PgPool, PgClient } from '../client.js';
import { addWikiDependency } from './wikiContextRepository.js';
import { createWikiRepository } from './wikiRepository.js';
export const curatorHash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
type Db=Pick<PgPool,'query'>;
const policySql=`select r.policy,a.state from wiki_policy_revisions r join lateral(select state from wiki_policy_activations where policy_id=r.policy_id and revision_id=r.id order by created_at desc,id desc limit 1) a on true where r.policy_id=$1 order by r.created_at desc limit 1`;
async function readPolicy(db:Db,id:string){const row=(await db.query(policySql,[id])).rows[0];return row?AutomaticWikiPolicySchema.parse({...row.policy,state:row.state}):null;}
async function references(db:Db,sourceIds:string[],noteIds:string[],chunkIds?:string[]):Promise<CuratorTarget[]>{
 const sources=(await db.query("select id,title,type,parent_source_item_id,source_uri,language,metadata->'descriptor' as descriptor from source_items where id=any($1::uuid[]) order by id",[sourceIds])).rows;
 const notes=noteIds.length?(await db.query(`select n.*,((select c.source_item_id from chunks c where c.id=n.evidence_chunk_id) is distinct from n.created_from_source_item_id or exists(select 1 from atomic_note_source_links l left join chunks c on c.id=l.chunk_id where l.atomic_note_id=n.id and c.source_item_id is distinct from l.source_item_id)) as invalid_lineage,coalesce((select jsonb_agg(jsonb_build_object('sourceId',l.source_item_id,'chunkId',l.chunk_id) order by l.id) from atomic_note_source_links l where l.atomic_note_id=n.id),'[]'::jsonb) as links from atomic_notes n where n.id=any($1::uuid[]) and n.status not in('rejected','archived') and n.supersession_status='current' order by n.id`,[noteIds])).rows:[];
 const entities=(await db.query(`select e.id,e.canonical_name as title,jsonb_agg(jsonb_build_object('sourceId',m.source_item_id,'chunkId',m.chunk_id) order by m.id) as mentions from entities e join entity_mentions m on m.entity_id=e.id join chunks c on c.id=m.chunk_id join documents d on d.id=c.document_id where m.source_item_id=any($1::uuid[]) and ($2::uuid[] is null or m.chunk_id=any($2)) and c.source_item_id=m.source_item_id and d.metadata->>'supersededByDocumentId' is null and c.chunking_version<>'catalog-metadata-v1' group by e.id order by e.id limit 40`,[sourceIds,chunkIds??null])).rows;
 if(notes.length!==noteIds.length||notes.some(n=>n.invalid_lineage))throw new Error('organization.errors.evidence');
 return [...sources.map(s=>({kind:'source' as const,id:s.id,title:s.title,text:'',sourceIds:[s.id],chunkIds:[],fingerprint:curatorHash(s)})),...notes.map(n=>{const ids=[...new Set<string>([n.created_from_source_item_id,...n.links.map((l:any)=>l.sourceId)])];if(ids.some(id=>!sourceIds.includes(id)))throw new Error('organization.errors.scope');return {kind:'atomic_note' as const,id:n.id,title:n.title||n.idea_statement,text:n.body_markdown,sourceIds:ids,chunkIds:[...new Set<string>([n.evidence_chunk_id,...n.links.map((l:any)=>l.chunkId)].filter(Boolean))],fingerprint:curatorHash({...n,updated_at:undefined,created_at:undefined})};}),...entities.map(e=>({kind:'entity' as const,id:e.id,title:e.title,text:'',sourceIds:[...new Set<string>(e.mentions.map((m:any)=>m.sourceId))],chunkIds:[...new Set<string>(e.mentions.map((m:any)=>m.chunkId))],fingerprint:curatorHash(e)}))];
}
export function createWikiCuratorRepository(pool:PgPool){
 const transaction=async<T>(fn:(db:PgClient)=>Promise<T>)=>{const db=await pool.connect();try{await db.query('begin');const value=await fn(db);await db.query('commit');return value;}catch(e){await db.query('rollback');throw e;}finally{db.release();}};
 const api={
 async allowed(policy:AutomaticWikiPolicy){return(await pool.query(`with recursive excluded as(select id from source_items where id=any($4::uuid[]) union select s.id from source_items s join excluded e on s.parent_source_item_id=e.id), allowed as(select id from source_items where ($1 or id=any($2::uuid[])) and id not in(select id from excluded) union select s.id from source_items s join allowed a on s.parent_source_item_id=a.id where $3 and s.id not in(select id from excluded)) select id from allowed order by id`,[policy.scope.wholeLibrary,policy.scope.sourceIds,policy.scope.includeDescendants,policy.scope.excludedSourceIds])).rows.map(r=>r.id as string);},
 async evidencePage(sourceIds:string[],after:string|null,limit:number,chunkIds?:string[]){
  const rows=(await pool.query(`select c.id as "chunkId",c.source_item_id as "sourceItemId",c.document_id as "documentId",c.source_span_id as "sourceSpanId",c.content_hash as "contentHash",c.content as excerpt,s.title as "sourceTitle",d.created_at as "documentCreatedAt",coalesce(sp.label,sp.selector,sp.page::text) as locator from chunks c join documents d on d.id=c.document_id join source_items s on s.id=c.source_item_id left join source_spans sp on sp.id=c.source_span_id where c.source_item_id=any($1::uuid[]) and ($2::uuid is null or c.id>$2) and ($4::uuid[] is null or c.id=any($4)) and d.metadata->>'supersededByDocumentId' is null and c.metadata->>'processingMode' is distinct from 'catalog_metadata' and d.metadata->>'processingMode' is distinct from 'catalog_metadata' and c.chunking_version<>'catalog-metadata-v1' order by c.id limit $3`,[sourceIds,after,limit+1,chunkIds??null])).rows;
  if(rows.some(r=>r.excerpt.length>12000))throw new Error('organization.errors.scopeLimit');
  return{items:rows.slice(0,limit).map((r,i)=>({...r,documentCreatedAt:new Date(r.documentCreatedAt).toISOString(),handle:'e'+(i+1)})),next:rows.length>limit?rows[limit-1]!.chunkId as string:null};
 },
 async discover(policy:AutomaticWikiPolicy,sourceIds:string[],query:string){
  const allowed=await api.allowed(policy);
  const candidates=(await pool.query(`with candidates as(select p.id,p.title,p.kind,p.toc_owner_id,r.content,r.id revision_id,array(select distinct d.input_id from wiki_dependencies d where d.revision_id=r.id and d.kind='source') sources from wiki_pages p join wiki_page_revisions r on r.id=p.current_revision_id where not p.archived), ranked as(select id,title,kind,toc_owner_id,sources,sources<@$1::uuid[] permitted,case when sources&&$2::uuid[] then 10 else 0 end+ts_rank_cd(to_tsvector('simple',unaccent(coalesce(content->'automatic'->>'purpose','')||' '||title||' '||coalesce(content->>'aliases','')||case when cardinality(sources)>0 and sources<@$1::uuid[] then ' '||coalesce(content->>'sections','') else '' end)),to_tsquery('simple',(select string_agg(quote_literal(term), ' | ') from unnest(tsvector_to_array(to_tsvector('simple',unaccent($3)))) term where length(term)>3))) score from candidates where cardinality(sources)>0) select id,title,kind,toc_owner_id,sources,permitted,score from ranked where score>0 order by score desc,id limit 12`,[allowed,sourceIds,query])).rows;
  const topic=candidates.find(p=>p.kind!=='collection');
  if(topic&&!topic.permitted)return{pages:[],excluded:[{id:topic.id,title:topic.title,sourceIds:topic.sources.filter((id:string)=>!allowed.includes(id))}]};
  const ids=topic?[topic.id]:[];
  if(topic){const owners=(await pool.query("select id from wiki_pages where toc_owner_kind='page' and toc_owner_id=$1 and not archived order by id limit 2",[topic.id])).rows;ids.push(...owners.map(r=>r.id));}
  else ids.push(...candidates.filter(p=>p.permitted).slice(0,2).map(p=>p.id));
  const pages=[];for(const id of ids){const sources=(await pool.query("select distinct d.input_id from wiki_dependencies d join wiki_pages p on p.current_revision_id=d.revision_id where p.id=$1 and d.kind='source'",[id])).rows.map(r=>r.input_id as string);if(sources.some(id=>!allowed.includes(id)))return{pages:[],excluded:[{id,title:candidates.find(p=>p.id===id)?.title??'',sourceIds:sources.filter(id=>!allowed.includes(id))}]};pages.push(WikiPageSchema.parse(await createWikiRepository(pool).get(id)));}
  return{pages,excluded:[]};
 },
 async exactPages(policy:AutomaticWikiPolicy,ids:string[],visited=new Set<string>()):Promise<WikiPage[]>{const allowed=await api.allowed(policy),pages:WikiPage[]=[];for(const id of ids){if(visited.has(id)||visited.size>=3)continue;visited.add(id);const sources=(await pool.query("select distinct input_id from wiki_dependencies d join wiki_pages p on p.current_revision_id=d.revision_id where p.id=$1 and d.kind='source'",[id])).rows.map(r=>r.input_id as string);if(!sources.length||sources.some(id=>!allowed.includes(id)))throw new Error('organization.errors.scopeDecision');pages.push(WikiPageSchema.parse(await createWikiRepository(pool).get(id)));}const owned=(await pool.query("select id from wiki_pages where toc_owner_kind='page' and toc_owner_id=any($1::uuid[]) and not archived order by id limit 2",[ids])).rows.map(r=>r.id as string);const owners=[...owned,...pages.flatMap(p=>p.automatic?.role.kind==='collection'&&p.automatic.role.owner?.kind==='page'?[p.automatic.role.owner.id]:[])].filter(id=>!visited.has(id));if(owners.length)pages.push(...await api.exactPages(policy,owners.slice(0,3-pages.length),visited));return pages;},
 async editorialGeneration(sourceIds:string[]){return(await pool.query("select md5(coalesce(string_agg(e.id::text,',' order by e.id),'')) generation from knowledge_impact_events e where e.kind in('wiki_section','wiki_page') and e.causal_run_id is null and (e.source_ids ?| $1::text[] or exists(select 1 from wiki_dependencies d join wiki_pages p on p.current_revision_id=d.revision_id where d.kind=e.kind and d.input_id=e.input_id and exists(select 1 from wiki_dependencies s where s.revision_id=d.revision_id and s.kind='source' and s.input_id=any($1::uuid[]))))",[sourceIds])).rows[0]!.generation as string;},
 async entityReferenceCount(sourceIds:string[],chunkIds:string[]){return(await pool.query("select count(distinct m.entity_id)::int count from entity_mentions m join chunks c on c.id=m.chunk_id join documents d on d.id=c.document_id where m.source_item_id=any($1::uuid[]) and m.chunk_id=any($2::uuid[]) and c.source_item_id=m.source_item_id and d.metadata->>'supersededByDocumentId' is null and c.chunking_version<>'catalog-metadata-v1'",[sourceIds,chunkIds])).rows[0]!.count as number;},
 async noteOriginals(id:string){const row=(await pool.query("select n.created_from_source_item_id source_id,array(select distinct id from (select n.evidence_chunk_id id union select l.chunk_id from atomic_note_source_links l where l.atomic_note_id=n.id) q where id is not null) chunk_ids,array(select distinct id from (select n.created_from_source_item_id id union select l.source_item_id from atomic_note_source_links l where l.atomic_note_id=n.id) q where id is not null) source_ids from atomic_notes n where n.id=$1 and n.status not in('rejected','archived') and n.supersession_status='current'",[id])).rows[0];if(!row)throw new Error('organization.errors.evidence');return row as {source_id:string;source_ids:string[];chunk_ids:string[]};},
 async sourceMetadata(ids:string[]){return(await pool.query('select id,title from source_items where id=any($1::uuid[]) order by id limit 30',[ids])).rows as Array<{id:string;title:string}>;},
 async noteIds(sourceIds:string[]){return (await pool.query("select id from atomic_notes where created_from_source_item_id=any($1::uuid[]) and status not in('rejected','archived') and supersession_status='current' order by id limit 101",[sourceIds])).rows.map(r=>r.id as string);},
 async policy(id:string){return readPolicy(pool,id);},
 async policies(){const ids=(await pool.query('select distinct policy_id from wiki_policy_revisions')).rows;return (await Promise.all(ids.map(r=>readPolicy(pool,r.policy_id)))).filter((p):p is AutomaticWikiPolicy=>!!p);},
 async draft(policy:AutomaticWikiPolicy,preview:unknown,previewHash:string){await pool.query('insert into wiki_policy_revisions(id,policy_id,policy,preview,preview_hash) values($1,$2,$3,$4,$5)',[policy.revisionId,policy.id,policy,preview,previewHash]);},
 async activate(id:string,revision:string,previewHash:string){return transaction(async db=>{await db.query("select pg_advisory_xact_lock(hashtextextended($1,0))",['wiki-policy:'+id]);const row=(await db.query('select * from wiki_policy_revisions where id=$1 and policy_id=$2 for update',[revision,id])).rows[0];if(!row||row.preview_hash!==previewHash)throw new Error('organization.errors.conflict');const prior=await readPolicy(db,id);if(prior?.revisionId===revision&&prior.state==='enabled')return prior;await db.query("insert into wiki_policy_activations(policy_id,revision_id,state,created_at) values($1,$2,'enabled',clock_timestamp())",[id,revision]);return AutomaticWikiPolicySchema.parse({...row.policy,state:'enabled'});});},
 async resume(id:string){const policy=await readPolicy(pool,id);if(!policy)throw new Error('organization.errors.policy');const row=(await pool.query('select preview_hash from wiki_policy_revisions where id=$1',[policy.revisionId])).rows[0];return api.activate(id,policy.revisionId,row.preview_hash);},
 async pause(id:string){return transaction(async db=>{await db.query("select pg_advisory_xact_lock(hashtextextended($1,0))",['wiki-policy:'+id]);const policy=await readPolicy(db,id);if(!policy)throw new Error('organization.errors.scope');await db.query("insert into wiki_policy_activations(policy_id,revision_id,state,created_at) values($1,$2,'paused',clock_timestamp())",[id,policy.revisionId]);return {...policy,state:'paused' as const};});},
 async scope(policy:AutomaticWikiPolicy,selected:string[]){const allowed=await api.allowed(policy);if(selected.some(id=>!allowed.includes(id)))throw new Error('organization.errors.scope');return selected.toSorted();},
 references:(sourceIds:string[],noteIds:string[],chunkIds?:string[])=>references(pool,sourceIds,noteIds,chunkIds),
 async pages(sourceIds:string[]){const ids=(await pool.query(`select p.id from wiki_pages p join wiki_page_revisions r on r.id=p.current_revision_id where not p.archived and not exists(select 1 from wiki_evidence e where e.page_id=p.id and e.source_item_id<>all($1::uuid[])) and (exists(select 1 from wiki_evidence e where e.page_id=p.id and e.source_item_id=any($1::uuid[])) or exists(select 1 from wiki_dependencies d where d.revision_id=r.id and d.kind='source' and d.input_id=any($1::uuid[]))) and not exists(select 1 from wiki_dependencies d where d.revision_id=r.id and d.kind='source' and d.input_id<>all($1::uuid[])) order by p.id limit 101`,[sourceIds])).rows;if(ids.length>100)throw new Error('organization.errors.scopeLimit');return Promise.all(ids.map(async r=>WikiPageSchema.parse(await createWikiRepository(pool).get(r.id))));},
 async unchanged(inputFingerprint:string,policyId:string){
  const candidates=(await pool.query(`select r.id,g.targets from organization_runs r join wiki_group_receipts g on g.run_id=r.id where g.input_fingerprint=$1 and r.snapshot->'policy'->>'id'=$2 order by g.created_at desc limit 10`,[inputFingerprint,policyId])).rows;
  const editorial=(value:any)=>{if(!value)return null;const {pinned:_pin,position:_position,parentId:_parent,...content}=value;const automatic=content.automatic?structuredClone(content.automatic):undefined;if(automatic){delete automatic.placementProtected;automatic.groups=automatic.groups.map(({orderProtected:_order,...g}:any)=>g).toSorted((a:any,b:any)=>a.id.localeCompare(b.id));automatic.memberships=automatic.memberships.map(({expectedPageRevisionId:_revision,order:_order,placementProtected:_protection,...m}:any)=>m).toSorted((a:any,b:any)=>a.id.localeCompare(b.id));}return{...content,...(automatic?{automatic}:{}),sections:content.sections.toSorted((a:any,b:any)=>a.id.localeCompare(b.id))};};
  for(const candidate of candidates){let same=true;for(const target of candidate.targets){const row=(await pool.query('select old.content previous,current.content present from wiki_page_revisions old join wiki_pages p on p.id=old.page_id join wiki_page_revisions current on current.id=p.current_revision_id where old.id=$1 and p.id=$2',[target.revisionId,target.pageId])).rows[0];if(!row||curatorHash(editorial(row.previous))!==curatorHash(editorial(row.present))){same=false;break;}}if(same)return candidate.id as string;}
  return undefined;
 },
 async validate(snapshot:CuratorSnapshot,db:Db=pool,lock=false){
 if(snapshot.parentBootstrapId){const parent=(await db.query("select status,checkpoint from organization_runs where id=$1"+(lock?" for share":""),[snapshot.parentBootstrapId])).rows[0];if(!parent||parent.status==='canceled'||parent.checkpoint.state!=='running')throw new Error('organization.errors.policy');}
 const policy=await readPolicy(db,snapshot.policy.id);if(policy?.state!=='enabled'||policy.revisionId!==snapshot.policy.revisionId)throw new Error('organization.errors.policy');
 if(lock){await db.query('lock table source_items in share mode');await db.query('select id from source_items where id=any($1::uuid[]) order by id for update',[snapshot.sourceIds]);await db.query('select id from documents where id=any($1::uuid[]) order by id for share',[snapshot.evidence.map(e=>e.documentId)]);await db.query('select id from chunks where id=any($1::uuid[]) order by id for share',[snapshot.evidence.map(e=>e.chunkId)]);await db.query('lock table atomic_note_source_links in share mode');await db.query('lock table entity_mentions in share mode');await db.query('select id from entities where id=any($1::uuid[]) order by id for share',[snapshot.references.filter(r=>r.kind==='entity').map(r=>r.id)]);await db.query('select id from atomic_notes where id=any($1::uuid[]) order by id for update',[snapshot.references.filter(r=>r.kind==='atomic_note').map(r=>r.id)]);}
 const scope=(await db.query(`with recursive excluded as(select id from source_items where id=any($4::uuid[]) union select s.id from source_items s join excluded e on s.parent_source_item_id=e.id), allowed as(select id from source_items where ($1 or id=any($2::uuid[])) and id not in(select id from excluded) union select s.id from source_items s join allowed a on s.parent_source_item_id=a.id where $3 and s.id not in(select id from excluded)) select id from allowed`,[policy.scope.wholeLibrary,policy.scope.sourceIds,policy.scope.includeDescendants,policy.scope.excludedSourceIds])).rows;if(snapshot.sourceIds.some(id=>!scope.some(r=>r.id===id)))throw new Error('organization.errors.scope');
 const current=(await db.query(`select c.id,c.source_item_id,c.document_id,c.source_span_id,c.content_hash,c.content from chunks c join documents d on d.id=c.document_id where c.id=any($1::uuid[]) and d.metadata->>'supersededByDocumentId' is null and c.chunking_version<>'catalog-metadata-v1' and c.metadata->>'processingMode' is distinct from 'catalog_metadata' and d.metadata->>'processingMode' is distinct from 'catalog_metadata'`,[snapshot.evidence.map(e=>e.chunkId)])).rows;
 if(snapshot.evidence.some(e=>!current.some(c=>c.id===e.chunkId&&c.source_item_id===e.sourceItemId&&c.document_id===e.documentId&&c.source_span_id===e.sourceSpanId&&c.content_hash===e.contentHash&&c.content===e.excerpt)))throw new Error('organization.errors.evidence');
 const refs=await references(db,snapshot.sourceIds,snapshot.references.filter(r=>r.kind==='atomic_note').map(r=>r.id),snapshot.evidence.map(e=>e.chunkId));if(snapshot.references.filter(r=>r.kind!=='page').some(r=>!refs.some(c=>c.kind===r.kind&&c.id===r.id&&c.fingerprint===r.fingerprint)))throw new Error('organization.errors.evidence');
 for(const page of snapshot.pages){const row=(await db.query('select current_revision_id from wiki_pages where id=$1',[page.id])).rows[0];if(row?.current_revision_id!==page.revisionId)throw new Error('organization.errors.conflict');}
 },
 async apply(runId:string,human:boolean,validate:(s:CuratorSnapshot,p:CuratorChangeSet)=>void,authorize?:()=>Promise<void>){return transaction(async db=>{
 await db.query("select pg_advisory_xact_lock(hashtextextended('wiki-placement',0))");
 const preliminary=(await db.query('select snapshot from organization_runs where id=$1',[runId])).rows[0];if(!preliminary)throw new Error('organization.errors.invalid');const snapshot=CuratorSnapshotSchema.parse(preliminary.snapshot);
 await db.query("select pg_advisory_xact_lock(hashtextextended($1,0))",['wiki-policy:'+snapshot.policy.id]);
 const run=(await db.query('select * from organization_runs where id=$1 for update',[runId])).rows[0]!;
 const receipt=(await db.query('select targets from wiki_group_receipts where run_id=$1 and group_id=$2',[runId,snapshot.groupId])).rows[0];if(receipt)return receipt.targets;
 const job=(await db.query('select cancel_requested_at from jobs where id=$1 for update',[run.job_id])).rows[0];if(!human&&Date.now()>=Date.parse(snapshot.admittedAt)+snapshot.limits.deadlineMs)throw new Error('organization.errors.deadline');if(run.status!=='awaiting_review'||job?.cancel_requested_at)throw new Error('organization.errors.canceled');
 const proposal=CuratorChangeSetSchema.parse((await db.query('select proposal from organization_proposals where run_id=$1',[runId])).rows[0]?.proposal);validate(snapshot,proposal);
 const support=CuratorSupportAssessmentSchema.safeParse(run.checkpoint.supportAssessment),proposalHash=curatorHash(proposal);if(!support.success||!support.data.verdict.supported||support.data.proposalHash!==proposalHash||support.data.verdict.checkedTargets.length!==proposal.targets.length||proposal.targets.some(t=>!support.data.verdict.checkedTargets.includes(t.handle)))throw new Error('organization.errors.evidence');
 const checked=(await db.query("select s.ai_task_run_id from organization_steps s join ai_task_runs a on a.id=s.ai_task_run_id where s.run_id=$1 and s.ai_task_run_id=$2 and a.status='succeeded' and s.artifact->>'proposalHash'=$3 and s.artifact->'support'->>'supported'='true' and s.artifact->'support'=$4::jsonb and exists(select 1 from jsonb_array_elements(a.prompt_compositions) p where p->>'promptId'='organization.curator.support')",[runId,support.data.aiTaskRunId,proposalHash,JSON.stringify(support.data.verdict)])).rows[0];if(!checked)throw new Error('organization.errors.evidence');
 await db.query('select id from wiki_pages where id=any($1::uuid[]) order by id for update',[snapshot.pages.map(p=>p.id)]);await api.validate(snapshot,db,true);
 if(authorize){await db.query('select id from ai_profile_sets where id=$1 for share',[snapshot.profile.profileId]);await db.query('select id from ai_profile_tasks where profile_id=$1 order by id for share',[snapshot.profile.profileId]);if(snapshot.profile.localModelId)await db.query('select id from local_models where id=$1 for share',[snapshot.profile.localModelId]);if(snapshot.profile.providerConfigId)await db.query('select id from ai_provider_configs where id=$1 for share',[snapshot.profile.providerConfigId]);await authorize();}
 await db.query("select set_config('memora.causal_run_id',$1,true),set_config('memora.causal_group_id',$2,true)",[snapshot.causalRunId??runId,snapshot.causalGroupId??snapshot.groupId]);
 const ids=new Map(proposal.targets.map(t=>[t.handle,t.pageId??randomUUID()]));const resolve=(r:CuratorChangeSet['targets'][number]['links'][number])=>r.reference==='existing'?r.target:{kind:'page' as const,id:ids.get(r.handle)!};
 // Allocate all page identities first; only the transaction can observe them.
 for(const target of proposal.targets)if(!target.pageId){const duplicate=(await db.query(`select p.id from wiki_pages p join wiki_page_revisions r on r.id=p.current_revision_id where not p.archived and (unaccent(lower(p.title))=unaccent(lower($1)) or exists(select 1 from jsonb_array_elements_text(r.content->'aliases') a where unaccent(lower(a))=unaccent(lower($1))))`,[target.title])).rows;if(duplicate.length){const same=(await db.query("select r.content->'automatic'->>'purpose' as purpose from wiki_pages p join wiki_page_revisions r on r.id=p.current_revision_id where p.id=any($1::uuid[]) and p.kind=$2 and (exists(select 1 from wiki_evidence e where e.page_id=p.id and e.source_item_id=any($3::uuid[])) or exists(select 1 from wiki_dependencies d where d.revision_id=r.id and d.kind='source' and d.input_id=any($3::uuid[])))",[duplicate.map(r=>r.id),target.role.kind,snapshot.sourceIds])).rows;if(same.some(r=>r.purpose&&r.purpose.toLocaleLowerCase()===target.purpose.toLocaleLowerCase()))throw new Error('organization.errors.conflict');}await db.query('insert into wiki_pages(id,title,kind,management) values($1,$2,$3,$4)',[ids.get(target.handle),target.title,target.role.kind,'ai_managed']);}
 const result=[];
 // Parent identities exist before saving; existing global placement lock validates canonical cycles.
 for(const target of proposal.targets){const pageId=ids.get(target.handle)!,old=snapshot.pages.find(p=>p.id===pageId);if(old&&old.revisionId!==target.expectedRevisionId)throw new Error('organization.errors.conflict');
 if(old&&!human&&(old.automatic?.management!=='ai_managed'||old.review==='reviewed'||target.sections.some(p=>old.sections.find(s=>s.id===p.sectionId)?.protected)))throw new Error('organization.errors.review');
 const content=old?WikiPageContentSchema.strip().parse(old):WikiPageContentSchema.parse({title:target.title,kind:target.role.kind,parentId:target.initialParent?resolve(target.initialParent).id:null,entityId:target.role.kind==='entity'?target.role.entityId:null});content.title=target.title;if(target.sections.length)content.review='draft';const plannedRevision=randomUUID();
 for(const patch of target.sections){const previous=content.sections.find(s=>s.id===patch.sectionId);const sectionId=patch.sectionId??randomUUID(),sectionRevisionId=randomUUID();const evidenceIds=[...new Set(patch.originalHandles.map(h=>snapshot.evidence.find(e=>e.handle===h)!.chunkId))];const section={id:sectionId,sectionRevisionId,title:patch.title,kind:previous?.kind??'prose' as const,markdown:patch.markdown.replace(/\[(e[1-9][0-9]{0,3})\]/g,(m,h:string)=>`[${patch.originalHandles.indexOf(h)+1}]`),provenance:'generated' as const,protected:previous?.protected??false,evidenceReview:'needs_review' as const,evidenceIds,assessment:{version:'automatic-wiki-v1' as const,sectionId,sectionRevisionId,humanReview:'unreviewed' as const,support:'validated' as const,reason:'generated_pending_verification' as const,supportMethod:'model_checked' as const,supportAuditId:support.data.aiTaskRunId,inputFingerprint:curatorHash(patch.originalHandles.map(h=>snapshot.evidence.find(e=>e.handle===h))),freshness:'current' as const}};if(previous)content.sections[content.sections.indexOf(previous)]=section;else content.sections.push(section);}
 const role=target.role.kind==='collection'?{...target.role,owner:target.role.owner?resolve(target.role.owner):null}:target.role;
 const automatic=structuredClone(old?.automatic??{version:'automatic-wiki-v1' as const,management:'ai_managed' as const,role,purpose:target.purpose,placementProtected:false,links:[],groups:[],memberships:[]});automatic.purpose=target.purpose;automatic.links=target.links.map(resolve);automatic.role=role;
 for(const group of target.tocGroups){const prior=automatic.groups.find(g=>g.id===group.id);if(prior&&!human&&(prior.orderProtected||automatic.memberships.some(m=>m.groupId===prior.id&&m.placementProtected)))throw new Error('organization.errors.review');if(!group.id&&automatic.groups.some(g=>g.title===group.title))throw new Error('organization.errors.conflict');const groupId=group.id??randomUUID();const members:typeof automatic.memberships=group.memberships.map(m=>({version:'automatic-wiki-v1' as const,id:m.id??automatic.memberships.find(old=>old.groupId===groupId&&old.target.kind===resolve(m.target).kind&&old.target.id===resolve(m.target).id)?.id??randomUUID(),pageId,groupId,target:resolve(m.target),purpose:m.purpose,order:m.order,origin:'generated' as const,placementProtected:automatic.memberships.find(old=>old.id===m.id)?.placementProtected??false,expectedPageRevisionId:plannedRevision,targetFingerprint:m.target.reference==='existing'?m.target.fingerprint:snapshot.inputFingerprint}));const retained=automatic.memberships.filter(m=>m.groupId===groupId&&!members.some(next=>next.target.kind===m.target.kind&&next.target.id===m.target.id));members.unshift(...retained.map(m=>({...m,expectedPageRevisionId:plannedRevision})));members.forEach((member,order)=>member.order=order);const newGroup={version:'automatic-wiki-v1' as const,id:groupId,collectionId:pageId,title:group.title,explanation:group.explanation?.replace(/\[(e[1-9][0-9]{0,3})\]/g,(_m,h:string)=>'['+(group.originalHandles.indexOf(h)+1)+']')??null,explanationEvidenceIds:group.originalHandles.map(h=>snapshot.evidence.find(e=>e.handle===h)!.chunkId),membershipIds:members.map(m=>m.id),orderProtected:prior?.orderProtected??false,origin:'generated' as const};if(prior)automatic.groups[automatic.groups.indexOf(prior)]=newGroup;else automatic.groups.push(newGroup);automatic.memberships=automatic.memberships.filter(m=>m.groupId!==groupId).concat(members);}
 if(old?.automatic&&JSON.stringify(old.automatic.role)!==JSON.stringify(role))throw new Error('organization.errors.scope');content.automatic=automatic;
 const chunkIds=[...new Set([...target.sections.flatMap(s=>s.originalHandles),...target.tocGroups.flatMap(g=>g.originalHandles)].map(h=>snapshot.evidence.find(e=>e.handle===h)!.chunkId))];
 for(const chunkId of chunkIds){const original=snapshot.evidence.find(e=>e.chunkId===chunkId)!;const existing=(await db.query('select snapshot from wiki_evidence where page_id=$1 and chunk_id=$2',[pageId,chunkId])).rows[0];if(existing&&existing.snapshot.contentHash!==original.contentHash)throw new Error('organization.errors.evidence');}
 await createWikiRepository(pool).save({id:pageId,expectedRevisionId:target.expectedRevisionId,content,evidenceChunkIds:chunkIds},{transaction:db,origin:'organization',allocatedTarget:true,humanApproved:human,revisionId:plannedRevision});
 const revisionId=(await db.query('select current_revision_id from wiki_pages where id=$1',[pageId])).rows[0]!.current_revision_id;
 for(const patch of target.sections){const section=content.sections.find(s=>s.id===patch.sectionId||!patch.sectionId&&s.markdown===patch.markdown);if(section)await db.query("update wiki_dependencies set stale_reason=null,changed_at=null where revision_id=$1 and section_id=$2 and kind in('source','document','chunk')",[revisionId,section.id]);}
 for(const link of [...automatic.links,...(role.kind==='collection'&&role.owner?[role.owner]:[])]){const reference=snapshot.references.find(r=>r.kind===link.kind&&r.id===link.id);if(!reference||link.kind!=='page')continue;await addWikiDependency(db,revisionId,pageId,{kind:'wiki_page',id:link.id,fingerprint:reference.fingerprint},reference);for(const section of snapshot.pages.find(p=>p.id===link.id)?.sections??[]){const fingerprint=(await db.query("select md5(sec::text) fingerprint from wiki_page_revisions r cross join lateral jsonb_array_elements(r.content->'sections') sec where r.id=$1 and sec->>'id'=$2",[reference.fingerprint,section.id])).rows[0]?.fingerprint;if(fingerprint)await addWikiDependency(db,revisionId,pageId,{kind:'wiki_section',id:section.id,fingerprint},reference);}}

 await db.query('update wiki_pages set management=$2,role=$3,toc_owner_kind=$4,toc_owner_id=$5 where id=$1',[pageId,automatic.management,role.role,role.kind==='collection'?role.owner?.kind:null,role.kind==='collection'?role.owner?.id:null]);
 for(const section of content.sections)if(section.assessment)await db.query('insert into wiki_section_assessments(section_revision_id,section_id,page_id,assessment) values($1,$2,$3,$4) on conflict do nothing',[section.sectionRevisionId,section.id,pageId,section.assessment]);
 for(const group of automatic.groups)for(const membership of automatic.memberships.filter(m=>m.groupId===group.id)){const reference=snapshot.references.find(r=>r.kind===membership.target.kind&&r.id===membership.target.id);if(reference){if(reference.kind==='page'){await addWikiDependency(db,revisionId,group.id,{kind:'wiki_page',id:reference.id,fingerprint:reference.fingerprint},reference);for(const section of snapshot.pages.find(p=>p.id===reference.id)?.sections??[])await addWikiDependency(db,revisionId,group.id,{kind:'wiki_section',id:section.id,fingerprint:(await db.query("select md5(sec::text) fingerprint from wiki_page_revisions r cross join lateral jsonb_array_elements(r.content->'sections') sec where r.id=$1 and sec->>'id'=$2",[reference.fingerprint,section.id])).rows[0]?.fingerprint??reference.fingerprint},reference);}if(reference.kind!=='page')await addWikiDependency(db,revisionId,group.id,{kind:reference.kind,id:reference.id,fingerprint:reference.fingerprint},reference);for(const sourceId of reference.sourceIds)await addWikiDependency(db,revisionId,group.id,{kind:'source',id:sourceId,fingerprint:reference.fingerprint},reference);for(const chunkId of reference.chunkIds){const e=snapshot.evidence.find(e=>e.chunkId===chunkId);if(e)for(const [kind,id]of [['chunk',e.chunkId],['document',e.documentId]])await addWikiDependency(db,revisionId,group.id,{kind:kind!,id:id!,fingerprint:e.contentHash},e);}}}
 result.push({pageId,revisionId});
 }
 await db.query('insert into wiki_group_receipts(run_id,group_id,input_fingerprint,targets) values($1,$2,$3,$4)',[runId,snapshot.groupId,snapshot.inputFingerprint,JSON.stringify(result)]);await db.query("update organization_proposals set decision=$2,decided_at=now() where run_id=$1",[runId,human?'accept':'policy']);await db.query("update organization_runs set status='applied',updated_at=now() where id=$1",[runId]);return result;
 });}
 };return api;
}
