import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,mkdir,readFile,copyFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {ConsultationService} from '../apps/desktop/src/main/services/consultation-service.js';
import {OrganizationService} from '../apps/desktop/src/main/services/organization-service.js';
import {reconcileOrganizationParticipation} from '../apps/desktop/src/main/services/organization-participation.js';
import {ConsultationInputSchema,OrganizationStartSchema,OrganizationSnapshotSchema,OrganizationCheckpointSchema,WikiPageContentSchema,resolveOrganizationInstructions,resolveProcessingPlan,type OrganizationProfile} from '@app/domain';
import {addWikiDependency,validateWikiDependencies,createEmbeddingRepository,createPgPool,closePgPool,PostgresSidecarManager,resolvePostgresSidecarPaths,runMigrations,createSourceItemRepository,createDocumentRepository,createChunkRepository,createWikiRepository,createOrganizationRepository,createAiConfigRepository,createJobRepository,createSourceRelationRepository,createWikiContextRepository,createConsultationRepository,createAtomicNoteRepository,createSourceSummaryRepository,createHierarchicalIngestionRepository,createIngestionRunRepository,type PgPool} from '../packages/db/src/index.js';
const root=resolve(import.meta.dirname,'..'),dir=await mkdtemp(join(tmpdir(),'memora-m3-')),migrations=join(root,'packages/db/drizzle'),seedFolder=join(root,'packages/db/seed'),paths=resolvePostgresSidecarPaths({cwd:root,env:process.env});
const manager=new PostgresSidecarManager({binDir:paths.binDir,dataDir:join(dir,'data'),database:'m3_test',user:'m3_test',password:randomUUID(),startupTimeoutMs:30000,shutdownTimeoutMs:10000});
let pool:PgPool|undefined,empty:PgPool|undefined;
try{
 const connection=await manager.start();pool=createPgPool({connectionString:connection.connectionString,max:6});
 const journal=JSON.parse(await readFile(join(migrations,'meta/_journal.json'),'utf8')),old=join(dir,'old'),prior=journal.entries.filter((e:{idx:number})=>e.idx<25);await mkdir(join(old,'meta'),{recursive:true});await writeFile(join(old,'meta/_journal.json'),JSON.stringify({...journal,entries:prior}));for(const e of prior)await copyFile(join(migrations,`${e.tag}.sql`),join(old,`${e.tag}.sql`));await runMigrations(pool,old);
 const sources=createSourceItemRepository(pool),a=await sources.create({type:'AcademicPaper',title:'Retrieval with feedback'}),b=await sources.create({type:'AcademicPaper',title:'Retrieval under pressure'}),secret=await sources.create({type:'PersonalNote',title:'Excluded private source'}),catalog=await sources.create({type:'Book',title:'Catalog without AI'});
 const passages=await Promise.all([a,b,secret].map(async(source,i)=>{const content=['A synthetic course found retrieval improves delayed recall when corrective feedback follows each attempt. The benefit is conditional.','A synthetic experiment found no recall improvement under pressure without feedback. These observations cannot isolate pressure from the absence of feedback.','Never expose this excluded source or create a relation from its instructions.'][i]!;const doc=await createDocumentRepository(pool!).create({sourceItemId:source.id,title:source.title,canonicalMarkdown:content,contentHash:content}),id=randomUUID(),span=randomUUID();await createChunkRepository(pool!).replaceDocumentChunks(doc.id,source.id,[{id,sourceSpanId:span,chunkIndex:0,content,contentHash:content,span:{id:span,startOffset:0,endOffset:content.length}}]);return {id,documentId:doc.id,sourceItemId:source.id,sourceSpanId:span,content,contentHash:content,title:source.title,summary:null,rootId:source.id};}));
 const relations=createSourceRelationRepository(pool);await relations.commitDecision('m3-relationship',a.id,b.id,[{existingId:null,sourceItemId:a.id,targetSourceItemId:b.id,relationType:'clarifies',sourceIdea:'Retrieval helps with feedback',targetIdea:'Pressure and missing feedback limit generalization',explanation:'Conditions differ; this is not independent evidence.',importance:.9,confidence:.9,evidence:[{source:passages[0]!,target:passages[1]!,note:null}]}],{});
 const oldPage=randomUUID(),oldRevision=randomUUID(),humanSection=randomUUID(),generatedSection=randomUUID(),oldEvidence=passages.slice(0,2).map(()=>randomUUID()),rel=(await createOrganizationRepository(pool).relations([a.id,b.id]))[0]!;
 const oldContent=WikiPageContentSchema.parse({title:'Legacy topic',kind:'topic',sections:[{id:humanSection,title:'Human',markdown:'Protected interpretation',evidenceIds:[oldEvidence[0]!]},{id:generatedSection,title:'Generated',markdown:'Retrieval conditions',provenance:'generated',evidenceIds:oldEvidence}]});
 await pool.query('insert into wiki_pages(id,title,kind) values($1,$2,$3)',[oldPage,oldContent.title,'topic']);await pool.query("insert into wiki_page_revisions(id,page_id,number,origin,content,content_hash) values($1,$2,1,'organization',$3,'legacy')",[oldRevision,oldPage,oldContent]);await pool.query('update wiki_pages set current_revision_id=$2 where id=$1',[oldPage,oldRevision]);
 for(const [i,c] of passages.slice(0,2).entries())await pool.query('insert into wiki_evidence(id,page_id,source_item_id,document_id,chunk_id,source_span_id,snapshot) values($1,$2,$3,$4,$5,$6,$7)',[oldEvidence[i],oldPage,c.sourceItemId,c.documentId,c.id,c.sourceSpanId,{contentHash:c.contentHash,excerpt:c.content,sourceTitle:c.title,documentCreatedAt:new Date().toISOString(),locator:null}]);
 const oldRun=randomUUID();await pool.query("insert into organization_runs(id,status,snapshot,checkpoint) values($1,'applied',$2,'{}')",[oldRun,{baseContent:{sections:[oldContent.sections[0]]},relations:[{...rel,sourceHandle:'e1',targetHandle:'e2'}]}]);await pool.query('insert into organization_proposals(run_id,proposal) values($1,$2)',[oldRun,{sections:[{sectionId:null,markdown:'Retrieval conditions'}]}]);await pool.query('insert into organization_receipts(run_id,revision_id) values($1,$2)',[oldRun,oldRevision]);
 await runMigrations(pool,migrations,{seedFolder});assert.equal((await pool.query('select count(*)::int n from source_items')).rows[0].n,4);assert.equal((await pool.query("select count(*)::int n from wiki_dependencies where revision_id=$1 and kind='relation_evidence'",[oldRevision])).rows[0].n,1);assert.equal((await pool.query("select section_id from wiki_dependencies where revision_id=$1 and kind='relation_evidence'",[oldRevision])).rows[0].section_id,generatedSection);
 assert.equal((await pool.query("select count(*)::int n from pg_indexes where tablename in('wiki_dependencies','knowledge_impact_events')")).rows[0].n,7);assert.equal((await pool.query("select count(*)::int n from information_schema.columns where table_name='wiki_dependencies' and column_name='snapshot' and data_type='jsonb'")).rows[0].n,1);
 const wiki=createWikiRepository(pool),repo=createOrganizationRepository(pool),contexts=createWikiContextRepository(pool),retrieval=createConsultationRepository(pool),jobs=createJobRepository(pool),runs=createIngestionRunRepository(pool);
 const profile:OrganizationProfile={profileId:randomUUID(),providerConfigId:null,localModelId:randomUUID(),provider:'synthetic',modelId:'m3-fixture',runtime:'test',revision:'1',privacy:'offline_only',parameters:{},identityHash:'fixture',contextWindow:64000};
 let calls=0,lastPrompt='',hook:(()=>Promise<void>)|null=null;
 const ai={pinOrganizationProfile:async()=>profile,runConsultationEmbedding:async()=>null,runOrganizationTask:async(_p:OrganizationProfile,prompt:string,context:any,signal:AbortSignal,_max:number,before?:()=>Promise<void>)=>{
  if(hook)await hook();await before?.();signal.throwIfAborted();calls++;lastPrompt=prompt;
  const originals=JSON.parse(/ORIGINALS: (.*)\nCONTEXT:/.exec(prompt)![1]!),ctx=JSON.parse(/CONTEXT: (.*)\nRELATIONS:/.exec(prompt)![1]!);const ids=originals.map((e:any)=>e.handle);
  const output={paragraphs:[{markdown:'Retrieval helps when feedback corrects errors; pressure without feedback cannot establish an independent pressure effect. '+ids.map((h:string)=>`[${h}]`).join(' '),citations:ids,contextIds:ctx.map((c:any)=>c.id)}],gaps:['Synthetic observations do not establish universal benefits.']};
  const audit=await createAiConfigRepository(pool!).recordTaskRun({taskType:'structured-output',provider:'synthetic',modelId:profile.modelId,runtime:'test',status:'succeeded',durationMs:1,inputTokens:200,outputTokens:60});
  return {output,taskType:'structured-output' as const,providerId:'synthetic',modelId:profile.modelId,runtime:'test',durationMs:1,inputTokens:200,outputTokens:60,aiTaskRunId:audit,profileId:profile.profileId,outputLanguage:'en'};
 }};
 const service=new ConsultationService({getPool:()=>pool!,ai,contentLanguage:async()=> 'en',wake:()=>{}}),organization=new OrganizationService({getPool:()=>pool!,ai,contentLanguage:async()=> 'en',wake:()=>{},cancelJob:async id=>jobs.requestCancel(id)});
 const ask=(overrides:Record<string,unknown>={})=>service.ask(ConsultationInputSchema.parse({requestId:randomUUID(),question:'When does retrieval with feedback improve recall and what limits pressure claims?',sourceIds:[a.id,b.id],profileId:profile.profileId,...overrides}));
 const embedding=Array.from({length:768},(_,i)=>i===0?1:0),embeddingIdentity={embedding,model:'fixture-embedding',provider:'fixture',runtime:'test',spaceKey:'space-one'};
 await createEmbeddingRepository(pool).upsert({targetType:'chunk',targetId:passages[0]!.id,chunkId:passages[0]!.id,provider:'fixture',model:'fixture-embedding',runtime:'test',strategy:'native-v2:space-one',contentHash:passages[0]!.contentHash,embedding});
 assert.equal((await retrieval.vector([a.id],embeddingIdentity)).length,1);assert.equal((await retrieval.vector([a.id],{...embeddingIdentity,spaceKey:'different'})).length,0);assert.equal((await retrieval.vector([a.id],{...embeddingIdentity,provider:'other'})).length,0);assert.equal((await retrieval.vector([b.id],embeddingIdentity)).length,0);
 const beforeCounts=(await pool.query('select (select count(*) from wiki_pages)::int pages,(select count(*) from source_relations)::int relations,(select count(*) from source_matching_decisions)::int decisions')).rows[0];
 const answer=await ask({mode:'hybrid'});assert.equal(answer.evidence.length,2);assert.equal(answer.coverage.vector,'unavailable');assert.ok(!lastPrompt.includes(secret.title));assert.deepEqual((await pool.query('select (select count(*) from wiki_pages)::int pages,(select count(*) from source_relations)::int relations,(select count(*) from source_matching_decisions)::int decisions')).rows[0],beforeCounts);
 assert.ok((await wiki.search({text:'Catalog',sourceIds:[],includeDescendants:false,pageId:null,kind:'source',reviewedOnly:false,currentOnly:true,limit:10,offset:0})).items.some(i=>i.id===catalog.id));
 assert.ok((await retrieval.candidates([a.id,b.id],'recall feedback',false)).some(c=>c.text>0));await assert.rejects(ask({question:'zxqvwmnblstr',relationContext:false}),/noEvidence/);
 const pageAnswer=await ask({pageId:oldPage});assert.ok(pageAnswer.contexts.some(c=>c.kind==='wiki_section'&&c.pageId===oldPage&&c.revisionId===oldRevision));const generatedContext=pageAnswer.contexts.find(c=>c.id===generatedSection)!,humanContext=pageAnswer.contexts.find(c=>c.id===humanSection)!;
 const beforePageEdit=await wiki.get(oldPage);await wiki.save({id:oldPage,expectedRevisionId:beforePageEdit!.revisionId,content:{...WikiPageContentSchema.strip().parse(beforePageEdit),sections:beforePageEdit!.sections.map((section:any)=>section.id===humanSection?{...section,markdown:'A revised human interpretation.'}:section)},evidenceChunkIds:[]});await contexts.validate(generatedContext.dependencies);await assert.rejects(contexts.validate(humanContext.dependencies),/evidence/);
 const saveCalls=calls;const pair=await Promise.all([service.save(answer.id),service.save(answer.id)]);assert.equal(calls,saveCalls);assert.equal(pair[0].checkpoint.reportedInputTokens,200);assert.equal(pair[0].checkpoint.reportedOutputTokens,60);assert.equal(pair[0].checkpoint.usageCounts.input,1);assert.equal(pair[0].checkpoint.usageCounts.output,1);assert.equal(pair[0].checkpoint.usageCounts.cost,0);assert.equal(pair[0].checkpoint.usageIncomplete,true);assert.ok(pair[0].proposal?.tool==='proposePageChange'&&pair[0].proposal.sections.some(s=>s.markdown.includes(answer.answer.gaps[0]!)));assert.equal(pair[0].id,pair[1].id);assert.equal((await jobs.findById(pair[0].jobId!))!.status,'succeeded');assert.equal((await pool.query('select count(*)::int n from organization_steps where run_id=$1',[pair[0].id])).rows[0].n,1);const callCount=calls;
 await organization.command({command:'cancel',id:pair[0].id});await organization.command({command:'retry',id:pair[0].id});await organization.execute((await jobs.findById(pair[0].jobId!))!,new AbortController().signal);assert.equal(calls,callCount);assert.equal((await organization.get(pair[0].id))!.status,'awaiting_review');await organization.apply(pair[0].id,true);await organization.apply(pair[0].id,true);assert.equal((await wiki.history(pair[0].snapshot.targetId)).length,1);
 const note=await createAtomicNoteRepository(pool).upsertGenerated({sourceItemId:a.id,evidenceChunkId:passages[0]!.id,title:'Corrective feedback',bodyMarkdown:'Feedback corrects retrieval errors.',ideaStatement:'Feedback conditions retrieval benefits.',generationProvider:'synthetic',generationModel:'fixture',generationRuntime:'test',generationPromptVersion:'fixture',generationKey:'m3-note',evidenceLinks:[]});
 await createSourceSummaryRepository(pool).create({sourceItemId:a.id,summary:'Conditional retrieval',provider:'synthetic',model:'fixture',runtime:'test',promptVersion:'summary-v3',inputHash:'fixture',outputHash:'fixture',metadata:{concepts:[{idea:'Retrieval benefits depend on feedback.',evidenceChunkIds:[passages[0]!.id]},{idea:'Excluded secret influence',evidenceChunkIds:[passages[2]!.id]}]}});
 const scopedContexts=await contexts.contexts([a.id,b.id],passages.slice(0,2).map(c=>c.id),false);assert.ok(scopedContexts.some(c=>c.id===note.id));assert.ok(!JSON.stringify(scopedContexts).includes('Excluded secret influence'));assert.ok(!(await contexts.contexts([a.id], [passages[0]!.id],true)).some(c=>c.id===note.id));
 const noteAnswer=await ask(),noteSave=await service.save(noteAnswer.id);await organization.apply(noteSave.id,true);const consumedPage=await wiki.get(noteSave.snapshot.targetId);assert.ok(consumedPage);const untouchedId=await wiki.save({expectedRevisionId:null,content:WikiPageContentSchema.parse({title:'Unrelated direct page',kind:'topic',sections:[{id:randomUUID(),title:'Independent',markdown:'Direct source',evidenceIds:[passages[1]!.id]}]}),evidenceChunkIds:[passages[1]!.id]});
 await pool.query("update atomic_notes set status='rejected',updated_at=now() where id=$1",[note.id]);assert.ok((await wiki.get(consumedPage!.id))!.impacts.some(i=>i.kind==='atomic_note'));assert.equal((await wiki.get(untouchedId))!.impacts.length,0);assert.ok(!(await contexts.contexts([a.id,b.id],passages.slice(0,2).map(c=>c.id),false)).some(c=>c.id===note.id));
 await pool.query("update atomic_notes set status='pending_review' where id=$1",[note.id]);const pending=await ask();await pool.query('insert into atomic_note_source_links(atomic_note_id,source_item_id,chunk_id) values($1,$2,$3)',[note.id,secret.id,passages[2]!.id]);await assert.rejects(service.save(pending.id),/evidence/);await pool.query('delete from atomic_note_source_links where atomic_note_id=$1',[note.id]);
 hook=async()=>{hook=null;await pool!.query('insert into atomic_note_source_links(atomic_note_id,source_item_id,chunk_id) values($1,$2,$3)',[note.id,secret.id,passages[2]!.id]);};const beforeQueued=calls;await assert.rejects(ask(),/evidence/);assert.equal(calls,beforeQueued,'FIFO-admission revalidation rejects changed scope before provider exposure');await pool.query('delete from atomic_note_source_links where atomic_note_id=$1',[note.id]);
 async function verifyNoteManifestLock(operation:'insert'|'delete'){
  let linkId:string|null=null;
  if(operation==='delete')linkId=(await pool!.query('insert into atomic_note_source_links(atomic_note_id,source_item_id,chunk_id) values($1,$2,$3) returning id',[note.id,a.id,passages[0]!.id])).rows[0].id;
  const noteContext=(await contexts.contexts([a.id,b.id],passages.slice(0,2).map(c=>c.id),false)).find(c=>c.id===note.id)!;
  const sectionId=randomUUID(),pageId=await wiki.save({expectedRevisionId:null,content:WikiPageContentSchema.parse({title:'Manifest lock '+operation,kind:'topic',sections:[{id:sectionId,title:'Note interpretation',markdown:'Feedback remains conditional.',evidenceIds:[passages[0]!.id]}]}),evidenceChunkIds:[passages[0]!.id]}),page=await wiki.get(pageId);
  const applying=await pool!.connect(),changing=await pool!.connect();
  try{
   await applying.query('begin');await validateWikiDependencies(applying,noteContext.dependencies,true);const pid=(await changing.query('select pg_backend_pid() as pid')).rows[0].pid;
   let settled=false;const mutation=(operation==='insert'?changing.query('insert into atomic_note_source_links(atomic_note_id,source_item_id,chunk_id) values($1,$2,$3)',[note.id,secret.id,passages[2]!.id]):changing.query('delete from atomic_note_source_links where id=$1',[linkId])).then(()=>{settled=true;});
   let waiting=false;for(let attempt=0;attempt<100&&!waiting;attempt++){waiting=(await pool!.query('select wait_event_type from pg_stat_activity where pid=$1',[pid])).rows[0]?.wait_event_type==='Lock';if(!waiting)await new Promise(resolve=>setTimeout(resolve,10));}
   assert.ok(waiting&&!settled,'Concurrent note-link '+operation+' waits for the apply validation lock');
   for(const dependency of noteContext.dependencies)await addWikiDependency(applying,page!.revisionId,sectionId,dependency,noteContext);
   await applying.query('commit');await mutation;assert.ok((await contexts.impacts(pageId)).some(i=>i.kind==='atomic_note'&&i.inputId===note.id),'The serialized link mutation invalidates the newly committed exact consumer');
  }finally{await applying.query('rollback');applying.release();changing.release();}
  await pool!.query('delete from atomic_note_source_links where atomic_note_id=$1',[note.id]);
 }
 await verifyNoteManifestLock('insert');await verifyNoteManifestLock('delete');
 const impactBefore=(await contexts.impacts(untouchedId)).length;await pool.query("update source_items set metadata=metadata||'{\"processingProgress\":0.5}'::jsonb,updated_at=now() where id=$1",[b.id]);assert.equal((await contexts.impacts(untouchedId)).length,impactBefore);
 const occurrence=(await repo.relations([a.id,b.id]))[0]!;await pool.query('insert into source_relation_evidence(relation_id,evidence_key,origin,source_chunk_id,target_chunk_id,snapshot) select relation_id,$2,origin,source_chunk_id,target_chunk_id,snapshot from source_relation_evidence where id=$1',[occurrence.evidenceId,randomUUID()]);await pool.query("update source_relation_evidence set snapshot=jsonb_set(snapshot,'{sourceHash}','\"stale\"'::jsonb) where id=$1",[rel.evidenceId]);assert.equal((await repo.relations([a.id,b.id])).length,1);const exactImpacts=await contexts.impacts(oldPage);assert.ok(exactImpacts.some(i=>i.kind==='relation_evidence'&&i.inputId===rel.evidenceId));assert.ok(!exactImpacts.some(i=>i.sectionId===humanSection));assert.ok(exactImpacts.every(i=>i.sectionId===generatedSection));
 const revised=await wiki.get(untouchedId);await pool.query("update documents set metadata=metadata||jsonb_build_object('supersededByDocumentId',$2::text) where id=$1",[passages[1]!.documentId,randomUUID()]);assert.ok((await wiki.get(untouchedId))!.impacts.length>0);await wiki.save({id:untouchedId,expectedRevisionId:revised!.revisionId,content:{...WikiPageContentSchema.strip().parse(revised),title:'Edited historical page'},evidenceChunkIds:[]});assert.ok((await wiki.get(untouchedId))!.impacts.length>0);await pool.query("update documents set metadata=metadata-'supersededByDocumentId' where id=$1",[passages[1]!.documentId]);
 const plan=resolveProcessingPlan({preset:'custom',requestedStages:['organizeKnowledge','sourceMatching'],organization:{title:'Batch retrieval topic',profileId:profile.profileId,privacy:'offline_only',domainId:null},scope:'source_only',targetSourceItemIds:[a.id,b.id],forceRegeneration:false,previousArtifactPolicy:'reuse_valid'});
 const batch=await createHierarchicalIngestionRepository(pool).createBatch({trigger:'test',requestedPlan:plan,effectivePlan:plan,reingestionPolicy:'reuse_valid',targetSourceItemIds:[a.id,b.id]});
 const r1=await runs.create({sourceItemId:a.id,batchId:batch.id,effectiveStages:plan.effectiveStages,requestedStages:plan.requestedStages,status:'succeeded'}),r2=await runs.create({sourceItemId:b.id,batchId:batch.id,effectiveStages:['chunking','knowledgeGraph','organizeKnowledge'],status:'succeeded'});
 for(const stage of ['chunking','summarization','embedding'])await runs.completeStage(r1.id,stage,{});await runs.waitForBatchStage(r1.id,'sourceMatching');await runs.completeStage(r2.id,'chunking',{});await runs.completeStage(r2.id,'knowledgeGraph',{});
 await reconcileOrganizationParticipation(pool,organization);assert.equal(await repo.participationRun(batch.id),null,'Ended parents do not release waiting matching checkpoint');
 await runs.completeStage(r1.id,'sourceMatching',{});const stageJob=await jobs.create({type:'knowledge-graph-generation',payload:{ingestionRunId:r2.id}});await reconcileOrganizationParticipation(pool,organization);assert.equal(await repo.participationRun(batch.id),null,'Active stage job blocks snapshot');await jobs.update(stageJob.id,{status:'failed'});await runs.failStage(r2.id,'knowledgeGraph','synthetic failure',false);
 await reconcileOrganizationParticipation(pool,organization);const enrolled=await repo.participationRun(batch.id);assert.ok(enrolled);assert.ok(enrolled.snapshot.participation.omissions.some((o:any)=>o.stage==='knowledgeGraph'&&o.status==='failed'));await reconcileOrganizationParticipation(pool,organization);assert.equal((await repo.participationRun(batch.id))!.id,enrolled.id);
 await repo.cancelBatch(batch.id);assert.equal((await repo.get(enrolled.id))!.status,'canceled');await assert.rejects(organization.apply(enrolled.id,true));assert.equal((await runs.findById(r1.id))!.stagesCheckpoint.sourceMatching?.status,'completed');
 await assert.rejects(repo.topicTarget(oldContent.title,[secret.id]),/topicScope/);
 await pool.query('create database m3_empty');const url=new URL(connection.connectionString);url.pathname='/m3_empty';empty=createPgPool({connectionString:url.toString(),max:2});assert.equal((await runMigrations(empty,migrations,{seedFolder})).seed.applied,true);assert.equal((await empty.query('select count(*)::int n from drizzle.__drizzle_migrations')).rows[0].n,journal.entries.length);assert.equal((await empty.query("select count(*)::int n from pg_trigger where tgname like 'wiki_%_impact' and not tgisinternal")).rows[0].n,12);
 console.log('M3 real PostgreSQL verified: populated M2 history upgrade and exact-section backfill, empty baseline/history/index/types/triggers, scoped lexical retrieval and no-model catalog, optional note/concept provenance, read-only cited answers, shared FIFO admission revalidation, concurrent atomic save + audit links + cancel/retry without inference, protected apply receipts, exact note/occurrence/source impacts with surviving contributions, historical edits, operational no-op updates, terminal matching/stage barriers, partial batch admission, cancellation and scope-safe topic reuse. Model outputs are deterministic fixtures, not real model validation.');
}finally{if(empty)await closePgPool(empty);if(pool)await closePgPool(pool);await manager.stop();await rm(dir,{recursive:true,force:true});}
