import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {mkdtemp,mkdir,readFile,copyFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {MaintenanceService} from '../apps/desktop/src/main/services/maintenance-service.js';
import {MaintenancePolicySchema,MaintenanceRunSchema,MaintenanceScheduleSchema,WikiPageContentSchema,type OrganizationProfile,type MaintenancePolicy} from '@app/domain';
import {createPgPool,closePgPool,PostgresSidecarManager,resolvePostgresSidecarPaths,runMigrations,createSourceItemRepository,createDocumentRepository,createChunkRepository,createWikiRepository,createMaintenanceRepository,createAiConfigRepository,createJobRepository,type PgPool} from '../packages/db/src/index.js';
const root=resolve(import.meta.dirname,'..'),dir=await mkdtemp(join(tmpdir(),'memora-maintenance-')),migrations=join(root,'packages/db/drizzle'),seedFolder=join(root,'packages/db/seed'),paths=resolvePostgresSidecarPaths({cwd:root,env:process.env});
const manager=new PostgresSidecarManager({binDir:paths.binDir,dataDir:join(dir,'data'),database:'maintenance_test',user:'maintenance_test',password:randomUUID(),startupTimeoutMs:30000,shutdownTimeoutMs:10000});
let pool:PgPool|undefined,empty:PgPool|undefined;
try{
 const connection=await manager.start();pool=createPgPool({connectionString:connection.connectionString,max:6});const journal=JSON.parse(await readFile(join(migrations,'meta/_journal.json'),'utf8')),old=join(dir,'old'),prior=journal.entries.filter((e:{idx:number})=>e.idx<26);await mkdir(join(old,'meta'),{recursive:true});await writeFile(join(old,'meta/_journal.json'),JSON.stringify({...journal,entries:prior}));for(const e of prior)await copyFile(join(migrations,`${e.tag}.sql`),join(old,`${e.tag}.sql`));await runMigrations(pool,old);
 const sources=createSourceItemRepository(pool),source=await sources.create({type:'AcademicPaper',title:'Maintenance original evidence'}),catalog=await sources.create({type:'Book',title:'Catalog outlier'}),wiki=createWikiRepository(pool);const doc=await createDocumentRepository(pool).create({sourceItemId:source.id,title:source.title,canonicalMarkdown:'Retrieval practice improves learning with corrective feedback.',contentHash:'fixture'}),chunk=randomUUID(),span=randomUUID();await createChunkRepository(pool).replaceDocumentChunks(doc.id,source.id,[{id:chunk,sourceSpanId:span,span:{id:span,startOffset:0,endOffset:60},chunkIndex:0,content:'Retrieval practice improves learning with corrective feedback.',contentHash:'fixture'}]);
 const human=await wiki.save({expectedRevisionId:null,content:WikiPageContentSchema.parse({title:'Human page',kind:'topic',sections:[{id:randomUUID(),title:'Manual',markdown:'Original interpretation',evidenceIds:[chunk]}]}),evidenceChunkIds:[chunk]});
 const interim=join(dir,'intermediate');await mkdir(join(interim,'meta'),{recursive:true});const intermediateEntries=journal.entries.filter((e:{idx:number})=>e.idx<=26);await writeFile(join(interim,'meta/_journal.json'),JSON.stringify({...journal,entries:intermediateEntries}));for(const e of intermediateEntries)await copyFile(join(migrations,e.tag+'.sql'),join(interim,e.tag+'.sql'));await runMigrations(pool,interim);
 const migratedSchedule=randomUUID(),migratedPolicy=MaintenancePolicySchema.parse({name:'Previously persisted disabled routine',cadence:{timezone:'UTC'},scope:{sourceIds:[catalog.id]},categories:['navigation']});await pool.query('insert into maintenance_schedules(id,policy,next_at) values($1,$2,now())',[migratedSchedule,migratedPolicy]);assert.equal((await pool.query("select count(*)::int n from information_schema.columns where table_name='maintenance_schedules' and column_name='last_error'")).rows[0].n,0);
 await runMigrations(pool,migrations,{seedFolder});assert.equal((await pool.query('select last_error,policy from maintenance_schedules where id=$1',[migratedSchedule])).rows[0].last_error,null);assert.equal((await pool.query('select count(*)::int n from source_items')).rows[0].n,2);assert.ok(await wiki.get(human));assert.equal((await pool.query("select count(*)::int n from information_schema.tables where table_schema='public' and table_name like 'maintenance_%'")).rows[0].n,7);assert.equal((await pool.query("select count(*)::int n from drizzle.__drizzle_migrations")).rows[0].n,28);
 const repo=createMaintenanceRepository(pool),jobs=createJobRepository(pool);
 async function draft(title:string,kind='topic',parentId:string|null=null,cited=true,markdown='Retrieval practice supports learning with feedback.'){const id=randomUUID(),revision=randomUUID(),evidence=randomUUID(),content=WikiPageContentSchema.parse({title,kind,parentId,sections:cited?[{id:randomUUID(),title:'Synthetic fixture',markdown,provenance:'generated',protected:false,evidenceReview:'needs_review',evidenceIds:[evidence]}]:[]});await pool!.query('insert into wiki_pages(id,title,kind,parent_id) values($1,$2,$3,$4)',[id,title,kind,parentId]);await pool!.query("insert into wiki_page_revisions(id,page_id,number,origin,content,content_hash) values($1,$2,1,'organization',$3,$4)",[revision,id,content,createHash('sha256').update(JSON.stringify(content)).digest('hex')]);await pool!.query('update wiki_pages set current_revision_id=$2 where id=$1',[id,revision]);if(cited)await pool!.query('insert into wiki_evidence(id,page_id,source_item_id,document_id,chunk_id,snapshot) values($1,$2,$3,$4,$5,$6)',[evidence,id,source.id,doc.id,chunk,{contentHash:'fixture',excerpt:'Retrieval practice improves learning with corrective feedback.',sourceTitle:source.title,documentCreatedAt:new Date().toISOString(),locator:null}]);return id;}
 const collection=await wiki.save({expectedRevisionId:null,content:WikiPageContentSchema.parse({title:'Learning and memory',kind:'collection'}),evidenceChunkIds:[]}),topic=await draft('Retrieval practice'),unrelated=await draft('Unrelated topic sharing the original');
 const profile:OrganizationProfile={profileId:randomUUID(),providerConfigId:null,localModelId:randomUUID(),provider:'fixture',modelId:'deterministic-maintenance',runtime:'test',revision:'1',privacy:'offline_only',parameters:{},identityHash:'fixture',contextWindow:64000};let calls=0,mode:'move'|'none'|'invalid'='move',hook:(()=>Promise<void>)|null=null,lastPrompt='';
 const ai={pinOrganizationProfile:async()=>profile,runOrganizationTask:async(_p:OrganizationProfile,prompt:string,context:any,signal:AbortSignal,_max:number,before?:()=>Promise<void>)=>{if(hook)await hook();await before?.();signal.throwIfAborted();calls++;lastPrompt=prompt;const candidates=JSON.parse(prompt.split('CANDIDATES: ')[1]!),page=candidates.find((c:any)=>c.eligibleMove&&c.content.kind==='topic'),parent=candidates.find((c:any)=>c.content.kind==='collection');const output=mode==='invalid'?{tool:'deleteEverything'}:{operations:mode==='move'&&page&&parent?[{type:'reparent',pageId:page.id,expectedRevisionId:page.revisionId,parentId:parent.id,parentRevisionId:parent.revisionId,reason:'Place retrieval practice under its learning collection for discoverability.',benefit:.9}]:[],explanation:'Deterministic fixture proposal; no model quality claim.'};const audit=await createAiConfigRepository(pool!).recordTaskRun({taskType:'structured-output',provider:'fixture',modelId:profile.modelId,runtime:'test',status:'succeeded',durationMs:1,inputTokens:500,outputTokens:100,maintenanceRunId:context.maintenanceRunId,maintenanceStep:context.maintenanceStep});return {output,taskType:'structured-output' as const,providerId:'fixture',modelId:profile.modelId,runtime:'test',durationMs:1,inputTokens:500,outputTokens:100,aiTaskRunId:audit,profileId:profile.profileId,outputLanguage:'en'};}};
 let now=Date.now(),idle=0;const service=new MaintenanceService({getPool:()=>pool!,ai,contentLanguage:async()=> 'en',wake:()=>{},cancelJob:async id=>jobs.requestCancel(id),now:()=>now,idleSeconds:()=>idle});
 const policy=(overrides:Partial<MaintenancePolicy>={})=>MaintenancePolicySchema.parse({name:'Synthetic scoped maintenance',enabled:false,cadence:{timezone:'UTC'},scope:{pageIds:[collection,topic],includePageDescendants:false},categories:['navigation','knowledge','evidence'],profileId:profile.profileId,modelEnabled:true,...overrides});
 async function schedule(p=policy()){return MaintenanceScheduleSchema.parse(await service.command({command:'save',policy:p}));}
 async function run(id:string){now=Math.max(now,Date.now()+10);return MaintenanceRunSchema.parse(await service.command({command:'run',id,requestId:randomUUID()}));}
 async function execute(id:string){const r=await service.get(id),job=(await jobs.findById(r!.jobId))!;try{await jobs.update(job.id,{status:'running'});await service.execute(job,new AbortController().signal);await jobs.update(job.id,{status:'succeeded'});}catch(e){await jobs.update(job.id,{status:'failed'});throw e;}return (await service.get(id))!;}
 const inspected=await repo.inspect(await repo.scope(policy().scope),'page',null,new Date(now+1000).toISOString(),50);assert.deepEqual(new Set(inspected.rows.map(r=>r.id)),new Set([collection,topic]));assert.ok(!inspected.rows.some(r=>r.id===unrelated));assert.deepEqual((await repo.scope(policy().scope)).sourceIds,[]);
 const s=await schedule(),requestId=randomUUID(),dupe=await Promise.all([service.command({command:'run',id:s.id,requestId}),service.command({command:'run',id:s.id,requestId})]);assert.equal((dupe[0] as any).id,(dupe[1] as any).id);assert.equal(await service.ready((await jobs.findById((dupe[0] as any).jobId))!),true,'Run now bypasses idle preference');let result=await execute((dupe[0] as any).id);assert.equal(result.status,'awaiting_review');assert.equal(calls,1);assert.ok(!lastPrompt.includes('Unrelated topic'));assert.equal(result.checkpoint.cost,null);assert.equal((await pool.query('select count(*)::int n from maintenance_steps where run_id=$1',[result.id])).rows[0].n,1);
 const before=await wiki.get(topic);await service.command({command:'review',id:result.id,decision:'accept'});await service.command({command:'review',id:result.id,decision:'accept'});const after=await wiki.get(topic);assert.equal(after!.parentId,collection);assert.deepEqual(after!.sections,before!.sections);assert.deepEqual(after!.evidence,before!.evidence);assert.equal((await wiki.history(topic)).length,2);await repo.modelStarted(result.id);await repo.checkpoint(result.id,'analyzing',result.checkpoint);assert.equal((await service.get(result.id))!.status,'applied');
 result=await execute((await run(s.id)).id);assert.equal(result.status,'no_change');assert.equal(calls,1);const reservation=(await pool.query('select reservation from maintenance_runs where id=$1',[result.id])).rows[0].reservation;assert.equal(reservation.calls,0);assert.equal(reservation.tokens,0);assert.equal(reservation.spend,0);
 const noModel=await schedule(policy({profileId:null,modelEnabled:false,scope:{wholeLibrary:false,pageIds:[],sourceIds:[catalog.id],excludedPageIds:[],includePageDescendants:false}}));result=await execute((await run(noModel.id)).id);assert.equal(result.checkpoint.signals.unplaced_source,1);assert.equal(calls,1);assert.equal(result.checkpoint.candidates.length,0);
 const queued=await run(s.id);await service.command({command:'pause',id:s.id,expectedRevision:s.revision});assert.equal((await service.get(queued.id))!.status,'canceled');await assert.rejects(service.command({command:'review',id:queued.id,decision:'accept'}),/revoked/);
 const child=await draft('Child candidate','topic',collection),tree=await repo.scope(policy({scope:{wholeLibrary:false,pageIds:[collection],sourceIds:[],excludedPageIds:[topic],includePageDescendants:true}}).scope);assert.ok(tree.pageIds.includes(child));assert.ok(!tree.pageIds.includes(topic));assert.ok(!tree.pageIds.includes(unrelated));
 const archive=await draft('Disposable empty generated fixture','topic',null,false),archiveSchedule=await schedule(policy({scope:{wholeLibrary:false,pageIds:[archive],sourceIds:[],excludedPageIds:[],includePageDescendants:false}}));const archiveRun=await run(archiveSchedule.id);await execute(archiveRun.id);const ar=(await service.get(archiveRun.id))!,candidate=ar.checkpoint.candidates.find(c=>c.id===archive)!;assert.ok(candidate.eligibleArchive);await pool.query("update maintenance_runs set status='awaiting_review',proposal=$2 where id=$1",[ar.id,{operations:[{type:'archive',pageId:archive,expectedRevisionId:candidate.revisionId,reason:'An explicitly empty disposable generated fixture can be archived.',benefit:.9}],explanation:'Fixture'}]);await draft('New child after proposal','topic',archive,false);await assert.rejects(service.command({command:'review',id:ar.id,decision:'accept'}),/protected/);assert.equal((await wiki.get(archive))!.archived,false);await service.command({command:'cancel',id:ar.id});
 const overlapPolicy=policy({enabled:true,modelEnabled:false,profileId:null,scope:{wholeLibrary:false,pageIds:[human],sourceIds:[],excludedPageIds:[],includePageDescendants:false}}),weekly=await schedule(overlapPolicy),monthly=await schedule({...overlapPolicy,name:'Monthly fixture',routine:'monthly',cadence:{...overlapPolicy.cadence,kind:'monthly'}});await pool.query("update maintenance_schedules set next_at=now()-interval '100 days' where id=any($1::uuid[])",[[weekly.id,monthly.id]]);await service.tick();assert.equal((await repo.schedules()).find(x=>x.id===weekly.id)!.lastError,'maintenance.errors.idle');idle=120;await service.tick();const ws=(await repo.schedules()).find(x=>x.id===weekly.id)!,ms=(await repo.schedules()).find(x=>x.id===monthly.id)!;assert.ok(ws.lastRunId);assert.equal(ws.lastRunId,ms.lastRunId);assert.equal((await service.get(ws.lastRunId))!.snapshot.policy.routine,'monthly');assert.equal((await service.get(ws.lastRunId))!.scheduleIds.length,2);await service.tick();assert.equal((await pool.query('select count(*)::int n from maintenance_occurrences where run_id=$1',[ws.lastRunId])).rows[0].n,2);idle=0;assert.equal(await service.ready((await jobs.findById((await service.get(ws.lastRunId))!.jobId))!),false,'Queued scheduled work rechecks idle after restart');idle=120;await execute(ws.lastRunId);
 const staleTopic=await draft('Concurrent edit target'),staleSchedule=await schedule(policy({scope:{wholeLibrary:false,pageIds:[collection,staleTopic],sourceIds:[],excludedPageIds:[],includePageDescendants:false}})),staleRun=await run(staleSchedule.id);hook=async()=>{hook=null;const p=await wiki.get(staleTopic);await wiki.save({id:staleTopic,expectedRevisionId:p!.revisionId,content:{...WikiPageContentSchema.strip().parse(p),title:'Changed before FIFO'},evidenceChunkIds:[]});};const beforeCalls=calls;await assert.rejects(execute(staleRun.id),/conflict/);assert.equal(calls,beforeCalls);
 const budgetPage=await draft('Independent budget fixture','collection',null,false);const budget=await schedule(policy({modelEnabled:false,profileId:null,scope:{wholeLibrary:false,pageIds:[budgetPage],sourceIds:[],excludedPageIds:[],includePageDescendants:false},budget:{calls:0,tokens:2048,spend:null,inspected:1,changes:0},periodBudget:{calls:0,tokens:2048,spend:null,inspected:1,changes:0}}));now=Date.UTC(2026,8,30,23,59);const monthRun=await run(budget.id);now=Date.UTC(2026,9,1,0,1);const nextMonthRun=await run(budget.id);assert.equal(monthRun.id,nextMonthRun.id,'compatible pending manual runs share work');await repo.reservePeriod(monthRun.id,'2026-10');assert.equal((await pool.query('select count(*)::int n from maintenance_budget_reservations where run_id=$1',[monthRun.id])).rows[0].n,2);
 const capPage=await draft('Strict cap fixture'),capSchedule=await schedule(policy({scope:{wholeLibrary:false,pageIds:[capPage,collection],sourceIds:[],excludedPageIds:[],includePageDescendants:false},budget:{...policy().budget,spend:1},periodBudget:{...policy().periodBudget,spend:3}}));const costCalls=calls,capped=await execute((await run(capSchedule.id)).id);assert.equal(capped.checkpoint.error,'maintenance.errors.costUnknown');assert.equal(calls,costCalls);assert.equal((await pool.query('select reservation from maintenance_runs where id=$1',[capped.id])).rows[0].reservation.calls,0);
 const conflicting=await run(capSchedule.id),otherProfile=await schedule(policy({profileId:randomUUID(),scope:capSchedule.policy.scope,budget:capSchedule.policy.budget,periodBudget:capSchedule.policy.periodBudget}));await assert.rejects(run(otherProfile.id),/wait/);await service.command({command:'cancel',id:conflicting.id});assert.equal((await pool.query('select reservation from maintenance_runs where id=$1',[conflicting.id])).rows[0].reservation.calls,0);
 const cursorPages=await Promise.all([draft('Cursor one','collection',null,false),draft('Cursor two','collection',null,false),draft('Cursor three','collection',null,false)]),cursorSchedule=await schedule(policy({modelEnabled:false,profileId:null,scope:{wholeLibrary:false,pageIds:cursorPages,sourceIds:[],excludedPageIds:[],includePageDescendants:false},budget:{...policy().budget,inspected:2}}));const cursorFirst=await execute((await run(cursorSchedule.id)).id);assert.equal(cursorFirst.checkpoint.inspected,2);assert.equal(cursorFirst.checkpoint.total,3);assert.equal(cursorFirst.checkpoint.cursor.kind,'page');const cursorSecond=await execute((await run(cursorSchedule.id)).id);assert.equal(cursorSecond.checkpoint.inspected,1);assert.equal(cursorSecond.checkpoint.total,1);assert.equal(cursorSecond.checkpoint.cursor.kind,'done');
 const rejectPage=await draft('Reject and cooldown fixture'),rejectSchedule=await schedule(policy({scope:{wholeLibrary:false,pageIds:[rejectPage,collection],sourceIds:[],excludedPageIds:[],includePageDescendants:false}})),rejected=await execute((await run(rejectSchedule.id)).id);assert.equal(rejected.status,'awaiting_review');await service.command({command:'review',id:rejected.id,decision:'reject'});const rejectionCalls=calls;await execute((await run(rejectSchedule.id)).id);assert.equal(calls,rejectionCalls);
 const uncertainPage=await draft('Interrupted fixture'),uncertainSchedule=await schedule(policy({scope:{wholeLibrary:false,pageIds:[uncertainPage,collection],sourceIds:[],excludedPageIds:[],includePageDescendants:false}})),uncertain=await run(uncertainSchedule.id);await repo.checkpoint(uncertain.id,'analyzing',{...uncertain.checkpoint,calls:1,callPending:true});await assert.rejects(execute(uncertain.id),/uncertain/);assert.equal(calls,rejectionCalls);assert.equal((await pool.query('select reservation from maintenance_runs where id=$1',[uncertain.id])).rows[0].reservation.calls,1);await assert.rejects(service.command({command:'retry',id:uncertain.id}),/retry/);
 const mixed=await draft('Mixed scope must remain private'),mixedPage=await wiki.get(mixed),foreignEvidence=randomUUID();await pool.query('insert into wiki_evidence(id,page_id,source_item_id,document_id,chunk_id,snapshot) values($1,$2,$3,$4,$5,$6)',[foreignEvidence,mixed,catalog.id,randomUUID(),randomUUID(),{contentHash:'foreign',excerpt:'Do not expose mixed private prose.',sourceTitle:catalog.title,documentCreatedAt:new Date().toISOString(),locator:null}]);await wiki.save({id:mixed,expectedRevisionId:mixedPage!.revisionId,content:{...WikiPageContentSchema.strip().parse(mixedPage),sections:mixedPage!.sections.map((s:any)=>({...s,evidenceIds:[...s.evidenceIds,foreignEvidence]}))},evidenceChunkIds:[]});const sourceScope=await repo.scope(policy({scope:{wholeLibrary:false,pageIds:[],sourceIds:[source.id],excludedPageIds:[],includePageDescendants:false}}).scope);assert.ok(!(await repo.inspect(sourceScope,'page',null,new Date(now).toISOString(),100)).rows.some(r=>r.id===mixed));
 const saturated=await schedule(policy({modelEnabled:false,profileId:null,scope:{wholeLibrary:false,pageIds:[budgetPage],sourceIds:[],excludedPageIds:[],includePageDescendants:false},budget:{calls:0,tokens:2048,spend:null,inspected:1,changes:0},periodBudget:{calls:0,tokens:2048,spend:null,inspected:1,changes:0}}));await service.command({command:'cancel',id:monthRun.id});const consumed=await execute((await run(saturated.id)).id);assert.equal(consumed.checkpoint.inspected,1);await assert.rejects(run(saturated.id),/period/);
 const recoverable=await draft('Recoverable archive fixture','topic',null,false),recoverSchedule=await schedule(policy({scope:{wholeLibrary:false,pageIds:[recoverable],sourceIds:[],excludedPageIds:[],includePageDescendants:false}})),recoverRun=await execute((await run(recoverSchedule.id)).id),recoverCandidate=recoverRun.checkpoint.candidates.find(c=>c.id===recoverable)!;await pool.query("update maintenance_runs set status='awaiting_review',proposal=$2 where id=$1",[recoverRun.id,{operations:[{type:'archive',pageId:recoverable,expectedRevisionId:recoverCandidate.revisionId,reason:'This is an explicitly empty generated fixture with no dependent navigation.',benefit:.9}],explanation:'Recoverability fixture'}]);await service.command({command:'review',id:recoverRun.id,decision:'accept'});const archivedPage=await wiki.get(recoverable);assert.equal(archivedPage!.archived,true);await wiki.save({id:recoverable,expectedRevisionId:archivedPage!.revisionId,content:{...WikiPageContentSchema.strip().parse(archivedPage),archived:false},evidenceChunkIds:[]});assert.equal((await wiki.history(recoverable)).length,3);const restoredDiagnostic=(await repo.inspect(await repo.scope(recoverSchedule.policy.scope),'page',null,new Date(now).toISOString(),10)).rows[0];assert.equal(restoredDiagnostic.manual,true,'Deliberate restoration protects archive placement');
 const {OrganizationConfigurationSchema,defaultOrganizationConfiguration}=await import('@app/domain');const {createOrganizationRepository}=await import('../packages/db/src/index.js');const configurations=createOrganizationRepository(pool),custom=OrganizationConfigurationSchema.parse({...defaultOrganizationConfiguration,functionsVersion:3,weekly:{advanced:'Review {{title}} in {{language}} with a useful bounded structural proposal.'}}),configurationId=await configurations.saveDraft(custom);await assert.rejects(service.validateActivation(configurationId,custom,defaultOrganizationConfiguration,'en'),/sample/);const sampleId=await service.sample(configurationId,profile.profileId,'offline_only',null,'weekly');assert.equal((await execute(sampleId)).status,'sample_passed');await service.validateActivation(configurationId,custom,defaultOrganizationConfiguration,'en');assert.equal((await pool.query('select count(*)::int n from maintenance_receipts where run_id=$1',[sampleId])).rows[0].n,0);
 // Only supplied mutation candidates acquire decisions; later passes must reach the byte-deferred remainder.
 mode='none';const packingCollection=await wiki.save({expectedRevisionId:null,content:WikiPageContentSchema.parse({title:'Bounded learning collection',kind:'collection'}),evidenceChunkIds:[]});const packingPages=[] as string[];for(let i=0;i<7;i++)packingPages.push(await draft('Bounded topic '+i,'topic',null,true,'A detailed synthetic discussion of retrieval practice and corrective feedback. '.repeat(40)));
 const packingSchedule=await schedule(policy({scope:{wholeLibrary:false,pageIds:[packingCollection,...packingPages],sourceIds:[],excludedPageIds:[],includePageDescendants:false},budget:{...policy().budget,tokens:10000}})),firstPacked=await execute((await run(packingSchedule.id)).id),suppliedFirst=firstPacked.checkpoint.candidates.filter(c=>c.eligibleMove||c.eligibleArchive).map(c=>c.id),decidedFirst=(await pool.query('select page_id from maintenance_decisions where run_id=$1',[firstPacked.id])).rows.map(r=>r.page_id);
 assert.ok(suppliedFirst.length>0&&suppliedFirst.length<packingPages.length);assert.deepEqual(new Set(decidedFirst),new Set(suppliedFirst));assert.equal(firstPacked.checkpoint.analyzedKeys.length,suppliedFirst.length);
 const packedCalls=calls,secondPacked=await execute((await run(packingSchedule.id)).id),suppliedSecond=secondPacked.checkpoint.candidates.filter(c=>c.eligibleMove||c.eligibleArchive).map(c=>c.id);assert.equal(calls,packedCalls+1);assert.ok(suppliedSecond.length);assert.ok(suppliedSecond.every(id=>!suppliedFirst.includes(id)));assert.deepEqual(new Set((await pool.query('select page_id from maintenance_decisions where run_id=$1',[secondPacked.id])).rows.map(r=>r.page_id)),new Set(suppliedSecond));
 // An exact no-change result is quiet, but a changed destination is new useful context.
 const contextCollection=await wiki.save({expectedRevisionId:null,content:WikiPageContentSchema.parse({title:'General collection',kind:'collection',pinned:true,review:'reviewed'}),evidenceChunkIds:[]}),contextTopic=await draft('Context-sensitive retrieval topic'),contextSchedule=await schedule(policy({scope:{wholeLibrary:false,pageIds:[contextTopic,contextCollection],sourceIds:[],excludedPageIds:[],includePageDescendants:false}}));const contextualFirst=await execute((await run(contextSchedule.id)).id);assert.equal(contextualFirst.status,'no_change');const contextualCalls=calls;await execute((await run(contextSchedule.id)).id);assert.equal(calls,contextualCalls,'Exact unchanged context is quiet');
 const destinationBefore=await wiki.get(contextCollection);await wiki.save({id:contextCollection,expectedRevisionId:destinationBefore!.revisionId,content:{...WikiPageContentSchema.strip().parse(destinationBefore),title:'Learning and retrieval collection'},evidenceChunkIds:[]});mode='move';const reconsidered=await execute((await run(contextSchedule.id)).id);assert.equal(calls,contextualCalls+1);assert.equal(reconsidered.status,'awaiting_review');assert.equal(reconsidered.proposal!.operations[0]!.pageId,contextTopic);assert.ok(lastPrompt.includes('"canReceiveChildren":true'));assert.equal((await wiki.get(contextCollection))!.pinned,true);
 await service.command({command:'review',id:reconsidered.id,decision:'reject'});const rejectedCalls=calls,destinationAgain=await wiki.get(contextCollection);await wiki.save({id:contextCollection,expectedRevisionId:destinationAgain!.revisionId,content:{...WikiPageContentSchema.strip().parse(destinationAgain),title:'Learning and retrieval navigation'},evidenceChunkIds:[]});await execute((await run(contextSchedule.id)).id);assert.equal(calls,rejectedCalls,'Rejected structural decisions retain cooldown across context changes');assert.equal((await pool.query("select count(*)::int n from maintenance_decisions where run_id=$1 and outcome='rejected'",[reconsidered.id])).rows[0].n,1);
 await pool.query('create database maintenance_empty');const url=new URL(connection.connectionString);url.pathname='/maintenance_empty';empty=createPgPool({connectionString:url.toString(),max:2});assert.equal((await runMigrations(empty,migrations,{seedFolder})).seed.applied,true);assert.equal((await empty.query('select count(*)::int n from drizzle.__drizzle_migrations')).rows[0].n,journal.entries.length);assert.equal((await empty.query("select count(*)::int n from pg_indexes where tablename like 'maintenance_%'")).rows[0].n,14);
 console.log('M3b deterministic real PostgreSQL passed: populated M3 upgrade and empty baseline, 28 migrations, scope isolation/tree exclusions, no-model catalog inspection, idempotent manual admission, canonical AI audit links, reviewed structural preservation/receipts, no-repeat analysis and released unspent reservation, pause/cancel, archive child-race rejection, idle and missed weekly/monthly coalescing, pre-FIFO concurrent edit rejection, cross-month reservation. No real model was loaded.');
}finally{if(empty)await closePgPool(empty);if(pool)await closePgPool(pool);await manager.stop();await rm(dir,{recursive:true,force:true});}
