import { OrganizationService } from '../apps/desktop/src/main/services/organization-service.js';
import { reconcileOrganizationParticipation } from '../apps/desktop/src/main/services/organization-participation.js';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,mkdir,readFile,writeFile,copyFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createPgPool,closePgPool,PostgresSidecarManager,resolvePostgresSidecarPaths,runMigrations,createWikiRepository,createWikiCuratorRepository,createWikiCollectionRepository,createOrganizationRepository,createJobRepository,createAiConfigRepository,createHierarchicalIngestionRepository,createIngestionRunRepository,createSourceItemRepository,createDocumentRepository,createChunkRepository,type PgPool} from '../packages/db/src/index.js';
import {WikiAssessmentSchema,WikiPageContentSchema,AutomaticWikiPolicySchema,CuratorPreviewSchema,WikiBootstrapSchema,initialCuratorLimits,resolveProcessingPlan,type OrganizationProfile,type CuratorSnapshot} from '@app/domain';
import {WikiCurator,parseCuratorProposal} from '../apps/desktop/src/main/services/wiki-curator.js';
import {WikiCollection} from '../apps/desktop/src/main/services/wiki-collection.js';
import {promptAudit,capturePromptPin} from '../apps/desktop/src/main/services/prompt-runtime.js';
const root=resolve(import.meta.dirname,'..'),dir=await mkdtemp(join(tmpdir(),'memora-wiki-a3-')),paths=resolvePostgresSidecarPaths({cwd:root,env:process.env}),migrationPath=join(root,'packages/db/drizzle'),seedFolder=join(root,'packages/db/seed');
const manager=new PostgresSidecarManager({binDir:paths.binDir,dataDir:join(dir,'data'),database:'wiki_a3',user:'wiki_a3',password:randomUUID()});let pool:PgPool|undefined,empty:PgPool|undefined;
async function source(db:PgPool,title:string,texts:string[],parentId:string|null=null){const item=await createSourceItemRepository(db).create({type:'GenericDocument',title,parentSourceItemId:parentId});let documentId:string|null=null;const ids:string[]=[];if(texts.length){const doc=await createDocumentRepository(db).create({sourceItemId:item.id,title,canonicalMarkdown:texts.join('\n\n'),contentHash:texts.join('|')});documentId=doc.id;await createChunkRepository(db).replaceDocumentChunks(doc.id,item.id,texts.map((text,index)=>{const id=randomUUID(),span=randomUUID();ids.push(id);return{id,sourceSpanId:span,chunkIndex:index,content:text,contentHash:text,span:{id:span,startOffset:index*100,endOffset:index*100+text.length}};}));}return{id:item.id,ids:ids.toSorted(),documentId};}
async function exercise(db:PgPool){
 const repo=createWikiCuratorRepository(db),collectionRepo=createWikiCollectionRepository(db),runs=createOrganizationRepository(db),jobs=createJobRepository(db),wiki=createWikiRepository(db);
 const fixture=JSON.parse(await readFile(new URL('./fixtures/automatic-wiki/mixed-library.json',import.meta.url),'utf8'));
 const a=await source(db,'Recuperação ativa',[fixture.sources.find((s:any)=>s.key==='A').text]),b=await source(db,'Intervalos e retenção',[fixture.sources.find((s:any)=>s.key==='B').text]),catalog=await source(db,'Catalog only',[]);
 const profile:OrganizationProfile={profileId:randomUUID(),providerConfigId:null,localModelId:randomUUID(),provider:'synthetic',modelId:'fixture',runtime:'test',revision:'1',privacy:'offline_only',parameters:{maxTokens:4096},identityHash:'fixture-a3',contextWindow:65536};let calls=0;
 const draft=(snapshot:CuratorSnapshot)=>{const handle=(kind:string,id:string)=>'r'+(snapshot.references.findIndex(r=>r.kind===kind&&r.id===id)+1),topic=snapshot.pages.find(p=>p.kind==='topic'),index=snapshot.pages.find(p=>p.kind==='collection'),topicHandle=topic?handle('page',topic.id):'new_topic';return{explanation:'Integrate the admitted original classroom evidence.',topics:[{handle:topicHandle,title:topic?.title??'Recuperação e retenção',purpose:topic?.automatic?.purpose??'Compare classroom retrieval and spacing evidence.',sections:[{id:topic?.sections[0]?.id??null,title:'Classroom evidence',markdown:snapshot.evidence.map(e=>e.excerpt+' ['+e.handle+']').join('\n\n'),originalHandles:snapshot.evidence.map(e=>e.handle)}],links:[]}],indexes:[{handle:index?handle('page',index.id):'new_index',title:index?.title??(topic?'Reading '+topic.title:'Reading the classroom evidence'),purpose:index?.automatic?.purpose??'Navigate the original classroom evidence.',owner:{topic:topicHandle},groups:[{id:index?.automatic?.groups[0]?.id??null,title:'Original evidence',explanation:null,originalHandles:[],targets:snapshot.references.filter(r=>r.kind==='source'||r.kind==='atomic_note').map(r=>handle(r.kind,r.id))}]}]};};
 const ai={pinOrganizationProfile:async()=>profile,runOrganizationTask:async(_profile:any,prompt:string,context:any,signal:AbortSignal,_max:number,guard?:()=>Promise<void>)=>{await guard?.();signal.throwIfAborted();calls++;const run=(await runs.get(context.organizationRunId))!;const output=context.stage==='support'?{supported:true,checkedTargets:run.checkpoint.proposal.targets.map((t:any)=>t.handle),issues:[]}:draft(run.snapshot);const aiTaskRunId=await createAiConfigRepository(db).recordTaskRun({...context,promptCompositions:promptAudit(prompt),taskType:'structured-output',provider:'synthetic',modelId:'fixture',runtime:'test',durationMs:1,status:'succeeded',inputTokens:100,outputTokens:50});return{output,aiTaskRunId,inputTokens:100,outputTokens:50,providerId:'synthetic',modelId:'fixture',runtime:'test',durationMs:1,taskType:'structured-output' as const};}};
 const options={getPool:()=>db,ai,contentLanguage:async()=> 'en',wake:()=>{},cancelJob:(id:string)=>jobs.requestCancel(id)};
 const curator=()=>new WikiCurator(options),collection=()=>new WikiCollection(options);
 const preview=CuratorPreviewSchema.parse(await curator().command({command:'preview',input:{wholeLibrary:true,sourceIds:[],includeDescendants:true,excludedSourceIds:[],profileOverrideId:profile.profileId,limits:initialCuratorLimits}}));
 const policy=AutomaticWikiPolicySchema.parse(await curator().command({command:'activate',policyId:preview.policy.id,revisionId:preview.policy.revisionId,previewHash:preview.previewHash}));
 // Read-only inventory neither generates nor creates dispatch jobs.
 const beforeJobs=(await db.query('select count(*)::int n from jobs')).rows[0].n,assessment=await collectionRepo.assessment(policy,null,10);assert.equal(assessment.totals.sources,3);assert.equal(assessment.totals.originals,2);assert.equal(assessment.sources.find(s=>s.id===catalog.id)?.coverage,'cataloged');assert.equal((await db.query('select count(*)::int n from jobs')).rows[0].n,beforeJobs);assert.equal(calls,0);
 const execute=async(id:string)=>{const run=(await curator().get(id))!,job=(await jobs.findById(run.jobId!))!;try{await curator().execute(job,new AbortController().signal);}catch(error){console.error('Synthetic run failed',run.snapshot.requiredPageIds,(await curator().get(id))?.checkpoint.validationIssues);throw error;}};
 const ab=(await curator().start({policyId:policy.id,policyRevisionId:policy.revisionId,sourceIds:[a.id,b.id],noteIds:[]}))!;await execute(ab.id);assert.equal((await curator().get(ab.id))!.status,'applied');assert.equal(calls,2);const topic=(await wiki.list()).find(p=>p.kind==='topic'&&p.automatic)!,originalRevision=topic.revisionId;
 const drain=async(max=160)=>{for(let i=0;i<max;i++){await db.query("update knowledge_impact_deliveries set defer_until=now() where status='deferred'");await collection().tick();const queued=(await db.query("select id from organization_runs where snapshot->>'version'='wiki-curator-v2' and status='queued' order by created_at")).rows;for(const row of queued)await execute(row.id);const count=(await db.query("select count(*)::int n from knowledge_impact_deliveries where consumer_key=$1 and status<>'acknowledged'",[policy.id])).rows[0].n;if(!count&&i>1)break;}};
 await drain();assert.equal(calls,2,'Retained pre-consumption events reuse the A/B receipt without a new call');
 // C is created only AFTER the first canonical A/B group has committed.
 const c=await source(db,fixture.sources.find((s:any)=>s.key==='C').title,[fixture.sources.find((s:any)=>s.key==='C').text]);
 const discovered=await repo.discover(policy,[c.id],fixture.sources.find((s:any)=>s.key==='C').text);assert.ok(discovered.pages.some(p=>p.id===topic.id),'An unfamiliar contradictory C locates the A/B topic by content');
 await drain();
 assert.notEqual((await wiki.get(topic.id))!.revisionId,originalRevision,'Automatic event delivery must commit C before any manual repeat');assert.match((await wiki.get(topic.id))!.sections[0].markdown,/not reproduced/);assert.equal((await db.query("select count(*)::int n from knowledge_impact_deliveries where consumer_key=$1 and status<>'acknowledged'",[policy.id])).rows[0].n,0,'The enabled consumer reaches durable quiescence');const callsAfterAutomatic=calls;
 const increment=(await curator().start({policyId:policy.id,policyRevisionId:policy.revisionId,sourceIds:[c.id],noteIds:[]}))!;assert.deepEqual(increment.snapshot.sourceIds.toSorted(),[a.id,b.id,c.id].toSorted());assert.equal(increment.snapshot.evidence.length,3);assert.equal(increment.status,'applied');assert.equal(calls,callsAfterAutomatic);assert.equal((await curator().get(increment.id))!.status,'applied');assert.equal((await wiki.list()).filter(p=>p.kind==='topic'&&p.automatic).length,1);assert.notEqual((await wiki.get(topic.id))!.revisionId,originalRevision);assert.match((await wiki.get(topic.id))!.sections[0].markdown,/not reproduced/);const noChange=calls;assert.equal((await curator().start({policyId:policy.id,policyRevisionId:policy.revisionId,sourceIds:[c.id],noteIds:[]}))!.id,increment.id);assert.equal(calls,noChange);
 const context=await wiki.context({pageId:topic.id,view:'sources',after:null,limit:1});assert.equal(context.items.length,1);assert.ok(context.next);const nextContext=await wiki.context({pageId:topic.id,view:'sources',after:context.next,limit:30});assert.ok(nextContext.items.every(item=>item.key!==context.items[0]!.key));assert.equal(context.items.length+nextContext.items.length,3,'Sources aggregate evidence and memberships before the cursor');assert.equal((await wiki.context({pageId:topic.id,view:'notes',after:null,limit:30})).items.length,0);assert.ok((await wiki.context({pageId:topic.id,view:'connections',after:null,limit:30})).items.length>=3);
 // Excluded A/B yields metadata-only scope attention, never an alternate duplicate page.
 const narrow={...policy,id:randomUUID(),revisionId:randomUUID(),scope:{...policy.scope,wholeLibrary:false,sourceIds:[c.id],includeDescendants:false}};await repo.draft(narrow,{},'narrow');await repo.activate(narrow.id,narrow.revisionId,'narrow');const denied=await repo.discover(narrow,[c.id],fixture.sources.find((s:any)=>s.key==='C').text);assert.equal(denied.pages.length,0);assert.ok(denied.excluded.length);await assert.rejects(curator().start({policyId:narrow.id,policyRevisionId:narrow.revisionId,sourceIds:[c.id],noteIds:[]}),/scopeDecision/);assert.equal(calls,noChange);await repo.pause(narrow.id);
 // Source/section insert events are source-free, and administrative pinning creates no events.
 const retained=(await db.query("select id from knowledge_impact_events where kind='source' and input_id=$1",[c.id])).rows[0]!;assert.ok(retained);assert.ok((await db.query("select id from knowledge_impact_events where kind='wiki_section' and operation='insert'")).rows.length);const eventCount=(await db.query('select count(*)::int n from knowledge_impact_events')).rows[0].n,current=(await wiki.get(topic.id))!;await wiki.save({version:2,id:topic.id,expectedRevisionId:current.revisionId,content:{...WikiPageContentSchema.strip().parse(current),pinned:true},evidenceChunkIds:[]});assert.equal((await db.query('select count(*)::int n from knowledge_impact_events')).rows[0].n,eventCount);assert.equal((await curator().start({policyId:policy.id,policyRevisionId:policy.revisionId,sourceIds:[c.id],noteIds:[]}))!.id,increment.id,'Pinning preserves the unchanged receipt');
 await db.query('update knowledge_impact_events set consumed_at=now() where id=$1',[retained.id]);await collectionRepo.reconcileDeliveries(policy);await collectionRepo.reconcileDeliveries(narrow);const deliveries=(await db.query("select consumer_key from knowledge_impact_deliveries where event_id=$1 and consumer='curator'",[retained.id])).rows;assert.ok(deliveries.some(d=>d.consumer_key===policy.id));assert.ok(deliveries.some(d=>d.consumer_key===narrow.id));assert.equal((await repo.policy(narrow.id))!.state,'paused');
 // Many originals in ONE source are inspected in resumable bounded groups.
 // Pause event automation during this explicit bootstrap test; its pending deliveries remain intact.
 await repo.pause(policy.id);
 const long=await source(db,'Classroom retrieval study',Array.from({length:14},(_,i)=>`Classroom retrieval measurement ${i+1}: a complete original passage concerning feedback and recall in this synthetic study.`));
 const bootPolicy={...policy,id:randomUUID(),revisionId:randomUUID(),scope:{...policy.scope,wholeLibrary:true,sourceIds:[long.id],includeDescendants:false},triggers:['processing_settled'] as const};await repo.draft(AutomaticWikiPolicySchema.parse(bootPolicy),{},'bootstrap');await repo.activate(bootPolicy.id,bootPolicy.revisionId,'bootstrap');
 const noteIds:string[]=[];for(const chunkId of [long.ids[0]!,long.ids.at(-1)!]){const id=randomUUID();await db.query("insert into atomic_notes(id,title,idea_statement,body_markdown,created_from_source_item_id,evidence_chunk_id,generation_provider,generation_model,generation_runtime,generation_prompt_version,generation_key) values($1::uuid,'Existing reusable note','Existing attributed classroom finding','Existing attributed classroom finding',$2,$3,'synthetic','fixture','test','fixture-v1',$1::text)",[id,long.id,chunkId]);noteIds.push(id);}
 const plan=resolveProcessingPlan({preset:'custom',requestedStages:['organizeKnowledge','atomicNotes'],integrateWiki:{version:2,policyId:bootPolicy.id,policyRevisionId:bootPolicy.revisionId},scope:'source_only',targetSourceItemIds:[long.id],forceRegeneration:false,previousArtifactPolicy:'reuse_valid'}),batches=createHierarchicalIngestionRepository(db),ingestion=createIngestionRunRepository(db);
 const batch=await batches.createBatch({trigger:'synthetic-a3-processing',requestedPlan:plan,effectivePlan:plan,reingestionPolicy:'reuse_valid',targetSourceItemIds:[long.id],promptPin:capturePromptPin(null)}),sourceRun=await ingestion.create({sourceItemId:long.id,batchId:batch.id,effectiveStages:plan.effectiveStages,requestedStages:plan.requestedStages,status:'succeeded'});
 for(const stage of plan.effectiveStages.filter(s=>s!=='organizeKnowledge'))await ingestion.completeStage(sourceRun.id,stage,{reused:true});
 await reconcileOrganizationParticipation(db,new OrganizationService(options));const participation=(await runs.participationRun(batch.id))!;assert.equal(participation.snapshot.version,'wiki-bootstrap-v1','A selected 14-original processing stage uses the resumable parent');const boot=(await collectionRepo.get(participation.id))!;assert.equal((await ingestion.findById(sourceRun.id))!.stagesCheckpoint.organizeKnowledge?.status,'running');
 for(let step=0;step<50;step++){await collection().tick();const run=(await collectionRepo.get(boot.id))!;if(step===0){await collection().command({command:'bootstrapPause',id:boot.id});const stopped=calls;await collection().tick();assert.equal(calls,stopped);await collection().command({command:'bootstrapResume',id:boot.id});}if(run.checkpoint.childRunId){const child=(await curator().get(run.checkpoint.childRunId))!;assert.ok(child.snapshot.evidence.length<=12);if(child.status==='queued')await execute(child.id);}const next=(await collectionRepo.get(boot.id))!;if(next.checkpoint.state==='complete')break;if(next.checkpoint.state==='attention')throw new Error('bootstrap attention: '+next.checkpoint.error);}
 const finished=(await collectionRepo.get(boot.id))!;assert.equal(finished.checkpoint.state,'complete');assert.equal(finished.checkpoint.completedGroups,5);await reconcileOrganizationParticipation(db,new OrganizationService(options));assert.equal((await ingestion.findById(sourceRun.id))!.stagesCheckpoint.organizeKnowledge?.status,'completed');assert.equal((await db.query('select count(*)::int n from atomic_notes where id=any($1::uuid[])',[noteIds])).rows[0].n,2);const covered=WikiAssessmentSchema.parse(await collection().command({command:'assessment',input:{policyId:bootPolicy.id}}));assert.equal(covered.sources.find(s=>s.id===long.id)!.coverage,'integrated');assert.equal(covered.sources.find(s=>s.id===long.id)!.covered,14);const settledCalls=calls;const again=WikiBootstrapSchema.parse(await collection().command({command:'bootstrap',input:{policyId:bootPolicy.id,policyRevisionId:bootPolicy.revisionId,sourceIds:[long.id]}}));await collection().tick();await collection().tick();assert.equal((await collectionRepo.get(again.id))!.checkpoint.state,'complete');assert.equal(calls,settledCalls);
 // No requested optional derivative is regenerated during bootstrap.
 assert.equal((await db.query('select count(*)::int n from atomic_notes')).rows[0].n,2);assert.equal((await db.query('select count(*)::int n from source_summaries')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from embeddings_1024')).rows[0].n,0);
 // A page-oriented cursor processes more than twenty exact dependents; a sibling stays untouched.
 const dependents:string[]=[],parent=(await wiki.get(topic.id))!,parentSection=parent.sections[0]!;
 for(let i=0;i<23;i++){const client=await db.connect();try{await client.query('begin');const id=await wiki.save({expectedRevisionId:null,content:WikiPageContentSchema.parse({title:'Dependent '+i,kind:'topic',sections:[{id:randomUUID(),sectionRevisionId:randomUUID(),title:'Classroom evidence',markdown:fixture.sources.find((s:any)=>s.key==='A').text+' [1]',provenance:'generated',protected:false,evidenceReview:'needs_review',evidenceIds:[a.ids[0]!]}],automatic:{version:'automatic-wiki-v1',management:'ai_managed',role:{kind:'topic',role:'topic'},purpose:'Read the classroom finding in context '+i,placementProtected:false,links:[],groups:[],memberships:[]}}),evidenceChunkIds:a.ids},{transaction:client,origin:'organization',allocatedTarget:false,humanApproved:false});await client.query("update wiki_pages set management='ai_managed' where id=$1",[id]);if(i<22)await client.query("insert into wiki_dependencies(revision_id,section_id,kind,input_id,fingerprint,snapshot) select current_revision_id,$2,'wiki_section',$3,'synthetic-consumption','{}' from wiki_pages where id=$1",[id,(await wiki.get(id))?.sections[0]?.id??randomUUID(),parentSection.id]);await client.query('commit');dependents.push(id);}catch(error){await client.query('rollback');throw error;}finally{client.release();}}
 const untouched=(await wiki.get(dependents[22]!))!.revisionId;
 const eventPolicy=AutomaticWikiPolicySchema.parse({...policy,id:randomUUID(),revisionId:randomUUID(),scope:{...policy.scope,wholeLibrary:false,sourceIds:[a.id],includeDescendants:false},triggers:['input_changed']});await repo.draft(eventPolicy,{},'events');await repo.activate(eventPolicy.id,eventPolicy.revisionId,'events');
 const parentContent=WikiPageContentSchema.strip().parse(parent);parentContent.sections[0]!.markdown+=' A meaningful human qualification.';await wiki.save({version:2,id:parent.id,expectedRevisionId:parent.revisionId,content:parentContent,evidenceChunkIds:[]});
 const parentEvent=(await db.query("select id from knowledge_impact_events where kind='wiki_section' and input_id=$1 and causal_run_id is null order by created_at desc limit 1",[parentSection.id])).rows[0]!.id;
 // The checkpoint starts at this exact event; older retained events still own separate receipts.
 const delivery=(await db.query("select id from knowledge_impact_deliveries where event_id=$1 and consumer_key=$2",[parentEvent,eventPolicy.id])).rows[0]!.id;
 for(let i=0;i<5;i++)await collectionRepo.reconcileDeliveries(eventPolicy);
 await db.query("update knowledge_impact_deliveries set status='deferred',defer_until=now()+interval '1 day' where consumer_key=$1 and id<>$2",[eventPolicy.id,delivery]);
 for(let i=0;i<160;i++){await db.query("update knowledge_impact_deliveries set defer_until=now() where id=$1",[delivery]);await collection().tick();const queued=(await db.query("select id from organization_runs where snapshot->>'version'='wiki-curator-v2' and snapshot->'policy'->>'id'=$1 and status='queued'",[eventPolicy.id])).rows;for(const row of queued)await execute(row.id);const value=(await db.query('select status,checkpoint from knowledge_impact_deliveries where id=$1',[delivery])).rows[0];if(value.status==='acknowledged')break;}
 const delivered=(await db.query('select status,checkpoint,receipt from knowledge_impact_deliveries where id=$1',[delivery])).rows[0]!;assert.equal(delivered.status,'acknowledged');const exact=delivered.checkpoint.outcomes.filter((o:any)=>dependents.slice(0,22).includes(o.pageId));assert.equal(exact.length,22);assert.ok(exact.every((o:any)=>o.status==='applied'),JSON.stringify(exact));assert.equal((await wiki.get(dependents[22]!))!.revisionId,untouched);assert.equal((await db.query('select count(*)::int n from organization_runs where snapshot->\'requiredPageIds\' ? $1',[dependents[21]])).rows[0].n,1,'The 22nd target has its own durable admitted group'); // A real two-page dependency cycle visits both pages and stops at its own durable output.
 await db.query("update knowledge_impact_deliveries set status='deferred',defer_until=now()+interval '1 day' where consumer_key=$1 and status<>'acknowledged'",[eventPolicy.id]);
 let cycleA=(await wiki.get(dependents[0]!))!,cycleB=(await wiki.get(dependents[1]!))!;
 await db.query("insert into wiki_dependencies(revision_id,section_id,kind,input_id,fingerprint,snapshot) values($1,$2,'wiki_section',$3,'cycle','{}') on conflict do nothing",[cycleB.revisionId,cycleB.sections[0]!.id,cycleA.sections[0]!.id]);
 const changedCycle=WikiPageContentSchema.strip().parse(cycleA);changedCycle.sections[0]!.markdown+=' Synthetic external qualification.';changedCycle.sections[0]!.sectionRevisionId=randomUUID();
 const cycleWriter=await db.connect();try{await cycleWriter.query('begin');await wiki.save({version:2,id:cycleA.id,expectedRevisionId:cycleA.revisionId,content:changedCycle,evidenceChunkIds:[]},{transaction:cycleWriter,origin:'organization',allocatedTarget:false,humanApproved:false});await cycleWriter.query('commit');}finally{cycleWriter.release();}
 cycleA=(await wiki.get(cycleA.id))!;await db.query("insert into wiki_dependencies(revision_id,section_id,kind,input_id,fingerprint,snapshot) values($1,$2,'wiki_section',$3,'cycle','{}') on conflict do nothing",[cycleA.revisionId,cycleA.sections[0]!.id,cycleB.sections[0]!.id]);
 const cycleCalls=calls;for(let i=0;i<100;i++){await db.query("update knowledge_impact_deliveries set defer_until=now() where consumer_key=$1 and status='deferred' and defer_until<now()+interval '1 hour'",[eventPolicy.id]);await collection().tick();for(const row of(await db.query("select id from organization_runs where snapshot->>'version'='wiki-curator-v2' and snapshot->'policy'->>'id'=$1 and status='queued'",[eventPolicy.id])).rows)await execute(row.id);const pending=(await db.query("select count(*)::int n from knowledge_impact_deliveries where consumer_key=$1 and status<>'acknowledged' and (defer_until is null or defer_until<now()+interval '1 hour')",[eventPolicy.id])).rows[0].n;if(!pending&&i>2)break;}
 assert.notEqual((await wiki.get(cycleB.id))!.revisionId,cycleB.revisionId,'A real cross-page dependent is updated');assert.notEqual((await wiki.get(cycleA.id))!.revisionId,cycleA.revisionId,'The other side of the cycle is updated');assert.ok(calls-cycleCalls<=8,'A causal cycle has a bounded number of admissions');assert.ok((await db.query("select id from knowledge_impact_deliveries where consumer_key=$1 and receipt::text like '%causal_output_already_applied%'",[eventPolicy.id])).rows.length,'The visited output has a durable no-repeat receipt');
await repo.pause(eventPolicy.id);
 // The parent guard used by transactional apply serializes pause acknowledgment.
 const pauseParentId=await collectionRepo.bootstrap({...finished.snapshot,sourceIds:[a.id],noteIds:[],participation:null}),pauseParent=(await collectionRepo.get(pauseParentId))!;
 const pauseChild=(await curator().start({policyId:bootPolicy.id,policyRevisionId:bootPolicy.revisionId,sourceIds:[a.id],noteIds:[]},null,{parentBootstrapId:pauseParentId,targetPageId:dependents[22]!}))!;
 const lock=await db.connect();let pausing:Promise<unknown>|undefined,pauseAcknowledged=false;try{await lock.query('begin');await lock.query("set local statement_timeout='5s'");await repo.validate(pauseChild.snapshot,lock,true);pausing=collection().command({command:'bootstrapPause',id:pauseParentId}).then(value=>{pauseAcknowledged=true;return value;});
 let waiting=false;for(let i=0;i<30&&!waiting;i++){waiting=(await db.query("select exists(select 1 from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and query like 'update organization_runs set checkpoint%') waiting")).rows[0].waiting;if(!waiting)await new Promise(resolve=>setTimeout(resolve,5));}assert.ok(waiting);assert.equal(pauseAcknowledged,false);
 }finally{await lock.query('rollback').catch(()=>undefined);lock.release();}
 let pauseTimer:ReturnType<typeof setTimeout>|undefined;try{await Promise.race([pausing,new Promise((_,reject)=>{pauseTimer=setTimeout(()=>reject(new Error('Pause acknowledgment timeout')),3000);})]);}finally{if(pauseTimer)clearTimeout(pauseTimer);}
 assert.equal((await collectionRepo.get(pauseParentId))!.checkpoint.state,'paused');await assert.rejects(repo.validate(pauseChild.snapshot),/policy/);pauseParent.checkpoint.state='running';await assert.rejects(collectionRepo.checkpoint(pauseParent),/conflict/,'An old cursor cannot overwrite a later pause');
 // A human rejection is stable until a meaningful canonical input generation changes.
 const rejectedProposal=parseCuratorProposal(draft(pauseChild.snapshot),pauseChild.snapshot);await runs.propose(pauseChild.id,rejectedProposal,pauseChild.checkpoint,false);await runs.reject(pauseChild.id);const repeat=(await curator().start({policyId:bootPolicy.id,policyRevisionId:bootPolicy.revisionId,sourceIds:[a.id],noteIds:[]},null,{targetPageId:dependents[22]!}))!;assert.equal(repeat.id,pauseChild.id);assert.equal(repeat.status,'rejected');const rejectionCalls=calls;await db.query("update source_items set title=title||' clarified' where id=$1",[a.id]);const reconsider=(await curator().start({policyId:bootPolicy.id,policyRevisionId:bootPolicy.revisionId,sourceIds:[a.id],noteIds:[]},null,{targetPageId:dependents[22]!}))!;assert.notEqual(reconsider.id,repeat.id);assert.equal(calls,rejectionCalls);await curator().command({command:'cancel',id:reconsider.id});await collection().command({command:'bootstrapCancel',id:pauseParentId});
 // Historical result pagination cannot hide an older active coordinator from execution.
 const older=await collectionRepo.bootstrap({...finished.snapshot,sourceIds:[catalog.id],noteIds:[],participation:null});const oldWork=(await collectionRepo.get(older))!;
 await db.query("insert into organization_runs(status,snapshot,checkpoint,created_at) select 'applied',$1,$2,clock_timestamp()+i*interval '1 millisecond' from generate_series(1,60) i",[oldWork.snapshot,{...oldWork.checkpoint,state:'complete'}]);assert.ok((await collectionRepo.active()).some(r=>r.id===older));assert.ok((await collectionRepo.list(bootPolicy.id)).some(r=>r.id===older));await collection().tick();assert.equal((await collectionRepo.get(older))!.checkpoint.completedSources,1);await collection().command({command:'bootstrapCancel',id:older});
 // Rich optional entity output is bounded by admitted originals rather than blocking their use.
 await db.query("with e as(insert into entities(type,canonical_name,normalized_name,confidence) select 'concept','Optional '||i,'optional '||i,1 from generate_series(1,121) i returning id) insert into entity_mentions(entity_id,source_item_id,chunk_id,surface_text,confidence) select id,$1,$2,'optional',1 from e",[a.id,a.ids[0]]);assert.equal((await repo.references([a.id],[],a.ids)).filter(r=>r.kind==='entity').length,40);assert.equal(await repo.entityReferenceCount([a.id],a.ids),121);assert.equal((await repo.references([a.id],[],long.ids)).filter(r=>r.kind==='entity').length,0);
 // A link and membership retain two associations but one canonical contextual identity.
 const memberPageId=(await db.query("select page_id from wiki_memberships where target_kind='atomic_note' and target_id=$1 limit 1",[noteIds[0]])).rows[0]!.page_id,memberPage=(await wiki.get(memberPageId))!,memberContent=WikiPageContentSchema.strip().parse(memberPage),sourceMember=memberContent.automatic!.memberships.find(m=>m.target.kind==='source')!;
 memberContent.automatic!.links.push({kind:'atomic_note',id:noteIds[0]!},sourceMember.target);
 const contextWriter=await db.connect();try{await contextWriter.query('begin');await wiki.save({id:memberPage.id,expectedRevisionId:memberPage.revisionId,content:memberContent,evidenceChunkIds:[]},{transaction:contextWriter,origin:'organization',allocatedTarget:false,humanApproved:false});await contextWriter.query('commit');}catch(error){await contextWriter.query('rollback');throw error;}finally{contextWriter.release();}
 for(const [view,target]of [['notes',noteIds[0]!],['sources',sourceMember.target.id]] as const){let cursor:string|null=null;const items:any[]=[];do{const result=await wiki.context({pageId:memberPage.id,view,after:cursor,limit:1});items.push(...result.items);cursor=result.next;}while(cursor);assert.equal(items.filter(item=>item.id===target).length,1);assert.ok(items.find(item=>item.id===target)!.associations.length>=2,'Canonical grouping preserves every association across one-item keyset pages');}
 const connected=(await wiki.context({pageId:memberPage.id,view:'connections',after:null,limit:50})).items.filter(item=>item.id===noteIds[0]);assert.ok(connected.length>=2);assert.ok(connected.every(item=>item.reason&&item.viaTitle===memberPage.title));
 // More than 1,000 pages are reachable with bounded metadata pages, including late selection paths.
 await db.query(`with ids as(select gen_random_uuid() id,gen_random_uuid() revision,i from generate_series(1,1105) i), pages as(insert into wiki_pages(id,title,kind,current_revision_id) select id,'Scale '||lpad(i::text,4,'0'),'topic',revision from ids returning id) insert into wiki_page_revisions(id,page_id,number,origin,content,content_hash) select revision,id,1,'human',jsonb_build_object('title','Scale '||lpad(i::text,4,'0'),'kind','topic','aliases','[]'::jsonb,'parentId',null,'position',0,'collectionIds','[]'::jsonb,'entityId',null,'pinned',false,'archived',false,'review','draft','sections','[]'::jsonb),'scale' from ids`);
 const seen=new Set<string>();let after:null|{id:string;title:string;position:number}=null;do{const page=await wiki.tree({parentId:null,after,limit:37});assert.ok(page.items.length<=37);for(const item of page.items){assert.ok(!seen.has(item.id));seen.add(item.id);assert.ok(!('sections' in item));}after=page.next;}while(after);assert.ok(seen.size>1105);const last=(await db.query("select id from wiki_pages where title='Scale 1105'")).rows[0]!.id;assert.ok(seen.has(last));assert.ok((await wiki.tree({parentId:null,after:null,limit:1,pathTo:last})).path.some(p=>p.id===last));
 const cycle=(await db.query("select id from wiki_pages where title in('Scale 1101','Scale 1102') order by id")).rows.map(r=>r.id);await db.query('update wiki_pages set parent_id=case when id=$1 then $2::uuid else $1::uuid end where id=any($3::uuid[])',[cycle[0],cycle[1],cycle]);const path=await wiki.tree({parentId:null,after:null,limit:1,pathTo:cycle[1]});assert.ok(path.path.length>=1);assert.ok(path.path.some(p=>p.parentId===null));const movable=(await wiki.get(last))!;await assert.rejects(wiki.move({id:last,expectedRevisionId:movable.revisionId,targetId:cycle[0],placement:'into'}),/cycle/);assert.equal((await wiki.get(last))!.revisionId,movable.revisionId);
 console.log('A3 database checks: read-only inventory, actual later C with A/B reuse, excluded originals, per-policy retained-event enrollment, pin no-event, selected processing with 14 complete originals plus two reused notes, durable 22-target worklist and causal cycle, parent-pause serialization/CAS, rejected/new-generation handling, unchanged/pin no calls, >1,100-page navigation and cyclic-move rejection passed. Deterministic model double only.');
}
try{
 const connection=await manager.start();pool=createPgPool({connectionString:connection.connectionString,max:8});const journal=JSON.parse(await readFile(join(migrationPath,'meta/_journal.json'),'utf8')),prior=journal.entries.filter((e:{idx:number})=>e.idx<32),old=join(dir,'old');await mkdir(join(old,'meta'),{recursive:true});await writeFile(join(old,'meta/_journal.json'),JSON.stringify({...journal,entries:prior}));for(const e of prior)await copyFile(join(migrationPath,e.tag+'.sql'),join(old,e.tag+'.sql'));await runMigrations(pool,old);
 const humanId=await createWikiRepository(pool).save({expectedRevisionId:null,content:WikiPageContentSchema.parse({title:'Retained human history',kind:'topic',sections:[{id:randomUUID(),title:'Human',markdown:'Preserve this human text.'}]}),evidenceChunkIds:[]});const history=JSON.stringify(await createWikiRepository(pool).history(humanId));await runMigrations(pool,migrationPath,{seedFolder});assert.equal(JSON.stringify(await createWikiRepository(pool).history(humanId)),history);assert.equal((await pool.query('select count(*)::int n from drizzle.__drizzle_migrations')).rows[0].n,journal.entries.length);await exercise(pool);
 await pool.query('create database wiki_a3_empty');const url=new URL(connection.connectionString);url.pathname='/wiki_a3_empty';empty=createPgPool({connectionString:url.toString(),max:8});assert.equal((await runMigrations(empty,migrationPath,{seedFolder})).seed.applied,true);assert.equal((await empty.query('select count(*)::int n from drizzle.__drizzle_migrations')).rows[0].n,journal.entries.length);await exercise(empty);
}finally{if(empty)await closePgPool(empty);if(pool)await closePgPool(pool);await manager.stop();await rm(dir,{recursive:true,force:true});}
