import {JobSupervisor} from '../apps/desktop/src/main/services/job-supervisor.js';
import {OrganizationService} from '../apps/desktop/src/main/services/organization-service.js';
import {reconcileOrganizationParticipation} from '../apps/desktop/src/main/services/organization-participation.js';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,mkdir,readFile,writeFile,copyFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createPgPool,closePgPool,PostgresSidecarManager,resolvePostgresSidecarPaths,runMigrations,createWikiRepository,createWikiCuratorRepository,createWikiCollectionRepository,createOrganizationRepository,createJobRepository,createAiConfigRepository,createAutomaticMaintenanceRepository,createMaintenanceRepository,createDocumentRepository,createChunkRepository,createSourceItemRepository,createHierarchicalIngestionRepository,createIngestionRunRepository,type PgPool} from '../packages/db/src/index.js';
import {WikiBootstrapSchema,resolveProcessingPlan,CuratorPreviewSchema,AutomaticWikiPolicySchema,WikiPageContentSchema,MaintenancePolicySchema,MaintenanceSnapshotSchema,MaintenanceCheckpointSchema,initialCuratorLimits,type CuratorSnapshot,type OrganizationProfile} from '@app/domain';
import {WikiCurator} from '../apps/desktop/src/main/services/wiki-curator.js';
import {WikiCollection} from '../apps/desktop/src/main/services/wiki-collection.js';
import {MaintenanceService} from '../apps/desktop/src/main/services/maintenance-service.js';
import {promptAudit} from '../apps/desktop/src/main/services/prompt-runtime.js';
import {seedAutomaticWikiFixture} from './fixtures/automatic-wiki-fixture.js';
const root=resolve(import.meta.dirname,'..'),dir=await mkdtemp(join(tmpdir(),'memora-wiki-a4-')),paths=resolvePostgresSidecarPaths({cwd:root,env:process.env}),migrationPath=join(root,'packages/db/drizzle'),seedFolder=join(root,'packages/db/seed');
const manager=new PostgresSidecarManager({binDir:paths.binDir,dataDir:join(dir,'data'),database:'wiki_a4',user:'wiki_a4',password:randomUUID()});let pool:PgPool|undefined,empty:PgPool|undefined;
async function exercise(db:PgPool){
 const fixture=await seedAutomaticWikiFixture(db,false),repo=createAutomaticMaintenanceRepository(db),policies=createWikiCuratorRepository(db),runs=createOrganizationRepository(db),jobs=createJobRepository(db),wiki=createWikiRepository(db),collections=createWikiCollectionRepository(db);
 let now=Date.now(),idle=0,calls=0,configured=true,separateUpkeep=false;const profile:OrganizationProfile={profileId:randomUUID(),providerConfigId:null,localModelId:randomUUID(),provider:'synthetic',modelId:'fixture-a4',runtime:'test',revision:'1',privacy:'offline_only',parameters:{maxTokens:2048},identityHash:'fixture-a4',contextWindow:65536};
 const draft=(s:CuratorSnapshot)=>{const ref=(kind:string,id:string)=>'r'+(s.references.findIndex(r=>r.kind===kind&&r.id===id)+1),topic=s.pages.find(p=>p.kind==='topic'),index=s.pages.find(p=>p.kind==='collection'),topicHandle=topic?ref('page',topic.id):'new_topic';return{explanation:'Maintain the exact admitted sources and retain their distinct findings.',topics:separateUpkeep&&s.requiredPageIds.some(id=>s.pages.some(p=>p.id===id&&p.kind==='collection'))?[]:[{handle:topicHandle,title:topic?.title??'Learning evidence',purpose:topic?.automatic?.purpose??'Compare findings about learning.',sections:[{id:topic?.sections.find(s=>!s.protected)?.id??null,title:'Evidence',markdown:s.evidence.map(e=>e.excerpt+' ['+e.handle+']').join('\n\n'),originalHandles:s.evidence.map(e=>e.handle)}],links:[]}],indexes:separateUpkeep&&!s.requiredPageIds.some(id=>s.pages.some(p=>p.id===id&&p.kind==='collection'))?[]:[{handle:index?ref('page',index.id):'new_index',title:index?.title??'Reading learning evidence',purpose:index?.automatic?.purpose??'Navigate the original findings.',owner:{topic:topicHandle},groups:[{id:index?.automatic?.groups[0]?.id??null,title:'Original findings',explanation:s.sourceIds.length>1?s.evidence.map(e=>e.excerpt+' ['+e.handle+']').join(' '):null,originalHandles:s.sourceIds.length>1?s.evidence.map(e=>e.handle):[],targets:s.references.filter(r=>r.kind==='source').map(r=>ref('source',r.id))}]}]};};
 const ai={pinOrganizationProfile:async()=>{if(!configured)throw new Error('organization.errors.model');return profile;},runOrganizationTask:async(_p:any,prompt:string,context:any,signal:AbortSignal,_max:number,guard?:()=>Promise<void>)=>{await guard?.();signal.throwIfAborted();await context.onProviderStart?.();calls++;const r=(await runs.get(context.organizationRunId))!;if(context.stage!=='support'&&r.snapshot.pages.length){const shown=JSON.parse(prompt.split('\n').find(line=>line.startsWith('EXISTING KNOWLEDGE: '))!.slice('EXISTING KNOWLEDGE: '.length));for(const page of r.snapshot.pages){const view=shown.find((p:any)=>p.handle==='r'+(r.snapshot.references.findIndex((ref:any)=>ref.kind==='page'&&ref.id===page.id)+1));for(const group of page.automatic?.groups??[]){if(group.explanationEvidenceIds.some((id:string)=>page.evidence.some((e:any)=>e.id===id&&!e.current))){const shownGroup=view.groups.find((g:any)=>g.id===group.id);assert.equal(shownGroup.evidenceState,'stale_requires_replacement');assert.equal(shownGroup.patchable,true);assert.equal(shownGroup.previousProseIsCurrentSupport,false);assert.ok(shownGroup.availableOriginalHandles.length);assert.ok(prompt.includes('even if its wording remains accurate'));}}for(const section of page.sections){const item=view.sections.find((s:any)=>s.id===section.id);assert.ok(item,'Actual model input must expose existing section identity');if(section.protected){assert.equal(item.patchable,false);assert.ok(!('previousMarkdown' in item));}else if(section.evidenceIds.some((id:string)=>page.evidence.some((e:any)=>e.id===id&&!e.current))){assert.equal(item.evidenceState,'stale_requires_replacement');assert.equal(item.patchable,true);assert.equal(item.previousProseIsCurrentSupport,false);}}}}const output=context.stage==='support'?{supported:true,checkedTargets:r.checkpoint.proposal.targets.map((t:any)=>t.handle),issues:[]}:draft(r.snapshot);const aiTaskRunId=await createAiConfigRepository(db).recordTaskRun({...context,promptCompositions:promptAudit(prompt),taskType:'structured-output',provider:'synthetic',modelId:'fixture-a4',runtime:'test',durationMs:1,status:'succeeded',inputTokens:100,outputTokens:50});return{output,aiTaskRunId,inputTokens:100,outputTokens:50,providerId:'synthetic',modelId:'fixture-a4',runtime:'test',durationMs:1,taskType:'structured-output' as const};}};
 const options={getPool:()=>db,ai,contentLanguage:async()=> 'en',wake:()=>{},cancelJob:(id:string)=>jobs.requestCancel(id),now:()=>now,idleSeconds:()=>idle,aiBusy:()=>false},curator=new WikiCurator(options),maintenance=new MaintenanceService(options),collection=new WikiCollection(options);
 const preview=CuratorPreviewSchema.parse(await curator.command({command:'preview',input:{sourceIds:fixture.sourceIds,wholeLibrary:false,includeDescendants:false,excludedSourceIds:[],profileOverrideId:profile.profileId,limits:initialCuratorLimits,timezone:'Europe/London'}}));assert.equal(preview.maintenance!.routines.length,4);const retiredIds=(await db.query('select id from maintenance_schedules where retired_at is not null')).rows.map(r=>r.id);assert.ok(preview.maintenance!.legacy.every(s=>!retiredIds.includes(s.id)),'Retired legacy schedules stay out of setup reconciliation while historical receipts remain');assert.equal((await repo.schedules()).length,0);assert.equal(calls,0);
 const policy=AutomaticWikiPolicySchema.parse(await curator.command({command:'activate',policyId:preview.policy.id,revisionId:preview.policy.revisionId,previewHash:preview.previewHash}));await curator.command({command:'activate',policyId:policy.id,revisionId:policy.revisionId,previewHash:preview.previewHash});assert.equal((await repo.schedules(policy.id)).length,4,'Activation is idempotent');
 // Public explicit work immediately after activation bypasses idle only.
 const first=await curator.command({command:'start',input:{policyId:policy.id,policyRevisionId:policy.revisionId,sourceIds:fixture.sourceIds,noteIds:[]}}) as any;assert.ok(first.snapshot.maintenanceRunId);const execute=async(id:string)=>{const r=(await curator.get(id))!,job=(await jobs.findById(r.jobId!))!;await curator.execute(job,new AbortController().signal);await db.query("update jobs set status='succeeded',finished_at=clock_timestamp() where id=$1",[job.id]);};const beforeClose=new Date(now-7*86400000).toISOString();await db.query("update organization_runs set snapshot=jsonb_set(snapshot,'{admittedAt}',to_jsonb($2::text)) where id=$1",[first.id,beforeClose]);await execute(first.id);assert.equal((await curator.get(first.id))!.snapshot.admittedAt,beforeClose,'Closed-app queue time preserves the admission snapshot');assert.equal((await curator.get(first.id))!.checkpoint.executionAdmittedAt,new Date(now).toISOString());assert.equal((await curator.get(first.id))!.status,'applied');assert.equal(calls,2);const ledger=await repo.monthly(policy.id,new Date(now).toISOString().slice(0,7));assert.equal(ledger.calls,2);assert.equal(ledger.spend,null);assert.ok(ledger.tokens>300);const beforeCalls=calls;assert.equal((await curator.command({command:'start',input:{policyId:policy.id,policyRevisionId:policy.revisionId,sourceIds:fixture.sourceIds,noteIds:[]}})as any).id,first.id);assert.equal(calls,beforeCalls);
 // Reservation identity is per organization run/step, even when guards/retries repeat.
 const owner=await repo.get(first.snapshot.maintenanceRunId);await Promise.all([repo.reserve(owner!.id,first.id,1,999,new Date(now)),repo.reserve(owner!.id,first.id,1,999,new Date(now))]);assert.equal((await repo.monthly(policy.id,new Date(now).toISOString().slice(0,7))).calls,2);
 const page=(await wiki.get((await wiki.list()).find(p=>p.kind==='topic'&&p.automatic?.management==='ai_managed')!.id))!,generatedId=page.sections[0]!.id,humanId=randomUUID(),content=WikiPageContentSchema.strip().parse(page);content.sections.push({id:humanId,sectionRevisionId:randomUUID(),title:'Human interpretation',kind:'prose',markdown:'I retain a separate interpretation; this is not empirical corroboration.',protected:true,provenance:'human',evidenceIds:[],evidenceReview:'needs_review'});await wiki.save({version:2,id:page.id,expectedRevisionId:page.revisionId,content,evidenceChunkIds:[]});const human=(await wiki.get(page.id))!.sections.find(s=>s.id===humanId)!;
 const oldIndex=(await wiki.get((await wiki.list()).find(p=>p.kind==='collection'&&p.automatic?.management==='ai_managed')!.id))!,oldGroup=oldIndex.automatic!.groups[0]!;separateUpkeep=true;
 // Retained histories remain immutable while new originals replace a stale generated consumer.
 await db.query("update knowledge_impact_deliveries set status='acknowledged',receipt='{\"kind\":\"fixture_prior_inspection\"}' where consumer_key=$1",[policy.id]);
 const sourceId=fixture.sources.get('A')!,text='Corrected original: retrieval with corrective feedback improved delayed retention in this classroom exercise. The result does not establish clinical effects.',doc=await createDocumentRepository(db).create({sourceItemId:sourceId,title:'Corrected A',canonicalMarkdown:text,contentHash:text}),chunk=randomUUID(),span=randomUUID();await createChunkRepository(db).replaceDocumentChunks(doc.id,sourceId,[{id:chunk,sourceSpanId:span,chunkIndex:0,content:text,contentHash:text,span:{id:span,startOffset:0,endOffset:text.length}}]);await db.query("update documents set metadata=metadata||jsonb_build_object('supersededByDocumentId',$2::text) where id=$1",[fixture.documents.get('A'),doc.id]);await db.query("update wiki_dependencies set stale_reason='input_changed' where kind='source' and input_id=$1",[sourceId]);
 // The original occurrence is canceled: automatic edits must wait for debounce and idle, without starting a fresh allowance through A3.
 await repo.cancel(owner!.id);await db.query("update maintenance_schedules set next_at=$2 where policy->>'policyId'=$1 and policy->>'kind'='incremental'",[policy.id,new Date(now)]);await maintenance.tick();await collection.tick();assert.equal(calls,2);assert.equal((await repo.active(policy.id)).length,0,'Debounce prevents admission');now+=121000;await maintenance.tick();const due=(await repo.active(policy.id))[0]!;assert.equal(due.checkpoint.reason,'maintenance.errors.idle');await collection.tick();assert.equal(calls,2);const runNow=await maintenance.command({command:'automaticRun',scheduleId:due.scheduleIds[0]!,requestId:randomUUID()}) as any;assert.equal(runNow.id,due.id);assert.equal((await repo.get(due.id))!.checkpoint.manualRequested,true);assert.equal((await repo.get(due.id))!.checkpoint.reason,null,'Run-now bypasses idle on the same occurrence');idle=60;now+=1000;
 // Discovery updates only the topic. Exact TOC upkeep must retain its own cursor across an exhausted occurrence.
 const topicOnly=await curator.command({command:'start',input:{policyId:policy.id,policyRevisionId:policy.revisionId,sourceIds:fixture.sourceIds,noteIds:[]}}) as any;await execute(topicOnly.id);assert.equal((await wiki.get(oldIndex.id))!.revisionId,oldIndex.revisionId);assert.ok((await wiki.get(oldIndex.id))!.evidence.some(e=>!e.current));
 for(let i=0;i<80;i++){await db.query("update knowledge_impact_deliveries set defer_until=now() where consumer_key=$1 and status='deferred'",[policy.id]);await maintenance.tick();await collection.tick();if((await repo.get(due.id))!.status==='failed')break;}
 const exhausted=(await repo.get(due.id))!;assert.equal(exhausted.status,'failed');assert.equal(exhausted.checkpoint.reason,'maintenance.errors.budget');assert.equal(exhausted.checkpoint.incomplete,true);assert.ok(await repo.pending(policy.id));const deferred=(await db.query("select * from knowledge_impact_deliveries where consumer_key=$1 and checkpoint->>'blockedReason'='maintenance.errors.budget'",[policy.id])).rows[0]!;assert.ok(deferred);assert.equal(deferred.receipt,null);assert.equal(deferred.checkpoint.childRunId,null);assert.ok(!deferred.checkpoint.outcomes.some((o:any)=>o.status==='organization.errors.failed'));assert.equal((await wiki.get(oldIndex.id))!.revisionId,oldIndex.revisionId);
 const followSchedule=(await repo.schedules(policy.id)).find(s=>s.policy.kind==='daily')!,follow=await maintenance.command({command:'automaticRun',scheduleId:followSchedule.id,requestId:randomUUID()}) as any;assert.notEqual(follow.id,due.id);assert.deepEqual((await repo.get(due.id))!.reservation,exhausted.reservation,'A new occurrence does not refund the exhausted one');
 for(let i=0;i<80;i++){await db.query("update knowledge_impact_deliveries set defer_until=now() where consumer_key=$1 and status='deferred'",[policy.id]);await maintenance.tick();await collection.tick();for(const r of(await db.query("select id from organization_runs where snapshot->>'version'='wiki-curator-v2' and snapshot->'policy'->>'id'=$1 and status='queued'",[policy.id])).rows)await execute(r.id);if((await repo.pending(policy.id))===0)break;}
 await maintenance.tick();assert.equal(await repo.pending(policy.id),0,'All exact dependents must resolve before coverage is complete');const repairedIndex=(await wiki.get(oldIndex.id))!;assert.notEqual(repairedIndex.revisionId,oldIndex.revisionId);assert.equal(repairedIndex.automatic!.groups[0]!.id,oldGroup.id);assert.ok(repairedIndex.automatic!.groups[0]!.explanationEvidenceIds.some(id=>repairedIndex.evidence.some(e=>e.id===id&&e.chunkId===chunk&&e.current)));assert.ok(!repairedIndex.automatic!.groups[0]!.explanationEvidenceIds.some(id=>repairedIndex.evidence.some(e=>e.id===id&&!e.current)));const exactIndex=(await db.query("select snapshot,status from organization_runs where snapshot->'requiredPageIds' @> $1::jsonb",[JSON.stringify([oldIndex.id])])).rows;assert.ok(exactIndex.some(r=>r.status==='applied'));assert.ok((await wiki.history(oldIndex.id)).length>=2);assert.ok(!['applied','no_change'].includes((await repo.get(due.id))!.status));
 const updated=(await wiki.get(page.id))!;assert.ok(updated.sections.find(s=>s.id===generatedId)!.markdown.includes('Corrected original'));assert.deepEqual(updated.sections.find(s=>s.id===humanId),human);assert.ok(updated.evidence.some(e=>e.chunkId===chunk&&e.current));assert.ok((await wiki.history(page.id)).length>=3);assert.ok(calls>2);assert.ok((await repo.monthly(policy.id,new Date(now).toISOString().slice(0,7))).calls<=8);
 // A completed discovery bootstrap must never hide an older unresolved dependent outcome.
 const preservedDelivery=(await db.query('select * from knowledge_impact_deliveries where id=$1',[deferred.id])).rows[0]!,completeBootstrap=(await collections.list(policy.id)).find(b=>b.checkpoint.state==='complete')!;assert.ok(completeBootstrap);
 await db.query("update knowledge_impact_deliveries set status='deferred',receipt=null,defer_until=now(),checkpoint=$2 where id=$1",[deferred.id,{...preservedDelivery.checkpoint,blockedReason:null,blockedMaintenanceRunId:null,childRunId:null,bootstrapId:completeBootstrap.id,outcomes:[{pageId:oldIndex.id,runId:null,status:'organization.errors.failed'}]}]);
 const unresolvedSchedule=(await repo.schedules(policy.id)).find(s=>s.policy.kind==='monthly')!,unresolvedRun=await maintenance.command({command:'automaticRun',scheduleId:unresolvedSchedule.id,requestId:randomUUID()}) as any;await collection.tick();await maintenance.tick();const unresolvedReceipt=(await db.query('select receipt,checkpoint from knowledge_impact_deliveries where id=$1',[deferred.id])).rows[0]!;assert.equal(unresolvedReceipt.receipt,null);assert.equal(unresolvedReceipt.checkpoint.blockedReason,'organization.errors.review');assert.equal((await repo.get(unresolvedRun.id))!.status,'awaiting_review');assert.equal((await repo.get(unresolvedRun.id))!.checkpoint.incomplete,true);
 await repo.cancel(unresolvedRun.id);await db.query('update knowledge_impact_deliveries set status=$2,receipt=$3,checkpoint=$4 where id=$1',[deferred.id,preservedDelivery.status,preservedDelivery.receipt,preservedDelivery.checkpoint]);
 // Attention/review is resolved before clock accrual, including its first observed tick.
 const attentionSchedule=(await repo.schedules(policy.id)).find(s=>s.policy.kind==='monthly')!,attention=(await repo.admit([attentionSchedule],new Date(now),true,randomUUID(),{profile,promptPin:first.snapshot.promptPin,contentLanguage:'en'}))!;
 assert.equal(attention.snapshot.dueAt,new Date(now).toISOString());assert.equal((await db.query('select due_from from maintenance_occurrences where run_id=$1',[attention.id])).rows[0].due_from.toISOString(),attention.snapshot.dueAt,'A new manual run records its actual due time, not a future calendar occurrence');
 const blockedBootstrapId=await collections.bootstrap({version:'wiki-bootstrap-v1',policy,profile,promptPin:first.snapshot.promptPin,contentLanguage:'en',sourceIds:fixture.sourceIds,noteIds:[],participation:null,admittedAt:new Date(now).toISOString()}),blockedBootstrap=(await collections.get(blockedBootstrapId))!;blockedBootstrap.checkpoint.state='attention';blockedBootstrap.checkpoint.error='organization.errors.invalid';await collections.checkpoint(blockedBootstrap);attention.status='inspecting';attention.checkpoint.bootstrapId=blockedBootstrapId;attention.checkpoint.startedAt=new Date(now).toISOString();attention.checkpoint.lastTickAt=new Date(now).toISOString();attention.checkpoint.executionMs=34000;await repo.checkpoint(attention);const callsBeforeAttention=calls;
 for(let tick=0;tick<49;tick++){now+=1000;await maintenance.tick();}const observed=(await repo.get(attention.id))!;assert.equal(observed.status,'awaiting_review');assert.equal(observed.checkpoint.reason,'organization.errors.invalid');assert.equal(observed.checkpoint.executionMs,34000,'49 seconds awaiting review must not become generation time');assert.equal(observed.checkpoint.eligibleMs,0);assert.equal(observed.checkpoint.deferredMs,49000);assert.equal(calls,callsBeforeAttention);assert.equal((await collections.get(blockedBootstrapId))!.checkpoint.state,'attention');await repo.cancel(attention.id);
 // Policy pause revokes inference and guarded apply, while retaining all reservations.
 await policies.pause(policy.id);await assert.rejects(policies.validate((await curator.get(first.id))!.snapshot),/policy|revoked/);const spent=await repo.monthly(policy.id,new Date(now).toISOString().slice(0,7));await maintenance.tick();assert.deepEqual(await repo.monthly(policy.id,new Date(now).toISOString().slice(0,7)),spent);
 // Custom cadence and nested budgets survive a JSONB round-trip and renewed setup.
 const daily=(await repo.schedules(policy.id)).find(s=>s.policy.kind==='daily')!;await repo.save(daily.id,daily.revision,{...daily.policy,cadence:{...daily.policy.cadence,hour:7,minute:35},allowance:{...daily.policy.allowance,calls:3}},new Date(now));const again=CuratorPreviewSchema.parse(await curator.command({command:'preview',input:{policyId:policy.id,sourceIds:fixture.sourceIds,wholeLibrary:false,includeDescendants:false,excludedSourceIds:[],profileOverrideId:profile.profileId,limits:initialCuratorLimits,timezone:'UTC'}}));assert.equal(again.maintenance!.routines.find(r=>r.policy.kind==='daily')!.policy.cadence.hour,7);await curator.command({command:'activate',policyId:policy.id,revisionId:again.policy.revisionId,previewHash:again.previewHash});assert.equal((await repo.schedules(policy.id)).length,4);assert.equal((await repo.schedules(policy.id)).find(s=>s.policy.kind==='daily')!.policy.allowance.calls,3);
 // A closed week admits one catch-up per distinct routine, keeping exact individual limits and receipts.
 await db.query("update maintenance_schedules set next_at=$2 where policy->>'policyId'=$1 and policy->>'kind'<>'incremental'",[policy.id,new Date(now-7*86400000)]);await maintenance.tick();const catches=(await repo.active(policy.id)).filter(r=>r.snapshot.policy.kind!=='incremental');assert.equal(catches.length,3);assert.deepEqual(catches.map(r=>r.snapshot.policy.executionMs).sort((a,b)=>a-b),[1200000,2700000,5400000]);await maintenance.tick();assert.equal((await repo.active(policy.id)).filter(r=>r.snapshot.policy.kind!=='incremental').length,3);assert.equal((await db.query('select count(*)::int n from maintenance_occurrences where run_id=any($1::uuid[])',[catches.map(r=>r.id)])).rows[0].n,3);
 assert.equal((await db.query('select count(*)::int n from atomic_notes')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from source_summaries')).rows[0].n,0);assert.equal((await db.query("select count(*)::int n from ai_task_runs where cost_estimate is not null")).rows[0].n,0);
 // Resume is not a new setup and must not overwrite independently customized schedules.
 await curator.command({command:'pause',policyId:policy.id});await curator.command({command:'resume',policyId:policy.id});assert.equal((await repo.schedules(policy.id)).find(s=>s.policy.kind==='daily')!.policy.cadence.hour,7);
 // Low synthetic limits exercise atomic cross-routine contention without making model calls.
 const low=CuratorPreviewSchema.parse(await curator.command({command:'preview',input:{sourceIds:fixture.sourceIds,wholeLibrary:false,includeDescendants:false,excludedSourceIds:[],profileOverrideId:profile.profileId,limits:initialCuratorLimits,timezone:'UTC'}}));for(const item of low.maintenance!.routines){item.policy.allowance={calls:2,tokens:1000,spend:null};item.policy.monthAllowance={calls:2,tokens:1000,spend:null};}low.maintenance!.monthAllowance={calls:2,tokens:1000,spend:null};await db.query('update wiki_policy_revisions set preview=$2,preview_hash=$3 where id=$1',[low.policy.revisionId,low,'synthetic-low-limits']);const lowPolicy=AutomaticWikiPolicySchema.parse(await curator.command({command:'activate',policyId:low.policy.id,revisionId:low.policy.revisionId,previewHash:'synthetic-low-limits'}));
 const lowSchedules=await repo.schedules(lowPolicy.id),lowRuns=[];for(const s of lowSchedules.slice(0,2)){const r=(await repo.admit([s],new Date(now),true,randomUUID(),{profile,promptPin:first.snapshot.promptPin,contentLanguage:'en'}))!;r.status='inspecting';r.checkpoint.startedAt=new Date(now).toISOString();await repo.checkpoint(r);lowRuns.push(r);}const children=[];for(const r of lowRuns)children.push(await runs.create({...first.snapshot,policy:lowPolicy,maintenanceRunId:r.id,inputFingerprint:randomUUID(),groupId:randomUUID()},first.checkpoint));
 const concurrent=await Promise.allSettled(lowRuns.map((r,i)=>repo.reserve(r.id,children[i]!,1,600,new Date(now))));assert.equal(concurrent.filter(r=>r.status==='fulfilled').length,1);assert.equal(concurrent.filter(r=>r.status==='rejected').length,1);const winning=concurrent.findIndex(r=>r.status==='fulfilled'),losing=1-winning;assert.equal((await repo.monthly(lowPolicy.id,new Date(now).toISOString().slice(0,7))).tokens,600);await repo.reserve(lowRuns[winning]!.id,children[winning]!,1,600,new Date(now));await repo.reserve(lowRuns[winning]!.id,children[winning]!,2,400,new Date(now));await assert.rejects(repo.reserve(lowRuns[losing]!.id,children[losing]!,1,1,new Date(now)),/period/);assert.equal((await repo.monthly(lowPolicy.id,new Date(now).toISOString().slice(0,7))).calls,2);
 const oldClock=(await repo.get(lowRuns[winning]!.id))!;await repo.heartbeat(oldClock.id,new Date(now),5000);await repo.checkpoint(oldClock);assert.equal((await repo.get(oldClock.id))!.checkpoint.executionMs,5000,'A stale checkpoint cannot overwrite heartbeat consumption');
 const nextMonth=new Date(now);nextMonth.setUTCMonth(nextMonth.getUTCMonth()+1);await repo.heartbeat(lowRuns[losing]!.id,nextMonth,0);await repo.reserve(lowRuns[losing]!.id,children[losing]!,1,600,nextMonth);assert.equal((await repo.monthly(lowPolicy.id,nextMonth.toISOString().slice(0,7))).calls,1);assert.equal((await repo.monthly(lowPolicy.id,new Date(now).toISOString().slice(0,7))).calls,2,'Month rollover retains historic debits');await repo.cancel(lowRuns[losing]!.id);await assert.rejects(repo.reserve(lowRuns[losing]!.id,children[losing]!,2,1,nextMonth),/revoked/);await policies.pause(lowPolicy.id);
 separateUpkeep=false;
 // Public collection bootstrap uses the real supervisor and keeps one parent occurrence across multiple groups.
 for(const p of await policies.policies())if(p.state==='enabled')await policies.pause(p.id);await db.query("update jobs set status='canceled' where status='queued'");
 const long=await createSourceItemRepository(db).create({type:'GenericDocument',title:'Zirconium ceramic glaze'}),texts=Array.from({length:14},(_,i)=>'Zirconium ceramic glaze batch '+(i+1)+' has a separately documented observation.'),longDoc=await createDocumentRepository(db).create({sourceItemId:long.id,title:long.title,canonicalMarkdown:texts.join('\n'),contentHash:texts.join('|')});await createChunkRepository(db).replaceDocumentChunks(longDoc.id,long.id,texts.map((text,i)=>{const id=randomUUID(),span=randomUUID();return{id,sourceSpanId:span,chunkIndex:i,content:text,contentHash:text,span:{id:span,startOffset:i*100,endOffset:i*100+text.length}};}));
 const bootPreview=CuratorPreviewSchema.parse(await curator.command({command:'preview',input:{sourceIds:[long.id],wholeLibrary:false,includeDescendants:false,excludedSourceIds:[],profileOverrideId:profile.profileId,limits:initialCuratorLimits,timezone:'UTC'}}));const bootPolicy=AutomaticWikiPolicySchema.parse(await curator.command({command:'activate',policyId:bootPreview.policy.id,revisionId:bootPreview.policy.revisionId,previewHash:bootPreview.previewHash}));idle=0;const bootstrap=WikiBootstrapSchema.parse(await collection.command({command:'bootstrap',input:{policyId:bootPolicy.id,policyRevisionId:bootPolicy.revisionId,sourceIds:[long.id]}}));const parent=(await repo.active(bootPolicy.id))[0]!;assert.equal(parent.snapshot.policy.kind,'daily');assert.equal(parent.checkpoint.bootstrapId,bootstrap.id);
 const organization=new OrganizationService(options),supervisor=new JobSupervisor({getPool:()=>db,maintenanceTick:()=>maintenance.tick(),maintenanceReady:job=>maintenance.ready(job),processMaintenance:(job,signal)=>maintenance.execute(job,signal),reconcileOrganization:async()=>{await reconcileOrganizationParticipation(db,organization);await collection.tick();},processOrganization:(job,signal)=>curator.execute(job,signal),logger:{error:()=>{},warn:()=>{}}});
 try{for(let i=0;i<100;i++){await db.query("update knowledge_impact_deliveries set defer_until=now() where consumer_key=$1 and status='deferred'",[bootPolicy.id]);await supervisor.runOnce();if((await collections.get(bootstrap.id))!.checkpoint.state==='complete')break;}const finished=(await collections.get(bootstrap.id))!;assert.equal(finished.checkpoint.state,'complete',JSON.stringify(finished.checkpoint));assert.equal(finished.checkpoint.completedGroups,3);assert.equal((await db.query("select count(distinct snapshot->>'maintenanceRunId')::int n from organization_runs where snapshot->>'parentBootstrapId'=$1",[bootstrap.id])).rows[0].n,1,'Every group inherits the same parent allowance');
  // Selected processing reuses exact existing coverage and remains free of optional derivation stages.
  const plan=resolveProcessingPlan({preset:'custom',requestedStages:['organizeKnowledge'],integrateWiki:{version:2,policyId:bootPolicy.id,policyRevisionId:bootPolicy.revisionId},scope:'source_only',targetSourceItemIds:[long.id],forceRegeneration:false,previousArtifactPolicy:'reuse_valid'}),batches=createHierarchicalIngestionRepository(db),ingestion=createIngestionRunRepository(db),batch=await batches.createBatch({trigger:'synthetic-a4-selected',requestedPlan:plan,effectivePlan:plan,reingestionPolicy:'reuse_valid',targetSourceItemIds:[long.id],promptPin:finished.snapshot.promptPin}),selectedRun=await ingestion.create({sourceItemId:long.id,batchId:batch.id,effectiveStages:plan.effectiveStages,requestedStages:plan.requestedStages,status:'succeeded'});
  for(const stage of plan.effectiveStages.filter(s=>s!=='organizeKnowledge'))await ingestion.completeStage(selectedRun.id,stage,{reused:true});for(let i=0;i<40;i++){await supervisor.runOnce();if((await ingestion.findById(selectedRun.id))!.stagesCheckpoint.organizeKnowledge?.status==='completed')break;}assert.equal((await ingestion.findById(selectedRun.id))!.stagesCheckpoint.organizeKnowledge?.status,'completed');assert.ok(!plan.effectiveStages.some(s=>['summarization','atomicNotes','embedding','knowledgeGraph','atomicNoteMatching','sourceMatching'].includes(s)));
 }finally{await supervisor.stop();}
 // A never-started missing-model occurrence remains history; run-now can recover with a newly configured route.
 configured=false;const missing=CuratorPreviewSchema.parse(await curator.command({command:'preview',input:{sourceIds:[long.id],wholeLibrary:false,includeDescendants:false,excludedSourceIds:[],profileOverrideId:null,limits:initialCuratorLimits,timezone:'UTC'}}));await curator.command({command:'activate',policyId:missing.policy.id,revisionId:missing.policy.revisionId,previewHash:missing.previewHash});const missingSchedule=(await repo.schedules(missing.policy.id)).find(s=>s.policy.kind==='daily')!;const unavailable=await maintenance.command({command:'automaticRun',scheduleId:missingSchedule.id,requestId:randomUUID()}) as any;assert.equal((await repo.get(unavailable.id))!.status,'failed');assert.equal((await repo.get(unavailable.id))!.snapshot.profile,null);configured=true;const recovered=await maintenance.command({command:'automaticRun',scheduleId:missingSchedule.id,requestId:randomUUID()}) as any;assert.notEqual(recovered.id,unavailable.id);assert.equal((await repo.get(recovered.id))!.snapshot.profile!.modelId,profile.modelId);assert.equal((await repo.get(unavailable.id))!.snapshot.profile,null);await curator.command({command:'pause',policyId:missing.policy.id});assert.equal((await maintenance.command({command:'automaticDashboard',policyId:missing.policy.id}) as any).policyState,'paused');
 console.log('A4: activation/custom preservation, shared reservation idempotence, explicit first run, debounce/idle, topic-only correction followed by retained budget cursor and separate exact TOC evidence repair/human preservation, pause, distinct bounded closed-week catches, historical receipts, concurrent month limits/rollover, monotonic heartbeat, 14-original supervisor bootstrap, selected processing, missing-model recovery and no optional artifacts passed.');
}
try{const connection=await manager.start();pool=createPgPool({connectionString:connection.connectionString,max:8});const journal=JSON.parse(await readFile(join(migrationPath,'meta/_journal.json'),'utf8')),prior=journal.entries.filter((e:{idx:number})=>e.idx<35),old=join(dir,'old');await mkdir(join(old,'meta'),{recursive:true});await writeFile(join(old,'meta/_journal.json'),JSON.stringify({...journal,entries:prior}));for(const e of prior)await copyFile(join(migrationPath,e.tag+'.sql'),join(old,e.tag+'.sql'));await runMigrations(pool,old);
 const legacy=await createMaintenanceRepository(pool).save(undefined,undefined,MaintenancePolicySchema.parse({name:'Retained legacy',scope:{wholeLibrary:true},categories:['navigation'],cadence:{timezone:'UTC'}}),new Date().toISOString());const legacyBefore=(await pool.query('select policy from maintenance_schedules where id=$1',[legacy.id])).rows[0].policy;const historicalRun=randomUUID(),historicalJob=(await pool.query("insert into jobs(type,status,payload) values('maintenance','succeeded',$1) returning id",[{maintenanceRunId:historicalRun}])).rows[0]!.id,historicalSnapshot=MaintenanceSnapshotSchema.parse({version:'wiki-maintenance-v1',policy:legacy.policy,configurationId:null,configurationHash:'historical-fixture',instructions:{slots:{guidance:'',advanced:''},origins:{guidance:'default',advanced:'default'},domainId:null},profile:null,language:'en',scopeKey:'historical',period:'2026-08',cutoff:new Date().toISOString()});await pool.query("insert into maintenance_runs(id,job_id,scope_key,period,schedule_ids,status,snapshot,checkpoint,reservation) values($1,$2,'historical','2026-08',$3,'no_change',$4,$5,$6)",[historicalRun,historicalJob,JSON.stringify([legacy.id]),historicalSnapshot,MaintenanceCheckpointSchema.parse({}),{calls:0,tokens:0,spend:null}]);await pool.query("insert into maintenance_occurrences(schedule_id,occurrence_key,due_from,due_until,run_id) values($1,'historical',$2,$2,$3)",[legacy.id,new Date(),historicalRun]);const originalReceipt=await createMaintenanceRepository(pool).get(historicalRun);await runMigrations(pool,migrationPath,{seedFolder});assert.deepEqual((await pool.query('select policy from maintenance_schedules where id=$1',[legacy.id])).rows[0].policy,legacyBefore);assert.equal((await pool.query('select count(*)::int n from automatic_routine_bindings')).rows[0].n,0);assert.equal((await pool.query('select count(*)::int n from drizzle.__drizzle_migrations')).rows[0].n,journal.entries.length);assert.equal((await pool.query("select is_nullable from information_schema.columns where table_name='maintenance_schedules' and column_name='retired_at'")).rows[0].is_nullable,'YES');await createAutomaticMaintenanceRepository(pool).retireLegacy([legacy.id]);assert.ok((await pool.query('select retired_at from maintenance_schedules where id=$1',[legacy.id])).rows[0].retired_at);assert.equal((await createMaintenanceRepository(pool).schedules()).length,0);assert.deepEqual(await createMaintenanceRepository(pool).get(historicalRun),originalReceipt);assert.equal((await pool.query('select count(*)::int n from maintenance_occurrences where run_id=$1',[historicalRun])).rows[0].n,1);assert.equal((await pool.query('select status from jobs where id=$1',[historicalJob])).rows[0].status,'succeeded');await exercise(pool);
 await pool.query('create database wiki_a4_empty');const url=new URL(connection.connectionString);url.pathname='/wiki_a4_empty';empty=createPgPool({connectionString:url.toString(),max:8});assert.equal((await runMigrations(empty,migrationPath,{seedFolder})).seed.applied,true);assert.equal((await empty.query('select count(*)::int n from drizzle.__drizzle_migrations')).rows[0].n,journal.entries.length);await exercise(empty);
}finally{if(empty)await closePgPool(empty);if(pool)await closePgPool(pool);await manager.stop();await rm(dir,{recursive:true,force:true});}
