import {reconcileOrganizationParticipation}from'../apps/desktop/src/main/services/organization-participation.js';
import {promptAudit,withPromptPin}from'../apps/desktop/src/main/services/prompt-runtime.js';
import {curatorSupportPrompt}from'../apps/desktop/src/main/services/wiki-curator.js';
import assert from'node:assert/strict';
import {randomUUID}from'node:crypto';
import {mkdtemp,mkdir,readFile,writeFile,copyFile,rm}from'node:fs/promises';
import {tmpdir}from'node:os';
import {join,resolve}from'node:path';
import {createPgPool,closePgPool,PostgresSidecarManager,resolvePostgresSidecarPaths,runMigrations,createWikiRepository,createWikiCuratorRepository,curatorHash,createOrganizationRepository,createJobRepository,createAiConfigRepository,createHierarchicalIngestionRepository,createIngestionRunRepository,type PgPool}from'../packages/db/src/index.js';
import {AutomaticWikiPolicySchema,CuratorPreviewSchema,CuratorRunSchema,WikiPageContentSchema,type OrganizationProfile,resolveProcessingPlan}from'@app/domain';
import {WikiCurator,validateCuratorProposal}from'../apps/desktop/src/main/services/wiki-curator.js';
import {seedAutomaticWikiFixture,fixtureCuratorProposal}from'./fixtures/automatic-wiki-fixture.js';
const root=resolve(import.meta.dirname,'..'),dir=await mkdtemp(join(tmpdir(),'memora-automatic-wiki-')),paths=resolvePostgresSidecarPaths({cwd:root,env:process.env}),migrationPath=join(root,'packages/db/drizzle'),seedFolder=join(root,'packages/db/seed');
const manager=new PostgresSidecarManager({binDir:paths.binDir,dataDir:join(dir,'data'),database:'automatic_wiki',user:'automatic_wiki',password:randomUUID()});let pool:PgPool|undefined,empty:PgPool|undefined;
try{const connection=await manager.start();pool=createPgPool({connectionString:connection.connectionString,max:8});const journal=JSON.parse(await readFile(join(migrationPath,'meta/_journal.json'),'utf8')),prior=journal.entries.filter((e:{idx:number})=>e.idx<31),old=join(dir,'old');await mkdir(join(old,'meta'),{recursive:true});await writeFile(join(old,'meta/_journal.json'),JSON.stringify({...journal,entries:prior}));for(const e of prior)await copyFile(join(migrationPath,e.tag+'.sql'),join(old,e.tag+'.sql'));await runMigrations(pool,old);
 const fixture=await seedAutomaticWikiFixture(pool,true),oldRevision=(await createWikiRepository(pool).get(fixture.humanId))!.revisionId;const legacyDraft=randomUUID(),legacyProtected=randomUUID();for(const [id,protectedText]of [[legacyDraft,false],[legacyProtected,true]]as const){const revision=randomUUID(),content=WikiPageContentSchema.parse({title:'Legacy '+id,kind:'topic',sections:[{id:randomUUID(),title:'Legacy',markdown:'Historical interpretation',protected:protectedText,provenance:'generated',evidenceReview:'needs_review'}]});await pool.query('insert into wiki_pages(id,title,kind,current_revision_id) values($1,$2,$3,$4)',[id,content.title,'topic',revision]);await pool.query("insert into wiki_page_revisions(id,page_id,number,origin,content,content_hash) values($1,$2,1,'organization',$3,'legacy')",[revision,id,content]);}
 await runMigrations(pool,migrationPath,{seedFolder});assert.equal((await pool.query('select management from wiki_pages where id=$1',[legacyDraft])).rows[0].management,'ai_managed');assert.equal((await pool.query('select management from wiki_pages where id=$1',[legacyProtected])).rows[0].management,'human_managed');
 assert.equal((await pool.query('select count(*)::int n from source_items')).rows[0].n,12);assert.equal((await createWikiRepository(pool).get(fixture.humanId))!.revisionId,oldRevision);assert.equal((await pool.query('select management from wiki_pages where id=$1',[fixture.humanId])).rows[0].management,'human_managed');assert.equal((await pool.query('select count(*)::int n from wiki_policy_activations')).rows[0].n,0);
 const profile:OrganizationProfile={profileId:randomUUID(),providerConfigId:null,localModelId:randomUUID(),provider:'synthetic',modelId:'fixture',runtime:'test',revision:'1',privacy:'offline_only',parameters:{maxTokens:4096},identityHash:'fixture',contextWindow:65536};let calls=0,override:((s:any)=>Promise<any>)|null=null;
 async function exercise(db:PgPool,inputs:Awaited<ReturnType<typeof seedAutomaticWikiFixture>>){const initialPages=(await createWikiRepository(db).list()).length;const runs=createOrganizationRepository(db),jobs=createJobRepository(db),wiki=createWikiRepository(db),repo=createWikiCuratorRepository(db);const ai={pinOrganizationProfile:async()=>profile,runOrganizationTask:async(_p:any,_prompt:string,context:any,signal:AbortSignal,_max:number,guard?:()=>Promise<void>)=>{await guard?.();signal.throwIfAborted();calls++;const snapshot=(await runs.get(context.organizationRunId))!.snapshot;const candidate=(await runs.get(context.organizationRunId))!.checkpoint.proposal;const output=context.stage==='support'?{supported:true,checkedTargets:candidate.targets.map((t:any)=>t.handle),issues:[]}:override?await override(snapshot):await fixtureCuratorProposal(snapshot);const aiTaskRunId=await createAiConfigRepository(db).recordTaskRun({...context,promptCompositions:promptAudit(_prompt),taskType:'structured-output',provider:'synthetic',modelId:'fixture',runtime:'test',durationMs:1,status:'succeeded',inputTokens:100,outputTokens:50});return{output,aiTaskRunId,inputTokens:100,outputTokens:50,providerId:'synthetic',modelId:'fixture',runtime:'test',durationMs:1,taskType:'structured-output' as const};}};
 const service=()=>new WikiCurator({getPool:()=>db,ai:ai as any,contentLanguage:async()=> 'en',wake:()=>{},cancelJob:id=>jobs.requestCancel(id)});
 const preview=CuratorPreviewSchema.parse(await service().command({command:'preview',input:{sourceIds:inputs.sourceIds,includeDescendants:false,excludedSourceIds:[],profileOverrideId:profile.profileId,limits:{targets:3,sectionPatchesPerPage:6,originalPassages:12,tools:20,modelCalls:21,repairs:1,deadlineMs:600000}}}));assert.equal(calls,0);// Exercise the historical A2/A3 activation snapshot; A4 public setup has its own verifier.
 await db.query("update wiki_policy_revisions set preview=preview-'maintenance' where id=$1",[preview.policy.revisionId]);
 const policy=AutomaticWikiPolicySchema.parse(await service().command({command:'activate',policyId:preview.policy.id,revisionId:preview.policy.revisionId,previewHash:preview.previewHash}));
 const certify=async(run:any,proposal:any)=>{const checkpoint={...run.checkpoint,proposal};const prompt=withPromptPin(run.snapshot.promptPin,()=>curatorSupportPrompt(run.snapshot,checkpoint));const sequence=checkpoint.calls+1,aiTaskRunId=await createAiConfigRepository(db).recordTaskRun({organizationRunId:run.id,organizationStep:sequence,taskType:'structured-output',provider:'synthetic',modelId:'fixture',runtime:'test',durationMs:1,status:'succeeded',promptCompositions:withPromptPin(run.snapshot.promptPin,()=>{const input=curatorSupportPrompt(run.snapshot,checkpoint);return promptAudit(input);})});const verdict={supported:true,checkedTargets:proposal.targets.map((t:any)=>t.handle),issues:[]};checkpoint.calls=sequence;checkpoint.supportAssessment={proposalHash:curatorHash(proposal),aiTaskRunId,verdict};await runs.step(run.id,sequence,checkpoint,{support:verdict,proposalHash:curatorHash(proposal)},aiTaskRunId);return checkpoint;};
 const start=()=>service().start({policyId:policy.id,policyRevisionId:policy.revisionId,sourceIds:inputs.sourceIds,noteIds:inputs.noteIds});const execute=async(run:any)=>{const job=await jobs.findById(run.jobId);return service().execute(job!,new AbortController().signal);};const run=(await start())!;assert.equal(run.snapshot.pages.some(p=>p.id===inputs.humanId),false,'Unbound human prose is never scope-authorized');assert.equal(run.snapshot.evidence.length,2);assert.equal(run.snapshot.references.filter(r=>r.kind==='atomic_note').length,inputs.noteIds.length);await execute(run);const applied=(await service().get(run.id))!;assert.equal(applied.status,'applied');assert.equal(applied.checkpoint.calls,2);assert.equal(applied.checkpoint.supportAssessment?.verdict.supported,true);assert.equal(applied.checkpoint.supportAssessment?.proposalHash,curatorHash(applied.proposal));assert.equal(applied.checkpoint.usageCounts.cost,0);assert.equal(applied.checkpoint.usageIncomplete,true);
 const pages=await wiki.list();assert.equal(pages.length,initialPages+3);const topic=pages.find(p=>p.kind==='topic'&&p.automatic?.management==='ai_managed')!;const page=(await wiki.get(topic.id))!;assert.equal(page.sections[0].protected,false);assert.equal(page.sections[0].assessment.humanReview,'unreviewed');assert.equal(page.sections[0].assessment.support,'validated');assert.equal(page.evidence.length,2);
 const before=calls;assert.equal((await start())!.id,run.id);await db.query('update source_items set updated_at=clock_timestamp() where id=any($1::uuid[])',[inputs.sourceIds]);assert.equal((await start())!.id,run.id,'Administrative timestamps do not change semantic input identity');assert.equal(calls,before);await repo.apply(run.id,false,validateCuratorProposal);assert.equal((await wiki.history(topic.id)).length,1);
 // Explicit selected processing can reuse a completed curator receipt without an orphaned batch barrier.
 const selectedPlan=resolveProcessingPlan({preset:'custom',requestedStages:['organizeKnowledge',...(inputs.noteIds.length?['atomicNotes']:[])],integrateWiki:{version:2,policyId:policy.id,policyRevisionId:policy.revisionId},scope:'source_only',targetSourceItemIds:inputs.sourceIds,forceRegeneration:false,previousArtifactPolicy:'reuse_valid'});const batches=createHierarchicalIngestionRepository(db),ingestion=createIngestionRunRepository(db),batch=await batches.createBatch({trigger:'synthetic-selected-processing',requestedPlan:selectedPlan,effectivePlan:selectedPlan,reingestionPolicy:'reuse_valid',targetSourceItemIds:inputs.sourceIds,promptPin:run.snapshot.promptPin});const ingestionIds=[];for(const sourceItemId of inputs.sourceIds){const child=await ingestion.create({sourceItemId,batchId:batch.id,effectiveStages:selectedPlan.effectiveStages,requestedStages:selectedPlan.requestedStages,status:'succeeded'});ingestionIds.push(child.id);for(const stage of selectedPlan.effectiveStages.filter(s=>s!=='organizeKnowledge'))await ingestion.completeStage(child.id,stage,{reused:true});}const participationService={automaticStart:(input:any,participation:any)=>service().start(input,participation)};await reconcileOrganizationParticipation(db,participationService as any);await reconcileOrganizationParticipation(db,participationService as any);assert.equal((await runs.participationRun(batch.id))!.id,run.id);for(const id of ingestionIds)assert.equal((await ingestion.findById(id))!.stagesCheckpoint.organizeKnowledge?.status,'completed');assert.equal(calls,before,'Reused selected processing performs no model admission');assert.equal((await db.query('select count(*)::int n from organization_runs')).rows[0].n,1);assert.equal((await service().get(run.id))!.snapshot.references.filter(r=>r.kind==='atomic_note').length,inputs.noteIds.length);
 // Admission identity includes effective parameters; changing them cannot inherit an exhausted failed generation.
 const originalParameters=structuredClone(profile.parameters);profile.parameters={...originalParameters,temperature:0.2};const failedParameters=(await start())!;assert.notEqual(failedParameters.id,run.id);await runs.checkpoint(failedParameters.id,'failed',{...failedParameters.checkpoint,calls:2,repairs:1,error:'organization.errors.invalid'});assert.equal((await start())!.id,failedParameters.id);profile.parameters={...originalParameters,temperature:0};const changedParameters=(await start())!;assert.notEqual(changedParameters.id,failedParameters.id);const retained=(await service().get(failedParameters.id))!;assert.equal(retained.snapshot.profile.parameters.temperature,0.2);assert.equal(retained.checkpoint.calls,2);assert.equal(retained.checkpoint.repairs,1);assert.equal(changedParameters.snapshot.profile.parameters.temperature,0);assert.equal(changedParameters.checkpoint.calls,0);profile.parameters=originalParameters;assert.equal(calls,before);
 const indexes=pages.filter(p=>p.kind==='collection');for(const index of indexes){const p=(await wiki.get(index.id))!;assert.ok(p.automatic.groups[0].id);for(const member of p.automatic.memberships){assert.notEqual(member.expectedPageRevisionId,p.id);assert.equal(member.expectedPageRevisionId,p.revisionId);const target=await wiki.linkedTarget({pageId:p.id,...member.target});assert.ok(target);if(member.target.kind==='atomic_note')assert.equal(target!.evidence.length,1);}}
 // Native pinning keeps current TOC query rows on the new revision without changing membership authorship/order.
 const indexBefore=(await wiki.get(indexes[0]!.id))!,indexHistory=JSON.stringify((await db.query('select content from wiki_page_revisions where id=$1',[indexBefore.revisionId])).rows[0].content);await wiki.save({version:2,id:indexBefore.id,expectedRevisionId:indexBefore.revisionId,content:{...WikiPageContentSchema.strip().parse(indexBefore),pinned:true},evidenceChunkIds:[]});const indexAfter=(await wiki.get(indexBefore.id))!;assert.deepEqual(indexAfter.automatic!.groups,indexBefore.automatic!.groups);for(const member of indexAfter.automatic!.memberships){const prior=indexBefore.automatic!.memberships.find(m=>m.id===member.id)!;assert.deepEqual({...member,expectedPageRevisionId:prior.expectedPageRevisionId},prior);assert.equal(member.expectedPageRevisionId,indexAfter.revisionId);}assert.ok((await db.query('select revision_id from wiki_toc_groups where page_id=$1',[indexBefore.id])).rows.every(r=>r.revision_id===indexAfter.revisionId));for(const row of(await db.query('select snapshot from wiki_memberships where page_id=$1',[indexBefore.id])).rows)assert.deepEqual(row.snapshot,indexAfter.automatic!.memberships.find(m=>m.id===row.snapshot.id));assert.equal(JSON.stringify((await db.query('select content from wiki_page_revisions where id=$1',[indexBefore.revisionId])).rows[0].content),indexHistory);
 const beforeSection=structuredClone(page.sections[0]);await wiki.save({version:2,id:page.id,expectedRevisionId:page.revisionId,content:{...WikiPageContentSchema.strip().parse(page),pinned:true},evidenceChunkIds:[]});let changed=(await wiki.get(page.id))!;assert.deepEqual(changed.sections[0],beforeSection,'Pin preserves exact provenance and assessment');const content=WikiPageContentSchema.strip().parse(changed);content.sections[0]!.markdown+=' Human qualification.';await wiki.save({version:2,id:changed.id,expectedRevisionId:changed.revisionId,content,evidenceChunkIds:[]});changed=(await wiki.get(page.id))!;assert.equal(changed.sections[0].protected,true);assert.equal(changed.sections[0].assessment.support,'unassessed');assert.notEqual(changed.sections[0].sectionRevisionId,beforeSection.sectionRevisionId);
 // Persisted proposals are guarded as one group: a conflict must allocate no subset.
 const conflict=(await start())!;const proposal=await fixtureCuratorProposal(conflict.snapshot);await runs.propose(conflict.id,proposal,conflict.checkpoint,false);await assert.rejects(repo.apply(conflict.id,true,validateCuratorProposal),/evidence/);const revisionCount=(await db.query('select count(*)::int n from wiki_page_revisions')).rows[0].n;await assert.rejects(repo.apply(conflict.id,false,validateCuratorProposal));assert.equal((await db.query('select count(*)::int n from wiki_page_revisions')).rows[0].n,revisionCount);await runs.reject(conflict.id);

 // Protected prose is one reviewable group; accepting it never certifies human evidence review.
 const reviewTemplate=(await start())!;const reviewId=await runs.create({...reviewTemplate.snapshot,inputFingerprint:'review-'+randomUUID(),groupId:randomUUID()},reviewTemplate.checkpoint);const reviewRun=(await service().get(reviewId))!,reviewProposal=await fixtureCuratorProposal(reviewRun.snapshot),base=reviewRun.snapshot.pages.find(p=>p.id===page.id)!;
 const patch={...reviewProposal.targets[0]!,pageId:base.id,expectedRevisionId:base.revisionId,title:base.title,purpose:base.automatic!.purpose,links:[],sections:[{...reviewProposal.targets[0]!.sections[0]!,sectionId:base.sections[0]!.id,expectedSectionRevisionId:base.sections[0]!.sectionRevisionId!}]};
 reviewProposal.targets=[patch,{...reviewProposal.targets[0]!,handle:'new_review_companion',title:'Companion reviewed group',purpose:'A separate explicit purpose',links:[]}];
 await runs.propose(reviewRun.id,reviewProposal,await certify(reviewRun,reviewProposal),false);const pageCount=(await wiki.list()).length;await assert.rejects(repo.apply(reviewRun.id,false,validateCuratorProposal),/review/);assert.equal((await wiki.list()).length,pageCount);await repo.apply(reviewRun.id,true,validateCuratorProposal);assert.equal((await wiki.get(base.id))!.sections[0].protected,true);assert.equal((await wiki.get(base.id))!.sections[0].assessment.humanReview,'unreviewed');
 // Known drafts are exploratory, never falsely human-reviewed. Exact source dependencies own freshness.
 const searchInput={text:'',sourceIds:inputs.sourceIds,includeDescendants:false,pageId:null,kind:'page',reviewedOnly:false,currentOnly:true,limit:100,offset:0};assert.ok((await wiki.search(searchInput)).items.some(r=>r.id===base.id));assert.ok(!(await wiki.search({...searchInput,reviewedOnly:true})).items.some(r=>r.id===base.id));
 const pending=async(label:string)=>{const template=(await start())!,pages=await repo.pages(inputs.sourceIds),snapshot={...template.snapshot,groupId:randomUUID(),inputFingerprint:label+randomUUID(),pages,references:[...template.snapshot.references.filter(r=>r.kind!=='page'),...pages.map(p=>({kind:'page' as const,id:p.id,title:p.title,fingerprint:p.revisionId,text:'',sourceIds:[...new Set(p.evidence.map(e=>e.sourceItemId))],chunkIds:p.evidence.map(e=>e.chunkId)}))]};const id=await runs.create(snapshot,{...template.checkpoint,proposal:null,calls:0,tools:3});const run=(await service().get(id))!,proposal=await fixtureCuratorProposal(run.snapshot);proposal.targets=[{...proposal.targets[0]!,title:label+' first',links:[]},{...proposal.targets[0]!,handle:'new_second',title:label+' second',links:[]}];await runs.propose(run.id,proposal,await certify(run,proposal),false);return run;};
 // Shared titles do not authorize reading unbound human prose or collapse distinct purposes.
 const distinct=await pending('Distinct purpose'),distinctRun=(await service().get(distinct.id))!,distinctProposal=distinctRun.proposal!;distinctProposal.targets[0]!.title=(await wiki.get(inputs.humanId))!.title;await db.query('update organization_proposals set proposal=$2 where run_id=$1',[distinct.id,distinctProposal]);await certify(distinctRun,distinctProposal);const humanRevision=(await wiki.get(inputs.humanId))!.revisionId;await repo.apply(distinct.id,false,validateCuratorProposal);assert.equal((await wiki.get(inputs.humanId))!.revisionId,humanRevision);
 // Exact admitted page revisions are checked even when the candidate has a valid support audit.
 const revisionConflict=await pending('Revision conflict'),revisionBase=(await wiki.get(page.id))!;await wiki.save({version:2,id:revisionBase.id,expectedRevisionId:revisionBase.revisionId,content:{...WikiPageContentSchema.strip().parse(revisionBase),pinned:!revisionBase.pinned},evidenceChunkIds:[]});const countAtConflict=(await wiki.list()).length;await assert.rejects(repo.apply(revisionConflict.id,false,validateCuratorProposal),/conflict/);assert.equal((await wiki.list()).length,countAtConflict);
 // The currently authorized hierarchy is recomputed under locks after reparenting.
 const hierarchyPolicy={...policy,id:randomUUID(),revisionId:randomUUID(),scope:{...policy.scope,sourceIds:[inputs.sources.get('book')!,inputs.sources.get('paper')!],includeDescendants:true}};await repo.draft(hierarchyPolicy,{},'hierarchy-preview');await repo.activate(hierarchyPolicy.id,hierarchyPolicy.revisionId,'hierarchy-preview');const hierarchyRun=(await service().start({policyId:hierarchyPolicy.id,policyRevisionId:hierarchyPolicy.revisionId,sourceIds:inputs.sourceIds,noteIds:inputs.noteIds}))!,hierarchyProposal=await fixtureCuratorProposal(hierarchyRun.snapshot);await runs.propose(hierarchyRun.id,hierarchyProposal,await certify(hierarchyRun,hierarchyProposal),false);await db.query('update source_items set parent_source_item_id=$2 where id=$1',[inputs.sources.get('B'),inputs.sources.get('C')]);await assert.rejects(repo.apply(hierarchyRun.id,true,validateCuratorProposal),/scope/);assert.equal((await wiki.list()).length,countAtConflict);await db.query('update source_items set parent_source_item_id=$2 where id=$1',[inputs.sources.get('B'),inputs.sources.get('paper')]);
 // Reference/evidence changes from another connection while apply is waiting invalidate the entire group.
 const concurrent=await pending('Concurrent'),writer=await db.connect();await writer.query('begin');await writer.query('update chunks set content_hash=$2 where id=$1',[inputs.chunks.get('A'),'changed-during-apply']);const countBefore=(await wiki.list()).length;const applying=repo.apply(concurrent.id,false,validateCuratorProposal).then(()=>({ok:true,error:''}),e=>({ok:false,error:String(e)}));let blocked=false;
 for(let i=0;i<100&&!blocked;i++){blocked=(await db.query("select exists(select 1 from pg_stat_activity where datname=current_database() and wait_event_type='Lock' and query like '%for share%') as waiting")).rows[0].waiting;if(!blocked)await new Promise(resolve=>setTimeout(resolve,5));}
 await writer.query('commit');writer.release();assert.ok(blocked,'Apply waits for the concurrently modified original row');const concurrentResult=await applying;assert.equal(concurrentResult.ok,false);assert.match(concurrentResult.error,/evidence/);assert.equal((await wiki.list()).length,countBefore);assert.equal((await wiki.get(base.id))!.evidence.find((e:any)=>e.chunkId===inputs.chunks.get('A'))!.excerpt,run.snapshot.evidence.find(e=>e.chunkId===inputs.chunks.get('A'))!.excerpt);await db.query('update chunks set content_hash=content where id=$1',[inputs.chunks.get('A')]);
 if(inputs.noteIds.length){const linked=await pending('Linked'),outside=inputs.sources.get('C')!,chunk=inputs.chunks.get('C')!;await db.query('insert into atomic_note_source_links(atomic_note_id,source_item_id,chunk_id) values($1,$2,$3)',[inputs.noteIds[0],outside,chunk]);await assert.rejects(repo.apply(linked.id,false,validateCuratorProposal),/scope|evidence/);await db.query('delete from atomic_note_source_links where atomic_note_id=$1 and chunk_id=$2',[inputs.noteIds[0],chunk]);}
 const unsupported=await pending('Unsupported');const stored=(await service().get(unsupported.id))!;await db.query("update organization_runs set checkpoint=jsonb_set(checkpoint,'{supportAssessment,proposalHash}',to_jsonb('wrong-proposal'::text)) where id=$1",[unsupported.id]);await assert.rejects(repo.apply(unsupported.id,true,validateCuratorProposal),/evidence/);await db.query('update organization_runs set checkpoint=$2 where id=$1',[unsupported.id,stored.checkpoint]);await db.query("update organization_steps set artifact=jsonb_set(artifact,'{support,checkedTargets}','[]'::jsonb) where run_id=$1 and artifact ? 'support'",[unsupported.id]);await assert.rejects(repo.apply(unsupported.id,true,validateCuratorProposal),/evidence/);
 const canceled=await pending('Canceled');await jobs.requestCancel(canceled.jobId!);await assert.rejects(repo.apply(canceled.id,false,validateCuratorProposal),/canceled/);
 const paused=await pending('Paused');await repo.pause(policy.id);await assert.rejects(repo.apply(paused.id,true,validateCuratorProposal),/policy/);await assert.rejects(start(),/policy/);
 assert.equal((await db.query('select count(*)::int n from source_summaries')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from atomic_notes')).rows[0].n,inputs.noteIds.length);assert.equal((await db.query('select count(*)::int n from entities')).rows[0].n,0);assert.ok((await db.query("select count(*)::int n from wiki_dependencies where section_id in(select id from wiki_toc_groups) and kind='source'")).rows[0].n>0);assert.equal((await db.query('select count(*)::int n from embeddings_1024')).rows[0].n,0);assert.equal((await db.query("select count(*)::int n from jobs where type<>'organization'")).rows[0].n,0);
 return {run,service,repo,runs,execute};}
 await exercise(pool,fixture);calls=0;await pool.query('create database automatic_wiki_empty');const url=new URL(connection.connectionString);url.pathname='/automatic_wiki_empty';empty=createPgPool({connectionString:url.toString(),max:8});assert.equal((await runMigrations(empty,migrationPath,{seedFolder})).seed.applied,true);assert.equal((await empty.query('select count(*)::int n from drizzle.__drizzle_migrations')).rows[0].n,journal.entries.length);await exercise(empty,await seedAutomaticWikiFixture(empty,false));console.log('A2 real PostgreSQL: populated history upgrade and empty baseline; A0 mixed material and change-set fixtures; selected existing notes and independent originals-only slice; coherent topic/source/topic TOCs, typed original lineage, idempotence, policy pause, all-or-nothing conflict, exact pin/edit protection, unknown costs and zero optional derivation calls passed. Synthetic model double only.');
}finally{if(empty)await closePgPool(empty);if(pool)await closePgPool(pool);await manager.stop();await rm(dir,{recursive:true,force:true});}
