import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createPgPool,closePgPool,PostgresSidecarManager,resolvePostgresSidecarPaths,runMigrations,createAiConfigRepository,createWikiCuratorRepository,createWikiCollectionRepository} from '../packages/db/src/index.js';
import {registerHooks} from 'node:module';
// This deterministic CLI gate replaces only Electron secure storage; no credentials are persisted.
const electronHook=registerHooks({resolve(specifier,context,next){return specifier==='electron'?{url:'data:text/javascript,export const safeStorage={};',shortCircuit:true}:next(specifier,context);}});
const {AiService}=await import('../apps/desktop/src/main/services/ai-service.js');electronHook.deregister();
import {WikiCollection} from '../apps/desktop/src/main/services/wiki-collection.js';
import {WikiCurator} from '../apps/desktop/src/main/services/wiki-curator.js';
import {AutomaticWikiPolicySchema,initialCuratorLimits} from '@app/domain';
import {defaultPromptPin} from '../apps/desktop/src/main/services/prompt-runtime.js';
import {seedAutomaticWikiFixture} from './fixtures/automatic-wiki-fixture.js';
import {providerParameterCapabilities} from '../packages/ai/src/parameter-capabilities.js';
const root=resolve(import.meta.dirname,'..'),dir=await mkdtemp(join(tmpdir(),'memora-ai-context-')),paths=resolvePostgresSidecarPaths({cwd:root,env:process.env}),manager=new PostgresSidecarManager({binDir:paths.binDir,dataDir:join(dir,'data'),database:'context',user:'context',password:randomUUID()});let pool;
try{const connection=await manager.start();pool=createPgPool({connectionString:connection.connectionString,max:4});await runMigrations(pool,join(root,'packages/db/drizzle'),{seedFolder:join(root,'packages/db/seed')});const db=pool,repository=createAiConfigRepository(db),make=()=>{const service=new AiService({userDataPath:dir,getPool:()=>db,workspaceRoot:root,resourcesPath:dir,isPackaged:false,getContentLanguage:async()=> 'en'});(service as any).credentials.save=async()=> 'synthetic-secret-ref';return service;};let calls=0;
for(const provider of ['google','openai-compatible','openai-codex'] as const){let service=make();(service as any).pendingOpenAiCodexCredential={access:'synthetic-not-a-real-token'};const input={provider,displayName:'Synthetic '+provider,modelId:'context-model',baseUrl:'https://synthetic.invalid',capabilities:['structured-output' as const],defaultParameters:{},apiKey:'synthetic-not-a-real-token'},model=await service.saveProvider(input),profile=await service.createProfile({name:'Context '+provider,isDefault:false,privacyMode:'allow_remote',outputLanguage:'ui'});await service.updateProfile({id:profile.id,providerConfigId:model.id,localModelId:null,modelId:model.modelId,runtime:'remote',capabilities:model.capabilities});await service.setProfileTask({profileId:profile.id,task:'structured-output',fallbackPolicy:'block',parameters:{}});await service.setTaskRoute({task:'structured-output',profileId:profile.id});
assert.equal((await service.pinOrganizationProfile(profile.id,'allow_remote')).contextWindow,128000);await service.saveProvider({...input,id:model.id,defaultParameters:{contextWindow:64000}});await service.setProfileTask({profileId:profile.id,task:'structured-output',fallbackPolicy:'block',parameters:{contextWindow:32000}});service=make();const pin=await service.pinOrganizationProfile(profile.id,'allow_remote');assert.equal(pin.contextWindow,32000);assert.equal((await service.listProviders()).find(m=>m.id===model.id)!.defaultParameters.contextWindow,64000);assert.equal((await service.listProfileTasks(profile.id))[0]!.parameters.contextWindow,32000);assert.equal(calls,provider==='google'?0:provider==='openai-compatible'?2:4);assert.equal((await db.query('select count(*)::int n from ai_task_runs')).rows[0].n,provider==='google'?0:provider==='openai-compatible'?2:4);
const requests:any[]=[],adapter={describe:()=>({providerId:provider,modelId:model.modelId,runtime:'remote',capabilities:model.capabilities,parameterCapabilities:providerParameterCapabilities({...input,capabilities:model.capabilities}),limits:{}}),canHandle:()=>true,listModels:async()=>[{modelId:model.modelId,limits:{contextWindow:16000}}],run:async(request:any)=>{calls++;requests.push(request);return{taskType:'structured-output',output:'{}',providerId:provider,modelId:model.modelId,runtime:'remote',durationMs:1};}};(service as any).createAdapter=async()=> (service as any).registerAdapter(adapter);
await service.setProfileTask({profileId:profile.id,task:'structured-output',fallbackPolicy:'block',parameters:{contextWindow:96000}});await service.runOrganizationTask(pin,'Synthetic short task',{},new AbortController().signal,2048);assert.equal(requests[0].parameters.contextWindow,32000);const old={...pin,contextWindow:null,parameters:{maxTokens:2048}},oldBefore=JSON.stringify(old);await service.runOrganizationTask(old,'Historical admitted task',{},new AbortController().signal,2048);assert.equal(JSON.stringify(old),oldBefore);assert.equal(requests[1].parameters.contextWindow,undefined);const audits=(await db.query('select parameters from ai_task_runs where profile_id=$1 order by started_at',[profile.id])).rows;assert.equal(audits[0].parameters.contextWindow,32000);assert.equal(audits[1].parameters.contextWindow,undefined);
if(provider==='google'){
const fixture=await seedAutomaticWikiFixture(db,false),sourceId=fixture.sources.get('A')!,policies=createWikiCuratorRepository(db),collections=createWikiCollectionRepository(db),policy=AutomaticWikiPolicySchema.parse({version:'automatic-wiki-v1',id:randomUUID(),revisionId:randomUUID(),state:'enabled',scope:{wholeLibrary:false,sourceIds:[sourceId],includeDescendants:false,excludedSourceIds:[],domainId:null},triggers:['processing_settled'],operations:['repair_navigation','create_grounded','update_unprotected','initial_placement'],profileOverrideId:profile.id,limits:initialCuratorLimits,allowancePreset:null});await policies.draft(policy,{},'historical-context');await policies.activate(policy.id,policy.revisionId,'historical-context');
const parentId=await collections.bootstrap({version:'wiki-bootstrap-v1',policy,profile:old,promptPin:defaultPromptPin(),sourceIds:[sourceId],noteIds:[],participation:null,contentLanguage:'en',admittedAt:new Date().toISOString()}),parentBefore=JSON.stringify((await collections.get(parentId))!.snapshot),options={getPool:()=>db,ai:service,contentLanguage:async()=> 'pt-BR',wake:()=>{},cancelJob:async()=>{}};await new WikiCollection(options).tick();const parent=(await collections.get(parentId))!;assert.equal(parent.checkpoint.state,'running');assert.ok(parent.checkpoint.childRunId);const child=(await new WikiCurator(options).get(parent.checkpoint.childRunId!))!;assert.equal(child.snapshot.profile.contextWindow,null);assert.equal(child.snapshot.profile.parameters.contextWindow,undefined);assert.equal(child.snapshot.contentLanguage,'en');assert.equal(JSON.stringify(parent.snapshot),parentBefore);assert.equal(calls,2);await new WikiCollection(options).command({command:'bootstrapCancel',id:parentId});
}
await service.listModels(model.id);const limited=make();await limited.listProviders();assert.equal(limited.getParameterCapabilities({...input,capabilities:model.capabilities}).contextWindow!.max,16000);assert.equal(limited.getParameterCapabilities({...input,modelId:"different-model",capabilities:model.capabilities}).contextWindow!.max,2000000);assert.equal(limited.getParameterCapabilities({...input,baseUrl:"https://other.invalid",capabilities:model.capabilities}).contextWindow!.max,2000000);assert.equal((await limited.pinOrganizationProfile(profile.id,'allow_remote')).contextWindow,16000);await limited.saveProvider({...input,id:model.id,defaultParameters:{contextWindow:12000}});assert.equal((await limited.listProviders()).find(m=>m.id===model.id)!.parameterCapabilities.contextWindow!.max,16000);await limited.saveProvider({...input,id:model.id,modelId:'different-model',defaultParameters:{}});assert.equal((await repository.listProviders()).find(m=>m.id===model.id)!.metadata.modelLimits,undefined);assert.equal((await limited.listProviders()).find(m=>m.id===model.id)!.defaultParameters.contextWindow,undefined);
}
assert.equal(calls,6);assert.equal((await db.query('select count(*)::int n from jobs')).rows[0].n,1);console.log('AI context PostgreSQL: three remote providers, empty defaults128000, model64000/task32000 precedence and reload, immutable old pins, effective audit parameters, discovered smaller capacity and identity-bound cache, no model calls on settings writes, legacy null-context bootstrap child retaining parameters/language after settings changes passed. Six deterministic adapter calls; no network/model runtime.');
}finally{if(pool)await closePgPool(pool);await manager.stop();await rm(dir,{recursive:true,force:true});}
