import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtemp,mkdir,readFile,writeFile,copyFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createPgPool,closePgPool,PostgresSidecarManager,resolvePostgresSidecarPaths,runMigrations,createWikiRepository,createWikiCuratorRepository,createWikiCollectionRepository,createOrganizationRepository,createAiConfigRepository,createAutomaticMaintenanceRepository,createInvestigationRepository,createKnowledgeConsultationRepository,createSourceItemRepository,createDocumentRepository,createChunkRepository,type PgPool} from '../packages/db/src/index.js';
import {ConsultationInputSchema,CuratorPreviewSchema,AutomaticWikiPolicySchema,WikiPageContentSchema,initialCuratorLimits,type OrganizationProfile} from '@app/domain';
import {ConsultationService} from '../apps/desktop/src/main/services/consultation-service.js';
import {InvestigationService} from '../apps/desktop/src/main/services/investigation-service.js';
import {WikiCurator} from '../apps/desktop/src/main/services/wiki-curator.js';
import {promptAudit,capturePromptPin} from '../apps/desktop/src/main/services/prompt-runtime.js';
const root=resolve(import.meta.dirname,'..'),dir=await mkdtemp(join(tmpdir(),'memora-wiki-a5-')),paths=resolvePostgresSidecarPaths({cwd:root,env:process.env}),migrationPath=join(root,'packages/db/drizzle'),seedFolder=join(root,'packages/db/seed');
const manager=new PostgresSidecarManager({binDir:paths.binDir,dataDir:join(dir,'data'),database:'wiki_a5',user:'wiki_a5',password:randomUUID()});let pool:PgPool|undefined,empty:PgPool|undefined;
async function exercise(db:PgPool){
 const sources=createSourceItemRepository(db),docs=createDocumentRepository(db),chunks=createChunkRepository(db),wiki=createWikiRepository(db),retrieval=createKnowledgeConsultationRepository(db),maintenance=createAutomaticMaintenanceRepository(db),investigations=createInvestigationRepository(db);
 async function source(title:string,text:string){const source=await sources.create({type:'GenericDocument',title}),document=await docs.create({sourceItemId:source.id,title,canonicalMarkdown:text,contentHash:text}),id=randomUUID(),span=randomUUID();await chunks.replaceDocumentChunks(document.id,source.id,[{id,sourceSpanId:span,chunkIndex:0,content:text,contentHash:text,span:{id:span,startOffset:0,endOffset:text.length}}]);return {source:source.id,document:document.id,chunk:id,text};}
 const a=await source('Study A','Retrieval learning with feedback improved delayed recall in experienced students.'),b=await source('Study B','Interleaving learning improved transfer in novices, with no retrieval manipulation.');
 let calls=0,meaningful=true,notifications=0;const profile:OrganizationProfile={profileId:randomUUID(),providerConfigId:null,localModelId:randomUUID(),provider:'synthetic',modelId:'fixture-a5',runtime:'test',revision:'1',privacy:'offline_only',parameters:{maxTokens:2048,contextWindow:128000},identityHash:'fixture-a5',contextWindow:128000};
 const ai={pinOrganizationProfile:async()=>profile,runConsultationEmbedding:async()=>null,runOrganizationTask:async(_p:any,prompt:string,context:any,signal:AbortSignal,_max:number,guard?:()=>Promise<void>)=>{await guard?.();signal.throwIfAborted();await context.onProviderStart?.();calls++;const originals=JSON.parse(prompt.split('\n').find(l=>l.startsWith('ORIGINALS: '))!.slice(11)),compiled=JSON.parse(prompt.split('\n').find(l=>l.startsWith('COMPILED KNOWLEDGE: '))!.slice(20));const output={paragraphs:[{markdown:originals.map((e:any)=>e.excerpt+' ['+e.handle+']').join('\n\n'),citations:originals.map((e:any)=>e.handle),contextIds:compiled.map((c:any)=>c.id)}],gaps:[],...(prompt.includes('explicitly followed question')?{change:{meaningful,explanation:meaningful?['The added original reports a failed replication.']:[]}}:{})};const aiTaskRunId=await createAiConfigRepository(db).recordTaskRun({...context,promptCompositions:promptAudit(prompt),taskType:'structured-output',provider:'synthetic',modelId:'fixture-a5',runtime:'test',durationMs:1,status:'succeeded',inputTokens:100,outputTokens:50});return{output,aiTaskRunId,inputTokens:100,outputTokens:50,providerId:'synthetic',modelId:'fixture-a5',runtime:'test',durationMs:1,taskType:'structured-output' as const};}};
 const options={getPool:()=>db,ai,contentLanguage:async()=> 'en',wake:()=>{},cancelJob:async()=>null},curator=new WikiCurator(options),consultation=new ConsultationService(options),follow=new InvestigationService({...options,consultation,notify:()=>notifications++});
 const preview=CuratorPreviewSchema.parse(await curator.command({command:'preview',input:{sourceIds:[],wholeLibrary:true,includeDescendants:false,excludedSourceIds:[],profileOverrideId:profile.profileId,limits:initialCuratorLimits,timezone:'UTC'}}));const policy=AutomaticWikiPolicySchema.parse(await curator.command({command:'activate',policyId:preview.policy.id,revisionId:preview.policy.revisionId,previewHash:preview.previewHash}));assert.ok(policy.operations.includes('refresh_investigation'));
 async function compiledPage(title:string,originals:typeof a[],generated=true){const id=randomUUID(),section=randomUUID(),revision=randomUUID(),content=WikiPageContentSchema.parse({title,kind:'topic',sections:[{id:section,sectionRevisionId:revision,title:'Findings',markdown:originals.map(s=>s.text).join(' '),provenance:'generated',protected:false,evidenceReview:generated?'needs_review':'verified',evidenceIds:originals.map(s=>s.chunk),assessment:{version:'automatic-wiki-v1',sectionId:section,sectionRevisionId:revision,humanReview:generated?'unreviewed':'verified',support:'validated',reason:generated?'generated_pending_verification':'human_verified',supportMethod:generated?'model_checked':'human_review',...(generated?{supportAuditId:randomUUID()}:{}),inputFingerprint:'fixture',freshness:'current'}}]});const tx=await db.connect();try{await tx.query('begin');await wiki.save({id,expectedRevisionId:null,content,evidenceChunkIds:originals.map(s=>s.chunk)},{transaction:tx,origin:'organization',allocatedTarget:true,humanApproved:false});await tx.query('commit');}finally{tx.release();}return(await wiki.get(id))!;}
 const topic=await compiledPage('Learning synthesis',[a,b]);
 assert.equal((await retrieval.compiled([a.source,b.source],'learning',null,false)).length,1,'Machine-checked fresh unreviewed sections participate');assert.equal((await retrieval.compiled([a.source,b.source],'learning',null,true)).length,0);assert.equal((await retrieval.compiled([a.source],'learning',null,false)).length,0,'Mixed source assertion stays excluded');
 const nested=await compiledPage('Private interpretation',[b]),wrapper=await compiledPage('Scoped wrapper',[a]);let parentFingerprint=(await db.query("select md5(s::text) fingerprint from wiki_page_revisions r cross join lateral jsonb_array_elements(r.content->'sections') s where r.id=$1",[nested.revisionId])).rows[0].fingerprint;await db.query("insert into wiki_dependencies(revision_id,section_id,kind,input_id,fingerprint,snapshot) values($1,$2,'wiki_section',$3,$4,'{}')",[wrapper.revisionId,wrapper.sections[0]!.id,nested.sections[0]!.id,parentFingerprint]);assert.ok(!(await retrieval.compiled([a.source],'Scoped wrapper',wrapper.id,false)).some(c=>c.context.pageId===wrapper.id),'Transitive excluded source cannot leak through an allowed wrapper');const expanded=(await retrieval.compiled([a.source,b.source],'Scoped wrapper',wrapper.id,false)).find(c=>c.context.pageId===wrapper.id)!;assert.ok(expanded.originals.some(e=>e.chunkId===b.chunk),'Every consumed transitive original expands with the compiled section');
 await wiki.save({version:2,id:nested.id,expectedRevisionId:nested.revisionId,content:WikiPageContentSchema.strip().parse({...nested,sections:nested.sections.map(s=>({...s,markdown:s.markdown+' Human interpretation.'}))}),evidenceChunkIds:[]});const edited=(await wiki.get(nested.id))!;parentFingerprint=(await db.query("select md5(s::text) fingerprint from wiki_page_revisions r cross join lateral jsonb_array_elements(r.content->'sections') s where r.id=$1",[edited.revisionId])).rows[0].fingerprint;await db.query("update wiki_dependencies set fingerprint=$3,stale_reason=null where revision_id=$1 and input_id=$2",[wrapper.revisionId,nested.sections[0]!.id,parentFingerprint]);assert.ok(!(await retrieval.compiled([a.source,b.source],'Scoped wrapper',wrapper.id,false)).some(c=>c.context.pageId===wrapper.id),'Already unassessed consumed prose is not laundered by a current fingerprint');
 const group=randomUUID(),indexId=randomUUID(),index=WikiPageContentSchema.parse({title:'Reading learning studies',kind:'collection',automatic:{version:'automatic-wiki-v1',management:'ai_managed',role:{kind:'collection',role:'topic_toc',owner:{kind:'page',id:topic.id}},purpose:'Read the studies',placementProtected:false,links:[],groups:[{version:'automatic-wiki-v1',id:group,collectionId:indexId,title:'Studies',explanation:null,explanationEvidenceIds:[],membershipIds:[],orderProtected:false,origin:'generated'}],memberships:[]}});const client=await db.connect();try{await client.query('begin');await wiki.save({id:indexId,expectedRevisionId:null,content:index,evidenceChunkIds:[]},{transaction:client,origin:'organization',allocatedTarget:true,humanApproved:false});await client.query("update wiki_pages set toc_owner_kind='page',toc_owner_id=$2 where id=$1",[indexId,topic.id]);await client.query('commit');}finally{client.release();}
 assert.deepEqual(await retrieval.scope({sourceIds:[],includeDescendants:false,pageId:indexId}),[a.source,b.source].sort(),'Collection scope resolves its canonical owner');
 assert.ok((await retrieval.compiled([a.source,b.source],'What have we learned?',indexId,false)).some(c=>c.context.pageId===topic.id),'Generic questions enter compiled knowledge through TOC owner');
 const outside=await source('Excluded high ranking learning','learning learning learning learning');for(let i=0;i<65;i++)await compiledPage('learning',[outside]);assert.ok((await retrieval.compiled([a.source,b.source],'learning',null,false)).some(c=>c.context.pageId===topic.id),'Excluded pages cannot crowd out the permitted page');
 const distracting:typeof a[]=[];for(let i=0;i<15;i++)distracting.push(await source('Learning synthesis','Learning synthesis Learning synthesis background unrelated result '+i));
 const answer=await consultation.ask(ConsultationInputSchema.parse({version:'knowledge-consultation-v2',requestId:randomUUID(),question:'Learning synthesis',sourceIds:[a.source,b.source,...distracting.map(s=>s.source)]}));assert.ok(answer.contexts.some(c=>c.pageId===topic.id));assert.ok(answer.evidence.some(e=>e.chunkId===a.chunk)&&answer.evidence.some(e=>e.chunkId===b.chunk));assert.ok(answer.evidence.length<=12);assert.equal(calls,1);assert.equal((await investigations.list()).length,0);assert.equal((await db.query('select count(*)::int n from organization_runs')).rows[0].n,0,'Ask persists no run/page/investigation');
 const saved=await Promise.all([consultation.save(answer.id),consultation.save(answer.id)]);assert.equal(saved[0]!.id,saved[1]!.id);assert.equal(calls,1);
 await db.query("insert into source_items(id,type,title) select ('00000000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid,'GenericDocument','Metadata only archive '||n from generate_series(1,505) n");
 assert.ok((await retrieval.scope({sourceIds:[],includeDescendants:false,pageId:null})).length>500);assert.deepEqual(await retrieval.scope({sourceIds:[],includeDescendants:false,pageId:indexId}),[a.source,b.source].sort(),'Page scope remains reachable beyond the former 501 source ceiling');
 // A broad follow may receive future sources, bounded by the parent policy. Use a question with exact relevance.
 const broad=await consultation.ask(ConsultationInputSchema.parse({version:'knowledge-consultation-v2',requestId:randomUUID(),question:'delayed recall transfer novices'}));const pair=await Promise.all([follow.follow({answerId:broad.id,policyId:policy.id}),follow.follow({answerId:broad.id,policyId:policy.id})]);const item=pair[0]!;assert.equal(item.id,pair[1]!.id);assert.equal(calls,2);assert.equal((await wiki.get(item.answerPageId))!.automatic!.role.role,'investigation');assert.equal((await investigations.list()).length,1);
 const schedule=(await maintenance.schedules(policy.id)).find(s=>s.policy.kind==='daily')!,occurrence=(await maintenance.admit([schedule],new Date(),true,randomUUID(),{profile,promptPin:capturePromptPin(),contentLanguage:'en'}))!;occurrence.status='inspecting';occurrence.checkpoint.startedAt=new Date().toISOString();await maintenance.checkpoint(occurrence);
 await follow.tick(occurrence);assert.equal(calls,2,'Unchanged inspection has zero calls');const before=await investigations.get(item.id);const irrelevant=await source('Botany','Seed germination under artificial illumination.');await follow.tick(occurrence);assert.equal(calls,2,'Irrelevant new source has zero calls');
 const c=await source('Study C','A preregistered replication of retrieval learning with feedback found no improvement in delayed recall in experienced students.');await follow.tick(occurrence);assert.equal(calls,3,'Relevant new evidence refreshes once');assert.equal(notifications,1,JSON.stringify((await investigations.get(item.id))?.history));const changed=(await investigations.get(item.id))!;assert.equal(changed.history.length,2);assert.ok(changed.current.evidence.some(e=>e.chunkId===c.chunk));assert.ok(changed.history.some(h=>h.previous?.id===before!.current.id));assert.equal((await maintenance.monthly(policy.id,new Date().toISOString().slice(0,7))).calls,1);await follow.tick(occurrence);assert.equal(calls,3);assert.equal((await createWikiCollectionRepository(db).dependents('chunk',a.chunk,null)).some(p=>p.id===item.answerPageId),false,'Curator does not own followed answers');
 // Equivalent replacement refreshes current evidence/history, but never announces changed understanding.
 meaningful=false;const replacement=await docs.create({sourceItemId:c.source,title:'Study C',canonicalMarkdown:c.text,contentHash:c.text}),replacementChunk=randomUUID(),replacementSpan=randomUUID();await db.query("update documents set metadata=metadata||jsonb_build_object('supersededByDocumentId',$2::text) where id=$1",[c.document,replacement.id]);await chunks.replaceDocumentChunks(replacement.id,c.source,[{id:replacementChunk,sourceSpanId:replacementSpan,chunkIndex:0,content:c.text,contentHash:c.text,span:{id:replacementSpan,startOffset:0,endOffset:c.text.length}}]);await follow.tick(occurrence);assert.equal(calls,4);assert.equal(notifications,1);const equivalent=(await investigations.get(item.id))!;assert.equal(equivalent.history[0]!.status,'no_change');assert.ok(equivalent.current.evidence.some(e=>e.chunkId===replacementChunk));assert.ok(!equivalent.current.evidence.some(e=>e.chunkId===c.chunk));assert.ok((await wiki.get(item.answerPageId))!.evidence.some(e=>e.chunkId===replacementChunk&&e.current));assert.equal((await wiki.history(item.answerPageId)).length,3);meaningful=true;
 const restarted=new InvestigationService({...options,consultation:new ConsultationService(options)});assert.equal((await restarted.list()).length,1);await restarted.tick(occurrence);assert.equal(calls,4);const paused=await restarted.state({id:item.id,expectedRevision:equivalent.revision,state:'paused'});await source('Study D','Delayed recall deteriorated after sleep deprivation.');await restarted.tick(occurrence);assert.equal(calls,4);assert.equal(paused!.state,'paused');
 const high=await investigations.highWater(item.id);await source('Study E','Transfer to novices showed no improvement in learning.');await investigations.acknowledge(item.id,{kind:'test_inspection'},high);assert.ok((await investigations.highWater(item.id)).length>0,'Captured high-water does not swallow later deliveries');
 const isolated=await source('Magenta observatory','Magenta observations found a violet nebula.'),oneOff=await consultation.ask(ConsultationInputSchema.parse({version:'knowledge-consultation-v2',requestId:randomUUID(),question:'Magenta observations',sourceIds:[isolated.source]})),tracked=(await follow.follow({answerId:oneOff.id,policyId:policy.id}))!;const noEvidenceCalls=calls;await db.query("update documents set metadata=metadata||jsonb_build_object('supersededByDocumentId',$2::text) where id=$1",[isolated.document,randomUUID()]);await restarted.tick(occurrence);assert.equal(calls,noEvidenceCalls);const missing=(await investigations.get(tracked.id))!;assert.equal(missing.state,'awaiting_evidence');assert.equal(missing.attention,'consultation.errors.noRelevantEvidence');assert.equal(missing.current.coverage.stale,true);assert.ok(missing.history.some(h=>h.status==='awaiting_evidence'));await restarted.tick(occurrence);assert.equal(calls,noEvidenceCalls);

 const cobalt=await source('Cobalt observatory','Cobalt observations found no meteor shower.'),cobaltAnswer=await consultation.ask(ConsultationInputSchema.parse({version:'knowledge-consultation-v2',requestId:randomUUID(),question:'Cobalt observations',sourceIds:[cobalt.source],includeDescendants:true})),cobaltFollow=(await follow.follow({answerId:cobaltAnswer.id,policyId:policy.id}))!;
 const cobaltNew=await docs.create({sourceItemId:cobalt.source,title:'Cobalt observatory',canonicalMarkdown:'Cobalt observations now found a meteor shower.',contentHash:'cobalt-new'}),cobaltChunk=randomUUID(),cobaltSpan=randomUUID();await db.query("update documents set metadata=metadata||jsonb_build_object('supersededByDocumentId',$2::text) where id=$1",[cobalt.document,cobaltNew.id]);await chunks.replaceDocumentChunks(cobaltNew.id,cobalt.source,[{id:cobaltChunk,sourceSpanId:cobaltSpan,chunkIndex:0,content:'Cobalt observations now found a meteor shower.',contentHash:'cobalt-new',span:{id:cobaltSpan,startOffset:0,endOffset:43}}]);
 const spent=(await maintenance.get(occurrence.id))!.reservation,budgetCalls=calls;await db.query("update maintenance_runs set snapshot=jsonb_set(snapshot,'{policy,allowance,calls}',to_jsonb($2::int)) where id=$1",[occurrence.id,spent.calls]);await follow.tick(occurrence);assert.equal(calls,budgetCalls);const deferred=(await investigations.get(cobaltFollow.id))!;assert.equal(deferred.history[0]!.status,'deferred');assert.equal(deferred.attention,'maintenance.errors.budget');assert.deepEqual((await maintenance.get(occurrence.id))!.reservation,spent);
 await maintenance.cancel(occurrence.id);const next=(await maintenance.admit([schedule],new Date(),true,randomUUID(),{profile,promptPin:capturePromptPin(),contentLanguage:'en'}))!;next.status='inspecting';next.checkpoint.startedAt=new Date().toISOString();await maintenance.checkpoint(next);await follow.tick(next);assert.equal(calls,budgetCalls+1,'A never-started budget deferral resumes in the next eligible occurrence');const resumed=(await investigations.get(cobaltFollow.id))!;assert.equal(resumed.attention,null);assert.equal(resumed.history[0]!.status,'changed');assert.equal(resumed.history[0]!.runId,deferred.history[0]!.runId);assert.deepEqual((await maintenance.get(occurrence.id))!.reservation,spent);assert.equal((await maintenance.get(next.id))!.reservation.calls,1);await follow.tick(next);assert.equal(calls,budgetCalls+1);
 const child=await sources.create({type:'GenericDocument',title:'Cobalt child observation',parentSourceItemId:cobalt.source});assert.equal((await db.query("select count(*)::int n from knowledge_impact_deliveries d join knowledge_impact_events e on e.id=d.event_id where d.consumer='investigation' and d.consumer_key=$1 and e.kind='source' and e.input_id=$2",[cobaltFollow.id,child.id])).rows[0].n,1,'New descendants enroll their followed consumer in the source transaction');

 // A provider-start crash retains its reservation and settles both persistent owners on startup.
 const uncertainItem=(await investigations.get(cobaltFollow.id))!,uncertainPrepared=await consultation.prepare(ConsultationInputSchema.parse({...uncertainItem.input,requestId:randomUUID()}),new AbortController().signal,{profile,language:'en'});const uncertainRun=await investigations.begin(uncertainItem.id,uncertainItem.revision,'uncertain-fixture','uncertain-composition',uncertainPrepared.snapshot,next.id);await maintenance.reserve(next.id,uncertainRun.run_id,1,1000);await investigations.pendingCall(uncertainRun.run_id,1,true);const reservations=(await maintenance.get(next.id))!.reservation,callsAtCrash=calls,recovering=new InvestigationService({...options,consultation});await recovering.initialize();assert.equal((await investigations.get(uncertainItem.id))!.history[0]!.status,'uncertain');assert.equal((await createOrganizationRepository(db).get(uncertainRun.run_id))!.status,'failed');await recovering.tick(next);assert.equal(calls,callsAtCrash);assert.deepEqual((await maintenance.get(next.id))!.reservation,reservations);recovering.shutdown();
 const amber=await source('Amber observatory','Amber observations found no comet.');let racedId:string|null=null;let racing:InvestigationService;const raceAi={...ai,runOrganizationTask:async(...args:Parameters<typeof ai.runOrganizationTask>)=>{const result=await ai.runOrganizationTask(...args);if(racedId){const current=(await investigations.get(racedId))!;await racing.state({id:racedId,expectedRevision:current.revision,state:'paused'});}return result;}};const raceConsultation=new ConsultationService({...options,ai:raceAi});racing=new InvestigationService({...options,consultation:raceConsultation});const amberAnswer=await raceConsultation.ask(ConsultationInputSchema.parse({version:'knowledge-consultation-v2',requestId:randomUUID(),question:'Amber observations',sourceIds:[amber.source]}));const amberFollow=(await racing.follow({answerId:amberAnswer.id,policyId:policy.id}))!;racedId=amberFollow.id;const amberRevision=(await wiki.get(amberFollow.answerPageId))!.revisionId,newAmber=await docs.create({sourceItemId:amber.source,title:'Amber observatory',canonicalMarkdown:'Amber observations found a comet.',contentHash:'amber-new'}),amberChunk=randomUUID(),amberSpan=randomUUID();await db.query("update documents set metadata=metadata||jsonb_build_object('supersededByDocumentId',$2::text) where id=$1",[amber.document,newAmber.id]);await chunks.replaceDocumentChunks(newAmber.id,amber.source,[{id:amberChunk,sourceSpanId:amberSpan,chunkIndex:0,content:'Amber observations found a comet.',contentHash:'amber-new',span:{id:amberSpan,startOffset:0,endOffset:32}}]);const callsBeforePause=calls;await racing.tick(next);assert.equal(calls,callsBeforePause+1);assert.equal((await investigations.get(amberFollow.id))!.state,'paused');assert.equal((await wiki.get(amberFollow.answerPageId))!.revisionId,amberRevision,'A pause after inference revokes canonical apply');await racing.tick(next);assert.equal(calls,callsBeforePause+1);racing.shutdown();
 await db.query("update wiki_investigations set state='followed',attention=null where id=$1",[amberFollow.id]);const tiny=structuredClone(next);tiny.snapshot.profile={...profile,contextWindow:128};const beforePreflight=calls;await follow.tick(tiny);assert.equal(calls,beforePreflight);assert.equal((await investigations.get(amberFollow.id))!.attention,'organization.errors.context','Preflight failures persist actionable attention without inference');
 assert.equal((await db.query('select count(*)::int n from source_summaries')).rows[0].n,0);assert.equal((await db.query('select count(*)::int n from atomic_notes')).rows[0].n,0);follow.shutdown();restarted.shutdown();console.log('A5 PostgreSQL: knowledge-first, TOC scope, 65 excluded candidates, transient ask, save/follow races, current exact originals, shared maintenance reservations, changed/unchanged/irrelevant/pause/restart/high-water, >500-source scope, transitive eligibility, evidence-only revisions, no-evidence receipts, next-occurrence budget resume, descendant enrollment, uncertain recovery and pause/apply race passed.');
}
try{const connection=await manager.start();pool=createPgPool({connectionString:connection.connectionString,max:8});const journal=JSON.parse(await readFile(join(migrationPath,'meta/_journal.json'),'utf8')),prior=journal.entries.filter((e:{idx:number})=>e.idx<37),old=join(dir,'old');await mkdir(join(old,'meta'),{recursive:true});await writeFile(join(old,'meta/_journal.json'),JSON.stringify({...journal,entries:prior}));for(const e of prior)await copyFile(join(migrationPath,e.tag+'.sql'),join(old,e.tag+'.sql'));await runMigrations(pool,old);const oldPage=await createWikiRepository(pool).save({expectedRevisionId:null,content:WikiPageContentSchema.parse({title:'Retained pre-A5 human page',kind:'topic',sections:[{id:randomUUID(),title:'Interpretation',markdown:'Personal interpretation stays unchanged.'}]}),evidenceChunkIds:[]}),before=await createWikiRepository(pool).get(oldPage);await runMigrations(pool,migrationPath,{seedFolder});assert.deepEqual(await createWikiRepository(pool).get(oldPage),before);assert.equal((await pool.query('select count(*)::int n from wiki_investigations')).rows[0].n,0);await exercise(pool);await pool.query('create database wiki_a5_empty');const url=new URL(connection.connectionString);url.pathname='/wiki_a5_empty';empty=createPgPool({connectionString:url.toString(),max:8});assert.equal((await runMigrations(empty,migrationPath,{seedFolder})).seed.applied,true);await exercise(empty);}finally{if(empty)await closePgPool(empty);if(pool)await closePgPool(pool);await manager.stop();await rm(dir,{recursive:true,force:true});}
