import {ObsidianOperationQueue} from '../apps/obsidian-plugin/src/operation-queue.js';
import {applyQueuedReceipt} from '../apps/obsidian-plugin/src/projection-delivery.js';
import { HierarchicalIngestionService } from '../apps/desktop/src/main/services/hierarchical-ingestion-service.js';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtemp, mkdir, readFile, writeFile, copyFile, rm, rename } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { createPgPool, createBibliographicRepository, createIntegrationClientRepository, closePgPool, PostgresSidecarManager, resolvePostgresSidecarPaths, runMigrations, createSourceItemRepository, createDocumentRepository, createChunkRepository, createAtomicNoteRepository, createWikiRepository, createJobRepository, createObsidianSyncRepository, type PgPool } from '../packages/db/src/index.js';
import { WikiPageContentSchema, ProcessingPlanRequestSchema } from '@app/domain';
import { parseObsidianMarkdown, type ObsidianEditOperation } from '@app/integration-contracts';
import { sha256 } from '@app/conversion';
import { ObsidianSyncService } from '../apps/desktop/src/main/services/obsidian-sync-service.js';
import { runObsidianSync } from '../apps/desktop/src/main/workers/obsidian-sync.worker.js';
const root = resolve(import.meta.dirname, '..'), work = await mkdtemp(join(tmpdir(), 'memora-m5-')), migrations = join(root, 'packages/db/drizzle'), seedFolder = join(root, 'packages/db/seed');
const paths = resolvePostgresSidecarPaths({ cwd: root, env: process.env }), manager = new PostgresSidecarManager({ binDir: paths.binDir, dataDir: join(work, 'data'), database: 'editorial', user: 'test', password: randomUUID(), startupTimeoutMs: 30000, shutdownTimeoutMs: 10000 });
let pool: PgPool | undefined, empty: PgPool | undefined;
try {
    const connection = await manager.start();
    pool = createPgPool({ connectionString: connection.connectionString, max: 8 });
    const journal = JSON.parse(await readFile(join(migrations, 'meta/_journal.json'), 'utf8')), prior = journal.entries.filter((e: {
        idx: number;
    }) => e.idx < 29), old = join(work, 'old');
    await mkdir(join(old, 'meta'), { recursive: true });
    await writeFile(join(old, 'meta/_journal.json'), JSON.stringify({ ...journal, entries: prior }));
    for (const entry of prior)
        await copyFile(join(migrations, entry.tag + '.sql'), join(old, entry.tag + '.sql'));
    await runMigrations(pool, old);
    const sources = createSourceItemRepository(pool), documents = createDocumentRepository(pool), notes = createAtomicNoteRepository(pool), wiki = createWikiRepository(pool);
    const catalog = await sources.create({ type: 'Book', title: 'Catalog intro' });
    const parent = await sources.create({ type: 'Book', title: 'Parent' }), child = await sources.create({ type: 'BookChapter', title: 'Child', parentSourceItemId: parent.id });
    const bibliography=createBibliographicRepository(pool),workRecord=await bibliography.createWork({type:'book',title:'Preserved catalog title',creators:[{name:'Catalog Author',role:'author'}],identifiers:{isbn13:'9780000000000'}}),instanceId=await bibliography.createInstance({workId:workRecord.id,type:'edition',publisher:'Preserved publisher',pageCount:321});
    await bibliography.linkSource({sourceItemId:parent.id,workId:workRecord.id,instanceId});await bibliography.linkSource({sourceItemId:child.id,workId:workRecord.id,instanceId,pages:'11-14'});
    const catalogBefore=(await pool.query('select * from bibliographic_works where id=$1',[workRecord.id])).rows[0];
    const makeDocument = async (source: typeof parent, body: string) => { const doc = await documents.create({ sourceItemId: source.id, title: source.title, canonicalMarkdown: body, contentHash: sha256(body) }); const id = randomUUID(), spanId = randomUUID(); await createChunkRepository(pool!).replaceDocumentChunks(doc.id, source.id, [{ id, sourceSpanId: spanId, chunkIndex: 0, content: body, contentHash: sha256(body), span: { id: spanId, startOffset: 0, endOffset: body.length } }]); return { doc, chunk: id }; };
    const p = await makeDocument(parent, 'Parent intro.  \n\n    code\n'), c = await makeDocument(child, 'Child original.  \nNext line.\n');
    const noteInput = { sourceItemId: child.id, title: 'Note', bodyMarkdown: '    indented code\nFinal hard break  \n', ideaStatement: 'One idea', evidenceChunkId: c.chunk, evidenceLinks: [{ chunkId: c.chunk }], generationProvider: 'fixture', generationModel: 'fixture', generationRuntime: 'fixture', generationPromptVersion: 'fixture', generationKey: 'fixture' };
    const note = await notes.upsertGenerated(noteInput);
    await pool.query("insert into atomic_note_review_events(atomic_note_id,action,previous_status,next_status,metadata) values($1,'edit','pending_review','pending_review','{}')", [note.id]);
    await runMigrations(pool, migrations, { seedFolder });
    assert.equal((await notes.findById(note.id))!.metadata.humanProtected, true);
    assert.equal((await pool.query('select count(*)::int as n from drizzle.__drizzle_migrations')).rows[0].n, 30);
    assert.equal((await pool.query("select count(*)::int as n from pg_indexes where tablename='obsidian_editorial_operations'")).rows[0].n, 2);
    const vault = join(work, 'vault');
    await mkdir(vault);
    let settings = { obsidianVaultPath: vault, managedRoot: 'Memora', obsidianSyncEnabled: true, obsidianSyncPaused: false, deletionPolicy: 'delete' as const, uploadCopiesEnabled: false, uploadCopiesFolderPath: null, updatedAt: new Date().toISOString() };
    const service = new ObsidianSyncService({ getPool: () => pool!, getStorageSettings: async () => settings, writeProjection: async (input) => ({ mtimeMs: Number((await runObsidianSync({ action: 'write', ...input })).mtimeMs) }) });
    const content = WikiPageContentSchema.parse({ title: 'Parent wiki', kind: 'topic', sections: [{ id: randomUUID(), title: 'Same', markdown: 'Identical body', evidenceIds: [c.chunk] }, { id: randomUUID(), title: 'Same', markdown: 'Identical body', evidenceIds: [] }] });
    const pageId = await wiki.save({ expectedRevisionId: null, content, evidenceChunkIds: [c.chunk] });
    await wiki.save({ expectedRevisionId: null, content: WikiPageContentSchema.parse({ title: 'Child wiki', kind: 'topic', parentId: pageId }), evidenceChunkIds: [] });
    const project = async () => { const jobId = (await service.wiki.enqueue(true))!, jobs = createJobRepository(pool!), job = (await jobs.findById(jobId))!; await jobs.update(jobId, { status: 'running' }); const result = await service.wiki.execute(job); await jobs.update(jobId, { status: 'succeeded', result }); return result; };
    await project();
    const clientId = (await createIntegrationClientRepository(pool).create({ clientType: 'obsidian-plugin', displayName: 'Synthetic M5', tokenHash: sha256(randomUUID()), scopes: ['obsidian-editorial-v1'], capabilities: ['obsidian-editorial-v1'], contractVersion: '1.0.0' })).id, vaultId = randomUUID();
    const manifest = async () => { const files = []; let cursor: number | null = 0; while (cursor !== null) {
        const result = await service.editorial.manifest(clientId, vaultId, cursor);
        files.push(...result.files);
        cursor = result.cursor;
    } return files; };
    const operation = async (id: string, change: (text: string) => string): Promise<ObsidianEditOperation> => { const file = (await manifest()).find(f => f.targetId === id)!; assert.ok(file, 'manifest target ' + id); return { version: 1, operationId: randomUUID(), vaultId, clientId: undefined, binding: (await service.editorial.bind(clientId, vaultId)).binding, targetId: id, targetType: file.targetType, kind: 'edit', relativePath: file.relativePath, baseRevision: file.revision, baseVersion: file.syncVersion, baseHash: file.contentHash, content: change(file.content), occurredAt: new Date().toISOString() } as ObsidianEditOperation; };
    const clean = (op: ObsidianEditOperation) => { delete (op as unknown as {
        clientId?: unknown;
    }).clientId; return op; };
    const apply = async (op: ObsidianEditOperation) => { clean(op); await writeFile(join(vault, op.relativePath), op.content); return service.editorial.apply(clientId, op); };
    const ack = async (receipt: Awaited<ReturnType<typeof apply>>, path: string) => { await writeFile(join(vault, path), receipt.content); await service.editorial.acknowledge(clientId, receipt.operationId, vaultId); };
    const edit = await operation(pageId, text => text.replace('Identical body', 'Human body.  \nA line.'));
    const first = await apply(edit);
    assert.equal(first.status, 'synced');
    assert.deepEqual(await service.editorial.apply(clientId, edit), first);
    await ack(first, edit.relativePath);
    const page = await wiki.get(pageId);
    assert.equal(page!.sections[0].markdown, 'Human body.  \nA line.');
    assert.equal(page!.sections[0].provenance, 'personal');
    assert.equal(page!.sections[0].evidenceReview, 'needs_review');
    assert.equal(page!.sections[1].markdown, 'Identical body');
    const sourceEdit = await operation(parent.id, text => text.replace('Parent intro.', 'Changed parent intro.'));
    const saved = await apply(sourceEdit);
    assert.equal(saved.status, 'synced');
    await ack(saved, sourceEdit.relativePath);const savedFrame=parseObsidianMarkdown(saved.content)!.frontmatter;assert.equal((await pool.query('select document_id from document_revisions where id=$1',[savedFrame.memoraDocumentRevisionId])).rows[0].document_id,savedFrame.memoraDocumentId);
    assert.equal((await documents.findById(p.doc.id))!.canonicalMarkdown, p.doc.canonicalMarkdown);
    assert.equal((await documents.listBySourceItem(parent.id))[0]!.canonicalMarkdown, 'Changed parent intro.  \n\n    code\n');
    assert.equal((await documents.findById(c.doc.id))!.canonicalMarkdown, c.doc.canonicalMarkdown);
    assert.equal((await pool.query("select count(*)::int as n from jobs where type='ingestion'")).rows[0].n, 0);
    const noteEdit = await operation(note.id, text => text.replace('Final hard break', 'Edited hard break'));
    const noteReceipt = await apply(noteEdit);
    assert.equal(noteReceipt.status, 'synced');
    await ack(noteReceipt, noteEdit.relativePath);
    assert.equal((await notes.findById(note.id))!.bodyMarkdown, '    indented code\nEdited hard break  \n');
    assert.equal((await notes.findById(note.id))!.status, 'pending_review');
    assert.equal((await pool.query('select count(*)::int as n from atomic_note_revisions where note_id=$1', [note.id])).rows[0].n, 1);
    await notes.upsertGenerated({ ...noteInput, title: 'Forbidden replacement', bodyMarkdown: 'Overwrite', evidenceLinks: [{ chunkId: p.chunk }] });
    assert.equal((await notes.findById(note.id))!.title, 'Note');
    assert.equal((await pool.query('select count(*)::int as n from atomic_note_source_links where atomic_note_id=$1', [note.id])).rows[0].n, 1);
    const concurrent = await operation(pageId, text => text.replace('Human body.', 'Local body.'));
    const current = await wiki.get(pageId);
    await wiki.save({ id: pageId, expectedRevisionId: current!.revisionId, content: { ...WikiPageContentSchema.strip().parse(current), sections: current!.sections.map((s: any, i: number) => i === 0 ? { ...s, markdown: 'App body' } : s) } as any, evidenceChunkIds: [] });
    const conflict = await apply(concurrent);
    assert.equal(conflict.status, 'conflict');
    assert.ok(conflict.comparison!.base.includes('Human body.'));
    assert.ok(conflict.comparison!.app.includes('App body'));
    assert.ok(conflict.comparison!.local.includes('Local body.'));
    const latestLocal = concurrent.content.replace('Local body.', 'Local body. Saved again before comparison.');
    await writeFile(join(vault, concurrent.relativePath), latestLocal);
    const freshComparison = await service.editorial.compareDesktop(concurrent.operationId);
    assert.equal(freshComparison.comparison!.local, latestLocal);
    await assert.rejects(service.editorial.resolveDesktop({ id: concurrent.operationId, choice: 'local', content: '', expectedLocal: concurrent.content, currentRevision: freshComparison.revision }));
    const independentConflict = { ...concurrent, operationId: randomUUID() };
    assert.equal((await service.editorial.apply(clientId, independentConflict)).status, 'conflict');
    const foreignTargetAttempt = clean(await operation(note.id, text => text));
    foreignTargetAttempt.resolution = { operationId: concurrent.operationId, currentRevision: freshComparison.revision, choice: 'manual' };
    assert.equal((await service.editorial.apply(clientId, foreignTargetAttempt)).status, 'conflict');
    const familyQueue = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => {});
    await familyQueue.enqueue(concurrent);
    await familyQueue.flush(op => service.editorial.apply(clientId, op), async () => false, async () => {});
    await familyQueue.resolve(concurrent.operationId, { ...concurrent, operationId: randomUUID(), content: latestLocal.replace('<!-- memora:generated:start -->', '<!-- invalid generated -->'), resolution: { operationId: concurrent.operationId, currentRevision: freshComparison.revision, choice: 'manual', observedLocal: latestLocal } }, latestLocal);
    await familyQueue.flush(op => service.editorial.apply(clientId, op), async () => false, async () => {});
    assert.equal(familyQueue.state.operations[0]!.receipt!.status, 'conflict');
    await assert.rejects(service.editorial.resolveDesktop({ id: concurrent.operationId, choice: 'manual', content: latestLocal.replace('memora_managed: true', 'memora_managed: false'), expectedLocal: latestLocal, currentRevision: freshComparison.revision }));
    const failedAttempts = (await pool.query("select id,request,receipt from obsidian_editorial_operations where request->'resolution'->>'operationId'=$1 and target_id=$2 and receipt->>'status'='conflict'", [concurrent.operationId, pageId])).rows;
    assert.equal(failedAttempts.length, 2);
    const pendingBefore = await service.editorial.conflicts();
    for (const id of [concurrent.operationId, independentConflict.operationId, ...failedAttempts.map(row => row.id)]) assert.ok(pendingBefore.some(row => row.id === id));
    const resolved = await service.editorial.resolveDesktop({ id: concurrent.operationId, choice: 'local', content: '', expectedLocal: latestLocal, currentRevision: freshComparison.revision });
    assert.equal(resolved.status, 'synced');
    assert.ok((await wiki.get(pageId))!.sections[0].markdown.includes('Saved again before comparison.'));
    assert.equal(await readFile(join(vault, concurrent.relativePath), 'utf8'), resolved.content);
    const resolvedManifest = await service.editorial.manifest(clientId, vaultId);
    const resolvedFamily = resolvedManifest.resolutions.find(row => row.originalOperationId === concurrent.operationId)!;
    assert.equal(resolvedFamily.operation.resolution!.observedLocal, latestLocal);
    assert.deepEqual(new Set(resolvedFamily.supersededOperationIds), new Set([concurrent.operationId, ...failedAttempts.map(row => row.id)]));
    const pendingAfter = await service.editorial.conflicts();
    for (const id of [concurrent.operationId, ...failedAttempts.map(row => row.id)]) assert.ok(!pendingAfter.some(row => row.id === id));
    assert.ok(pendingAfter.some(row => row.id === independentConflict.operationId));
    assert.ok(pendingAfter.some(row => row.id === foreignTargetAttempt.operationId));
    const preservedAttempts = (await pool.query('select id,request,receipt from obsidian_editorial_operations where id=any($1::uuid[]) order by id', [failedAttempts.map(row => row.id)])).rows;
    assert.deepEqual(preservedAttempts, failedAttempts.toSorted((a, b) => a.id.localeCompare(b.id)));
    const { acknowledgedBase: _attemptBase, ...failedRequest } = failedAttempts[0]!.request;
    const laterAttempt = { ...failedRequest, operationId: randomUUID(), resolution: { ...failedRequest.resolution, currentRevision: resolved.revision } };
    assert.equal((await service.editorial.apply(clientId, laterAttempt)).status, 'conflict');
    assert.ok((await service.editorial.conflicts()).some(row => row.id === laterAttempt.operationId));
    assert.ok(!(await service.editorial.manifest(clientId, vaultId)).resolutions.find(row => row.originalOperationId === concurrent.operationId)!.supersededOperationIds.includes(laterAttempt.operationId));
    const laterEdit = clean(await operation(pageId, text => text.replace('Saved again before comparison.', 'Saved again before comparison. Later queued edit.')));
    await writeFile(join(vault, laterEdit.relativePath), laterEdit.content);
    await familyQueue.enqueue(laterEdit);
    await familyQueue.acceptResolution(concurrent.operationId, resolvedFamily.operation, resolvedFamily.receipt, resolvedFamily.supersededOperationIds);
    assert.deepEqual(familyQueue.state.operations.map(row => row.operation.operationId), [resolved.operationId, laterEdit.operationId]);
    await familyQueue.flush(op => service.editorial.apply(clientId, op), (op, receipt, observed) => applyQueuedReceipt(familyQueue.state.operations, op, receipt, observed, {
        read: path => readFile(join(vault, path), 'utf8'),
        write: async (path, expected, content) => { assert.equal(await readFile(join(vault, path), 'utf8'), expected); await writeFile(join(vault, path), content); return true; }
    }), async id => { await service.editorial.acknowledge(clientId, id, vaultId); });
    assert.equal(familyQueue.state.operations.length, 0);
    assert.ok((await wiki.get(pageId))!.sections[0].markdown.includes('Later queued edit.'));
    const wikiFirst = clean(await operation(pageId, text => text.replace('Saved again before comparison.', 'Offline wiki first.'))), wikiSecond = { ...wikiFirst, operationId: randomUUID(), content: wikiFirst.content.replace('Offline wiki first.', 'Offline wiki latest.') };
    const wikiMove = { ...wikiSecond, operationId: randomUUID(), kind: 'move' as const, previousRelativePath: wikiSecond.relativePath, relativePath: wikiSecond.relativePath.replace(/[^/]+$/, 'Moved wiki.md') };
    const wikiQueue = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => {});
    for (const op of [wikiFirst, wikiSecond, wikiMove]) await wikiQueue.enqueue(op);
    await writeFile(join(vault, wikiFirst.relativePath), wikiSecond.content);
    await rename(join(vault, wikiFirst.relativePath), join(vault, wikiMove.relativePath));
    let wikiBase = resolved.content;
    const wikiSent: string[] = [];
    await wikiQueue.flush(async op => { wikiSent.push(op.kind); return service.editorial.apply(clientId, op); }, async (op, receipt, observed) => {
        wikiBase = receipt.content;
        return applyQueuedReceipt(wikiQueue.state.operations, op, receipt, observed, {
            read: async path => { try { return await readFile(join(vault, path), 'utf8'); } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null; throw error; } },
            write: async (path, expected, content) => { assert.equal(await readFile(join(vault, path), 'utf8'), expected); await writeFile(join(vault, path), content); return true; }
        });
    }, async id => { await service.editorial.acknowledge(clientId, id, vaultId); }, () => wikiBase);
    assert.deepEqual(wikiSent, ['edit', 'edit', 'move']);
    assert.equal(wikiQueue.state.operations.length, 0);
    assert.ok((await wiki.get(pageId))!.sections[0].markdown.includes('Offline wiki latest.'));
    assert.ok((await readFile(join(vault, wikiMove.relativePath), 'utf8')).includes('Offline wiki latest.'));
    const catalogEdit = await operation(catalog.id, text => text.replace('# Catalog intro\n\n', '# Catalog intro\n\nNew catalog introduction.  \n'));
    const promoted = await apply(catalogEdit);
    assert.equal(promoted.status, 'synced');
    assert.equal(parseObsidianMarkdown(promoted.content)!.frontmatter.memoraType, 'source_item');
    await ack(promoted, catalogEdit.relativePath);
    assert.ok((await documents.listBySourceItem(catalog.id))[0]!.canonicalMarkdown.includes('New catalog introduction.'));
    const newSectionId = randomUUID(), sectionEdit = await operation(pageId, text => text.replace('<!-- memora:generated:start -->', '<!-- memora:section:' + newSectionId + ':start -->\n## New human section\n\nUncited human interpretation.\n<!-- memora:section:' + newSectionId + ':end -->\n\n^memora-section-' + newSectionId + '\n\n<!-- memora:generated:start -->'));
    const added = await apply(sectionEdit);
    assert.equal(added.status, 'synced');
    await ack(added, sectionEdit.relativePath);
    assert.deepEqual((await wiki.get(pageId))!.sections.find((s: any) => s.id === newSectionId).evidenceIds, []);
    await project();const catalogIndex=(await createObsidianSyncRepository(pool).list()).find(file=>file.memoraType==='wiki_index'&&file.relativePath.endsWith('/Wiki/Sources/index.md'))!;
    const moved = clean(await operation(child.id, text => text));
    moved.kind = 'move';
    moved.previousRelativePath = moved.relativePath;
    moved.relativePath = moved.relativePath.replace(/[^/]+$/, 'Moved child.md');
    await rename(join(vault, moved.previousRelativePath), join(vault, moved.relativePath));
    const moveReceipt = await service.editorial.apply(clientId, moved);
    assert.equal(moveReceipt.status, 'synced');
    await ack(moveReceipt, moved.relativePath);await project();const movedCatalog=(await createObsidianSyncRepository(pool).findByMemoraId(catalogIndex.memoraId))!;assert.ok(movedCatalog.syncVersion>catalogIndex.syncVersion);assert.ok((await readFile(join(vault,movedCatalog.relativePath),'utf8')).includes(moved.relativePath.replace(/\.md$/,'')));
    assert.equal((await sources.findById(child.id))!.parentSourceItemId, parent.id);
    // A persisted old-plugin queue can contain a second dirty edit only in a
    // move payload. Both intermediate paths are already absent before replay.
    const moveEdit = clean(await operation(note.id, text => text.replace('Edited hard break', 'First offline hard break')));
    const firstMove = { ...moveEdit, operationId: randomUUID(), kind: 'move' as const, previousRelativePath: moveEdit.relativePath, relativePath: moveEdit.relativePath.replace(/[^/]+$/, 'Intermediate note.md'), content: moveEdit.content.replace('First offline hard break', 'Latest offline hard break') };
    const lastMove = { ...firstMove, operationId: randomUUID(), previousRelativePath: firstMove.relativePath, relativePath: firstMove.relativePath.replace(/[^/]+$/, 'Final note.md') };
    const moves = new ObsidianOperationQueue({ version: 1, operations: [] }, async () => {});
    for (const op of [moveEdit, firstMove, lastMove]) await moves.enqueue(op);
    await writeFile(join(vault, moveEdit.relativePath), lastMove.content);
    await rename(join(vault, moveEdit.relativePath), join(vault, firstMove.relativePath));
    await rename(join(vault, firstMove.relativePath), join(vault, lastMove.relativePath));
    let moveBase = (await manifest()).find(file => file.targetId === note.id)!.content;
    const moveSent: string[] = [];
    await moves.flush(async op => { moveSent.push(op.kind); return service.editorial.apply(clientId, op); }, async (op, receipt, observed) => {
        moveBase = receipt.content;
        return applyQueuedReceipt(moves.state.operations, op, receipt, observed, {
            read: async path => { try { return await readFile(join(vault, path), 'utf8'); } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return null; throw error; } },
            write: async (path, expected, content) => { assert.equal(await readFile(join(vault, path), 'utf8'), expected); await writeFile(join(vault, path), content); return true; }
        });
    }, async id => { await service.editorial.acknowledge(clientId, id, vaultId); }, () => moveBase);
    assert.deepEqual(moveSent, ['edit', 'edit', 'move', 'move']);
    assert.equal(moves.state.operations.length, 0);
    const finalNoteFile = (await createObsidianSyncRepository(pool).findByMemoraId(note.id))!;
    assert.equal(finalNoteFile.relativePath, lastMove.relativePath);
    assert.equal(finalNoteFile.status, 'synced');
    assert.equal(finalNoteFile.metadata.editorialAcknowledgedOperationId, lastMove.operationId);
    assert.ok((await notes.findById(note.id))!.bodyMarkdown.includes('Latest offline hard break'));
    assert.ok((await readFile(join(vault, lastMove.relativePath), 'utf8')).includes('Latest offline hard break'));
    await assert.rejects(readFile(join(vault, firstMove.relativePath)));
    await assert.rejects(readFile(join(vault, moveEdit.relativePath)));
    const offlineEdit=clean(await operation(child.id,text=>text.replace('Child original.','Offline edit before deletion.'))),deletion={...offlineEdit,operationId:randomUUID(),kind:'delete' as const};
    const queue=new ObsidianOperationQueue({version:1,operations:[]},async()=>{}),sent:ObsidianEditOperation[]=[];let tombstone:any;
    await queue.enqueue(offlineEdit);await queue.enqueue(deletion);await rm(join(vault,deletion.relativePath));
    await queue.flush(async op=>{sent.push(op);const result=await service.editorial.apply(clientId,op);if(result.status==='deleted')tombstone=result;return result;},async op=>queue.state.operations.some(r=>r.operation.targetId===op.targetId&&r.operation.kind==='delete'),async id=>{await service.editorial.acknowledge(clientId,id,vaultId);});
    assert.equal(queue.state.operations.length,0);assert.equal(tombstone.status,'deleted');assert.ok(await sources.findById(child.id));assert.ok(await documents.findById(c.doc.id));
    assert.deepEqual(await service.editorial.apply(clientId,sent.at(-1)!),tombstone);
    await project();assert.ok((await readFile(join(vault,catalogIndex.relativePath),'utf8')).includes('memora://open/source/'+child.id));
    await service.editorial.resolveDesktop({id:deletion.operationId,choice:'app',content:'',expectedLocal:null,currentRevision:tombstone.revision});
    assert.ok((await readFile(join(vault,deletion.relativePath),'utf8')).includes('Offline edit before deletion.'));
    const beforeRepeat = (await notes.findById(note.id))!.bodyMarkdown;
    await project();
    assert.equal((await notes.findById(note.id))!.bodyMarkdown, beforeRepeat);const noteFile=(await createObsidianSyncRepository(pool).findByMemoraId(note.id))!;assert.equal(parseObsidianMarkdown(await readFile(join(vault,noteFile.relativePath),'utf8'))!.frontmatter.memoraDocumentId,c.doc.id);
    const parallelLeft=clean(await operation(pageId,text=>text.replace('Local body.','Parallel local.'))),parallelRight=clean(await operation(pageId,text=>text.replace('Identical body','Parallel second section')));
    const parallel=await Promise.all([service.editorial.apply(clientId,parallelLeft),service.editorial.apply(clientId,parallelRight)]);assert.ok(parallel.every(r=>r.status==='synced'));assert.ok(parallel[1]!.content.includes('Parallel local.'));assert.ok(parallel[1]!.content.includes('Parallel second section'));await ack(parallel[1]!,parallelRight.relativePath);
    const duplicate = clean(await operation(parent.id, text => text));
    duplicate.relativePath += ' copy.md';
    const duplicateReceipt = await apply(duplicate);
    assert.equal(duplicateReceipt.status, 'conflict');
    assert.equal(duplicateReceipt.reason, 'path');
    await writeFile(join(vault, duplicate.relativePath), parseObsidianMarkdown(duplicate.content)!.bodyMarkdown);
    const detached = await service.editorial.apply(clientId, { ...duplicate, operationId: randomUUID(), kind: 'detach', resolution: { operationId: duplicate.operationId, currentRevision: duplicateReceipt.revision, choice: 'app' } });
    assert.equal(detached.status, 'ignored');
    assert.ok(!(await service.editorial.conflicts()).some(row => row.id === duplicate.operationId));
    const generated = await operation(pageId, text => text.replace('<!-- memora:generated:start -->', '<!-- memora:generated:broken -->'));
    const malformed = await apply(generated);
    assert.equal(malformed.status, 'conflict');
    await service.editorial.resolveDesktop({ id: generated.operationId, choice: 'app', content: '', expectedLocal: generated.content, currentRevision: malformed.revision });
    const pagedResolutionIds = new Set<string>([resolved.operationId]);
    for (let index = 0; index < 26; index++) {
        const invalid = await operation(pageId, text => text.replace('<!-- memora:generated:start -->', '<!-- invalid generated -->'));
        const blocked = await apply(invalid);
        assert.equal(blocked.status, 'conflict');
        const kept = await service.editorial.resolveDesktop({ id: invalid.operationId, choice: 'app', content: '', expectedLocal: invalid.content, currentRevision: blocked.revision });
        pagedResolutionIds.add(kept.operationId);
    }
    let resolutionCursor: number | null = 0, resolutionPages = 0;
    const deliveredResolutionIds = new Set<string>();
    while (resolutionCursor !== null) {
        const batch = await service.editorial.manifest(clientId, vaultId, resolutionCursor);
        assert.ok(batch.resolutions.length <= 25);
        if (resolutionPages > 0) assert.equal(batch.files.length, 0);
        for (const row of batch.resolutions) deliveredResolutionIds.add(row.operation.operationId);
        resolutionCursor = batch.cursor;
        resolutionPages++;
    }
    assert.ok(resolutionPages >= 2);
    for (const id of pagedResolutionIds) assert.ok(deliveredResolutionIds.has(id), 'old resolution remains pageable');
    const pendingManifest = await service.editorial.manifest(clientId, vaultId, 0, [failedAttempts[0]!.id, independentConflict.operationId]);
    assert.equal(pendingManifest.resolutions.length, 1);
    assert.equal(pendingManifest.resolutions[0]!.operation.operationId, resolved.operationId);
    assert.deepEqual(pendingManifest.resolutions[0]!.supersededOperationIds, [failedAttempts[0]!.id]);
    assert.equal(pendingManifest.cursor, null);
    assert.deepEqual((await service.editorial.manifest(clientId, vaultId, 0, [])).resolutions, []);
    const paused = clean(await operation(child.id, t => t + 'x'));
    settings = { ...settings, obsidianSyncPaused: true };
    await assert.rejects(service.editorial.apply(clientId, paused));
    settings = { ...settings, obsidianSyncPaused: false };
    assert.deepEqual((await pool.query('select * from bibliographic_works where id=$1',[workRecord.id])).rows[0],catalogBefore);assert.equal((await sources.findById(parent.id))!.metadata.descriptor,undefined);assert.equal((await pool.query('select pages from source_item_bibliographic_links where source_item_id=$1',[child.id])).rows[0].pages,'11-14');
    const staleNote = note.updatedAt.toISOString();
    await assert.rejects(notes.review({ id: note.id, action: 'edit', bodyMarkdown: 'Stale overwrite', expectedUpdatedAt: staleNote }), /conflict/);
    assert.equal((await notes.findById(note.id))!.bodyMarkdown, beforeRepeat);
    await new HierarchicalIngestionService({ getPool: () => pool! }).process({ runKind: 'reingestion', plan: ProcessingPlanRequestSchema.parse({ preset: 'custom', requestedStages: ['atomicNotes'], targetSourceItemIds: [child.id], forceRegeneration: true, previousArtifactPolicy: 'preserve_reviewed_archive_pending' }) });
    assert.equal((await notes.findById(note.id))!.status, 'pending_review');
    assert.equal((await notes.findById(note.id))!.supersessionStatus, 'current');
    await createIntegrationClientRepository(pool).setStatus(clientId, 'revoked');
    await assert.rejects(service.editorial.manifest(clientId, vaultId), /binding/);
    await pool.query('create database editorial_empty');
    const url = new URL(connection.connectionString);
    url.pathname = '/editorial_empty';
    empty = createPgPool({ connectionString: url.toString() });
    assert.equal((await runMigrations(empty, migrations, { seedFolder })).seed.applied, true);
    assert.equal((await empty.query("select count(*)::int as n from information_schema.tables where table_name in('atomic_note_revisions','obsidian_editorial_operations')")).rows[0].n, 2);
    console.info('M5 isolated PostgreSQL: populated upgrade, empty baseline, wiki/source/note revisions, history/protection, idempotence, concurrent merges, edit-delete replay and conflicts verified; editorial saves start no processing.');
    await service.shutdown();
}
finally {
    if (empty)
        await closePgPool(empty);
    if (pool)
        await closePgPool(pool);
    await manager.stop();
    await rm(work, { recursive: true, force: true });
}
